### ISSUE TITLE
Level: "No bunny left behind"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#10]
New level from @ColonelFazackerley:

    :name=No bunny left behind
    :description=They are going too fast!
    :num_rabbits=5
    :num_to_save=5
    :rabbit_delay=2
    :bridge=5
    :dig=1
    :music=tryad-witness
    ###################
    #######           #
    #######   Q       #
    #######           #
    #O                #
    #####   ######### #
    ####              #
    ####              #
    ####    ###########
    ####    #          
    ####    #          
    ####    #          
    #########

**Comment by andybalaam** [comment]
Fun.  I used the same trick as level hard 16: slow the other 4 down with bridgers.  Is there some other trick?  I also managed to get them trapped in the top part with bridges (and release them with a digger), but to do that I still needed to use further bridges to slow them down.
Thought: 7
Skill: 7

**Comment by andybalaam** [comment]
(Committed for now as new/level_01.rel)

**Comment by andybalaam** [comment]
ColonelFazackerley: I did not have to slow them down to complete the level. It is easier than I intended. I was trying to make it necessary to send a climber, who would convert into a bridger, but this seems to not work. Climbers can convert to diggers, so this seems anomalous. As it is, its easy, I think. But I guess new levels of all grades are required.

**Comment by andybalaam** [comment]
I reckon I'll put it in as it is, and if we think of a more difficult variant using climbers later, that is all good.  I really like variants of the same level...

**Comment by andybalaam** [comment]
@ColonelFazackerley, I think I consider climbers converting into anything a bug.

**Comment by andybalaam** [comment]
While they're climbing I mean.  But I just tried this and the token floated straight past, so that can't be what you mean.  Can you explain?  I tried this:

       d 
       d 
        #
        #
        #
    # rc#
    #####

And both the dig tokens drifted straight past the rabbit as they fell.
(Notes: r=rabbit, c=climb token, d=dig token)

**Comment by andybalaam** [comment]
@ColonelFazackerley what is your solution that doesn't require slowing them down?

**Comment by colonelfazackerley** [comment]
I tried again. I have to delay one of them at one point.

About the inconsistency: once a climber has reached the flat again he will become a digger, but not a bridgebuilder.

**Comment by andybalaam** [comment]
I guess he must not have had room to bridge.  If I put a bridge token at the top of a wall, the climber starts bridging.  In ASCII:

    
      i
      ##
      ##
    rc##
    ####

means he does start bridging at the top.

**Comment by andybalaam** [comment]
Having to delay them fits with the title, so it's all good.
