### ISSUE TITLE
Bug: splat from height consumes token

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#100]
```
r  
#  
   
   
   
 i 
###
```
This rabbit should not consume the bridge token as they die.

**Comment by tttppp** [comment]
I'm not sure this bug goes far enough. The current behaviour is mainly logical - a rabbit passing through a token consumes it (with some weird/confusing edge cases around bridging tokens). I propose we consider one of two changes:

1. Tokens are always consumed by rabbits, regardless of whether they can immediately use them. (i.e Change the bridge token implementation)

2. Tokens are not consumed by rabbits where they cannot use them. This means falling rabbits can never consume bridge/dig/bash/block tokens, but always consume climb/explode tokens. In addition, rabbits hitting the ground only consume bridge/dig/bash/block tokens if they are not flattened by the fall (this may happen automatically if fallers get converted into walkers). Note that I'm suggesting (controversially?) that flattened rabbits consume climb tokens upon impact.
