### ISSUE TITLE
Avoid manual wrapping of descriptions and hints

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#101]
Manually entering \n in the strings is a hassle. We could
1. Get the code displaying the dialog to figure out how long the lines should be, or,
2. Use a script or something to put the \n chars into the files.

**Comment by tttppp** [comment]
Number 1 clearly seems better to me. For Android most UI elements automatically wrap (if the width cannot be extended). Is there something similar for Swing? Knowing where the line breaks should go without knowing the font/dialog width is basically guesswork.

**Comment by andybalaam** [comment]
Yes, on Android we actually remove the \ns and let the dialog handle it.  Now that I've figured out how to use HTML-style layout in Swing dialogs (See https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-ui-swing/src/rabbitescape/ui/swing/SwingGameLaunch.java#L193) we can probably get rid of the \ns entirely.  (The hints dialogs would need fixing to be similar.)
