### ISSUE TITLE
Lava/Water/Death upon entry squares

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#105]
It would be cool to have something similar to the water in Lemmings. Some sort of square that is instant death for infinite lemmings. I've been simulating this with stacks of explode tokens, but it's a bit naff, and slightly mean on the unsuspecting player who thinks there's only one.

**Comment by andybalaam** [comment]
Yes, traps in general would be good.  Some are infinite instant death, some only kill one rabbit at a time, so others can slip past, if we think it makes for good puzzles.

**Comment by GamingInky** [comment]
I think that would be cool we could maybe have a token which means the rabbits can swin in hte water and not drown

**Comment by colonelfazackerley** [comment]
If water is implemented, then a life ring token would be good. Cartoon style etc.

**Comment by andybalaam** [comment]
Life ring would be cool.

**Comment by GamingInky** [comment]
I love that idea!

**Comment by colonelfazackerley** [comment]
I am working on this now. some more thoughts
- i will do water as a first pull request.
- i will get around to snorkels later, as there is some skepticism about how good an idea they are
- i say snorkels instead of life rings, as the life ring would put the rabbit on the surface of the water, between squares, which sounds awkward. with snorkels they would swim along on the top water square.

**Comment by tttppp** [comment]
Is water contained? Ie Can it fall like rabbits and tokens if there are no supporting blocks? Does each water square have its own containing border? If so then how do adjacent water squares work?

In short, I like the idea of water squares (and snorkels too), but I don't know that they're as simple to add as just reusing your ripped paper/highlighter inside the board to show other squares that rabbits will be evaporated on.

**Comment by colonelfazackerley** [comment]
I had no intention of adding hydrodynamics. I was thinking that each water square should have another water square to the side, or a solid block.

Now you mentions these issues, it does occur to me that the blocks forming the dam may be removed by digging and bashing. Perhaps any implementation of water does need to consider it flowing. I can see this being more effort, but puzzletunities* may arise.

I will not do any work on this, until a plan is outlined here.

* @andybalaam, I have honoured your neologism.

**Comment by andybalaam** [comment]
I have no problem with water simply staying where it is. Not only is it Biblical, but also this is not Minecraft.

**Comment by tttppp** [comment]
Redirecting water by bashing is quite an exciting/crazy idea. The bunnies doing the engineering works would almost certainly be drowned. Maybe water comes from taps/springs, and is only a danger to bunnies when pooled. This would allow a bunny to bash through the side of a water container, provided that there is an escape route for the water. I think I have some rough idea of laws governing which squares have what sort of water. I'll add them to a new discussion issue.

Maybe "water" should be saved for the more complicated scenario, and use fire/torn paper/something else to make squares that rabbits literally can't pass through?

**Comment by colonelfazackerley** [comment]
Some rabbits may be sacrificed. Or perhaps rabbots. 

This is very complicated. I can see it doubling the amount of fiddly code. I would help, but not sure i would want to start it. Have to think about it for a while.

**Comment by andybalaam** [comment]
If we are going with complex water I definitely think a simple lava or trap block that just kills rabbits is also needed.

**Comment by colonelfazackerley** [comment]
given this issue has parented #298 and #300 and they are more detailed and specific, I suggest this is closed.

**Comment by andybalaam** [comment]
Agreed
