### ISSUE TITLE
Rot13 shielding of hints in level files

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#106]
This would allow developers to share levels with each other, without accidentally ruining the fun.  This could be implemented using a new parameter - e.g.
```
:hint1rot13=Hfr gur oevqtr gbxra
```
or with some function thing:
```
:hint1=rot13(Hfr gur oevqtr gbxra)
```

**Comment by andybalaam** [comment]
Yes.  We could simply choose a convention for now (probably your first suggestion?) and later maybe make the build auto-translate rot13 into English.

We could consider making all hints rot13 in the file format, but it would be annoying to edit, and since the ease of editing level files is one of our greatest selling points at the moment, it would seem perverse.

**Comment by tttppp** [comment]
I have added the MegaCoder as a pull request to solve this (uses custom obfuscation rather than rot13).  The notation is:
```
:hint1.code=Blah
```

**Comment by colonelfazackerley** [comment]
How does one obfuscate for The MegaCoder?

As in, the game code knows how to de-obfuscate, but how do I obfuscate correctly when making levels?

**Comment by colonelfazackerley** [comment]
It's using simple encryption, or obfuscation, which I think is a little different to encoding.

is ".code" the correct suffix?

**Comment by colonelfazackerley** [comment]
see #122

**Comment by tttppp** [comment]
Obfuscation encoding can be performed with ideone here: https://ideone.com/iYsAoP

There might be a bug if the encoded hint ends up containing a colon, but I think that's a problem with the level format at the moment.

I think it's encoding rather than encryption, as there's no secret key.  A suffix of ".obfuscated" would be even better, but I thought it was a bit long!

**Comment by andybalaam** [comment]
We can add a little main method to encode a string or even the "interesting" parts of a level file.

**Comment by colonelfazackerley** [comment]
Perhaps a menu item next to "load level" and "retrieve github issue" could load "mylevel.rel" and save "mylevel.code.rel" with The MegaCoder applied to hint1-3.

I can pull request this when the outstanding pull requests have been merge.

**Comment by tttppp** [comment]
Ideone wasn't actually very suitable as a quick online option, as the only way to change the input is to fork the sample (which is slow).  Adding a main method would certainly work, and would allow command line access which could be nice.

I've just tested a few other online Java compilers, and settled on:
http://goo.gl/A5Zkg5
(redirects to http://www.tutorialspoint.com/compile_java_online.php?PID=0Bw_CjBb95KQMUVRMN2FmUE93SG8 in case you'd prefer to go directly to the page). You can change the INPUT constant to the string you want to encode, then click "Compile" and then "Execute".  The output is something like:
```
javac HelloWorld.java                                                                      
sh-4.3$ java -Xmx128M -Xms16M HelloWorld
Input was 'Hello World'
Output is 'Igjj*z{j={4'
```

Being able to run a script against a level file and obfuscate several strings at once would also be useful.

**Comment by andybalaam** [comment]
Can we close this issue now?

**Comment by tttppp** [comment]
Yes. Please close!

**Comment by colonelfazackerley** [comment]
@tttppp you opened it, you should user rights to close it.
