### ISSUE TITLE
Level: "Prison break"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#11]
New level from @ColonelFazackerley:

    :name=Prison break
    :description=In which order should you free them?
    :num_rabbits=3
    :num_to_save=3
    :bash=2
    :bridge=3
    :dig=2
    :music=tryad-witness
                ########          
                #  Q   # ######## 
     ########   #      # #   Q  # 
     #  Q   #   ######## #      # 
     #      #            ######## 
     ########                     
                                  
                           O      
                \       /######## 
                ##########        
                                  
     ##########

**Comment by andybalaam** [comment]
Love how this looks.  Did it second time, but really enjoyed it.  Might be a tiny bit too wide, in terms of fitting easily on the screen?  Also, "Which order should you free them in?" ends a sentence with a preposition ;-)
Thought: 7
Skill: 4

**Comment by andybalaam** [comment]
(Committed for now as new/level_02.rel)

**Comment by andybalaam** [comment]
ColonelFazackerley: "I shrank each cell by 1 column. Damn your grammar skills."

**Comment by andybalaam** [comment]
Love it.  It's going in.  I plan a new level set with another 20 levels.  I was thinking of calling it "Outdoors" because a lot of these levels have no border.

**Comment by colonelfazackerley** [comment]
I play with the sound off. At some point, we need to make sure that the
levels I submit do not all have the same music.

**Comment by andybalaam** [comment]
Yes.  I plan to add a new piece of music for the outdoors levels, and have them all use that.
