### ISSUE TITLE
Level: "C Red"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#111]
On my mobile, so can't copy and paste the level properly into github, but it's meant to be exactly the same as "C" with one fewer digger. I think there's something wrong with what I've put below, as on 0.6.1, the rabbits seem to have variable delay.  Anyway the Deja Vu level is "Can you solve C with one digging token left at the end?"  If someone feels like working out what this should look like, and posting it below that would be great - thanks.

Edited to include level (and encoded solution):

```
:name=C Red
:description=Down and around... and down a bit more than that?
:num_rabbits=9
:num_to_save=9
:rabbit_delay=10
:bridge=4
:dig=3
:block=4
:bash=3
:explode=2
:music=tryad-witness
:solution.1.code=.exzzv$Dz.Yz _YYzn|Y+|YzzZY.vY$YYz]L,vzz_+YY,D YnYznZ+z]xHYZzLz.$c]|$XvIdezy$.UYYz]+.qLY ]YxvvIzY$Z$zzz.]xqY v$IYvzIz.$D|zvv..HYz$zz
    Q                

    #########        
   # #####   #       
  ########\   #      
 # # #    #\  #      
 ####      ####      
 ####                
 ####                
 #  #                
 ####                
 ####      ####      
 #####    #####      
 ##  ######  O#      
  ## ######  #       
   ##########        
    ########         
```

**Comment by GamingInky** [comment]
Q                

    #########        
   # #####   #       
  ########\   #      
 # # #    #\  #      
 ####      ####      
 ####                
 ####                
 #  #                
 ####                
 ####      ####      
 #####    #####      
 ##  ### ##  O#      
  ## ######  #       
   ##########        
    ########         

Here's what it should look like.
But there need's to be a bridger

**Comment by colonelfazackerley** [comment]
```
:name=C Red
:description=
:num_rabbits=9
:num_to_save=9
:rabbit_delay=10
:bridge=4
:dig=3
:block=4
:bash=3
:explode=2
:music=tryad-witness
    Q                
              
    #########        
   # #####   #       
  ########\   #      
 # # #    #\  #      
 ####      ####      
 ####                
 ####                
 #  #                
 ####                
 ####      ####      
 #####    #####      
 ##  ######  O#      
  ## ######  #       
   ##########        
    ########         
```
Just putting this together into one code block.

**Comment by tttppp** [comment]
@colonelfazackerley Andy just merged my pull request to fix the blank line problem. Assuming your code uses the same level loading then you could merge/duplicate my fix on your branch and then remove the extra #s above.

Nb Git's pretty good with duplication of changes and merging. I wouldn't suggest duplicating history with some older VCSs. (But merging the changes to your branch should be easy too).

**Comment by colonelfazackerley** [comment]
done.

my branch cant get to this yet, it only retrieves the issues opening body text. i will update it to get follow up comments now.

**Comment by tttppp** [comment]
Hints for this level:
```
:hint.1.code=Z*,vI)E)&$I3$`)$EYI$E)$'&//E3IE?/y
:hint.2.code=ig5EE5'(E7i5ED}555]F5hF6qGq'(W6EbW5WWDg756;(65qqb'D
:hint.3.code=C72 C OsCuOn^ 2sCnabCCOuGGOnG2oy|GC9|XyyGoCyaCCsl7yCooCnuyyquCC2O .a2ubyyb
```

**Comment by colonelfazackerley** [comment]
```
:solution.2.code=wpPpPk:-jPk_V]pkp0w+DHPp-pkHjyj0pMcOO6Q<,kjMDk-,8YMOjy+0p%PjpO%,kPnp6pj0M0pCP+O8=
```
I like your solution, it uses the whole C. Mine is different.

I think this can be one of the earlier deja vu levels.

ref #87

**Comment by andybalaam** [comment]
Assuming this still fits the description above ie the original level with one less digger I just solved it after quite a few tries. I'll check whether my solution matches either of yours.

**Comment by tttppp** [comment]
Just checked @colonelfazackerley's solution. Very neat and much simpler than mine.

**Comment by andybalaam** [comment]
My solution is different again!

```
:solution.1.code=ts3#Oyv_^sg)d6JOyyZZlx|-30J#Z)ydtZsyZc#tZg0^t&-ZtZ)c#s#yZv-v#t[) Q-Z_3yZJ^#ZJy#O&ys[yZ^ttsyZZsdvZs6yt3)0-Z^J#ZPy)ZOZyt3ydsZs3#Z!EvZi6
```

**Comment by andybalaam** [comment]
Yes, I like @colonelfazackerley 's solution too.

**Comment by tttppp** [comment]
I just watched all the solutions - impressive range!
