### ISSUE TITLE
level:Planet Paradise

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#112]
```
:name=Planet Paradise
:description=Don't lose your gravity and fall off the planet just get to the core.
:author_name=GamingInky
:author_url=https://github.com/GamingInky
:hint1=You have to smash the planet.
:hint2=The lower you are the better.
:hint3=Bridging would be useful at the end.
:num_rabbits=1
:num_to_save=1
:bash=2
:bridge=2
:music=
                 Q         
                          #
                          #
               # #         
                ###        
               #####    #  
           #  #######   ## 
          #################
         # #  ## O###   ## 
        #        ###    #  
       #        ###        
     #           #         
     ########## # #        
```

Please somebody help me make theese levels harder

**Comment by colonelfazackerley** [comment]
How are you entering your levels? for my new parser to work the level 'code' needs to be in triple backticks

```

**Comment by andybalaam** [comment]
@colonelfazackerley equivalent markdown is a block of lines all starting with at least 4 spaces.

**Comment by colonelfazackerley** [comment]
I just looked in the JSON from the API. Yup, the world text is indented by 4 spaces. I will try to support that too.

**Comment by andybalaam** [comment]
Thanks. As far as I know those are the only 2 variants.

**Comment by tttppp** [comment]
Where is the "Q" meant to be on this level?  @GamingInky I'd suggest entering levels between triple back ticks (`).

**Comment by GamingInky** [comment]
@tttppp I think it I've fixed it can you try it?

**Comment by GamingInky** [comment]
The blank lines didn't work so I added #'s and tested. It works.

**Comment by andybalaam** [comment]
Yeah, GitHub was squashing lines that were completely blank.  In some future time I will make a repo for saving your levels into, and all will be good.

**Comment by tttppp** [comment]
This works fine now, but is fairly easy. Maybe the first level  in a paradise set?

**Comment by GamingInky** [comment]
yes that sounds good

**Comment by GamingInky** [comment]
I think we have given up on these levels.
