### ISSUE TITLE
Baddy rabbits/rabbots

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#114]
I just wanted to say me and Andy have been writing Code for baddy rabbits.

**Comment by andybalaam** [comment]
They behave exactly like normal rabbits except they explode on contact with a normal rabbit.

**Comment by colonelfazackerley** [comment]
Cool, can you push the branch or whatever? I will have a look.

**Comment by andybalaam** [comment]
Yeah we will. It's not actually working so far but there are some graphics and a general idea of what we're doing.

**Comment by tttppp** [comment]
This sounds a cool mechanic. Do the dark rabbits come out of entrances, or do they just start in the level?  Also how many extra characters are you using to represent them in Ascii?

**Comment by andybalaam** [comment]
For now they will just exist but if entrances enabled puzzletunities they could be added. 2 new ascii characters.

**Comment by colonelfazackerley** [comment]
Will the evil Nazi rabbits[1] consume tokens and gain abilities?

[1]
I am thinking watership down.

**Comment by andybalaam** [comment]
Some puzzles will require you to get them out of the way. Some will require you to use them for good.

**Comment by colonelfazackerley** [comment]
Name suggestion: "rabbots".

The idea came to me as I typoed. This might be considered a good reason to not use it.

**Comment by colonelfazackerley** [comment]
>  there are some graphics

Could you push a branch with that in? Or post png/gifs here?

**Comment by andybalaam** [comment]
Yes, I will try to remember. I am considering auto generating the graphics from normal rabbits by just changing their colours. At the moment this has been manually done. If we want more exciting graphics it will obviously need to be done by hand.

**Comment by andybalaam** [comment]
We hit a wall implementing this. It's beyond @GamingInky's capacity at the moment. I think we need to restructure the logic so it's clear where each rabbit will end up next time step, and then allow updates to what is going to happen based on that (because when a rabbit and rabbot collide their behaviour is different from what it would be if the other one were not there.)

**Comment by andybalaam** [comment]
Liking rabbot because it suggests graphics that would be fun.

**Comment by colonelfazackerley** [comment]
I think making them all custom graphics would be too much hassle. How about generating SVGs automatically (with the colour changes). (I guess someone smarter than me could get make to do this). 

If we want to have custom animations for certain things we can create the odd SVG frame that is different. These frames will override the auto-frames.

Some ideas for rabbot* custom frames;
- when they splat, some electromechanical innards are revealed.
- when they turn from rabbots to jabbots an eye glows red as their gaze sweeps over the player.

If we put them in the rel files with no entrances for them, would we use 'R' and 'J'?

*
I am proud of my baby neologism.

**Comment by andybalaam** [comment]
> How about generating SVGs automatically (with the colour changes)

That is my plan.

**Comment by andybalaam** [comment]
> If we put them in the rel files with no entrances for them, would we use 'R' and 'J'?

If they are not taken that seems appropriate. Puts me in mind of the Terminator who usually speaks in all caps.

**Comment by colonelfazackerley** [comment]
> >     How about generating SVGs automatically (with the colour changes)

> That is my plan.

Implemented cunningly, so when a custom rabbot frame exists it overrides the auto-frame.

**Comment by tttppp** [comment]
+1 for rabbits, jabbits, rabbots and jabbots.

**Comment by GamingInky** [comment]
this is what rabbots will look like: 
![baddy_rabbit_bash_left_01](https://cloud.githubusercontent.com/assets/15169323/12371367/4e747528-bc29-11e5-872a-e6ad50e9dce1.png)

**Comment by andybalaam** [comment]
> Implemented cunningly, so when a custom rabbot frame exists it overrides the auto-frame

Yes this should be simple to do in the Makefile.

**Comment by andybalaam** [comment]
@GamingInky I like it - it looks dangerously toxic!

**Comment by GamingInky** [comment]
yes it does

**Comment by GamingInky** [comment]
the animation is like this:
![rabbots-explode](https://cloud.githubusercontent.com/assets/15169323/12399374/9557efe4-be11-11e5-8f15-474a20c784d5.gif)

**Comment by tttppp** [comment]
Wow! It's going to be quite rewarding to let them collide! :-)

**Comment by colonelfazackerley** [comment]
Very nice.

Slight improvement: perhaps the cogs and springs could fade to 50% transparency on the frame before they disappear?

**Comment by andybalaam** [comment]
Yeah we will work on the transparency.

**Comment by andybalaam** [comment]
We've had a slight breakthrough in our thinking on this. Making rabbits explode as they pass each other is hard so instead we plan to have rabbots stop and wait when a rabbit is coming near, so we can only make them explode when they are occupying the same Square.

**Comment by tttppp** [comment]
Ah yes, this sounds hard now I think about it. It depends whether they pass in the middle of a square or on the edge of two squares. To make matters more complicated rabb[i/o]ts move at different speeds when performing actions. How will you make brollying rabbots wait for plummeting rabbits?!

Side note, should rabbots survive water because they don't breath, or die because electrics plus water is bad? Which leads to more puztunities?

**Comment by andybalaam** [comment]
My plan is to make rabbots' incoming rabbit detection a bit flawed, and pretend it's part of the charm of the game. 

Good question in your side note.

**Comment by GamingInky** [comment]
This is what I have been working on: https://github.com/GamingInky/rabbit-escape/tree/rabbots

**Comment by colonelfazackerley** [comment]
I read the commit messages. tabbots and yabbots, I see.

i want to spend my spare time trying to catch up with @tttppp's water work, so i probably won't build this for a while.

can you post gifs of the new animations?

**Comment by tttppp** [comment]
Looking good. Just the crossing over explosion left?

I propose rabbots are either immune to water or fire, as then they can get to places rabbits cannot. This would increase their value in certain circumstances, rather than just being something to steer away from your rabbits.

**Comment by andybalaam** [comment]
I really like that idea @tttppp. @GamingInky thinks they should survive in water and die in fire because they don't breath but can melt. Sounds good to me.

**Comment by andybalaam** [comment]
One point about all this. Rabbots have special animations for _all_ actions so they effectively double the download size. Maybe they make the case for adding svg rendering overwhelming.

**Comment by andybalaam** [comment]
Just to explain that:
1. SVGs are small
2. You only need 1 svg no matter what screen size, instead of needing 3 different sizes of png
3. We can modify svgs programmatically (at runtime if needed) to make variations e.g. making a rabbot red.

**Comment by colonelfazackerley** [comment]
still under 50MB.

could make a rabbot red from png.

**Comment by andybalaam** [comment]
You mean modify pngs at runtime?

**Comment by colonelfazackerley** [comment]
Yeah, might be slow. Should be possible to make a copy with different colours in.

**Comment by andybalaam** [comment]
If we kept it after loading it I don't expect it would be too slow.

**Comment by colonelfazackerley** [comment]
we could choose some odd colour, which we changed to rabbit or rabbot colour on loading.

means we would not need extra dependencies on SVG libs.

**Comment by andybalaam** [comment]
![animation](https://cloud.githubusercontent.com/assets/76812/13390775/570dbafc-dec8-11e5-835f-67c6fa43a0af.gif)

@GamingInky to make this I had to re-make `baddy_rabbit_crashing.rea`.  I think we forgot to add it to a commit?

**Comment by andybalaam** [comment]
@colonelfazackerley nice idea.  We should try prototyping this.  I have a feeling the SVG library is not compatible with API level 8, but could be wrong.  Would be very sad to exclude people.

**Comment by andybalaam** [comment]
@colonelfazackerley AnimationTester's gif generation ftw.

**Comment by colonelfazackerley** [comment]
Sweet.

looks like the springs/cogs are fading out instead of disappearing abruptly.

**Comment by andybalaam** [comment]
Yeah this is new and improved.

**Comment by GamingInky** [comment]
yes 😊 this is almost done

**Comment by GamingInky** [comment]
Rabbots are basically finished 😆 (https://github.com/GamingInky/rabbit-escape/tree/rabbots) we just thave to write a couple more tests and decide what to do about the download size.

**Comment by andybalaam** [comment]
There's still quite a bit to do before we can merge this, but the logic is working.  I am trying to build a working snapshot so people can experiment with levels.

To do:

1. Animations for drowning and burning rabbots
2. Automated test for missing rabbot animations
3. Tests for interaction of "waiting" and "crashing" with other behaviour e.g. falling, climbing, bridging, and walking up and down various slopes
4. Figure out what to do about download size: if it's OK, auto-generate rabbot animation frames when they are missing, and include all as PNGs.  If it's not OK, figure out how to generate rabbot frames at runtime.

Number 4 is the big one.

**Comment by tttppp** [comment]
For number 1, rabbots can't drown, at least according to our discussion above.

**Comment by andybalaam** [comment]
Ah, good point.  That is definitely not implemented.  To do amended.

**Comment by andybalaam** [comment]
1c. Animations for brollying rabbots

**Comment by colonelfazackerley** [comment]
How about a gif of the waiting anim? Do they tap their feet impatiently?

**Comment by andybalaam** [comment]
Currently they stand motionless but we were thinking of turning ominously towards the player with one eye glowing red.

**Comment by andybalaam** [comment]
Writing a script that replaces known colours in SVGs looks pretty easy (see 96ac62c ).  For now, we can recognise and replace the known colours to turn a rabbit into a rabbot, but if we have any trouble we can use the idea mentioned above by @colonelfazackerley and put fake colours into the original SVGs, and replace them for both rabbit and rabbots with the correct colour.

**Comment by andybalaam** [comment]
We discovered that several recent packaged versions of rabbit escape actually accidentally contained the PNG rabbot images, and were acceptable in size, so that answers that question!

**Comment by andybalaam** [comment]
I have merged the current work on rabbots from @GamingInky.  There is a fair bit more work to do, but it should be do-able.

I just noticed a bug: rabbots can enter the exit!

**Comment by andybalaam** [comment]
To do status:

* ~~Images for drowning, burning brollying etc.~~ done since we generate any missing images now
* Animation files (.rea) for missing rabbot animations.  Preferably, generate these when missing.  If not, automated test.
* Tests for interaction of "waiting" and "crashing" with other behaviour e.g. falling, climbing, bridging, and walking up and down various slopes
* ~~Figure out what to do about download size~~ done since it's < 20MB, phew
* Fix rabbots entering the exit

Later to dos:
* Rabbots survive in water
* More custom rabbot animations e.g.:
** turning (eye glint?)
** waiting (look at camera?)
** exploding (cogs?)
** burning (melt?)

**Comment by andybalaam** [comment]
```$ ls -sh dist/rabbit-escape-0.10.3.* | cat
18M dist/rabbit-escape-0.10.3.apk
20M dist/rabbit-escape-0.10.3.jar
```

**Comment by andybalaam** [comment]
```$ ./runrabbit swing -l development/unsorted/Bot.rel```

![rabbot](https://user-images.githubusercontent.com/76812/27416019-b90815d2-5702-11e7-97ee-7663b121e45c.gif)

**Comment by andybalaam** [comment]
Now make some levels!

**Comment by andybalaam** [comment]
I prevented rabbots entering the exit in 6c225a2

**Comment by andybalaam** [comment]
I will do some playing with creating levels and depending how buggy it looks I might make a release as-is, or I might need to add more tests for the waiting behaviour.

**Comment by andybalaam** [comment]
More todos:

* The "out" rabbit count should not reduce when rabbots die

**Comment by GamingInky** [comment]
made a new commit #481

**Comment by GamingInky** [comment]
New level Idea?
/home/kids/Desktop/Rabbot-Pactice-video.gif
(Sorry it's low res)

**Comment by GamingInky** [comment]
_To do status:_
    ~~Images for drowning, burning brollying etc.~~ **Done since we generate any missing images now**
    ~~Animation files (.rea) for missing rabbot animations. Preferably, generate these when missing. If not, automated test.~~ **Done**
    Tests for interaction of "waiting" and "crashing" with other behaviour e.g. falling, climbing, bridging, and walking up and down various slopes
    ~~Figure out what to do about download size~~ **Done since it's < 20MB, phew**
    ~~Fix rabbots entering the exit~~ **Done**

_Later to dos (not blocking a release I think):_
    Rabbots survive in water
    _More custom rabbot animations e.g.:_
        ~~turning (eye glint?)~~ **Done**
        ~~waiting (look at camera?)~~ **Done**
        ~~exploding (cogs?)~~ *Done**
        burning (melt?)
The "out" rabbit count should not reduce when rabbots die

**Comment by andybalaam** [comment]
Fantastic gif

**Comment by andybalaam** [comment]
The last todo is now done, so as far as we know we can release as soon as we have a new level set which includes some rabbot levels.

**Comment by GamingInky** [comment]
Yes, rabbots themselves are done but we need some levels please.
