### ISSUE TITLE
Subset of tests

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#115]
I am writing a few tests for the github interface. I am running them a lot. I code on the bus. "make test" is killing my battery.

Is there a good way to run the tests in one test class, or perhaps the tests for one package? I could write a little program to do it, but I fear I would commit it in error. I suspect there is a neat way to do this.

**Comment by andybalaam** [comment]
I'm pretty sure JUnit allows this but will need to research a bit to find exactly how. On a side point, does it really take more than about 5 seconds to run the tests? If so we should look into speeding them up.

**Comment by colonelfazackerley** [comment]
If you can give me a pointer to het

**Comment by colonelfazackerley** [comment]
takes over 7s to fail in a new test in swing package for the github api stuff. this is in my VM.

**Comment by tttppp** [comment]
Maybe I'm missing the point here, but can't you just run the junit package/class/method from Eclipse?

If you wanted to write a script and not commit it then you could edit the .gitignore file for the project to add a dev directory, or alternatively edit .git/info/exclude to add a file that you don't want to commit, without affecting anyone else.

**Comment by colonelfazackerley** [comment]
Oooh, that works very nicely. I have only just started using Eclipse, and I have not really used a java IDE heavily since 2003...

I just need to be told the obvious.

**Comment by andybalaam** [comment]
Ah sorry didn't realise just doing it in Eclipse would suffice :-)
