### ISSUE TITLE
Level: "Tree climb"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#12]
New level from @ColonelFazackerley:

    :name=Tree climb
    :description=There's no ladder
    :num_rabbits=4
    :num_to_save=3
    :rabbit_delay=15
    :bash=3
    :bridge=5
    :dig=2
    :block=1
    :explode=1
    :music=tryad-witness
                                  
                O  /#             
                #####             
                  ##              
                  ##              
                  ##########\     
          #       ###      ##     
         /#####\  ###             
         #    #######             
                 ####             
     Q           ####             
    \           /####\           #
    ##############################

**Comment by andybalaam** [comment]
Again, really like the look of this.  Again, a bit wide for some screens?  Solved it first time, but really enjoyed it.  I wonder whether there's a way to save all 4?
Thought: 5
Skill: 5

**Comment by andybalaam** [comment]
ColonelFazackerley: "I don't think there is a way to save all 4."

**Comment by andybalaam** [comment]
(Committed for now as new/level_03.rel)

**Comment by andybalaam** [comment]
I'll put it in as is.  If anyone figures out a way to save 4, we can have a harder variant.

**Comment by andybalaam** [comment]
Putting this one first because it's nice-looking and quite easy.

**Comment by tttppp** [comment]
I missed this level until now. Very nice. I couldn't save four either, but with a small tweak it becomes possible, e.g.
```
:name=Tree climb 2
:description=There's no ladder
:num_rabbits=4
:num_to_save=4
:rabbit_delay=15
:bash=3
:bridge=5
:dig=2
:block=1
:explode=1
:music=tryad-witness
                              
            O  /#             
            #####             
              ##              
              ##              
              ##########\     
      #       ###      ##     
     /#####\  ###      ##    
     #    #######             
             ####             
 Q           ####             
\           /####\           #
##############################
```

**Comment by andybalaam** [comment]
@tttppp please propose this as a new level if you think it's nice.  I'll miss it if it festers here.

**Comment by tttppp** [comment]
I think the solution is basically the same as the original, all it adds is a way to save the last rabbit (using the leftover tokens).

**Comment by andybalaam** [comment]
Are you proposing it as an update?  @colonelfazackerley do you prefer this?

**Comment by colonelfazackerley** [comment]
There's a lot a levels where every rabbit must be saved by freeing blockers. I like the original. It's quite relaxing to just pop the last bunny and move on once in a while.

**Comment by andybalaam** [comment]
Agreed.

**Comment by tttppp** [comment]
+1 There's not enough nuking in some of these levels. ;-)

**Comment by andybalaam** [comment]
Nuking ftw

**Comment by andybalaam** [comment]
I modified this in commit a1ea44455d77a9a197c45973c8e27b07817091bc to look like the Deja Vu level #113 "Tree, tree, tree again" which I know is a bit of a cheat, but hey.

**Comment by andybalaam** [comment]
Is there any interest in using @tttppp 's modified level (comment https://github.com/andybalaam/rabbit-escape/issues/12#issuecomment-147067275 ) somewhere else?

**Comment by tttppp** [comment]
I don't think my modification was very interesting.

The Deja Vu level for this seemed well thought out. Just the right number of tokens to misdirect me!

**Comment by andybalaam** [comment]
Agreed. Yeah it's a good one.
