### ISSUE TITLE
Bug: scrollbar half hides token buttons

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#128]
If the window height is shrunk enough for vertical scrolling to be necessary in the token button pane the vertical scrollbar appears. It hides half of each button. What is the best fix?
- have some blank space for the bar to occupy when it appears?
- don't let the window height go that small (maybe a problem if lots of token types are introduced)
- widen the token button pane when necessary (may make the main pane jerk oddly to the right).
- drag the pane to scroll (have no scrollbar)

**Comment by andybalaam** [comment]
I prefer the third option (widen when necessary) if it's possible.

**Comment by andybalaam** [comment]
Since I added the number of tokens remaining, the bar is wider, so this problem has gone away.  If you spot it somewhere, please re-open this issue.
