### ISSUE TITLE
Idea: allow standing on blockers

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#131]
Possible feature idea for your comment. What if rabbits could stand on blockers? Then you could use them to break falls and build structures. You could even pile blockers on blockers. ..

**Comment by tttppp** [comment]
Potential game changer! This would need all the existing levels to be replayed, to see if it opens up new trivial solutions. I really like the idea though.

Might also need some graphics changing?

**Comment by colonelfazackerley** [comment]
Probably a lot of hassle, but it would be cool if the blocker-come-acrobat moved forelimbs up when another rabbit stood on them.

**Comment by andybalaam** [comment]
@colonelfazackerley yeah, that would be cool. @tttppp we would definitely need to test all levels, yes.

**Comment by andybalaam** [comment]
Too controversial for now.  Maybe one day.
