### ISSUE TITLE
RFC: exits and behaviour trigger order.

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#135]
with the fix I am thinking of for exit-prevents-splat the following happens.
```
  r   
 O# r 
  # # 
rc#   
###   
   O O
```
It is possible to climb into exits.
Rabbits always fall past exits.

This looks OK to me.

**Comment by tttppp** [comment]
Looks fine to me too. What would happen in the following case?
```
rO
# 
```

**Comment by colonelfazackerley** [comment]
Rabbits consider falling before exiting, so they miss the exit and fall. I think that's OK.

**Comment by tttppp** [comment]
The other cases I wondered about were rabbits on slopes with exit 'hovering' above the slope. I have a feeling that they don't actually go 'through' the exit square, and so can't exit. Great stuff!

**Comment by colonelfazackerley** [comment]
As far as the code is concerned, they are on the slope square: they don't go through the square above the slope. I am used to this now, though it is awkward for the animations.

The obvious solution is that everyone is forced to play in text mode.

**Comment by andybalaam** [comment]
lol.  I will read this properly when my head is less full of snot.

**Comment by andybalaam** [comment]
OK, I see what you are getting at in #142.  I think I'm ok with it if you two are.

**Comment by andybalaam** [comment]
Is this issue ready to be closed?

**Comment by colonelfazackerley** [comment]
yes, I just opened it to discuss what everyone thought should happen. I think everyone is happy with the behaviour interactions resulting from the behaviour order.
