### ISSUE TITLE
Fix animation of falling to death on slopes

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#138]
See TODOs here:

https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/engine/behaviours/Falling.java#L125 

I am not aware of a problem with falling on to slopes. Are these TODOs obsolete? If not please elucidate.

**Comment by andybalaam** [comment]
The animations look bad, that is all.  I plan new states and new animations for dying from falling onto slopes.

**Comment by colonelfazackerley** [comment]
I see, that makes sense.

**Comment by colonelfazackerley** [comment]
The animation looked OK in my branch for #210

now I that is merged, and I have updated, it looks wrong. The offsets are not correct. I cant see how this was broken.

now the rabbit is too low, under the slope's surface as it crumples.

**Comment by colonelfazackerley** [comment]
I could tweak the offsets, but that might be a waste of time, depending on what the cause is.

**Comment by colonelfazackerley** [comment]
If I use the test level (as opposed to the anim tester), it seems to have different frames in.

**Comment by colonelfazackerley** [comment]
:-s

**Comment by andybalaam** [comment]
Annoying. I will look into this when I get time but it won't be very soon. It sounds like there is still a bug in the animation tester.

**Comment by colonelfazackerley** [comment]
with this test level
```
j
 
 
 
 
(
```
I got it to print rabbit states:
RABBIT_FALLING
RABBIT_DYING_OF_FALLING_SLOPE_RISE_RIGHT
RABBIT_DYING_OF_FALLING_2


which explains why I am seeing frames from the wrong animation, after mine. (But not why this appeared...)

**Comment by andybalaam** [comment]
Ah. Is it fine if the rabbit falls one square further? If so then this is because the rabbit is hitting the ground halfway through a time step. There is one animation for a death that happens all in one time step and 2 more for a death that spans 2 time steps. The images are the same, but the .rea files are different.

**Comment by colonelfazackerley** [comment]
i think it is that, but I don't understand why I did not see this in my branch. i deleted it after the merge, so I can't look now.

**Comment by colonelfazackerley** [comment]
I guess part of the explanation may be that I forgot to push the last commit.

**Comment by andybalaam** [comment]
Is this done?

**Comment by colonelfazackerley** [comment]
Yes

**Comment by andybalaam** [comment]
After playing a bit I think the rabbit bits should fall sideways a bit more as they splat. I'm very happy with it as it is but would be even happier if we made that change. I guess I should open a new issue.
