### ISSUE TITLE
Level: "Home sweet home"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#14]
New level from @ColonelFazackerley:

    :name=Home sweet home
    :description=Save the chimney bunnies!
    :num_rabbits=8
    :num_to_save=6
    :rabbit_delay=4
    :bash=3
    :bridge=5
    :block=2
    :explode=2
    :music=tryad-witness
                                  
                 /## #            
                /### #            
               /#    #            
           Q  /#     #            
             /#      #\           
            /####### ##\          
           /      #     \         
           #      #     #         
           #      #     #         
           ##############         
           #    #       #         
     Q     #    #       #         
           #    #       #      O  
     #############################

**Comment by andybalaam** [comment]
Nice looking.  I saved all 8 on the first attempt with just 3 bashers along the bottom, and 2 diggers at the top to get the top ones down.  Was another solution intended?
Thought: 3
Skill: 5
(Committed for now as new/level_06.rel)

**Comment by andybalaam** [comment]
ColonelFazackerley: "Leaving any diggers in was an error. I havve fixed this. See what you think now."

**Comment by andybalaam** [comment]
Yeah, tricky.  Took me several goes, but I managed 6 with a blocker at the top and one under the exit, and a bridge to save those falling from the top.
Thought: 7
Skill: 8

**Comment by andybalaam** [comment]
Let's put this in as-is.

**Comment by colonelfazackerley** [comment]
Sounds like my solution.
