### ISSUE TITLE
Test that all levels can be solved (automated)

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#140]
I am working on a unit test that runs all available solutions. When we have solutions for all levels we can make the test fail if a level we ship has no (winning) solution. 

I will be hoping for help with authoring solutions. You can do this using `make runmenu`. At the moment you have to be on the `solutionChecker` branch but soon I will merge the required fixes into`master`.

**Comment by colonelfazackerley** [comment]
Absolutely. when it is merged to master, I will do 20 or more level solutions.

**Comment by andybalaam** [comment]
Test that runs all solutions was introduced in 281466b9f03d87c64fa0045466dceaf441dd5930 as `TestAllActiveLevels.All_solutions_are_correct`

**Comment by andybalaam** [comment]
This is now merged into master.

**Comment by colonelfazackerley** [comment]
I will start work on solutions for the hard set.

**Comment by andybalaam** [comment]
Cool, thanks.  2 things to note:
1. I realised I never actually tried to see whether the test fails when a solution fails
2. It doesn't currently ensure at least one solution is a genuine solution (i.e. ends up with state WON)

**Comment by andybalaam** [comment]
As mentioned in #145 we need to ensure that all levels have at least one solution that ends with WON.

**Comment by colonelfazackerley** [comment]
#164 for hard set.
I will start the outdoor set next.

**Comment by andybalaam** [comment]
#164 is merged

**Comment by colonelfazackerley** [comment]
I am also working on this for the arcade set. I have to play the arcade set anyway to get the order roughly right. I thought I may as well play them in text mode and get the solutions. 

I had been using 'until' in them, which I have now rebased away to sync with upstream. So now 'make test' fails in the arcade branch.

I am about 70% through solutions for the arcade set.

**Comment by andybalaam** [comment]
Thanks for all your work on this.

**Comment by andybalaam** [comment]
I believe I have now committed all that is needed for until to work.  Please let me know if I haven't.

**Comment by andybalaam** [comment]
Should we close this issue, or are you tracking your work against it?

**Comment by colonelfazackerley** [comment]
I think this should stay open until all the levels in the repo have solutions in.

**Comment by tttppp** [comment]
I can't see anything in @colonelfazackerley 's repo for the outdoor set, so I'm going to try to make a couple of outdoors solutions now.

**Comment by colonelfazackerley** [comment]
I will do the easy set.

**Comment by andybalaam** [comment]
Brilliant, thanks. I think the test should fail if any level in an official set has no successful solution,  so let's leave this issue open until we implement that.

**Comment by colonelfazackerley** [comment]
Looks like no one else is doing medium, so I will.

**Comment by andybalaam** [comment]
You are a hero.

**Comment by tttppp** [comment]
Is this complete? It looks like it's done.

**Comment by colonelfazackerley** [comment]
yes, this can be closed.
