### ISSUE TITLE
Enhancement: Solution simplifier

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#144]
When recording a solution using the command line game interface, the solutions are very verbose. It would be good to combine wait instructions in particular, but also strip out extraneous changes of selected token.  There might be other things too which could be simplified?

I've made a start on this in https://github.com/tttppp/rabbit-escape/tree/recordingSimplifier and if anyone wants to get it  to a state where it can be merged then just add a note in this thread.  I think it needs the output string constructing and a test.

**Comment by andybalaam** [comment]
I haven't looked at this yet, but as a general comment I'd prefer to be constructing a list of `Instruction`s and converting that back into a string.  It would make this cleaner, and be better style.

**Comment by tttppp** [comment]
I felt similarly, so that's what I've done. The downside is that it requires converting back to a string at the end, which is one of the outstanding issues I mentioned above.

I'm hoping we can get this in before too many solutions are created, as it should make much shorter solutions that are less memory intensive. I guess we could always apply it retrospectively.

**Comment by colonelfazackerley** [comment]
I see what you mean

:solution.1=8;bridge;;;(12,7);;(12,7);;;;;;;;(10,6);;;;;;;(13,4);;;;;4;2;2;2;2;;;1
:solution.1.code="Rccd6cc!c!c!d8(cRhccccd?dch!cc(!c8ZcRc(clccgOc^cRu(cC6c~cdc!ccchccchc

for now, i intend to manually clean up the solution. if i do this for a bunch of levels. what's the best way to obfuscate? (We will have the same issue with the hints).

**Comment by andybalaam** [comment]
The production levels should not be obfuscated. We only need obfuscation when sharing levels with each other in source form.

**Comment by andybalaam** [comment]
Is this done?

**Comment by andybalaam** [comment]
Yes, it is :-)
