### ISSUE TITLE
RFC: Instruction to run until completion

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#145]
When using the text interface or authoring a solution it would be very useful to be able to say "Keep executing steps until the level is finished."

This could lead to never ending solutions that effectively lock the application.

We could work around this by recording current states and searching for a loop, but this might require a large amount of memory, particularly when different rabbits had coprime periods.

We could have a hard limit, but what would be a sensible value? Would a hard limit be intuitive?

**Comment by tttppp** [comment]
I also meant to mention the tortoise and hare cycle finding algorithm which would reduce memory usage, but still might take a long time to complete.

**Comment by andybalaam** [comment]
I suggest a hard limit of about 1000 time steps. This would be fine for almost all realistic levels (who wants to play a level longer than that? ) but could be worked around in exceptional cases with a long wait instruction.

**Comment by tttppp** [comment]
That sounds good to me. Any thoughts on the command notation? Maybe:
```
:eventually(WON)
```
Or maybe something more friendly like:
```
resolve
```
We could allow resolve to be followed by an assertion instruction.

**Comment by colonelfazackerley** [comment]
i like this.
```
bash;(10,10);until;WON
```
where until means keep stepping until the level plays out.

I don't mind your suggestions either, though I am not keen on using brackets. I like those reserved for coordinates.

not sure why use colons instead of semi-colons too.

**Comment by tttppp** [comment]
The colons were because I was being a fool. I like "until".

**Comment by andybalaam** [comment]
I like until.

**Comment by andybalaam** [comment]
Does anyone have any plan on how to know that there is at least one winning solution?  Should the checking code just keep a note of any solution that ends with WON, and complain if there are none?

**Comment by colonelfazackerley** [comment]
yup sounds OK. every level that is a fully installed part of the game should have a solution ending in WON.

**Comment by tttppp** [comment]
Having just created a prototype of this, I think it should be:
```
until&WON
```
rather than
```
until;WON
```
Anyone think colon makes more sense?

**Comment by colonelfazackerley** [comment]
Either looks good to me.

**Comment by andybalaam** [comment]
Yes, semicolon is bad because it implies a separate time step.

**Comment by andybalaam** [comment]
I actually quite like the idea of colon since until should never exist without a corresponding state. Anyway I hope to look at your pull request tonight.

**Comment by tttppp** [comment]
I started work on this in a branch. The discussion can be seen in this (closed) pull request:
https://github.com/andybalaam/rabbit-escape/pull/165

Summary:
 * The code used seemed to work most of the time.
 * Unit tests are needed.
 * There is a bug that colonelfazackerly found when using the command in the text UI.
 * Andy thinks the command should contain the end state (e.g. "until:WON" rather than "until). (For what it's worth I think he might be wrong* on this, but mainly because "until" is easier to type in the text UI).
 * There should be some exciting event (like an exception) if the level is not complete after 1000 steps. Or possibly not, which would allow for finishing a 2000 step wait level with "until&until&WON".

* Footnote: Andy is never actually wrong, but freedom of thought allows me to think this.

**Comment by colonelfazackerley** [comment]
I think in the text ui, you should just type "until", and it then tells you whether you WON or LOST.

I think the solution text mode reports back should include WON on the end.

I had to rebase this

"Add support for UntilInstruction." https://github.com/andybalaam/rabbit-escape/commit/f677c4f9c36f4c38f35536be60181dba6acaf8e5

away to avoid conflict with Andy's work last night. Could the "until" command be implemented again, but be compatible with the current master?

**Comment by andybalaam** [comment]
It will need to be implemented differently, in SolutionExecutor. Should be reasonably similar to the WaitAction.

**Comment by andybalaam** [comment]
I am often wrong and am very happy to see what you think is useful here - I don't have strong opinions.

**Comment by andybalaam** [comment]
I was thinking of `until`as an assertion that we finish (in a given state) without further interaction but seeing it as just a variable-length wait makes sense and may be more useful and flexible.

**Comment by colonelfazackerley** [comment]
I am working on this now. please let me know if you have done some already

**Comment by andybalaam** [comment]
I haven't.

**Comment by andybalaam** [comment]
Btw I'd be happy for `until` to be an abbreviation for `until:WON` but I'd also be happy for until to just be a variable length wait.

**Comment by colonelfazackerley** [comment]
I intend for any completion state to be valid after the colon.

**Comment by tttppp** [comment]
@colonelfazackerley Sounds great! I haven't done anything outside the code on the branch. I'm happy for you to use that or start afresh.

**Comment by andybalaam** [comment]
This is done in 944b6dad3e9565e62a086f67c96078793443b61c.  If we want to enhance/fix any of it, let's open a new issue.
