### ISSUE TITLE
Make unit tests check opposite rabbit orders

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#151]
Many unit tests use `assertWorldEvolvesLike`.  This already checks that the world you gave works how you say it should, and also that the exact mirror image works as an exact mirror image of what you said.  It should also check that the same level with the order of rabbits in the rabbits array reversed has the same behaviour, if that can be reasonably easily done.

**Comment by andybalaam** [comment]
Here is a demonstration of some of the inconsistent behaviour we have at the moment:

![immediate-block-inconsistency](https://user-images.githubusercontent.com/76812/57127147-5ffdec80-6d87-11e9-9c71-7fbf5872819f.gif)

**Comment by andybalaam** [comment]
To fix this we may need to modify the way we calculate rabbit behaviour.

Here is an example of a test that fails:

```
kjj  // 2 rabbits approach a token
###

H|   // The first becomes a blocker,
###  // the second gets blocked and turns
```

The above test passes if the left-hand rabbit is first in the order,
because it becomes a blocker before the right-hand rabbit looks to see
whether there is a blocker in front, but fails if the right-hand rabbit
is first because it looks for blockers before the left-hand rabbit becomes
one.

There are 2 ways I can see to make this behaviour consistent (assuming we
want to ...?):

1. Have a order of abiities, so e.g. becoming a blocker is earlier than
walking, and evaluate all rabbits to find out whether they block before
we evaluate any for whether they walk.

2. Keep changes to rabbits "secret" from other rabbits during processing
of a time step, so that if someone becomes a blocker at the exact moment
you try to walk past them, you will definitely walk past because you don't
see that they are a blocker until the next time step.

Note that both the above do not fix every single order-dependency problem -
we always have the question of who picks up a token if two rabbits are on
the same square.  This can be important if one of the two already has some
other ability - so you want one rabbit to be a climber and the other to
have a brolley, but you end up with one who is both instead.  I don't see
this as a big problem because the player will probably not feel unfairly
treated in that case.

I am torn on this because I feel like it's hardly worth the effort to fix,
but the above test case does seem weird that it woud behave differently
depending on this secret property of a rabbit which is its order in the
list.

What do you think @tttppp @colonelfazakerly @GamingInky ?

**Comment by tttppp** [comment]
We definitely had this discussion before, because @colonelfazackerley added the rabbit order as information displayed on the pause screen.  We definitely knew it was important at that point.

I think we still need the rabbit order because different rabbits can have different attributes. For example imagine a level where a floater and normal rabbit are overlapping and you need to give the floater a climb token to win. Only one of the rabbits can get the token, and the ordering is what determines whether the level is possible or not.  If you had a test for this then it would fail when the rabbit ordering is reversed.

**Comment by tttppp** [comment]
Also I think that your option 2 ("Keep changes to rabbits "secret" from other rabbits") will break existing levels. I'm sure we will have relied on the ability to place a blocker like you did on the left of your gif.

**Comment by tttppp** [comment]
I think option 1 should be ok, but it doesn't remove the need for rabbit ordering, and it adds a new arbitrary ordering for players to somehow learn.

**Comment by andybalaam** [comment]
I feel bad about the case I documented above, but I agree that:
* we won't be able to eliminate rabbit order from logic entirely
* option 2 would likely be disruptive to existing levels and not be a very nice behaviour for players (I prefer the left-hand behaviour in my gif to the right-hand one)

In addition option 1 is annoying to implement and complex to understand.

So probably option 1 is a good choice but I have no immediate plan to actually do it, so I will close this issue.  If someone wants to work on it, I will gratefully accept patches, so long as all the tests pass, and the implementation is not incredibly complicated.
