### ISSUE TITLE
Enhancement: Discussion: command line interface

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#154]
- refactor to have a single class with a main(). 
- have a bash script called "re" that hides away the java call and classpath stuff. it takes arguments and passes them all on to the main().
- similar bat for win cmd.
```
re                         default is to start swing ui
re text                    start text ui
re swing                   also an option, for completeness
re swing ~/some/level.rel  bypass all menus and start a level
re text solution.1 lvl.rel step through solution.1 in lvl.rel rendering each step 
```

**Comment by colonelfazackerley** [comment]
Android ui may need to keep it's own main(). I have not looked at that.

**Comment by colonelfazackerley** [comment]
It occurs to me that that we could analyse solutions to determine how hard they are. If we have a few solutions they can be used as an index of how hard the level is. Things indicating a solution is hard
- lots of token drops required
- need to equip different token types
- time critical token placement. (can run the solutions a few times moving token drops in time and see if they still lead to WON)
- position critical token placement.

Could put these together and rank the levels in a set. 

I realise this would not be a high priority, but it sounds interesting to me, so I might do it. (when the solutions playback works).

I put it here because it's an obvious thing for the CLI.
```
re difficulty ~/some/level.rel
re rank_difficulty ~/level-set-dir/
```

**Comment by tttppp** [comment]
The AI level analyser sounds great fun and should be a different enhancement ticket. Amazingly thought though.

**Comment by andybalaam** [comment]
AI analyser will be fun but will find it hard/impossible to rank for "non-obviousness". Ranking for skill as you describe sounds doable.

**Comment by andybalaam** [comment]
Yes I have been thinking similarly about one or more launch scripts.

**Comment by andybalaam** [comment]
@colonelfazackerley is working on this via pull requests, so closing.  Re-open if we still need it.

**Comment by colonelfazackerley** [comment]
The stuff I mentioned works now (apart from the analyser).
