### ISSUE TITLE
Level: "Asteroids"

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#156]
```
:name=Asteroids
:block=2
:bridge=3
:rabbit_delay=8
:num_rabbits=7
:num_to_save=5
:explode=2
               
Q            # 
        ##     
##     O####   
##   #  ####   
     #  ###    
               
  ###      *## 
   ##     #####
           ##  
#              
     ##        
:*=cccccc
```
Should be enough for the arcade set with this.

**Comment by colonelfazackerley** [comment]
merged to master f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a

**Comment by andybalaam** [comment]
Totally stuck! Loving it.

**Comment by colonelfazackerley** [comment]
@tttppp have you completed this one?

I think it is a little fiddly, but not as hard as some.

**Comment by tttppp** [comment]
Not yet.  I haven't tried many of the arcade levels (except the ones I wrote!)  I'll start on arcade now and see how far I get.

**Comment by tttppp** [comment]
After having to fiddle with my path to get the right java I eventually failed pacman :-(  Better luck next time!

**Comment by andybalaam** [comment]
Got it! I realised I had assumed there were 5 climbing tokens in the pile. With 6 this is nothing like as hard as I made it! Good level though.

**Comment by tttppp** [comment]
I just solved this on my phone. Took me two goes, and the first was because I guessed the number of climb tokens wrong.

Some of the earlier levels caused me much more pain! The Matrix, Invader and Breakout were the worst.
