### ISSUE TITLE
Level: "Saw"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#16]
New level from @ColonelFazackerley:

    :name=Saw
    :description=One way
    :num_rabbits=6
    :num_to_save=4
    :rabbit_delay=5
    :bridge=7
    :dig=3
    :block=2
    :music=tryad-witness
                             
                             
                       Q     
                             
       O                /### 
     ///////////////// /#  # 
     ####################  # 
     #######################

**Comment by andybalaam** [comment]
Intruiging at first glance.  Quite easy because there's only really one solution.  Different, though.  With 1 more bridger I reckon I could save 6.  [Rabbits don't move very pleasingly in this level - several graphic glitches are exposed.]
Thought: 2
Skill: 4
(Committed for now as new/level_08.rel)

**Comment by andybalaam** [comment]
ColonelFazackerley: "Perhaps best to leave this one out of the game, until said glitches are fixed. I was trying to play with the enforced one way flow effect of the slope tiles."

**Comment by andybalaam** [comment]
Nah, just a good reminder to fix all those animation glitches.  Let's put it in.

**Comment by andybalaam** [comment]
Moved to be the second level in the new set because it's quite easy, even though it's a bit unattractive.

**Comment by andybalaam** [comment]
(Or rather, it makes the game look unattractive...)

**Comment by andybalaam** [comment]
Add an exploder to finish off the blocker.

**Comment by tttppp** [comment]
I really like this level. It's challenging without being unforgiving, and it looks good too.
