### ISSUE TITLE
Level: "Oh we do like to be beside the tree-side"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#160]
My alternative version of #113:

```
:name=Oh we do like to be beside the tree-side
:description=Wait, can rabbits climb trees?
:author_name=tttppp
:author_url=https://github.com/tttppp
:num_rabbits=4
:num_to_save=4
:rabbit_delay=15
:bash=20
:bridge=20
:dig=20
:block=20
:explode=20
:music=tryad-empty

            O  /#  
            #####  
              ##   
              ##   
              #####
      #       ###  
     /#####\  ###  
     #    #######  
             ####  
 Q           ####  
#           /####\ 
#################  
```

**Comment by andybalaam** [comment]
Really wishing I could try these levels on my phone. Will get to this as soon as I can. (Bypassing permissions problem by just copying and pasting.)

**Comment by colonelfazackerley** [comment]
have not tried this yet. I would like it for "deja vu".

did someone say they wanted the deja vu levels to be very similar to the original?

if not, it makes enough sense for paradise.

**Comment by tttppp** [comment]
I think this doesn't qualify for deja vu, because the layout is different from the other levels. It could be a paradise or other level though. It would go really well in my tongue-in-cheek proposal of a tree themed set (along with Forest and Tree Tree Tree Again). Fun times!

**Comment by tttppp** [comment]
The original of this level has changed since I made this, so I don't think it's really a Deja Vu level. Oh well, I'm sure no one will notice  :-)

**Comment by andybalaam** [comment]
Ah well, it's vaguely familiar anyway

**Comment by tttppp** [comment]
Released in Deja Vu.
