### ISSUE TITLE
Bug: text mode: given one more time step than requested

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#161]
Hopefully this explains why the solutions given by text mode don't work.
```
00 Q            
01  r           
02 #############
03              
   0000000000111
   0123456789012


Type 'help' then press return for help.
> 1

00 Q            
01    r         
02 #############
03              
   0000000000111
   0123456789012


Type 'help' then press return for help.
> 2

00 Q            
01   r   r      
02 #############
03              
   0000000000111
   0123456789012


Type 'help' then press return for help.
> 3

00 Q            
01   r   r   r  
02 #############
03              
   0000000000111
   0123456789012

```

**Comment by colonelfazackerley** [comment]
I made a simple level that has some critical timing
```
:name=Critical timing
:bridge=1
:num_rabbits=2
:num_to_save=2
:rabbit_delay=4
O Q   
#    #
#p####
######
```

After winning, text mode reports
```
:solution.1=1;1;bridge;(2,1);1;1;1;bridge;1
:solution.1.code=;)T|pT[bdpTT)i)TT:))1Tb.))di[)|
You won!
```

removing the spurious 1 it added at the end, and adding 1 to each wait instruction that I gave worked
```
:solution.1=2;2;bridge;(2,1);2;2;2;bridge;WON
```

this was against latest master

**Comment by colonelfazackerley** [comment]
This also works against latest iterable-solutions branch.

So, text mode just needs a quick fix and we can get writing the solutions.

(I will leave the bug fix for you guys, unless you ask me).

Also pleased that my existing few hard level solutions should be OK.

**Comment by tttppp** [comment]
The spurious 1 at the end was the 'fix' I added when testing my solution to Easy 1.

**Comment by tttppp** [comment]
I've made the text UI compatible with the solution runner now. It also does simplification of the waiting.
https://github.com/tttppp/rabbit-escape/tree/recordingSimplifier

Have a go and let me know if it works for you. I've tested it with Easy 1 and Hard 1, and the solutions output from the text UI are now functional.

**Comment by andybalaam** [comment]
@colonelfazackerley is this fixed in master now?  @tttppp do we still need the changes you made?

**Comment by colonelfazackerley** [comment]
yes it is fixed in master.

**Comment by tttppp** [comment]
I just checked, and we already have the changes I made.  I failed to link to this issue though.  Great to hear that the bug's fixed!
