### ISSUE TITLE
Enhancement: Abbreviations for commands in text mode

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#162]
When playing in text mode allow 4,4 as well as (4,4)

**Comment by andybalaam** [comment]
Seems sensible to me

**Comment by tttppp** [comment]
This sounds convenient, so +1 from me. I think it would be worth discouraging in solutions (e.g. using stern looks), as it makes them slightly less readable.

**Comment by colonelfazackerley** [comment]
I think brackets around coordinates in solutions should be mandatory. The text ui would add them for you when reporting the solution back.

**Comment by tttppp** [comment]
I thought having two distinct instruction languages might get confusing, and require extra code. I agree that reporting back solutions using brackets makes sense.

**Comment by andybalaam** [comment]
Command line mode is already a distinct dialect as Enter translates to `;`. I was thinking of allowing unambiguous abbreviations of commands e.g. W for WON in command line mode but definitely not in solutions.

**Comment by colonelfazackerley** [comment]
I was thinking i for bridge, k for block, etc would be nice. (In text ui, not in solution strings).

**Comment by andybalaam** [comment]
You mean the same characters as in level files? Makes sense.

**Comment by colonelfazackerley** [comment]
Yes, that's what I meant. 

I was also thinking it would be useful to allow multiple actions to be entered at once by separating with ';'. When developing the solution for a complex level it would be possible to copy-paste the solution up until it went wrong.

I mention this, as it would change how the other things discussed here are implemented.

**Comment by tttppp** [comment]
I've tried pasting partial solutions in too. It would definitely speed up solution writing. In a ten step solution it's too easy to accidentally type instruction 9 straight after 7. Another useful feature would be undo.

**Comment by andybalaam** [comment]
Yes, good ideas. Undo sounds cool but likely should be a separate issue. I had an idea for a "time slider" (essentially easier to use undo) for the level editor I am designing in my head.

**Comment by andybalaam** [comment]
Fixed in ddde558f18a2d056825e1c9cfe2b5a8cbd024f39
