### ISSUE TITLE
'make runmenu' should not result in png files being created

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#166]
fresh clone
make runmenu
...

**Comment by andybalaam** [comment]
It needs pngs to run successfully. But, I do like your idea of run scripts that are outside of make (and therefore assume make has been called already).

**Comment by colonelfazackerley** [comment]
Why does the text ui need png files?

**Comment by andybalaam** [comment]
Ah sorry totally missed that you were talking about the text ui.

**Comment by andybalaam** [comment]
Agree

**Comment by GamingInky** [comment]
I get what you mean but it sounds quite hard to do
