### ISSUE TITLE
Level: "Re-entry"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#17]
New level from @ColonelFazackerley:

    :name=Re-entry
    :description=
    :num_rabbits=6
    :num_to_save=4
    :rabbit_delay=10
    :bridge=1
    :dig=3
    :block=2
    :bash=3
    :music=tryad-witness
                  #####  
                 ##   ## 
                ##     ##
                #       #
                #   Q   #
                #       #
                ##     ##
           /\    ##   ## 
          /  \    #####  
         /    \          
        /Q     \         
        #      #         
        ########         
        #      #         
        #      #         
        ########         
        #      #         
        #      #         
        ########         
        #      #         
       /#      #\        
      /##########\     O 
    #####################

**Comment by andybalaam** [comment]
Big, fun-looking.  Quite large for some screens.  Thought it was easy to save them all, but was fooled by the drop from the moon to the rocket being too far.  Was able to save 3 extremely easily by just digging and bashing inside the rocket.  Presumably the challenge is to save one of the ones in the moon.  Was able to save all 3 of them by using issue #8 (falling direct onto exit) but assume that is not the intended solution.  (I hope not, because I think that is a bug that should be fixed.)  Was able to save 5 by bridging from rocket towards moon, which I presume is the intended solution?
To get 3: Thought: 3, Skill:1
To get 4 without cheating: Thought: 8, Skill: 7
(Committed for now as new/level_09)

**Comment by andybalaam** [comment]
ColonelFazackerley: "I shrank the level, and upped the escape criterion to 4. I can get 5 too, sounds like I use the same plan as you."

**Comment by andybalaam** [comment]
OK.  If 5 is possible, I reckon we want hard levels where possible, so I'll change it to 5.  Other than that, it's in!

**Comment by tttppp** [comment]
I enjoyed this level. Nice design as well as a challenge to find the right solution (it's a bit counter intuitive I think). I (like Andy) thought the moon-rabbits could just drop onto the rocket - SPLAT!
