### ISSUE TITLE
Discussion: "num_rabbits" is the wrong name

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#174]
Something like "num_entering" is better, as it is the number that will use the entrances if the level is allowed to run long enough. It is legitimate to have "num_to_save" greater, if there are some r and j in the world's ASCII art.

**Comment by andybalaam** [comment]
Yes, but is it worth the backwards compatability nightmare of changing it?

**Comment by andybalaam** [comment]
Compatibility

**Comment by andybalaam** [comment]
Stupid autocomplete

**Comment by colonelfazackerley** [comment]
I will see if I am feeling energetic one day. I agree it's not the highest priority.

**Comment by andybalaam** [comment]
I feel like it's unlikely we will change this, so closing for now.  Feel free to reopen or make a new one if you want to do it.
