### ISSUE TITLE
Enhancement: Visible edge of world

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#176]
The edge of the world should be more visible so that the player knows not to try bridging or climbing into it.

I suggest that a slightly different background is drawn that gives an impression of being in space, or in some sort of vaporiser.

The same graphic could be used for the enhancement of "death squares", so it might be worth making sure the image works ok ad a standalone square.

**Comment by colonelfazackerley** [comment]
For "death squares" I like wavey blue lines like the sea. Possibly animated, but that might be too annoying.

For the end of the world, I like light grey scribbled shading. Like the blocks but lighter.

**Comment by andybalaam** [comment]
Yes, all sounds good.

**Comment by colonelfazackerley** [comment]
I have been working on showing the void beyond the edge of the world. I have this. I was going to do all 4 sides, but I am not sure I like it.
![void_prototype_scribble](https://cloud.githubusercontent.com/assets/9596719/12385469/57504546-bdb4-11e5-93c5-ff67f85fef63.png)
options;
- make the scribbling around the edge thinner and more transparent
- go for something that looks like hand drawn hatching, but is a little neater than the scribbling above.
- aim for a yellow highlighter look:  a box drawn around the edge.
- aim for it to look like the graph paper has been ripped off just outside the world.

**Comment by colonelfazackerley** [comment]
neater hand drawn look hatching. Again I would put this around the whole edge, but this is just a quick mockup.
![void-hatching](https://cloud.githubusercontent.com/assets/9596719/12391114/4fc61e9e-bddd-11e5-8942-0c521999f9d8.png)

**Comment by colonelfazackerley** [comment]
Highlighter dashes option. This is my favourite so far. I would go all around with it and do 4 variants of the dashes for each side.
![void-highlighter-dashes](https://cloud.githubusercontent.com/assets/9596719/12398806/dbfca178-be0d-11e5-8494-feae6fd674fb.png)

**Comment by tttppp** [comment]
Highlighter is my favourite so far too.

**Comment by colonelfazackerley** [comment]
torn paper. i quite like this one too, again, I will do more variants.
![void_paper_rift](https://cloud.githubusercontent.com/assets/9596719/12401143/799e3762-be1c-11e5-9a6d-c8a3c0e8122c.png)

Let me know the winner and I will do a pull request.

**Comment by colonelfazackerley** [comment]
Which is best? highlighter dashes or ripped paper? Or does anyone have other ideas that I should try?

Let me know and I will finish a pull request.

**Comment by andybalaam** [comment]
Wow you've put a lot of effort into this! Fantastic! I can't decide but will think on. Maybe we could use several?

**Comment by colonelfazackerley** [comment]
You mean in the rel file, you can choose the style you want?

**Comment by andybalaam** [comment]
Maybe, or random.

**Comment by andybalaam** [comment]
Thoughts so far: if torn paper could be done so it doesn't look silly, I think it will be the best. But I think there's a decent chance we won't manage to avoid it looking silly. If so, marker pen is very cool and less likely to look silly.

**Comment by andybalaam** [comment]
Any thoughts on implementation? Partially see through images might be enough.

**Comment by colonelfazackerley** [comment]
I will do both, highlighter and ripped paper.

These are screenshots of half-implementations. The highlighter is a mostly transparent image. The ripped paper is opaque white covering the grid.

**Comment by andybalaam** [comment]
My kids like the torn paper and @GamingInky suggests diagonal cross hatching of red marker pen.

**Comment by andybalaam** [comment]
I really like the yellow marker too. I think this is going to enhance the visual impact of the game quite a bit. By the way I think with this we may want to change the scrolling rules. At the moment on a small screen you can't see any edge at all.

**Comment by colonelfazackerley** [comment]
I will do highlighter, torn paper and red hatching as @GamingInky suggests.

I was thinking I should add this to the graph paper, thinking that it would be drawn at the start, and kept. It looks like the lines on the graph paper get redrawn each frame, so there would be no benefit.

I intend to just add to the list of sprites in SpriteAnimator. Let me know if this is the wrong approach.

**Comment by andybalaam** [comment]
Sounds good. The drawing routines are very inefficient at the moment but the only place I've seen performance problems was on raspberry pi. I do hope to address them but when we do it shouldn't affect how you do this.

**Comment by colonelfazackerley** [comment]
I have performance problems on my VirtualBox Debian too.

**Comment by colonelfazackerley** [comment]
Highlighter style complete. 4 vert dash variants, 4 horiz dash variants and 4 corner cross variants.
![void_highlighter_complete](https://cloud.githubusercontent.com/assets/9596719/12475379/75d23ff2-c01a-11e5-92e4-df1716c2e35c.png)

**Comment by andybalaam** [comment]
Looks amazing.

**Comment by colonelfazackerley** [comment]
Work in progress shot of hatching style. If I finish it I will make custom sprites to go up to the corners properly and do more variants. Not sure I like it enough to bother.

Any suggestions to improve it?
![void_hatching_wip](https://cloud.githubusercontent.com/assets/9596719/12478079/ec1a5428-c02a-11e5-827b-9a807614096b.png)

**Comment by andybalaam** [comment]
Yeah not so good.

**Comment by colonelfazackerley** [comment]
i will delete the hatching option before completing the pull request, unless someone can suggest a way of improving it.

**Comment by colonelfazackerley** [comment]
Needs more variants, but it's coming along.
![void_torn_prototype](https://cloud.githubusercontent.com/assets/9596719/12492750/b19fef84-c079-11e5-9411-e8f2edb9b2dc.png)

Still need a brainwave on the hatching.

**Comment by colonelfazackerley** [comment]
all variants for the torn style done.
![void-torn-complete](https://cloud.githubusercontent.com/assets/9596719/12511075/5678e6be-c106-11e5-862c-bd365c1e40ad.png)

Still need a brainwave on the hatching.

**Comment by colonelfazackerley** [comment]
I will wait a little longer for tips on the hatching, or suggestions for other styles. I will do the pull req this evening.

**Comment by tttppp** [comment]
These are really excellent! My favourite is still the highlighter, but ripped paper is a very close second.

**Comment by andybalaam** [comment]
The holes are genius.

**Comment by GamingInky** [comment]
this is what I thought the red cross hatching should look like (sorry this is a screenshot from minecraft :( ) 
![red cross hatching](https://cloud.githubusercontent.com/assets/15169323/12587913/3686e7f2-c44e-11e5-922c-5651b7ff0389.png)

**Comment by colonelfazackerley** [comment]
minecraft has a very pixelly style. i think we need a more hand-drawn look. if you can mock something up, or do some inkscaping, i can put it in.
