### ISSUE TITLE
Discussion: canonical solutions

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#178]
In #148, the idea of the simplest solution came up. However, there are equally simple solutions that are not char-for-char equivalent. We need to agree the canonical form. Consider:
- a ```bash;(10,10);1;bridge;1;(12,10);``` 
- b ```bash;(10,10);bridge;2;(12,10);``` 
- c ```bash;(10,10);2;bridge;(12,10);```
- d ```bash;(10,10)&bridge;3(12,10);```  
Discussion:
- a has 2 wait actions that can be combined, so is not the simplest. 
- I propose the principal that unnecessary ampersands should be removed, discounting d.
- b and c are similar, but I prefer b. In swing c would represent a player waiting until the last moment to select bridge. b represents forethought.

**Comment by tttppp** [comment]
I'm not sure what the point of this is at the moment, but I would have thought that:
 * e 1;bash&(10,10);3;bridge&(12,10);
should be one of the options. It's always valid to have the token selection and placement in the same time step, and then simplify the wait steps.

For this particular scenario c looks "nicest" to me, but it gets more complicated when a token needs to be placed in the first step, or two different tokens are placed on consecutive steps.

Anyway, I'm not sure what the point of agreeing a canonical form is, so my opinion is based just on ease of computation (e) and asthetics (c).

**Comment by colonelfazackerley** [comment]
We also discussed this in #149 
It's so we can test if 2 solutions are the same. an expect script can play the game, and compare the solution presented at the end with the one it started with. This wont work if the solution has been simplified in a different way.

**Comment by tttppp** [comment]
Ah ok, I see. I don't actually think it matters at all then. Use e, assuming it's the easiest to code, and then check that:
```
canonical(storedSolution) == canonical(winScreenSolution)
```

At some point the code needs to be able to compute the canonical solution from a given solution, because getting a human to do it manually is going to be very error prone. Once we have the code to produce the canonical solution then we can apply it to both sides of the equation.

Does this sound reasonable?

**Comment by colonelfazackerley** [comment]
Yes

we just need to agree the form. we seem to disagree about ampersands.

**Comment by tttppp** [comment]
Ah, I think I see the problem. We're using expect to run the test, so it can't call any java functions. Fun times!

**Comment by andybalaam** [comment]
I don't think that the solutions you have listed sre "the same" in the sense I meant. Imagine watching a demo mode run through them. They would look different. I don't think we should simplify away differences like when you chose a token. The solution printed by the command line should be identical to what you did, except adjacent waits should get combined.

**Comment by colonelfazackerley** [comment]
I would prefer token selection to be moved so more waits can be combined, but I don't mind that much.

I would also like superseded token selections to be removed
```bash;1;bridge;1;(12,10);``` becomes ```2;bridge;1;(12,10);```

How about ampersands? should they be removed if they are not necessary? Should they be introduced (which is what the current win report is doing).

**Comment by andybalaam** [comment]
I'd like solutions to record what you did and not simplify that away. I genuinely plan a demo mode. So that makes the ampersand question irrelevant in the sense that they should be preserved but never added. See the unit tests I added and marked `@Ignore` for several bugs including the addition of ampersands.

**Comment by andybalaam** [comment]
Real solutions should almost never contain ampersands because they are almost impossible to do in the real game.

**Comment by andybalaam** [comment]
Since 1ae364df40edee50822aad6ec085152a3dfa8c59 solutions should round-trip OK, and they are simplified before being printed out, so I'm closing this.  @colonelfazackerley if you want more complex simplification, re-open and convince me ;-)

**Comment by colonelfazackerley** [comment]
It's fine. I think we needed a discussion of specification.
