### ISSUE TITLE
Level: "Cups and bridges"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#18]
New level from @ColonelFazackerley:

    :name=Cups and bridges
    :description=
    :num_rabbits=9
    :num_to_save=6
    :rabbit_delay=32
    :bridge=4
    :dig=3
    :block=4
    :explode=2
    :music=tryad-witness
                                     
    #        #  #       #  #        #
    #        #  #       #  #        #
    #        #  #       #  #        #
    #        #  #       #  #        #
    # Q      #  # Q     #  # Q      #
    #        #  #       #  #        #
    #\      /#  #\     /#  #\      /#
     ##    ##    ##   ##    ##    ## 
      ######      #####      ######  
                                     
      O                              
      ######      #####      ######

**Comment by andybalaam** [comment]
Quite large for some screens, but again fun to look at.  Was quite stumped by this one.  Can bridge your way out of the top and kill your rabbits: probably should have more empty space at the top.  Took me a while to work out - really enjoyed it!  By some crazy coincidence, the 2 bridgers to get over the left-hand gap were exactly synchronised, so I saved 7, but could probably never do it again (could saving 7 be the last level in a very hard set?).  In theory, you could get 8 by doing this on both gaps.
Thought: 9
Skill: 9
(Committed for now as new/level_10.rel)

**Comment by andybalaam** [comment]
ColonelFazackerley: "I tweaked the exit delay. Now I can get 6 out consistently. It is a big level, but I don't think it can be shrunk and retain its essence. perhaps reserve it for a big screen set of levels."

**Comment by andybalaam** [comment]
Big levels are OK where it's necessary - I just want them smaller where it doesn't matter either way.  Phones these days have more pixels than there are atoms in the universe anyway.

**Comment by andybalaam** [comment]
So, it's in!

**Comment by andybalaam** [comment]
Tricky!  I did it accidentally on about the 4th try.  I don't know how long it would have taken me to figure out how to trap the 2 rabbits between the sails - I clicked wrong and it happened!
Thought: 9 Skill:8

**Comment by colonelfazackerley** [comment]
Sounds like a comment on the sailing level against a different issue.

**Comment by andybalaam** [comment]
D'oh.

**Comment by tttppp** [comment]
Getting out 8 is fairly consistent using blocker tokens to allow synchronised bridging. Great level, I don't think I tried it before.

**Comment by andybalaam** [comment]
Good candidate for Deja vu #87 then.
