### ISSUE TITLE
Solutions for all published levels should be mandatory

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#182]
Currently, if you have a level with no solution, `make test` passes, but it should fail.

This may be annoying while we are developing levels - suggestions welcome.

**Comment by colonelfazackerley** [comment]
Keep levels without solutions in dev branches lke my current arcade2 branch until they have solutions in.

**Comment by andybalaam** [comment]
I added a warning.  We need solutions for medium and outdoors before we can activate this.

**Comment by andybalaam** [comment]
I feel fairly happy with having this switched on in future: I think once a level is mature enough to be in Git and referenced in a level menu item, it should have a solution to prove it's soluble.
