### ISSUE TITLE
Snapshots forbidden

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#184]
http://artificialworlds.net/rabbit-escape/snapshots/
I click on 	rabbit-escape-0.6.1.1.jar	and get
```
Forbidden

You don't have permission to access /rabbit-escape/snapshots/rabbit-escape-0.6.1.1.jar on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by andybalaam** [comment]
Sorry, I've only just seen this.  It's now fixed.  I don't know why it happened.

**Comment by andybalaam** [comment]
Re-opening to try and look at how to make the Makefile set the right permissions, if that is the problem.
