### ISSUE TITLE
Animation tester

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#188]
'make runat' does not work.

I would like to try and contribute some animations. I need some pointers to get started.

**Comment by andybalaam** [comment]
What error does it give?

**Comment by andybalaam** [comment]
We should start some developer documentation, probably as github pages. I'll make an issue to track this.

**Comment by andybalaam** [comment]
A tiny bit of documentation of animations is now at https://github.com/andybalaam/rabbit-escape/wiki/Making-Animations . Please add more as you learn.
