### ISSUE TITLE
Level: "Spare a blocker"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#19]
:name=Spare a blocker
    :description=How to rescue 9?
    :num_rabbits=10
    :num_to_save=9
    :rabbit_delay=4
    :bridge=4
    :block=10
    :explode=10
    :dig=1
    :bash=1
    :music=tryad-witness
                                  
                               O  
         /  /  /              ### 
                                  
                               #\ 
      Q                           
                               #\ 
                                  
     ##############\           #\ 
     ##################

**Comment by andybalaam** [comment]
Would appreciate ratings from others, but I reckon:
Thought: 7
Skill: 5

**Comment by colonelfazackerley** [comment]
Thought 7
Skill 8
I understood how to do it on my second attempt, but it took around 20 attempts to click accurately and quickly enough to do it. I had to abandon the touchpad and fetch the gaming mouse. Hard, but not so difficult that it was frustrating.I enjoyed it. The distraction decorations leave me wondering about other possible methods. My solution.
![untitled](https://cloud.githubusercontent.com/assets/9596719/9825956/e4325ba2-58ce-11e5-814f-bc4b380fa628.png)

**Comment by andybalaam** [comment]
Ah, not my method at all, but not a problem I think to have a second way.  Does this method also work for "Save 2 Blockers?"

**Comment by andybalaam** [comment]
I guess it does :-(

**Comment by andybalaam** [comment]
Let's leave this one as it is, and try to make #20 harder.
