### ISSUE TITLE
Level: "Spare 2 blockers?"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#20]
:name=Spare 2 blockers?
    :description=How to rescue 10?
    :num_rabbits=10
    :num_to_save=10
    :rabbit_delay=4
    :bridge=4
    :block=10
    :explode=10
    :dig=1
    :bash=1
    :music=tryad-witness
                                  
                               O  
         /  /  /              ### 
                                  
                               #\ 
      Q                           
                               #\ 
                                  
     ###############\          #\ 
     ##################

**Comment by andybalaam** [comment]
Would appreciate ratings from others, but I reckon:
Thought: 9
Skill: 9

**Comment by colonelfazackerley** [comment]
I find it hard to judge, because I just completed easier version, but it is definitely hard. I had a plan the first time I saw it, and managed to implement it on my 5th attempt. 

It is a buttock-clencher that will shock the unprepared, so I will go along with 9, 9.

**Comment by andybalaam** [comment]
Your solution for #19 works for this one, which is annoying because that is not my intended solution.  I intended you to make everyone a blocker and then bash underneath them to free them.  If you had no bridgers, and there was some other slow process needed for the leading rabbit (e.g. more bashing?) it's possible you could be forced to do it my way.  I will have another go.

**Comment by colonelfazackerley** [comment]
the basher is slow, so the bridger has time to complete (see pic on other issue).

**Comment by colonelfazackerley** [comment]
making the double thickness platform shorter may make it impossible without blockers.

could also start with a blocker in play that needs saving. (I did not know it was possible to undermine blockers to rescue them - I have never done it - might be nice to have an easy level that introduces the technique).

**Comment by andybalaam** [comment]
Yes, I will have another go at this one.

**Comment by andybalaam** [comment]
And yes, an easy level introducing that would be good.

**Comment by andybalaam** [comment]
Actually, it's easy to make your solution impossible - get rid of the extra bridger:

    :name=Spare 2 blockers?
    :description=How to rescue 10?
    :num_rabbits=10
    :num_to_save=10
    :rabbit_delay=4
    :bridge=3
    :block=10
    :explode=10
    :dig=1
    :bash=1
    :music=tryad-witness
                                  
                               O  
         /  /  /              ### 
                                  
                               #\ 
      Q                           
                               #\ 
                                  
     ###############\          #\ 
     ##################           
                                  
I think my solution (lots of blockers, all getting undermined) is now the only solution.  Let me know if I'm wrong.

**Comment by colonelfazackerley** [comment]
You are wrong
![s2b](https://cloud.githubusercontent.com/assets/9596719/9917240/78622cca-5cb8-11e5-82b5-586aabb24b3b.png)
* let first bunny past
* get second bunny digging, then bashing
* the double row platform is so long that the lead bunny has built the bridge before the basher has bashed all the way along

make the double row platform shorter, and this wont work.

**Comment by tttppp** [comment]
Even with a shorter platform I think you can still solve only using one blocker:
1. Set up the bridging token.
2. Dig a pit with the second rabbit.
3. Turn him into a blocker.
4-5. Bridge to the finish.
6. Turn blocker into a basher to escape.

![spare2blockers](https://cloud.githubusercontent.com/assets/7073263/9953467/041d8306-5dd9-11e5-95dc-dc17edcd2e34.png)

**Comment by colonelfazackerley** [comment]
I have never turned a blocker into a basher or digger. I the game needs an easy level that introduces the idea.

**Comment by andybalaam** [comment]
Hmm.  Lemmings didn't let you do that, and I think we shouldn't either.

**Comment by andybalaam** [comment]
OK, I think I've changed my mind and am OK with being able to do that.

**Comment by andybalaam** [comment]
With the latest change I think I've prevented @colonelfazackerley's solution, and I think we will have to live with @tttppp's solution - it's quite good.

If anyone can think of a way of forcing you to make lots of blockers in a line and then undermine them, it think it's a cool idea so I'd love to see a level based on it.

Knowing what we know now, I think this is:
Thought: 8 Skill: 7
