### ISSUE TITLE
World.getBlockAt faster

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#203]
I would like to to have a go at TODOing this.

```java
    public Block getBlockAt( int x, int y )
    {
        // TODO: faster
        for ( Block block : blocks )
        {
            if ( block.x == x && block.y == y )
            {
                return block;
            }
        }
        return null;
    }
```

[World.java](https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/engine/World.java)

Is this a good time, or is major refactoring imminent?

**Comment by andybalaam** [comment]
This is a good time.

**Comment by colonelfazackerley** [comment]
I have something working. The getBlockAt calls are 2-3 times faster.

https://github.com/andybalaam/rabbit-escape/compare/master...colonelfazackerley:getblockat-faster

advice gratefully received. several things to fix still. I also plan to bring tokens on board.

**Comment by andybalaam** [comment]
Looks interesting, and could be the right way to do it.  I think I was assuming we would have a Map<Position, Block> rather than a 2d array, but a 2d array may be right, especially since it probably won't be particularly sparse.

**Comment by andybalaam** [comment]
Maybe internally we could use an Object[][] and cast on the way in/out, since we know for sure the type of each thing.  This may be faster (although probably marginal - then again this whole TODO item is pretty unlikely to be a real performance issue - more a neatness thing) but it may also be cleaner.

I also wonder whether the LookupItems2D is really buying us anything over just using a Vector directly.

**Comment by colonelfazackerley** [comment]
I pushed another commit. It works now, and 'make test' is good.

I was wondering if we should not allow blocks to exist outside the world's size. they can be created by bridging. at the moment in the text ui it does not render them. it might simplify the code if the Block constructor said no.

The casting thing might work. I have it working this way now.

The getBlockAt calls are 2-3 times faster on outdoor 20 (K2).

I have written it so it could be used for tokens as well as blocks.

It could be pulled now. I suspect you may have comments first, though.

**Comment by andybalaam** [comment]
Is this done?

**Comment by colonelfazackerley** [comment]
yes

**Comment by andybalaam** [comment]
Woot!
