### ISSUE TITLE
"Official" solutions for Outdoors 8 and Medium 1

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#206]
Outdoors 8 and Medium 1 have solutions that don't match the hints and/or are not the author's intention.

Since solutions are partly intended to demonstrate that the ideas in the level still work, it would be good to have solutions that reflect the original intention.

More importantly, it would be nice to know for sure that the hints lead you to a correct solution, so it is particularly important to fix cases where the solution from the hints is not tested.

**Comment by tttppp** [comment]
I've done a solution for Outdoors 8 now. I totally forgot that I could find out the 'official' solution by looking at the hints!

**Comment by andybalaam** [comment]
Pull request me.

**Comment by tttppp** [comment]
I don't seem to be able to create a pull request from my phone. :(

**Comment by andybalaam** [comment]
Or point me to a branch and I'll merge when I get computer time.

**Comment by tttppp** [comment]
The Outdoors 8 is included in the tttppp/outdoorsSolutions pull request. I haven't done Medium 1, and I imagine there may be others where the hints don't match the method.

**Comment by tttppp** [comment]
Solution to Medium 1 is now in the pull request too.

**Comment by andybalaam** [comment]
We are close to releasing the arcade levels. I just need to solve 18 to 20.
