### ISSUE TITLE
'make test' should report missing animation (.rea) files and rea testing.

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#207]
perhaps  little java to fetch the states from ChangeDescription and make sure there are all the lowercased rea files.

Perhaps there is some checking of the rea file content that could also be incorporated.

**Comment by andybalaam** [comment]
Yes, very good.  I feel like I once wrote a TODO item about this, but I could be wrong :-)

**Comment by colonelfazackerley** [comment]
implemented in 3b42bcbb31b33f997de82f570911fb34c279d8f2
