### ISSUE TITLE
Level: "Cloud bunnies"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#21]
New level from @ColonelFazackerley:

    :name=Cloud bunnies
    :description=
    :num_rabbits=9
    :num_to_save=8
    :rabbit_delay=20
    :bridge=3
    :dig=4
    :block=2
    :explode=2
    :music=tryad-witness
     Q                                   
                            Q            
         /##\                            
        /#  #\                  /##\     
     /###    ###\              /#  #\    
     #          #           /###    ###\ 
     ##        ##           #          # 
      ##########            ##      O ## 
               Q   /##\      ##########  
                  /#  #\                 
               /###    ###\              
               #          #              
               ##        ##              
                ##########

**Comment by andybalaam** [comment]
Harder than I first thought it was!  Very nice looking, very outdoors-y, quite big again, but that is needed for the look as well as the puzzle.
Thought: 8
Skill: 7

**Comment by andybalaam** [comment]
Definitely in.

**Comment by andybalaam** [comment]
ColonelFazackerley: "I thought it was going to be super easy, but its not quite so trivial. There may be an easier way, of course."

**Comment by tttppp** [comment]
This was harder than I expected. I saved all 9 on my mobile, but it required a bit of pause control to scroll around.

**Comment by tttppp** [comment]
I have a solution to save 9 bunnies with this. Is it worthy of Deja Vu?

**Comment by colonelfazackerley** [comment]
We need 20, why not? Is it relatively easy? we need a level 1 for deja vu...

Andy opened this issue, so I can't reopen it.

**Comment by colonelfazackerley** [comment]
We need 20 levels, why not? Is it relatively easy? we need a level 1 for deja vu...

Andy opened this issue, so I can't reopen it.

**Comment by tttppp** [comment]
Until I read the hints, I didn't realise there was a really neat way to save only 8. I found the solution to save 9 simpler than the solution to save 8. Kudos on the save 8 method btw.

**Comment by colonelfazackerley** [comment]
I got 9 now (I may have before, I dont recall). It is easier than the hinted solution. Is yours like this?
:solution.1=dig;(12,4);(32,3);bridge;(19,9);11;(22,7);dig;(11,3);61

**Comment by tttppp** [comment]
That's basically identical, yes. I'm not sure that "easier" solutions will make good Deja Vu levels, so maybe we shouldn't include this in Deja Vu.

**Comment by andybalaam** [comment]
Yeah let's just accept that there are 2 solutions.
