### ISSUE TITLE
Re-do #215 level dirs with numbers

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#216]
Assuming we think it's worth the effort, re-do #215, with a config upgrade so it remembers which levels you have completed even when the dir names have been modified.

@colonelfazackerley up to you whether you think it's worth it.  I will be happy to help with upgrade.  We need an upgrade structure anyway, so most of the effort is needed anyway.

**Comment by colonelfazackerley** [comment]
I can't be bothered at the moment. However, the disordered set directories are irksome, so I daresay I will come back to this at some point.

**Comment by andybalaam** [comment]
Yeah.  Sorry for accepting then reverting.  Didn't think of this.

**Comment by andybalaam** [comment]
@colonelfazackerley is this done?

**Comment by colonelfazackerley** [comment]
Yes
