### ISSUE TITLE
Some easier levels

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#218]
Quoting @colonelfazakerley:

I think we are in danger of making harder and harder levels with an audience exclusively composed of us. I would like to work on some easier levels that use new features. For example

    water squares (and snorkels to get across them)
    brollies to parachute.

This is why I am trying to cut my teeth on some outstanding animation work.

Quoting @tttppp:

That is an excellent observation. I have put very little effort into making beginner levels. I think @gaminginky had some promising-looking levels for those players interested in fun rather than brain ache.

**Comment by andybalaam** [comment]
I agree, but would also observe that committed players are likely to want a challenge, so I think hard levels are a good idea too.

**Comment by andybalaam** [comment]
Each new ability must be justified in terms of puzzletunities it enables that are not possible without it.

**Comment by GamingInky** [comment]
we can't have that after you complete easy all the levels after that a really hard we need some easy mixed in

**Comment by andybalaam** [comment]
@GamingInky has written some easier levels.  I think #241 (small world) will have a good mix.

**Comment by GamingInky** [comment]
I have written this one of small world #438

**Comment by colonelfazackerley** [comment]
I think #438 is too big for small world. Max dimension 8 or possibly 9.

**Comment by andybalaam** [comment]
Yes 8 or 9 max in both directions.

**Comment by GamingInky** [comment]
Changed it.
