### ISSUE TITLE
License permission for work by @ColonelFazackerley

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#22]
@ColonelFazackerley, do you agree I (and any company or organisation I one-day form) can distribute any levels, graphics, sound effects you have provided to me under all of the following licenses?

- **CC-BY-NC-SA**: Creative Commons Attribution Non-Commercial ShareAlike license
- **CC-BY-SA**: Creative Commons Attribution ShareAlike license
- **GPL**: GNU General Public License, v2 or a later version

The first license (CC-BY-NC-SA) is used at the moment.  By agreeing to all three, we make it easy to re-license to a completely [Free Culture](https://creativecommons.org/freeworks) license if we decide to do this in future.

This allows me to use the work commercially, but prevents others from doing so.  If/when we relicense to a Free Culture license, everyone will be allowed use it commercially.

**Comment by colonelfazackerley** [comment]
I consent to the use of any or all of  CC-BY-NC-SA, CC-BY-SA, GPL v2+ being used to distribute anything I contribute to the rabbit-escape project. This includes level designs, code, etc.

**Comment by andybalaam** [comment]
Woot.

**Comment by andybalaam** [comment]
@colonelfazackerley 

I have decided to release all our work under "GPL v2 or later", as you agreed above.

I regret using a non-free license originally.  This change should make it easier for others to build on our work, distribute it more widely, and have fun making modified versions with no restrictions other than the reciprocity provided by the GPL.  More info: https://creativecommons.org/share-your-work/public-domain/freeworks/

Separately, but related, I plan to release a free-of-charge version on the Google Play store.  The pay-for version will remain too, but make it clear you can get the free one if you prefer.
