### ISSUE TITLE
Command line option to print rabbit states

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#223]
When I am working on animations, I find it useful to put some code in to print each state the rabbits go through, so I can understand the status quo before I mess with it.

I have avoided committing it. I find I am doing this so often that I would like a command line option for swing that prints the states. Would that be OK?

**Comment by andybalaam** [comment]
Yes, no problem. I am wondering whether there is something better we can do - maybe expand animation tester into some kind of animation studio but adding this for now is fine.

**Comment by andybalaam** [comment]
Done in #249
