### ISSUE TITLE
Animation tester to make animated gifs

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#224]
I can't capture decent ones because of the performance limitations of my linux running in a VirtualBox VM. So I have to switch to Windows to make them, and the software I am using there is rather annoying.

The animation tester (AT) already does things like applies offsets and displays scenery tiles, so it seems like a good place to make gifs.

If it's too much hassle in java to make an animated gif, the AT could produce frames and mencoder, ImageMagick or something could be used to stick the frames together.

**Comment by andybalaam** [comment]
Sounds good. I am now also wondering whether a "tweet what I just did" button that makes an animated gif would be a cool feature.

**Comment by colonelfazackerley** [comment]
Sounds good to me.

**Comment by colonelfazackerley** [comment]
I have the anim tester spitting out png frames. Would it be objectionable if I just got java to do a system call to ImageMagick's convert to make them into an animated gif?

**Comment by andybalaam** [comment]
No, that would be fine for animation tester. In the main game I'd like a pure java version to allow tweeting your victories etc.

**Comment by andybalaam** [comment]
But that can come later.
