### ISSUE TITLE
Level: "Cliff Hanger 2"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#228]
```
:name=Cliff Hanger 2
:description= 
:num_rabbits=6
:num_to_save=6
:block=2
:climb=1
:dig=4
:bridge=2
:bash=3
:explode=2
:rabbit_delay=10
:music=tryad-witness
###########
#        O#
#         #
#         #
#         #
#        Q#
# *       #
###     ###
###########
:*=c
```

Not quite a Deja Vu level, and this might be classed as a bug!  Hopefully I've typed the level out right on my phone.

**Comment by tttppp** [comment]
This isn't right, I copied it from the original issue for Cliff Hanger, but the level has changed since then. We should have 4 rabbits, save 4 and 10,10,4 for the rabbit delay.

**Comment by tttppp** [comment]
Hints, in case we want to include it, or in case I need to remember how I solved it:

```
hint.1.code=`JF?&)28&2ie:9eF2i1pJJ7)28w?QQJmQJ&edS88i:Je22?&`ee:J9:`pJ?JJewJ9:QA?m:J:J0
hint.2.code=--$[--~6_)f-&IYc$I7$-~I#BY~(Y-}fC--#6YI(c~ff~Vg$&
hint.3.code=v:/dd7D7up:v6IRD57d6xV:6RzdpDD16dd1/*Dpvg7/Dodz17vpD7d<5d56D1dVu|71vpdpz15dpd1dm
```

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/93-cliff-hanger-2
