### ISSUE TITLE
Level: "Tomb of Doom"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#230]
```
:name=Tomb of Doom
:description=Reach the burial chamber
:num_to_save=3
:num_rabbits=3
:dig=5
:bash=5
:block=2
:rabbit_delay=10
          Q          

          /\         
         /##\        
        /####\       
       /######\      
      /########\     
     /##########\    
    /####O#######\   
  ##################
```

Deja Vu level. Tomb Raider with the bridge tokens removed. Took me about an hour to find a way to do this!

**Comment by tttppp** [comment]
Reference series: #87

**Comment by colonelfazackerley** [comment]
Looks hard. I am getting tense just looking at it.

**Comment by andybalaam** [comment]
Has github mangled it?

```
Line number 18 (  ##################) has the wrong length in text world lines:
:name=Tomb of Doom
```

**Comment by andybalaam** [comment]
(This was loading through the github download feature)

**Comment by colonelfazackerley** [comment]
Indeed. It now needs a space adding to line 18. The github download feature does save a copy that you can edit. Then use the load level feature.

Ideally the github download feature would
- auto-fix the level,
- put the error message in a dialog when there are errors it can't fix.

**Comment by tttppp** [comment]
Sorry, this will be because I set the level on my phone. I can't edit the issue on my phone either, so you could either fix a copy locally (as colonelfazackerley suggests), or play the original without using bridge tokens (which is how I tested it).

**Comment by colonelfazackerley** [comment]
This took me considerably longer than an hour. I finally figured out a new trick.
```
:solution.1.code=<x}:~-f`|:f`ZQPb~:H.x}f::3.3`|:f`Q{.Dfm.DUhJJ.hhm++e::DxxHb.}ffx}}e:{}``/::<$vC:::eexFQ[
```

@tttppp - I would like to know if this is the same as yours. 

Under linux, I can do this to show the solution (after copying into the level file).

```
./runrabbit text -level foo.rel -solution 1
```

I should do a runrabbit.bat.

**Comment by colonelfazackerley** [comment]
It can. Hack the manifest to ...text.TextMain

then
```
java -jar rabbit-escape-0.7.1-text.jar --level foo.rel --solution 1
```

**Comment by colonelfazackerley** [comment]
Or, without manifest hacking
```
java -cp rabbit-escape-0.7.1.jar rabbitescape.ui.text.TextMain --level level_01.rel --solution 1
```

**Comment by andybalaam** [comment]
The above comment deserves a page on the developer wiki

**Comment by tttppp** [comment]
@colonelfazackerley That's amazing, but I'm sure it is different from mine. I only have access to the Android interface atm, so can't give you mine.

To be honest I'm not sure I see how yours works without stepping through! :-)

Congratulations on completing it though! It was a nightmarish level.

**Comment by tttppp** [comment]
```
hint.1.code=?@1J&&@y,r@)&?@Iz7,a@&?@rr&@z29)/@[?)29?@@z?&h2@?a12 7Va)?&*y7?@[&[y@J9&Ir[z&r@?2&@&r@1z7 J9@@79)@71))[z2I1&*
hint.2.code=7HSxS*HK*/HkH7HS@W*s@*SH@0S sSH7s1HSD5:x*801+7s1xD1xrS5:!@@@JKH: S@SHsHsSDS7JHSSD@:JJJSS/5S7JHK5S0S0SSDx
hint.3.code=Z4T q4^*^k77.oZtuo .Zoy!7Lu47oto}kTo?7t,Zuoto+Tko6Z.y^kyt^4T!o,oukyty!Zk}roTo.ko!.k4o@y^yZToy@}47dsoZ46o kuy74oZokyo^okypoo^yky4^uoTtJ7L>tT>o^ 7L6uoZ.^q.ooTotkZ7o^ZTyZL@ookuTyo4o.o6uk7L^y^y>ook*,T
```

**Comment by andybalaam** [comment]
I am looking forward to trying this one. If it's truly horrible maybe we should think about a "nightmare" level set.

**Comment by andybalaam** [comment]
Although I assume deja vu will be pretty hard so maybe this can just be the last one in that set.

**Comment by tttppp** [comment]
I like the idea of a "nightmare" set! I really like the idea if we can scrap the hints for it and enable playing later levels without completing earlier ones. (The second of these suggestions is probably fat more work than it's worth)

**Comment by colonelfazackerley** [comment]
I think this one is easier than catch me with a target of 13. I can do this one, I can't do that one.

**Comment by andybalaam** [comment]
@tttppp fancy sharing your solution?

**Comment by tttppp** [comment]
Unfortunately there's been a code change and my solution no longer works. The first rabbit out always takes the token now, and I guess the last rabbit out used to take it.

Does this colonelfazackerley's solution still work?
https://github.com/andybalaam/rabbit-escape/issues/230#issuecomment-167857962

**Comment by andybalaam** [comment]
@colonelfazackerley ?

**Comment by andybalaam** [comment]
The solution in the level file works, as does mine:

```
bash&dig&block&dig&(11,2);6;bash;;(11,5)&dig;;(12,5);;bash;3;(12,8)&block;2;(13,8);3;bash;;(13,8);3;(12,8);14
```

Mine uses one more basher, but one less blocker, but they both use the same bash-then-block-then-bash trick.

**Comment by tttppp** [comment]
I don't know if I would have got this without Andy's hint above. I had quite a few tokens leftover, but regardless, this was a really hard level.

**Comment by andybalaam** [comment]
Yeah it's hard to discover. Glad you liked it. I was struck by quite how hard this level set is.

**Comment by andybalaam** [comment]
https://youtu.be/gYeP2zBrSvQ

**Comment by andybalaam** [comment]
Any reason why this issue is still open?

**Comment by tttppp** [comment]
No!

**Comment by andybalaam** [comment]
:-)
