### ISSUE TITLE
Level: "Flagging"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#235]
I have several solutions to Hard Level 11 "Flag".  These require:
- Climb: 5, Dig: 5 (original solution)
- Dig: 1, Bridge: 4 (fairly easy, but needs careful timing)
- Climb: 2, Dig: 4, Bridge: 1
- Climb: 1, Dig: 3, Bridge: 2

Any of these other three could be Deja Vu levels, and could include additional decoy tokens to make it harder.

I haven't selected a particular one of these to be "Flagging", as I wanted to gauge which people thought was the better challenge.

**Comment by tttppp** [comment]
Reference series: #87

**Comment by tttppp** [comment]
Another solution  (easier I think):
 * Climb: 5, Dig: 2, Bridge: 1

The reason I think these solutions are interesting is that none uses a subset of the tokens for another.

**Comment by colonelfazackerley** [comment]
I managed Climb: 5, Dig: 2, Bridge: 1.

I think the levels are all quite different, once you get past the blocks being in the same place. So I think we can use several. We will need more names: which brings me to...

```
:name=Flagellate
:description=I assume you like punishment.
:author_name=tttppp
:author_url=https://github.com/tttppp
:hint.1.code=
:hint.2.code=
:hint.3.code=
:solution.1.code=-;-;-;-;I:fxZH[-:MDx.e:I:~M:h:M:M:j:M*j4$Ch4bx;Hv:hx-QvDeMv:v$-xxv:xMMb;/Hxhh:<QI:eh-Pj|
:num_rabbits=5
:num_to_save=5
:rabbit_delay=10
:num_saved=0
:num_killed=0
:num_waiting=5
:paused=false
:bridge=1
:climb=5
:dig=2
##############
#            #
#            #
#   ######   #
#   ######   #
# Q ######   #
#   ######   #
#   #      O #
##############

```

**Comment by tttppp** [comment]
Looks good to me. The same as my solution too.

**Comment by colonelfazackerley** [comment]
I also managed Dig: 1, Bridge: 4

I think we should use this too.

```
:name=Flagging
:description=Are we nearly there yet?
:author_name=tttppp
:author_url=https://github.com/tttppp
:hint.1.code=
:hint.2.code=
:hint.3.code=
:solution.1.code=MhHM{E*O{ShE )vME<<hvv)vw(MH@:$)v4HmvME\vv[<|{vC|Erw)vn)8v$-
:num_rabbits=5
:num_to_save=5
:rabbit_delay=10
:num_saved=0
:num_killed=0
:num_waiting=5
:paused=false
:bridge=4
:dig=1
##############
#            #
#            #
#   ######   #
#   ######   #
# Q ######   #
#   ######   #
#   #      O #
##############

```

**Comment by colonelfazackerley** [comment]
I can't do
Climb: 1, Dig: 3, Bridge: 2

I think I could do 
Climb: 1, Dig: 3, Bridge: 3

Do we want this as another, easier deja vu level? (That would make 5 Flag derivatives).

**Comment by andybalaam** [comment]
More than 3 seems excessive. Although it does appeal. ..

**Comment by colonelfazackerley** [comment]
I like that the level can be changed completely with a few ability token tweaks.

It would be like a recurring joke in the level set. Amusing to me, anyway...

I reckon the more the better.

**Comment by andybalaam** [comment]
Yeah I'm convinced. If it truly is a different solution each time it's cool.

**Comment by tttppp** [comment]
I think it could work, particularly in a levelset called Deja Vu. We'd need to check the solutions are significantly different, which is a subjective thing. When I last counted Deja Vu levels I made it about 10, so 13/14 with these in.

**Comment by tttppp** [comment]
I don't think we should include Climb: 1, Dig: 3, Bridge: 3, as it can be solved with Climb: 1, Dig: 3, Bridge: 2. Also I remember two of my solutions being similar although not identical.

**Comment by andybalaam** [comment]
Flagellate (Climb: 5, Dig: 2, Bridge: 1) - thought: 8, skill:7  I really enjoyed that one.

**Comment by andybalaam** [comment]
I am having serious trouble with "Flagging" (Dig: 1, Bridge: 4).  I've just read @tttppp 's comments above, so I am thinking I'm not missing anything, but I am finding the timing does not work out for me.

**Comment by andybalaam** [comment]
I finally did Flagging. Thought 8, skill 9 for me but did others find it easier?

**Comment by andybalaam** [comment]
I had to count the rabbits out and use trial and error to find a timing that worked.

**Comment by colonelfazackerley** [comment]
> did others find it easier?

no

**Comment by andybalaam** [comment]
Phew, you're back

**Comment by andybalaam** [comment]
I've committed my solutions - let me know if they vary from yours.

I find "Flagging" (the one with very precise timing) very annoying - does anyone think we should pull it?  One thought: how to write hints for it?  If that's hard does it mean it's an unfair level?

**Comment by tttppp** [comment]
I think having annoying levels is ok, but I think at some point a level skip mechanism should be added. Eg. If a level is attempted and remains unsolved for 1 hour then the next level becomes accesible

**Comment by tttppp** [comment]
I am quite into making annoying levels though.

**Comment by andybalaam** [comment]
lol. Yes, now we have solutions, we can have a walk through, and I'm not against a skip option too. Kids today expect it.

**Comment by tttppp** [comment]
I just solved "Flagging" with just 5 climbs and 1 dig! A new Deja Deja Vu level.

**Comment by andybalaam** [comment]
Cool!

**Comment by andybalaam** [comment]
@tttppp did the solution you mention 2 comments ago end up in the game? If not let's have a separate issue for it and close this one.

**Comment by tttppp** [comment]
No, it didn't get in. I mainly wrote it here for you and the Colonel, as I know how much you like these levels!

We can close without including it.

**Comment by andybalaam** [comment]
Was it too similar to another? If not, let's include it!
