### ISSUE TITLE
Level: "Minefield Mind-fail"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#237]
I'm not sure whether this actually would be a good Deja Vu level, but I just completed "Minefield" (Arcade 17) getting all four rabbits out. If we feel that the Deja Vu levels are too easy and need a painstaking level to pad them out then I suggest this.

Reference series: #87

**Comment by andybalaam** [comment]
Ouch I replayed this one the other day and did wonder whether I could get 4 but it would not be easy. ..

**Comment by tttppp** [comment]
Mainly in case I forget how I did this (and while I can't create solutions):
```
hint.1.code=[3[<g3ym3$e3mIhH43*[z3[33[J=z*VHem*yheyM443Nyezh43zNWzzy)M3y
hint.2.code=::49ii;/8;xi:40w4&ixm&xP//ix/iu099iumi5xm$xim5t45i:tPi:&_x00mtxt{:95ii;x5_:i05:li&
hint.3.code==Pj!OjPmmjm=v{&jvj j1{1jjPmq!vjj1m= Ovjm{mjPaKj&vf1/Pjjmo:j01{=~fjOvj:11P1j&0m&j&jof= !BmW~mf=Oo=jfm!j& oj7=:m0Pj{v; {~fjmjvqj{81m&~jq:!{{PO ==100~&=mm!Ojj0 1vOmOovjo0/PmmvmO
```
