### ISSUE TITLE
Level: "F"

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#24]
Another medium/easy one, I think

```
:name=F
:description=
:num_rabbits=9
:num_to_save=8
:rabbit_delay=10
:bridge=3
:block=2
:bash=3
:music=tryad-witness
####################
#     Q            #
#                  #
#     #########    #
#     #########    #
#     ##           #
#     ## Q         #
#     ##           #
#     ########     #
#     ########     #
#     ##           #
#     ##           #
#Q    ##           #
#     ##     O     #
####################
```

**Comment by colonelfazackerley** [comment]
A more outdoor feel.
```
:name=F
:description=
:num_rabbits=9
:num_to_save=8
:rabbit_delay=10
:bridge=3
:block=2
:bash=3
:music=tryad-witness
      Q             
                    
                    
                    
      #########     
      #########     
      ##            
      ## Q          
      ##            
      ########      
      ########      
      ##            
      ##            
 Q    ##            
/     ##     O      
####################

```

**Comment by andybalaam** [comment]
Looks nice.  Another candidate for outdoor.

**Comment by tttppp** [comment]
I think the indoor variant is harder here as there is more things to try out with the walls on either side.  Incidentally - is there a trivial solution if you provide an extra blocker?  Having three blockers would open up lots of methods by blocking both ends of the top, and the open end of the middle.

**Comment by colonelfazackerley** [comment]
I cant judge if a solution is more trivial. I am too partial, as I designed it.

I think using more than one blocker is harder, becuase then you have to free a blocker, which is something that feels advanced to me. 

Glad you like it.

**Comment by andybalaam** [comment]
I enjoyed this - took me about 5 goes.
Thought: 8 Skill: 7

**Comment by andybalaam** [comment]
I didn't free any blocker btw
