### ISSUE TITLE
Level set: Small world

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#241]
Small levels, less than 9 in height and width (preferably smaller).  In no order:

1. **Bed** - thought: 4, skill: 2
2. **So much owed** - thought: 4 skill: 3 (but I liked it)
3. **Tunnel** - thought: 5, skill: 4
4. **Ramps** - thought: 5, skill: 7
5. **Brolly Hero** - thought: 6, skill: 6
6. **Playing catch up** - thought: 7 skill: 4
7. **Plug** - thought: 7, skill: 5
8. **Column** - thought: 7, skill: 6
9. **Up** - thought: 7, skill: 7
10. **House** - thought: 7, skill: 7
11. **Flow down** - thought: 7, skill: 7
12. **Sloping off** - thought: 7 skill: 8
13. **Grid** - thought: 8, skill: 7
14. **It's behind you** - thought: 8 skill: 7
15. **The bunny's not for turning** - thought: 8 skill: 7
16. **Totem** - thought: 8, skill: 7
17. **Upshot** - thought: 8, skill: 8
18. **Whack a rat** - thought: 3, skill: 9
19. **Uno** - thought: 8, skill: 9
20. **The Catch** - thought: 8 skill: 9

[*Levels involving water are excluded for now because #444 Water is not ready.*]

**Comment by tttppp** [comment]
This presents a whole new challenge in level creation! Great idea.

**Comment by colonelfazackerley** [comment]
Alternative name: claustrophobia

One of them (claustrophobia, small world) could be used for a level too.

**Comment by colonelfazackerley** [comment]
I think the height and width limit for this set could be 7 or 8.

**Comment by andybalaam** [comment]
Thanks for making the issue. I thought this was a good idea and then worried we wouldn't actually be able to make any levels but you have demonstrated otherwise!

**Comment by andybalaam** [comment]
7 or 8 in one or both directions sounds about right.

**Comment by colonelfazackerley** [comment]
I think I had to go to 9 in one direction for one of them.

**Comment by colonelfazackerley** [comment]
It's Brolly hero under #226 that has a height of 9.

**Comment by andybalaam** [comment]
The plan is to complete this level set and make it the main focus of release 0.9 #343

**Comment by tttppp** [comment]
I added a pull request with a new small world level in it: Uno. It was 7x9, which I think is within the size limit.

https://github.com/andybalaam/rabbit-escape/pull/404

**Comment by andybalaam** [comment]
We have 14 levels so far,13 of which have solutions.  They are in https://github.com/andybalaam/rabbit-escape/tree/master/rabbit-escape-engine/src/rabbitescape/level and https://github.com/andybalaam/rabbit-escape/tree/master/rabbit-escape-engine/src/rabbitescape/levels/development/smallworld

**Comment by andybalaam** [comment]
I have not played any of these yet, but I will build a snapshot with them in and give them a try using @colonelfazackerley 's highly useful work from #418 meaning we can play development levels inside the app.

**Comment by andybalaam** [comment]
Snapshot 0.8.0.10-dev-levels in http://artificialworlds.net/rabbit-escape/snapshots/ contains all the small world levels so far, and I have hacked it so all the dev levels are available all the time (it includes #418 too).

**Comment by andybalaam** [comment]
Adding my difficulty ratings at the top of this issue.  Feel free to chip in.

**Comment by andybalaam** [comment]
It's behind you - thought: 8 skill: 7

**Comment by andybalaam** [comment]
Playing catch up - thought: 7  skill: 4

**Comment by andybalaam** [comment]
Sloping off - thought: 7  skill: 8

**Comment by andybalaam** [comment]
So much owed - thought: 4  skill: 3  (but I liked it)

**Comment by andybalaam** [comment]
The bunny's not for turning - thought: 8  skill: 7

**Comment by colonelfazackerley** [comment]
> So much owed - thought: 4 skill: 3 (but I liked it)

I dont mind making easier levels.

**Comment by andybalaam** [comment]
The Catch - thought: 8  skill: 7 loved it

**Comment by colonelfazackerley** [comment]
i would like to see your solutions, so i know if they are the same as mine. encoding is probably good practice.

**Comment by andybalaam** [comment]
Uno - thought: 8, skill: 9

I am doing all this on my phone but will put in solutions when I get computer time.

**Comment by andybalaam** [comment]
Is the fact that turning a bridger into a climber stops it bridging a bug?

**Comment by colonelfazackerley** [comment]
I don't recall having my intuitions shattered when I learnt that token pickups interrupted behaviours. I think it's fine.

**Comment by andybalaam** [comment]
Whack a rat - thought: 3, skill: 9.  Reveals several bugs that I must log: 1. The animation when you place a brolly in the air appears too low (on Android at least), 2. If I give a rabbit a brolly near the end of its fall, it dies.

**Comment by andybalaam** [comment]
Re your previous comment: hurrah for declaring bugs are features!

**Comment by tttppp** [comment]
For the brolly bugs (/features?) I thought that giving a rabbit a brolly too late causing splatting seemed sensible. Although this didn't happen on Lemmings, I think that it's reasonable to expect some time for the brolly to open.

**Comment by GamingInky** [comment]
@andybalaam Please can you review my level. (#438)

**Comment by andybalaam** [comment]
I guess I could be convinced on point 2. 1 is a definite bug.

**Comment by andybalaam** [comment]
Solutions:
```
Brolly Hero   Y6E6b}b6E6CP66tY6E6|A%6~[%A&Z|t<AC[HI}6\}PY^C@6HIAhI\6CE6
```

**Comment by andybalaam** [comment]
This level set is now enabled in snapshot 0.8.0.14: http://artificialworlds.net/rabbit-escape/snapshots/
