### ISSUE TITLE
Level: The bunny's not for turning

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#242]
```
:name=The bunny's not for turning
:description=
:author_name=
:author_url=
:solution.1.code=3rK~Kj8e3(+Kh7Z+2O3tZ+yQrKKy&72n&K(~79(&[W~
:num_rabbits=3
:num_to_save=3
:rabbit_delay=4
:num_saved=0
:num_killed=0
:num_waiting=3
:paused=false
:bash=2
:block=1
 Q   
 *   
 # ##
O  ##
#####
:*=ccc
```

**Comment by colonelfazackerley** [comment]
For the small world set #241

**Comment by tttppp** [comment]
Totally brilliant.  The Small World levels I've seen so far are brilliant - each has a unique feel to it.

**Comment by andybalaam** [comment]
Yeah I was worried they'd be too constraining to make good levels but clearly not!

**Comment by andybalaam** [comment]
Currently at: https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/The-bunnys-not-for-turning.rel

**Comment by htgoebel** [comment]
The hint 3 for this level says: "Turn it back into a basher to release it." Yes, this will release it, but it will still move to the right, bashing away the last stone. Is this a bug in the level or did I miss something?

**Comment by colonelfazackerley** [comment]
This explains (level uses a similar trick)
https://www.youtube.com/watch?v=gYeP2zBrSvQ
do ask again, if you still have trouble.

**Comment by htgoebel** [comment]
Thanks for the quick answer, now I made it. Curiously I made the other one without even the hints, just did not remember the trick.
