### ISSUE TITLE
Level: The catch

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#243]
```
:name=The catch
:description=
:author_name=
:author_url=
:solution.1.code=v@vnvv<v6m"vEp_m)cnbb)E"Fx@Fx
:num_rabbits=0
:num_to_save=2
:rabbit_delay=4
:num_saved=0
:num_killed=0
:num_waiting=0
:paused=false
:block=1
:bridge=1
:dig=1
 #r  #
O ####
#     
      
    j#
  //##
```
for #241

**Comment by andybalaam** [comment]
Am now excited about #241

**Comment by tttppp** [comment]
Took me twenty minutes! Great level :-)

However the next try I came up with another solution using one fewer token.

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/The-catch.rel

**Comment by tttppp** [comment]
This is creditted to me, presumably because it's rock hard! ;-) It should be re-creditted to colonelfazackerley. Incidentally it's a brilliant final level for the set.

**Comment by andybalaam** [comment]
Oh no, sorry!
