### ISSUE TITLE
Insert placeholders for missing meta in rel files

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#245]
The --encode and --decode options do this, which I find quite handy. How about a --placeholders option that roundtrips the level without en/decoding? It would insert :description, etc.

**Comment by colonelfazackerley** [comment]
Also maybe --template can spit out a blank world with all placeholders. and a 6x6 world of spaces.

**Comment by andybalaam** [comment]
Sounds good. Are these utilities part of a "level" section similar to "text" and "swing"?

**Comment by colonelfazackerley** [comment]
See the -h explanation in #244

I am happy to change it.

**Comment by andybalaam** [comment]
I guess text covers all of it but I think batch operations like encode are quite different from playing a level.

**Comment by andybalaam** [comment]
But am very happy to leave as is for now. Just musing.

**Comment by colonelfazackerley** [comment]
I was thinking of removing the text arg to the scripts to reduce the amount of typing.

Not sure a level section is necessary.

**Comment by andybalaam** [comment]
Sounds good

**Comment by andybalaam** [comment]
Fixed in #249
