### ISSUE TITLE
Bug?: de/encoding a level loses comments

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#246]
Do we care? If we do, I guess the World has to store them.

de/encoding roundtrips, (which I quite like), but this does re-order the meta (which I also quite like - makes the levels ordered, which appeals to my OCD). If the comment precedes a line it refers to, I will need to figure out where to put it after. Do we care? I could just do

meta
comments
world
starpoints

**Comment by tttppp** [comment]
Comments are sometimes related to a specific meta data line, so I think it might make sense to link them to keys. These would get reordered, but I think this shouldn't often be a problem.

**Comment by colonelfazackerley** [comment]
I think I can assume the comment refers to the line below it.

**Comment by tttppp** [comment]
Both sound like excellent ideas.

**Comment by andybalaam** [comment]
I have several conflicting feelings. I will sleep on them.

**Comment by colonelfazackerley** [comment]
I am working on this already in #249

**Comment by andybalaam** [comment]
Preserving comments is good. Round trips are good. Canonical order is a bit good, but where not enforced it can just trigger unnecessary OCD.

So, ideally I'd like to preserve order through a round trip, and I'd even pay the tax of having order info in a world even though it is not really is business. 

However, I'd also live with associating all comments with the line below.

Questions:

How will we handle multi line comments? 

What about comments within the level data?

**Comment by andybalaam** [comment]
Is-> its

**Comment by andybalaam** [comment]
Documenting the line below thing definitely makes it more palatable btw. Without that our feels pretty wrong.

**Comment by colonelfazackerley** [comment]
I have already written the code that answers your questions. see the diff in #249 

It's almost ready

**Comment by andybalaam** [comment]
Ok. I am satisfied but still maintain on principle that preserving order would be the absolute best solution.

**Comment by andybalaam** [comment]
For the record, groups of comments will move around with the meta line immediately below them, and comments in the level data or * lines will get moved to above the level data.

**Comment by andybalaam** [comment]
Once the wiki change is done, this will be done.

**Comment by colonelfazackerley** [comment]
wiki updated.
