### ISSUE TITLE
Level: Playing catch up

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#247]
easy one for #241 
```
:name=Playing catch up
:description=
:author_name=
:author_url=
:solution.1.code=UhDu@_NuAt:AbD:{{je}:YMuSL:t:]:t_O+MM{H
:num_rabbits=3
:num_to_save=3
:rabbit_delay=10,4
:num_saved=0
:num_killed=0
:num_waiting=3
:paused=false
:bridge=5
:climb=2
:dig=2
      
#(####
#)####
#(####
Q)####
 (# O 
### # 
```

**Comment by tttppp** [comment]
I came up with several solutions to this, and none of them worked. See if you can guess what goes wrong in these cases:

Case 1:

Dig a hole and change the digger to a bridger. Wait for all rabbits to be in hole and then dig out bottom of hole to get to exit.

Case 2:

Dig a hole one column to the left of the exit. Convert to bridger to prevent falling off bottom. Once all rabbits are in the pit, create a climber that climbs rightwards. Dig down over exit with this rabbit.

**Comment by colonelfazackerley** [comment]
Both your solutions hit bugs I have not seen before. I will prepare small demo levels for those bugs, unless you beat me to it.

**Comment by colonelfazackerley** [comment]
I assume you are not giving up yet. There is a way to do it, as the game stands.

**Comment by tttppp** [comment]
No, not yet. I was contesting it being an "easy" level though!

**Comment by colonelfazackerley** [comment]
It would be easy if it was not afflicted by bugs.

**Comment by colonelfazackerley** [comment]
Have I captured all the inappropriate behaviour? 
#267 
#268

**Comment by tttppp** [comment]
Yep. Looks good.

**Comment by andybalaam** [comment]
Good work. Fixing these bugs will make is better. I imagine the small world set will uncover more.

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Playing-catch-up.rel
