### ISSUE TITLE
--interactive mode not working

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#248]
```
$ make runinteractive 
. Checking for warnings in Makefile
. Checking version number (0.7.1) is consistent everywhere
. Checking for use of java.awt in engine code
. Compiling

BUILD SUCCESSFUL
Total time: 3 seconds
java -cp rabbit-escape-engine/bin/:rabbit-escape-render/bin/:rabbit-escape-ui-text/bin/:rabbit-escape-ui-swing/bin/ rabbitescape.ui.text.TextMain test/level_01.rel --interactive
rabbitescape.engine.util.CommandLineOption$UnknownOption: Unkown option: 'test/level_01.rel'.
	at rabbitescape.engine.util.CommandLineOption.getUnknownOption(CommandLineOption.java:132)
	at rabbitescape.engine.util.CommandLineOptionSet.match(CommandLineOptionSet.java:37)
	at rabbitescape.engine.util.CommandLineOptionSet.parse(CommandLineOptionSet.java:11)
	at rabbitescape.ui.text.TextMain.main(TextMain.java:45)
make: *** [runinteractive] Error 1
```

```
$ java -cp rabbit-escape-engine/bin/:rabbit-escape-render/bin/:rabbit-escape-ui-text/bin/:rabbit-escape-ui-swing/bin/ rabbitescape.ui.text.TextMain --interactive test/level_01.rel
rabbitescape.engine.util.CommandLineOption$UnknownOption: Unkown option: '--interactive'.
	at rabbitescape.engine.util.CommandLineOption.getUnknownOption(CommandLineOption.java:132)
	at rabbitescape.engine.util.CommandLineOptionSet.match(CommandLineOptionSet.java:37)
	at rabbitescape.engine.util.CommandLineOptionSet.parse(CommandLineOptionSet.java:11)
	at rabbitescape.ui.text.TextMain.main(TextMain.java:45)
```

I think I am missing something - @colonelfazackerley how are you generating solutions if you can't run this way?

**Comment by colonelfazackerley** [comment]
putting the solution in the rel, and 
runrabbit text -l ../blah.rel -s1
(perhaps piping to more)
and improving the solution.

I think runinteractive was broken before I started messing with the options. (It's not just that my option code has broken the older stuff)

**Comment by colonelfazackerley** [comment]
./runrabbit text ../blah.rel
should let you play a single game using the text ui, but it does not. Something about the implementation of solutions broke it.

**Comment by colonelfazackerley** [comment]
I take it back. It's my fault. How could i have doubted you?

I am doing another pull request. The command line syntax may be different. Hope that's OK.

**Comment by colonelfazackerley** [comment]
what used to work
'make run' did ```rabbitescape.ui.text.TextMain test/level_01.rel```
make runinteractive ```rabbitescape.ui.text.TextMain test/level_01.rel --interactive```

how about
'make run' does ```rabbitescape.ui.text.TextMain --noinput test/level_01.rel```
'make runinteractive' does ```rabbitescape.ui.text.TextMain test/level_01.rel```

I think actually playing the game in text mode is more common, so should be the default, without the extra option. 

i will wait for a reply before fixing.

**Comment by andybalaam** [comment]
I agree entirely. The current situation is purely historical.

**Comment by andybalaam** [comment]
Btw I think the makefile targets for running are made obsolete by the script. I will remove them sometime and update the docs accordingly.

**Comment by andybalaam** [comment]
`make runinteractive` and `./runrabbit text easy/level_01.rel` both now work as expected, thanks to #249.
