### ISSUE TITLE
Bug: Climb after entering and fall

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#252]
If a rabbit picks up a climbing token immediately after entering and then starts climbing, they fall down and climb up again.
```
:num_rabbits=1
  O
 ##
Q##
c##
###
```

**Comment by andybalaam** [comment]
There are quite a few little behaviour bugs but my plan for now is to fix code (non-behaviour) bugs when I get the chance, and continue releasing level sets as we make them, and get onto this kind of thing later. 

But do definitely log them.

**Comment by colonelfazackerley** [comment]
I figured out that Falling.checkTriggered returns true because climbing.abilityActive is false, even though the state is RABBIT_CLIMBING_RIGHT_CONTINUE_2. Falling trigger comes before climbing, so they fall.

Have not got any further yet.
