### ISSUE TITLE
Rabbits falling to death should splat sideways a bit

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#254]
See issue #138 - the falling to death on a slope animation is brilliant but I feel the landing should impart more sideways momentum to the rabbit when it lands. If needed we can use a larger image.

**Comment by andybalaam** [comment]
#139 sorry

**Comment by andybalaam** [comment]
ARGH Sorry #138

**Comment by colonelfazackerley** [comment]
So the rabbit's coefficient of restitution should be increased? OK if bunny bits spray into the adjacent square. I will look into it. This will give you a break from reading my code...
![splat-slope-bounce1](https://cloud.githubusercontent.com/assets/9596719/12127948/1181c510-b3f2-11e5-95d8-0bc913796e39.png)

**Comment by andybalaam** [comment]
Exactly.  As always, it's a pleasure working with you :-)

**Comment by tttppp** [comment]
That diagram is brilliant.
