### ISSUE TITLE
Util.concat varargs

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#256]
There has been a 2 arg version around for a while
```java 
public static <T> T[] concat( T[] left, T[] right )
```
I wanted to have more arrays stuck together, so I wrote this varargs version.
```java
    @SafeVarargs
    public static <T> T[] concatVarargs( T[]... aA )
    {
        List<T[]> l = Arrays.asList( aA );
        return list( chain( l ) ).toArray( aA[0] );
    }
```
This compiles like a dream, but then, when it's used, you get this.
```
java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at java.util.Arrays.copyOf(Arrays.java:2248)
	at java.util.ArrayList.toArray(ArrayList.java:389)
	at rabbitescape.engine.util.Util.concatVarargs(Util.java:691)
	at rabbitescape.engine.util.TestUtil.ConcatVarargs_3(TestUtil.java:113)
```

It is possible. This works for me, but we don't like it
http://stackoverflow.com/questions/9476613/simplify-this-generic-method-to-concatenate-java-arrays
from user newacct

As a temporary measure I have 3 and 4 arg versions of concat (which call the 2 arg version).

**Comment by andybalaam** [comment]
The answer beginning "Simple answer: no." on that StackOverflow link explains why we can't do this.  The accepted answer uses reflection, which is just wrong, wrong wrong.  I have updated the 2, 3 and 4 argument versions of the function - see what you think.  Personally, I am now fairly sure splitting up into several functions is the only type-safe way of providing this functionality and it does what we need without being evil.

If you agree, I think we can just leave it as it is.

**Comment by andybalaam** [comment]
If this irritates you, you have good taste, and should consider non-Java languages.

**Comment by colonelfazackerley** [comment]
It's not pretty. I just won't look. Code folding in eclipse.

The problematic step is creating the generic array. I don't understand why the 2 arg concat does not throw runtime exceptions.

**Comment by andybalaam** [comment]
Link for my convenience https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/engine/util/Util.java

**Comment by andybalaam** [comment]
Can you explain more? The 2 argument form uses toArray and passes in a real array that the code can use at runtime to identify what type it should make. Underneath it is probably doing some kind of cast but as long as I can't see it I don't mind.

**Comment by colonelfazackerley** [comment]
In the varargs version I did ```.toArray( aA[0] );```. ```aA[0]``` is the first array in the array of arrays, just like ```.toArray( a );``` from the 2 arg version passes an array of the correct type. I don't get why the varags version throws a runtime exception and the 2 arg version does not.

**Comment by andybalaam** [comment]
I'm not actually sure you are allowed to take a varargs of arrays as a parameter in the first place, let alone do an asList on it.

**Comment by andybalaam** [comment]
We might do better talking in am explicit array of arrays bit I'm not sure.

**Comment by andybalaam** [comment]
Personally I'm done with fighting Java's stupid type system.

**Comment by colonelfazackerley** [comment]
I think the exchange of views is complete.

**Comment by andybalaam** [comment]
:-)
