### ISSUE TITLE
Merging new levels into old sets (e.g Brolly levels)

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#258]
#226 Gave us Brollies, which are brilliant.

Now, we should have levels that use brollies.

Some of these should be merged into existing level sets (possibly making each set contain 25 instead of 20?)  Otherwise new players won't see brollies, which would be criminal.

I guess for now we could make a brolly-based level set, but we will definitely want to spread them around in future.

But, once we start shuffling levels we will mess up our record of their progress.

Currently, progress is tracked via a number for each set of levels, saying which level has been solved (and all the ones before it).

In future (I think) we should store the names (or ids) of levels the player has solved.  If we mix up the order of levels, the UI should illustrate which levels have been solved (and haven't), and allow you to play the first unsolved level in a set (and all levels before it) but not any others.

This requires:

- Unique ids for each level.  We can probably just use their real names, but this would prevent us from e.g. fixing typos in level names.  Perhaps we could use their file name without the leading number?

- An upgrade script that takes current numerical progress and replaces it with the known IDs of the solved levels.

- Change the code that disables levels to use the new ID-based solution.

Really, to make this feature palatable, we would also want:

- #205 Level names in menu items

and

- #257 Tick in menu next to solved levels

**Comment by colonelfazackerley** [comment]
Breaking the immutability of sets makes me nervous. I am not sure it's worth it.

Inserting level sets seems fine to me.

**Comment by andybalaam** [comment]
I just don't think it's sustainable long term. The first 60 levels I ever wrote are not going to be the best introduction to the awesomeness of the game as we keep making it more awesome.

**Comment by colonelfazackerley** [comment]
fair point. I am persuaded.

If we grow the easy set to, say, 25 levels, are we OK with different size level sets?

the way the config stores progress will need a rewrite. I would also like a cheat, so I can test on different platforms/uis without having to play through.

- level set directories prefixed with numbers so they are in the correct order in file browsers
- the progress stored in config should not be broken if we re-order the level sets (to insert an easier one)

**Comment by andybalaam** [comment]
Yes. And +1 for a cheat mode. I was considering odd behaviour in level easy 1 to unlock all levels. Preferably something fun.

**Comment by andybalaam** [comment]
Other easter eggs would also be welcome.

**Comment by andybalaam** [comment]
Doing some research this morning on how to do this. The first step would be to unify the levels completed handling between Android and swing. There is a ConfigBasedLevelsCompleted that is used in swing but not in Android but actually it could be used in both of we implement IConfig on Android which should be straightforward.

**Comment by andybalaam** [comment]
The next step would be to write shared code that wraps an IConfig and upgrades it if needed. It would do this by checking the configuration version every time you used it (not just on startup) and upgrading if we're not at the latest. Then we write an upgrade from position-based levels completed to name based.

**Comment by andybalaam** [comment]
First we have to unify the way we store what level you got to in Swing and Android.  I have written an upgrade to do it, but not yet enabled it.

Next:
1. Dummy upgrade for Swing/text, so the version numbers are in sync
2. Enable the Android and Swing/text upgrades (by passing them into the constructor of Config).  Simultaneously switch Android to use the ConfigBasedLevelsComplete instead of the one it has now that uses the pre-upgrade config format.
3. Write a (universal) upgrade that converts to name-based instead of order-based remembering of what levels you have completed.  Simultaneously, modify ConfigBasedLevelsComplete to use this new format.
4. Profit

**Comment by andybalaam** [comment]
New snapshot 0.8.0.6 uploaded here: http://artificialworlds.net/rabbit-escape/snapshots/

This upgrades your config from version 0 to version 1 (in the new config-versioning scheme I am establishing).

On a PC this has no effect.  On Android it switches to using the now-standard Config class to access all config, instead of directly using Android's SharedPreferences object.  (On Android Config wraps SharedPreferences, and on PC it wraps the config file as before.)

Please test and check:
- your muted state and levels completed is still the same after upgrading.
- your muted state and levels completed are preserved when you leave and enter the game.
- it generally works.

**Comment by andybalaam** [comment]
Steps 1 and 2 above are done. 3 is next and hopefully 4 will take care of itself.

**Comment by andybalaam** [comment]
Snapshot 0.8.0.8 uploaded to http://artificialworlds.net/rabbit-escape/snapshots/ - please test and let me know what's broken.

**Comment by andybalaam** [comment]
This latest version upgrades your config to list the levels you have completed based only on their names, instead of their position, or their level set.

Please test and check:
- your levels completed is still the same after upgrading.
- your levels completed are preserved when you leave and enter the game.
- it generally works.

**Comment by andybalaam** [comment]
Argh, it crashes on Android when it tries to save your progress.  I will look into this asap.

**Comment by andybalaam** [comment]
Hopefully fixed in 0.8.0.9 - please test.  (It now works for me on Android.)

Having annoying problems getting my Android emulator to work, which explains my sloppiness, sorry.

**Comment by tttppp** [comment]
Totally screwed with my progress. Medium went from 13 down to 2. Hard and outdoors went from 1 to 20. Easy stayed at 20, Arcade stayed at 9.

**Comment by tttppp** [comment]
Completing medium 3 seems to have stored that progress.

**Comment by andybalaam** [comment]
@tttppp oh no!  Something's up.  My testing here seemed to work...I wonder what is different.

**Comment by andybalaam** [comment]
I really don't get this - I was testing with medium here and it worked fine!

**Comment by andybalaam** [comment]
One possibility is that the double upgrade 0->1->2 failed somehow.  Were you already running a snapshot from this issue (that would have done 0-> already)?

**Comment by andybalaam** [comment]
I've finally got an emulator up and running, so will investigate further when I have time.

**Comment by andybalaam** [comment]
I'm thinking it might be to do with stripping numbers off the beginning of level set names.

**Comment by tttppp** [comment]
I don't know what version I was running with previously.  I think it was either 8.0.3 or 7.1.3.

**Comment by andybalaam** [comment]
@colonelfazackerley please hold off on testing this, so we can have a clean test.  I have thought of a better way of testing this and will see whether my hunch about what is wrong is correct.  I'm going to take several real config states from old versions and confirm they actually upgrade correctly.

**Comment by andybalaam** [comment]
This has been the feature of nightmares.  It's taken so much time, and it's invisible!

**Comment by andybalaam** [comment]
Really missing that speedup button when testing with 0.7.1!  I am trying to reproduce the problem @tttppp found.

**Comment by andybalaam** [comment]
Got stuck on Invader, then got a real buzz out of figuring it out again!

**Comment by andybalaam** [comment]
When I installed the debug version it wiped all my progress :-)

Trying again using a debug version of 0.7.1, meaning I can inject my own progress-cheating code instead of playing through again.

**Comment by andybalaam** [comment]
So I recreated @tttppp's situation as closely as I can, and it seems to work perfectly for me.

Unless anyone else has a clue on how to reproduce the problem, I have to give up and hope it was a one-off.  Upgrade seems to be working - we'll have to watch for bug reports from others.
