### ISSUE TITLE
Level: "Platforms, small"

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#26]
It's easy. Perhaps use it near the start of the outdoor set.
```
:name=Platforms, small
:description=
:num_rabbits=5
:num_to_save=5
:rabbit_delay=10
:bridge=3
:bash=3
:dig=2
:music=tryad-witness
         Q            
                      
                      
                      
         ###     ###  
    ###               
                      
    ##                
          ####        
O                     
#####                 
                      

```

**Comment by andybalaam** [comment]
Very cool.

**Comment by andybalaam** [comment]
Did it first time, but liked it.
Thought: 6 Skill: 7

**Comment by GamingInky** [comment]
I found a glich in this level where if a rabbit start's building a bridge then another rabbit walk's up it and get's to a part which the first rabbit is still half way through building it fall's and dies.

**Comment by andybalaam** [comment]
Yeah I plan to make rabbits able to walk on half bridges but we have to be really careful because it may make some old levels trivial.
