### ISSUE TITLE
Make target to remove trailing whitespace

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#260]
from Java source. Good idea?

Apologies for all the code style blunders on my part.

**Comment by andybalaam** [comment]
Np np I don't ask you to fix them because I know it's relatively unimportant. 

If we could automatically format the code that would be great. I don't know of a good java formatter that is usable outside am ide but that doesn't mean there isn't one.

Stripping white space would be a good start.

**Comment by andybalaam** [comment]
We could make it a git precommit trigger if we really felt confident about it.

**Comment by colonelfazackerley** [comment]
The trailing whitespace is something I find eclipse is not very helpful with. It should be easy to do with make and sed (or something).

I have tried some formatters, but the problem is there are always exceptions to the formatting, which are made manually and look nice. The auto-formatters then make them worse.

**Comment by andybalaam** [comment]
`perl -p -i -e 's/[ \t]+$//'` (untested)

**Comment by colonelfazackerley** [comment]
Looks like sed. If it was sed it would need a g for global.

**Comment by andybalaam** [comment]
But there is only one piece of trailing whitespace per line so I left out the g?

**Comment by andybalaam** [comment]
I'm happy to depend on standard Unix tools like sed, perl, python (in dev).

**Comment by colonelfazackerley** [comment]
I thought it was per file, not per line, but i am sure your are right.

**Comment by andybalaam** [comment]
`find ./ -name '*.java' -print0 | xargs -0` then what I pasted above.

**Comment by colonelfazackerley** [comment]
Would it be possible to modify this so it does "git status" and only removes trailing whitespace from files that have been modified or are new?

**Comment by andybalaam** [comment]
Good idea. git status has a `--porcelain` switch that makes the output more machine readable.

**Comment by colonelfazackerley** [comment]
```
git status --porcelain | sed 's_...__' | grep '\.java$$' - | xargs perl -p -i -e 's/[ \t]+$$//'
```
This works.

adding -Z to grep and -0 to xargs would be better (cope with newlines in filenames). I even read the manuals, but this does not seem to work.

However, I doubt we will be putting newlines in java filenames, so this should be OK.

'--porcelain' uses a ' M ' prefix for modified and a '?? ' prefix for new files. Using sed to remove the first 3 chars seems OK. I dont know if 'git status --porcelain' may do something else.
