### ISSUE TITLE
Level: Brolly intro

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#261]
There is a non-brolly solution, but I don't mind becuase this is not supposed to be a tttppp\* level

```
:name=Brolly intro
:brolly=2
:bridge=1
:dig=1
:block=1
:explode=1
:climb=1
:rabbit_delay=13,13,5
:num_rabbits=5
:num_to_save=5
Q        

#####    
#####    
#####    
#####    
#####   O
#########
```

*
tttppp:
    /ˈti:ti:ti:pi:pi:pi/
    adjective
        needing much effort or skill to accomplish, deal with, or understand.

**Comment by andybalaam** [comment]
:-)

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/94-brolly-intro
