### ISSUE TITLE
Level: Brollychuting 101

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#262]
```
:name=Brollychuting 101
:brolly=1
:bridge=1
:climb=1
:rabbit_delay=23,1
:num_rabbits=5
:num_to_save=5
Q##########
          O
####   ####
####   ####
###    ####
####   ####
####   ####
####   ####
###########

```

**Comment by tttppp** [comment]
Tougher than it looks! Maybe consider increasing the number of climb tokens and bridge tokens? I'm not sure an extra bridge, or four extra climb tokens will add any solutions.

**Comment by tttppp** [comment]
Raised in the forum: https://www.artificialworlds.net/rabbit-escape/levels/d/49-brollychuting-101/2

**Comment by andybalaam** [comment]
Awesome, closing this then!
