### ISSUE TITLE
Level: The great divide

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#264]
```
:name=The great divide
:num_rabbits=3
:num_to_save=3
:climb=1
:brolly=1
:bridge=2
:bash=2
 O         
##   #   ##
#Q   #    #
#    #    #
#    #    #
#    #    #
#    #    #
###########
```

This is possible without brollies. I will work on that.

**Comment by tttppp** [comment]
Again, very nice small level and introduction to brollies.

**Comment by andybalaam** [comment]
Nice level.  I did it without brolleys, and enjoyed it!

**Comment by colonelfazackerley** [comment]
Just played this through. Can't recall how I intended to make brollies a requirement. Thought it was quite easy.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/91-the-great-divide
