### ISSUE TITLE
Level: Brolly hero

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#265]
Small world #241 candidate
```
:name=Brolly hero
:description=
:author_name=
:author_url=
:solution.1.code=4|x%%e%<$u4?J%9B"AQM%M?A4o5ZweE%Jx]4]A%]#h^##%BeAa@#]&e
:num_rabbits=2
:num_to_save=2
:rabbit_delay=4
:brolly=1
:dig=2
:explode=1
##   ##
#c/#\j#
###p###
#  # Q#
#     #
#     #
#  #  #
#O #  #
#######
```

**Comment by tttppp** [comment]
Nice introduction to brollies!

**Comment by andybalaam** [comment]
Worth logging an issue for that.

**Comment by colonelfazackerley** [comment]
I think I made an issue for num_rabbits actually meaning the number of rabbits that will use entrances, excluding rabbits that start in the world. This is the source of the -1.

**Comment by andybalaam** [comment]
Yes but it's not strictly this issue. I think the report of how many rabbits are "out" should be fixed to include those that started "out".

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Brolly-hero.rel

**Comment by andybalaam** [comment]
Really enjoyed this!

**Comment by andybalaam** [comment]
Now released at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/06_small_world/05_Brolly-hero.rel
