### ISSUE TITLE
?missing dependency on linux

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#27]
after installing everything listed in INSTALL.md "make rungui" yields

Gtk-Message: Failed to load module "canberra-gtk-module"

**Comment by colonelfazackerley** [comment]
I have "libcanberra-gtk3-module" installed already. probably some debian specific packaging issue

**Comment by colonelfazackerley** [comment]
sudo apt-get install libcanberra-gtk*

to install 32 bit versions and various guff fixed it. probably not a smart solution.

**Comment by andybalaam** [comment]
Did you see what it was doing when it complained about this?  Was it Inkscape failing?

**Comment by colonelfazackerley** [comment]
I think inkscape was complaining, and it made the build fail. if you really want to know, I can knock up another clean debian VM and repeat.

**Comment by andybalaam** [comment]
By the magic of Docker:

    $ docker run -it debian
    # apt-get update && apt-get install git make openjdk-7-jdk ant sox inkscape
    <snip>
    # git clone https://github.com/andybalaam/rabbit-escape.git
    <snip>
    # cd rabbit-escape/
    # make test
    <snip>
    inkscape images-src/token_bash.svg <snip>
    Bitmap saved as: rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/token_bash.png
    compile:
        [mkdir] Created dir: /rabbit-escape/rabbit-escape-engine/bin
        [javac] Compiling 112 source files to /rabbit-escape/rabbit-escape-engine/bin
        [javac] /rabbit-escape/rabbit-escape-engine/test/rabbitescape/engine/i18n/TestTranslation.java:67: error: unmappable character for encoding ASCII
        [javac]             Translation.Instance.sanitise( "foo! bar% Baz$ BASH?? Quux\" =" ),
        [javac]                                                                ^

So interestingly, in the Docker version of Debian (Jessie, 8.2), Inkscape seems fine, but the compile fails, I think because it is assuming the source code is ASCII, when I intend it to be UTF-8.

Using Docker, we can make this into an automated test easily.

**Comment by andybalaam** [comment]
What version of Debian where you using?  If possible, I would like to see the error again, as I certainly wouldn't want someone on Debian being unable to build it.

**Comment by colonelfazackerley** [comment]
debian 8.2

**Comment by andybalaam** [comment]
I logged #30 to track the ASCII problem.  Let's use this one for the original Inkscape problem.

**Comment by andybalaam** [comment]
Closed due to @colonelfazackerley 's comment on #30
