### ISSUE TITLE
'make compile' does not allow warnings but eclipse does

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#273]
So, if make hits a warning first, I find out about it, if eclipse happens to compile that file first, I don't.

**Comment by colonelfazackerley** [comment]
Is this just my eclipse settings, or is this shared config?

**Comment by andybalaam** [comment]
The "Problems" view in Eclipse shows you all warnings. Does that solve it? I think I looked into it once and found you can't make warnings errors in Eclipse.

**Comment by colonelfazackerley** [comment]
There's a risk that I make a pull request with warnings in but dont realise. I am trying to get into the habit of 
make clean
make slowtest

before making pull requests.

**Comment by andybalaam** [comment]
Good idea

**Comment by andybalaam** [comment]
Should we say this in the docs. Do we have a "contributing" page?

**Comment by colonelfazackerley** [comment]
> Should we say this in the docs. Do we have a "contributing" page? 
There is a baby one now.

**Comment by andybalaam** [comment]
Woot, thanks!
