### ISSUE TITLE
Enhancement: Discussion: swing demo mode

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#274]
Should further token drops by user clicks be allowed as the solution plays?

**Comment by andybalaam** [comment]
To allow incrementally building solutions?

**Comment by colonelfazackerley** [comment]
sounds good to me. shouldn't be a problem having a recorder capturing the modified solution as you go.

**Comment by colonelfazackerley** [comment]
Baggsy

**Comment by colonelfazackerley** [comment]
I am working on this now.

**Comment by colonelfazackerley** [comment]
implemented in #279

**Comment by tttppp** [comment]
How do we use this to incrementally build solutions?

**Comment by colonelfazackerley** [comment]
when the solution is playing 
```runrabbit swing -l foo.rel -s1```
you can click and add stuff. it gives you the updated solution at the end. this, can of course be manually edited before putting it back into the file and trying again.
