### ISSUE TITLE
Bridging rabbit can be distracted by a climbing token

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#275]
```
   #
   #
r* #
####
:*=ic
```

I'm not sure I typed the above right on my phone but basically if you place bridging and climbing tokens on the same Square in front of a rabbit it will start bridging and then give up. It should become a climber immediately and also build a bridge.

**Comment by tttppp** [comment]
Should we still be able to stop bridges early with climbing tokens?

**Comment by colonelfazackerley** [comment]
We probably need to try other token combinations. Does it make a difference if the tokens are the other way round?

```
:*=ci
```

**Comment by andybalaam** [comment]
> Should we still be able to stop bridges early with climbing tokens?

I didn't know you could do that and I consider it a bug. I think picking up climb and brolly tokens should have no effect on anything else and should happen immediately.

**Comment by andybalaam** [comment]
> Does it make a difference if the tokens are the other way round?

Probably and if so I consider that a bug too.

**Comment by colonelfazackerley** [comment]
> >    Should we still be able to stop bridges early with climbing tokens?

> I didn't know you could do that and I consider it a bug. I think picking up climb and brolly tokens should have no effect on anything else and should happen immediately.

I think climbing tokens should stop rabbits that are actively digging, and they should start climbing out of the hole they have dug. (This is current behaviour).

**Comment by tttppp** [comment]
It's quite useful to be able to spend tokens to stop bridging. It might mean you need to plan ahead, eg if you bridge too high then you need to have given the bridger a brolly token, or be forced to end the bridge early by giving him one.

**Comment by andybalaam** [comment]
Hmm. Maybe this is good. If so this bug is not a bug. Opinions?

**Comment by andybalaam** [comment]
Previously I had thought that "active" tokens like bash or dig would interrupt you but passive like climb would not.

**Comment by tttppp** [comment]
I'm sure this is being used for levels. I suggest this is not a bug.

**Comment by andybalaam** [comment]
Fine, it's probably too late now, and the behaviour is perfectly reasonable.
