### ISSUE TITLE
Discussion: multi-action commands including waits should be illegal

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#277]
I was implementing an exception to be thrown when a solution containing this is parsed.

I found a test with this in "bash&(1,1)&3;WON".

I think this should be illegal. The point of '&' is to allow multiple actions in a command in a single time step, so combining it with a wait defeats its purpose. We agreed '&' should be used as little as possible. 

... and (here it comes) it makes solution playback code fiddlier.

Can I make it illegal and implement that exception?

**Comment by tttppp** [comment]
Sounds sensible to me. It also avoids ambiguity in solutions like:
```
bash&2&(1,1)
```

**Comment by andybalaam** [comment]
Yes. I wrote that test (I think it was me) because I could see a potential sane interpretation but not because I thought it was a good idea. Btw I still think you can avoid the awkward logic by reusing SolutionInterpreter so it might make your last point moot.
