### ISSUE TITLE
'make dist' should only try to make the .apk for andybalaam

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#285]
'make dist' always ends up like this for me.
```
. Building generic jar dist/rabbit-escape-generic.jar
. Copying generic jar into Android workspace rabbit-escape-ui-android/app/libs/rabbit-escape-generic.jar
. Building and signing release apk dist/rabbit-escape-0.7.1.apk
ls: cannot access /home/cf/pw/android-key-store-password.txt: No such file or directory
Makefile:369: recipe for target 'dist/rabbit-escape-0.7.1.apk' failed
make: *** [dist/rabbit-escape-0.7.1.apk] Error 2
```
perhaps it could silently not try to build the .apk if ~/pw/android-key-store-password.txt does not exist

**Comment by andybalaam** [comment]
In principle it could work for anyone who had that key store details. Why are you running it? You can do `make dist-swing` to build the jar.

**Comment by andybalaam** [comment]
Or even someone who had different key store details and wanted to make their own signed apk.

**Comment by colonelfazackerley** [comment]
I had not noticed that target. I was just doing 'make dist'. I will use the other.
