### ISSUE TITLE
Self documenting Makefile

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#288]
https://gist.github.com/prwhite/8168133

Bearing in mind my recent failure to notice the dist-swing target, I think this would be really cool.

**Comment by andybalaam** [comment]
Sounds good - can we use it directly (is there a licence?)

Note that typing `make` then hitting TAB a couple of times will list the targets (in bash).

**Comment by andybalaam** [comment]
I will accept patches, but won't get around to this myself.
