### ISSUE TITLE
Enhancement discussion: change speed action for solutions

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#290]
This would help test that changing speed does not change the way the game plays out. It may also be useful for writing demos where the speed is seen to increase at the end as the bunnies skip home.

**Comment by andybalaam** [comment]
Soundsfine

**Comment by andybalaam** [comment]
I am thinking this is very low priority, so am inclined to close it unless someone wants to work on it now.  Any objections?  (Wanting to avoid the issue list being full of speculative maybe-features...)

**Comment by colonelfazackerley** [comment]
OK

I was thinking a solution could be made shorter by it speeding up. I guess the obvious alternative is to stop it playing.

**Comment by andybalaam** [comment]
Ok. If you work on it reopen this or make another.
