### ISSUE TITLE
Implementation order

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#294]
There are a lot of ideas floating in the issues. I have been wondering about how to tackle them.

a) #105 Death squares (water) and snorkels (maybe #131 standing on blockers too)
b) #257 Ticks in menus and a new way of recording level completion in the config. As we insert new levels a player may have completed 3 and 5, but not 4.
c) #205 Level names in menu items
d) #258 Five more levels for easy, medium, hard, outdoors and arcade. These would use brolly and snorkel tokens. #218 some easier levels is a related issue.
e) #109 Paradise (#218 easier levels) and #241 small world 
f) #87 Deja vu 

Not sure where #78 upside-down rabbits fit in.

Have I missed something, or is there a better order?

**Comment by GamingInky** [comment]
cool

**Comment by andybalaam** [comment]
To b) I would add remembering how many attempts you've made too. Then we can reveal hints and walk throughs progressively.

**Comment by andybalaam** [comment]
I would say do it in order of how interested you are. Just make clear what you are working on to avoid clashes. The above order looks fine.

**Comment by andybalaam** [comment]
Not sure I'm convinced of the need for snorkels by the way.

**Comment by tttppp** [comment]
I'm not sure I understand quite what the behaviour of snorkels is. We need to consider what a water will look like (e.g. is it contained?) If so then how does the rabbit swim (horizontally or are they affected by gravity?)

Gradual access to hints sounds great. Maybe also gradual access to future levels (without having completed earlier ones).

**Comment by andybalaam** [comment]
We have everything we need now to be able to provide walk throughs too. In super Mario after a while it just plays the level for you (if you want) and allows you to progress to the next one.

**Comment by GamingInky** [comment]
if people need it that will be helpful

**Comment by andybalaam** [comment]
Shall I close this?

**Comment by colonelfazackerley** [comment]
i suppose the milestones do the same job as this.
