### ISSUE TITLE
Level: Keep On Trying

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#296]
Deja Vu (#87) version of Keep (#67, Arcade 12). Save 19/20, slightly adjusted rabbit delay and loads of bridge and dig tokens.  I used the Swing solution recorder to solve - nice!

```
:name=Keep On Trying
:description=You don't want to be the dirty rascal
:solution.1.code=Yq:ScSLSS+cADSYq:>A:>A:q:JwYq:cw:J:q:Aw:L}9SSLDjFdAd:F>A:L}AA9Aq::L}9S+LA>Jw:L}SSA:>JwL9SeDS+:L}>Jw9LSjFAY?LYq#U#L#@qhFL>:AS+J:wjYqL}F>:cADJ:wA>JdwDe:>:9ADJ:wq:FL::A>JSw9Y:LjFq:}SwL>D:L:SA>cAAA>J:YJ:ADYq:J::hwqJ:Yq:Fcq:>J:YqASwA:>J:>DDjw:Sw:FYAwj.w.jFqA9FDA}L>::jA:J:>c:L>>:Yq:JD:FJL}h.ww:D:Yq::S:hL>Yq:JwSFdJA:cq:w.9:SA:F:cw::wYq:SA::A:L}+$+FjwYkkR}d}::FYL>j$}L]:q?JF::}hq:>:>>:dAJJ>:AJ:9dJwwL:::Y:9$}J]j:?Lh:wJ:F:>}SAwFc>:JeAAD:ADAwwF:L>Sq}:LS>Fhc:wJ>hA:+SJAw9F:dJ::jYDdj:>L>FqhwFAq}+::w:A:qSeY:::>:JAj>hLqJ::AFLA}AwJj::w+>A:SF>S:SJ.AF>Jwqe:.wdJ:L>>FwS:qA9JJ:Jej:wS9:A::qFY+q_wAUM_kdUM:::Ajdjw:LJ>:hSFAD}9J:>+>>wS:::A:JdYcDj>:L:Fq::Fq:}LA:F:SA:D9A::F>q:SS:9ASJJYc+]ww::#.+e#::F>L_Se}.JYJDjdw!w:Y::F::_q
:music=tryad-beat_into_submission
:num_rabbits=20
:num_to_save=19
:bash=5
:dig=99
:bridge=99
:climb=5
:block=2
:explode=10
:rabbit_delay=31,30,30,30,4
        #               #  
  #           O            
     #        #            

        # # # # # #  Q     
        ###########        
        )#       #(        
         #       #         
         #       #         
        /#########\        
        #         #       /
\       #         #       #
#Q      ###########       #
#       #         #       #
###########################
```

**Comment by colonelfazackerley** [comment]
That solution is extremely long. I am a little scared.

**Comment by tttppp** [comment]
That's partly because I used the Swing recorder. It records every switch between token type regardless of whether you use them. It's also really hard to get things right first time, so it's got my false moves recorded too.

Much easier than the text UI though!

**Comment by tttppp** [comment]
Ps If anyone records a shorter solution I'd be interested to see it.

**Comment by andybalaam** [comment]
I guess we should optimise away useless ability changes.

**Comment by tttppp** [comment]
This is a great choice for the final level of Deja Vu. I started it but failed, but the attempt took several minutes and showed me that I needed to solve at least two more sizable problems before the level would be complete.

**Comment by andybalaam** [comment]
Yeah I like the fact that the last level is really long and very challenging. I must say following the hints is probably harder than working it out yourself!

**Comment by tttppp** [comment]
I've lost this level once more since my previous comment. Fun challenge!

**Comment by tttppp** [comment]
This has been live for a while.
