### ISSUE TITLE
Warnings in AnimationTester

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#299]
```
. Compiling
    [javac] /home/andy/code/public/rabbit-escape/rabbit-escape-ui-swing/src/rabbitescape/ui/swing/AnimationTester.java:446: warning: [overrides] Class AnimationTester.FrameCounter overrides equals, but neither it nor any superclass overrides hashCode method
    [javac]     private class FrameCounter
    [javac]             ^
    [javac] error: warnings found and -Werror specified
```

**Comment by andybalaam** [comment]
@colonelfazackerley I still can't think of a way of making Eclipse object more strongly, but maybe we should investigate further, or just integrate a continuous integration server on GitHub so it notifies you if you leave a warning in.

**Comment by colonelfazackerley** [comment]
I think I saw a way of getting eclipse to be fussy. I will do a pull request if I can find it again.

Apologies for not taking my own advice and doing 'make clean slowtest'

**Comment by andybalaam** [comment]
No problem. By the way I saw more warnings when I opened it in Eclipse. I guess those ones don't come up in the javac build (unused variables and imports).
