### ISSUE TITLE
game is small on a high res screen

### ISSUE THREAD

**Issue by antonpiatek** [andybalaam/rabbit-escape#3]
On my laptop I have a fairly high res screen and the game is a small window on it. If your tiles are svg it would probably look pretty good scaled up to full screen as it is, otherwise you might want to make it bigger but fill the edges with something more exciting at some point

**Comment by andybalaam** [comment]
Yes, during the build we created scaled versions of all images (some source images are svg, some largish png) so zooming is possible.  On a phone/tablet you are going to expect to be able to zoom, so this is definitely on the radar.

**Comment by andybalaam** [comment]
The zooming functionality now implemented fixes this.
