### ISSUE TITLE
Compile fails on (Docker version of) Debian Jessie due to file encoding

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#30]
At least in the Docker version of Debian Jessie (8.2):

    $ docker run -it debian
    # apt-get update && apt-get install git make openjdk-7-jdk ant sox inkscape
    <snip>
    # git clone https://github.com/andybalaam/rabbit-escape.git
    <snip>
    # cd rabbit-escape/
    # make test
    <snip>
    compile:
        [mkdir] Created dir: /rabbit-escape/rabbit-escape-engine/bin
        [javac] Compiling 112 source files to /rabbit-escape/rabbit-escape-engine/bin
        [javac] /rabbit-escape/rabbit-escape-engine/test/rabbitescape/engine/i18n/TestTranslation.java:67: error: unmappable character for encoding ASCII
        [javac]             Translation.Instance.sanitise( "foo! bar% Baz$ BASH?? Quux\" =" ),
        [javac]                                                                ^

The fix is to add:

                <compilerarg value="-encoding"/>
                <compilerarg value="utf8"/>

To the javac command in build.xml

**Comment by colonelfazackerley** [comment]
I built a new Debian 8.2, and this time it worked just fine first time. I did use LXDE this time, and default Debian DE the first time. Probably just me doing something wrong the first time. I suggest closing the issue. If there are reports of failed builds, I can investigate more.

**Comment by andybalaam** [comment]
OK, weird.  Thanks.

**Comment by andybalaam** [comment]
Actually, wrong issue.  The encoding one should be fixed I think.
