### ISSUE TITLE
Enhancement: Discussion: fire

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#300]
A fire burning in a square would crisp bunnies entering it. It would not have the same complexity as water. Perhaps implement fire first. Of course, if we have fire and water, the water would put out the fire, introducing puzzling opportunities.

**Comment by andybalaam** [comment]
I like it a lot.

**Comment by colonelfazackerley** [comment]
I am working on this now. Just a little inkscaping so far.

behaviour thoughts
- I think the fire should fall (if it is undermined by a basher)
- It will not spread (bunny world materials are retarding)
- we may consider adding wooden blocks later
- when we have some water, that will put out fire.
- bunnies entering fire squares spend the next time step burning.

**Comment by tttppp** [comment]
If the fire falls then I think it would be good to have another type of death trap that can't be moved. Maybe reusing the edge-of-world void but for individual squares?

**Comment by andybalaam** [comment]
I don't see much of a problem with traps always falling. @tttppp did you have specific puzzles in mind?

**Comment by tttppp** [comment]
The puzzles where I used piles of bombs to prevent rabbits from going through certain squares are hacks for this type of static trap. It would be nice to say "this is the route the rabbits must/must not take".

**Comment by tttppp** [comment]
A couple of really simple examples:

```
X       
 T T    
 TOT    
 TTT    
        
########
```

And this low corridor with bridges, bashes and dig tokens:
```
TTTTTTTT
#X     #
#     O#
#      #
### # ##
```

**Comment by tttppp** [comment]
Note that I didn't test either of these examples, they were just off he top of my head.

**Comment by colonelfazackerley** [comment]
I don't like re-using the void edges. Having edges is a necessary evil.

I don't understand 'T' and 'X' in your examples.

Can you not put metal blocks under fire if you don't want the fire to be dropped?

**Comment by tttppp** [comment]
T is the trap, X is the entrance (did I get the symbol for entrance wrong?)

**Comment by tttppp** [comment]
In the corridor example the point is that the fire is the roof, so you can't bridge too high. It wouldn't work if there was a row of metal because bridgers wouldn't be able to get burnt.

In the other example there is a wall of fire to circumnavigate. Metal could be used for some of the squares, but with a wall of fire then the player is forced to use blockers on Bridges.  Also climbers can't scale fire (a minor point since climbers can't scale a mixture of fire and water).

Static traps are a staple of many puzzle games, including lemmings. It's possible to work around not having them in some cases, but I think it would look neater to support some sort of "this square is out of bounds" trap.

It'd clearly not an urgent thing, I just think it might be easier to make levels using fixed traps than falling ones.

**Comment by colonelfazackerley** [comment]
Sorry, but I still want the fire to fall. We can discuss more when we have some working code and we can play some levels. I think metal, fire and water will give plenty of options for no go areas.

I got bored while drawing the first frame of some fire, so I started hacking some GNU Octave to draw it for me. This needs a lot of work, but you should get the idea.

![fig](https://cloud.githubusercontent.com/assets/9596719/12643582/e6c9a714-c5b4-11e5-8c57-900cd9c6f7d9.png)

![fire](https://cloud.githubusercontent.com/assets/9596719/12643589/f5a41990-c5b4-11e5-9d9d-65a315324925.png)

**Comment by tttppp** [comment]
I have no objections to fire falling, I just think that a non-falling trap will add more options. Until water is added then fire will behave very much like a stack of explode tokens.

I love the gradients in the preview! Keeping a hand drawn look for flames, impressive.

**Comment by andybalaam** [comment]
Yes I am convinced that falling and non falling traps will both be good.

**Comment by colonelfazackerley** [comment]
Maybe we could have electrocution traps that don't fall. If the water shorted them, even shallow water would be deadly.

**Comment by andybalaam** [comment]
The fire looks brilliant and I'm excited about the water fire interactions.

**Comment by tttppp** [comment]
Electrocution + water + metal sounds like potential for some challenging puzzles.

**Comment by colonelfazackerley** [comment]
Glad to hear there is no resistance. I also think it has potential, and current.

**Comment by colonelfazackerley** [comment]
I am (slowly) working on the animation. I am working on a function to modulate the streamer width.

**Comment by colonelfazackerley** [comment]
Here is some modulated streamer width. Still needs animating.
![fire](https://cloud.githubusercontent.com/assets/9596719/12745017/36cc5120-c98f-11e5-8cc1-9c19e89ab59d.png)
They have a textured look. I left this in as I thought it might give it a nice texture. May have to develop the animation a bit further and decide if I still like it.

**Comment by colonelfazackerley** [comment]
colours will be fixed, and the streamers need to sway around a bit, and need more streamers, but here is some animation. also each streamer needs different modulation.
![fire](https://cloud.githubusercontent.com/assets/9596719/12751320/7e4658c8-c9b4-11e5-81a3-d0190846345d.gif)

**Comment by colonelfazackerley** [comment]
![fire](https://cloud.githubusercontent.com/assets/9596719/12757196/e2ac2846-c9ce-11e5-8ae7-5fd00f448b54.gif)
streamer modulation variability

**Comment by tttppp** [comment]
Looking hot! Once this is done I would like to change my existing levels to us fire rather than bomb stacks. Will fire rest on bridges in the same way as bombs? Does fire fall at the same rate as tokens?

**Comment by colonelfazackerley** [comment]
I have not done any java yet. just messing with the pictures. i intend for the fire to fall at token rate, and stop on bridges.

**Comment by colonelfazackerley** [comment]
I made a few improvements and then upped the streamer count.
![fire](https://cloud.githubusercontent.com/assets/9596719/12766096/cb1d5d96-c9f9-11e5-9811-5bc3dc6bbbb2.gif)
Any suggestions? 

I might start trying to work it into the game.

**Comment by colonelfazackerley** [comment]
4 variant animations calculated on the bus.

you can see the transparency in-game that i got wrong in the previews above.

![animation](https://cloud.githubusercontent.com/assets/9596719/12777167/ea17ada6-ca52-11e5-9845-e9f4a89453af.gif)
![animation](https://cloud.githubusercontent.com/assets/9596719/12777177/f755f324-ca52-11e5-835a-65388b68943e.gif)

**Comment by colonelfazackerley** [comment]
I find myself copy-pasting from Token for Fire. Can I use a common subclass, say FallingThing?

**Comment by colonelfazackerley** [comment]
methods like someoneIsBridgingAt could move to BehaviourTools, but that class is a bit of a monster.

**Comment by colonelfazackerley** [comment]
It's loaded from rel, and it falls. Does not burn yet.
![bunny-fire](https://cloud.githubusercontent.com/assets/9596719/12801201/97e9f914-cad2-11e5-9695-34da1140f2d2.gif)

**Comment by colonelfazackerley** [comment]
burn, bunny, burn
![bunny-fire](https://cloud.githubusercontent.com/assets/9596719/12812764/d4c9fe70-cb2b-11e5-913c-7cce273f72a6.gif)
I am going to do a custom animation. (this re-uses frames from out of bounds bunnies).

also the fire should be drawn over the rabbit.

**Comment by colonelfazackerley** [comment]
fire in front. custom frames.
![bunny-fire](https://cloud.githubusercontent.com/assets/9596719/12814113/83fe6cd4-cb34-11e5-8b54-aa8288f525f7.gif)

**Comment by andybalaam** [comment]
This is amazing

**Comment by andybalaam** [comment]
I think the fire should be lower in the frame so it looks like the block below is on fire. Now it looks like it is floating.

**Comment by andybalaam** [comment]
The animation is just beautiful

**Comment by andybalaam** [comment]
Yes, a common sub class is fine or preferably move the code outside and reuse it from both places.

**Comment by andybalaam** [comment]
I wonder whether we can make a more fally animation for when it is falling?

**Comment by colonelfazackerley** [comment]
fally...

longer streamers? the source of the streamers more round? As it falls at token and brolly speed, perhaps it should drift from side to side a bit, like a falling leaf?

**Comment by colonelfazackerley** [comment]
I have created my own project to store my picture generating scripts in.
https://github.com/colonelfazackerley/octave-particles
It needs a lot of work, but I figure it is better to have it backed up and versioned.

**Comment by andybalaam** [comment]
Less triangular. Other than that I reckon I should butt out and let you work since what you've got so far is so cool.

**Comment by colonelfazackerley** [comment]
i also need fire on slopes. different shapes req
- fire on flat surface
- fire on right slope
- fireball falling

animations for 
- flat fire changing to ball (as block below is bashed out).
- ball changing to flat (as it lands)
- same for left and right slopes.

quite a lot needs doing.

**Comment by andybalaam** [comment]
No need to animate the transition between States. E.g. walking rabbits turn abruptly into falling rabbits.

**Comment by colonelfazackerley** [comment]
I will try without first and see how it looks.

**Comment by colonelfazackerley** [comment]
I have been working on fire on slopes.
![fire_rise_right_a_](https://cloud.githubusercontent.com/assets/9596719/12871662/e98d1b14-cd7c-11e5-95a9-551ae67772a4.gif)

**Comment by colonelfazackerley** [comment]
I lowered a variant (the leftmost). I will lower the others too.
![bunny-fire](https://cloud.githubusercontent.com/assets/9596719/12874186/f5fa75aa-cdc6-11e5-9c73-6f6e0447f019.gif)

**Comment by andybalaam** [comment]
Looking good

**Comment by colonelfazackerley** [comment]
Couple of observations
- rabbits have a higher terminal velocity, so will catch up and burn. not sure how often this will crop up. I dont mind it. I do intend to make the falling fire drift side-to-side, so the slow falling looks natural. Its a mix of napalm and feathers or something.
- I will need a custom animation for falling onto slopes.
![re](https://cloud.githubusercontent.com/assets/9596719/12928837/a32e2270-cf67-11e5-9ef3-fb02e85f5d69.gif)

**Comment by colonelfazackerley** [comment]
A lot of large gifs on this page now. It is starting to get laggy on Firefox. Chrome is better.

The drag image on to page thingy does not work for me in Chrome, though. So I am using both.

**Comment by andybalaam** [comment]
Burning in the air is fine.

**Comment by andybalaam** [comment]
Fire falling onto slopes is not mandatory to fix now. It will be rare to nonexistent.

**Comment by andybalaam** [comment]
I really like the burning animation.

**Comment by colonelfazackerley** [comment]
I already started working on the fire falling on to slopes. It is almost done.

**Comment by andybalaam** [comment]
Cool

**Comment by colonelfazackerley** [comment]
This is coming along. Just need some ASCII art tests.

I added an offset feature to the rea parser. Can shift all frames at once.

https://github.com/colonelfazackerley/rabbit-escape/blob/fire/rabbit-escape-render/src/rabbitescape/render/AnimationLoader.java

**Comment by colonelfazackerley** [comment]
I have also made tokens sit higher on slopes in my fire branch.

**Comment by andybalaam** [comment]
Looks good

**Comment by tttppp** [comment]
I just sat and watched the latest animated gif for a while. Beautiful stuff.

**Comment by colonelfazackerley** [comment]
Ready, over at #327

**Comment by colonelfazackerley** [comment]
generating those fire images takes quite a long time. I was just looking into the timing of it (as i thought i would reuse some of the code for water). I thought calculating particle interactions was the slow bit, but its actually setting pixel values in the images. Setting the pixel values can take 20 times longer than calculating the interactions. I might write a c++ plugin for this bit of octave.

**Comment by andybalaam** [comment]
Yeah, I love the animations, especially the rabbit burning.  Also excited that the sound effect fits so well with the others, despite differing vocal chords.

**Comment by colonelfazackerley** [comment]
The sound took a few goes. I did check the level was about right compared to the existing sounds.
