### ISSUE TITLE
On Android void flips between variants each time step

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#303]
Since #301 the void around the level appears but it randomly flips between variants each time step. (On Android)

**Comment by colonelfazackerley** [comment]
It did that in swing to start with. then I stored the VoidMarker.Style in SpriteAnimator and it was OK. I guess the Android code must make a new SpriteAnimator each step.

**Comment by colonelfazackerley** [comment]
I will do a pull request to fix. 
- Store the void style in the world. 
- Support parsing void style from rel files.
- if no void style is chosen. do something.... maybe make a number from the world name, and use the remainder after dividing by the number of styles to pick one. then worlds with the same name always get the same edging.

**Comment by colonelfazackerley** [comment]
Oh, is engine allowed to have dependencies on render?

**Comment by colonelfazackerley** [comment]
No, it's not. Should I move the Style enum from VoidMarker to somewhere in engine, possibly World?

**Comment by andybalaam** [comment]
Yes, world seems a sensible enough place.

**Comment by colonelfazackerley** [comment]
I have made another class for it. I can move it to World. I should have the pull request ready this evening.

**Comment by andybalaam** [comment]
Another class is fine too.

**Comment by colonelfazackerley** [comment]
I think this is fixed. Just needs testing on Android.

BTW, could you write a wiki page on compiling for Android. I know you told me once by email or something, but I am struggling to dig it up.

**Comment by colonelfazackerley** [comment]
There is some stuff in INSTALL.md, but some more details (like how to install android studio) would be handy.

**Comment by colonelfazackerley** [comment]
I tested this on android when looking at the speedup button: it does not flip. please close this issue.

**Comment by andybalaam** [comment]
Will make a snapshot when I get a chance - thanks!

**Comment by andybalaam** [comment]
New snapshot 0.7.1.2 up at http://artificialworlds.net/rabbit-escape/snapshots/
