### ISSUE TITLE
Level: Heavy metal

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#316]
For #313 and #241

```
:name=Heavy metal
:description=
:author_name=colonelfazackerley
:author_url=
:num_rabbits=5
:num_to_save=5
:rabbit_delay=5
:bash=1
:bridge=3
:climb=1
:dig=1

 Q  M   O
#   #   #
#   M   #
#####  /#
##### /##
#########
```

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/development/smallworld/Heavy-metal.rel

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/90-heavy-metal
