### ISSUE TITLE
play store "what's new" does not mention what's new

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#32]
should probably mention the android 2.2 fix.

the update just got pushed to my phone.

**Comment by andybalaam** [comment]
I did mention it. What does it say for you?

**Comment by colonelfazackerley** [comment]
![img should be here](https://lh3.googleusercontent.com/-uG-jFmAjduc/VflIjPRHlyI/AAAAAAAAe0g/cJQpVJdhnSI/s512-Ic42/Screenshot_2015-09-16-09-47-43.png)

**Comment by colonelfazackerley** [comment]
a day after I installed the update, the "what's new" just changed to mention the Android 2.2 fix.

**Comment by andybalaam** [comment]
Weird.  Must just be the way it works.
