### ISSUE TITLE
Build instructions for Android Studio

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#320]
Write up proper build instructions for Android from scratch.

**Comment by colonelfazackerley** [comment]
It's a bit of a stream of consciousness, but there is something

https://github.com/andybalaam/rabbit-escape/wiki/Android-Studio

I suggest this it closed.

**Comment by andybalaam** [comment]
Brilliant! I think this is really helpful.  Could you add a link to how to enable your device?

**Comment by andybalaam** [comment]
I mean the bit of configuration your have to edit to add your manufacturer ID.

**Comment by colonelfazackerley** [comment]
I mean the bit of configuration your have to edit to add your manufacturer ID.

I think I read about that, but it was not necessary for me.

I added some bits about enabling dev options etc.

I think this issue can be closed now.

**Comment by andybalaam** [comment]
I added a link to http://developer.android.com/tools/device.html since I always seem to need it . Thanks again.
