### ISSUE TITLE
setting up a system for rabbit escape

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#324]
I have changed a windows system to dual-boot. I thought I would make some notes here.

INSTALL.md goes from installing dependencies to ```make test```. should we include this?
```
git clone https://github.com/andybalaam/rabbit-escape.git
cd rabbit-escape
make test
```

**Comment by colonelfazackerley** [comment]
I updated the wiki git page: set git username and email

**Comment by andybalaam** [comment]
Thanks. To answer your original question: yes that would be good.

**Comment by andybalaam** [comment]
Should we close this?

**Comment by colonelfazackerley** [comment]
I think it should stay open until INSTALL.md is updated.
