### ISSUE TITLE
Switching to another app and back forgets fast-forward state

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#325]
* Start playing a level
* Press fast-forward
* Switch to a different app
* Switch back to Rabbit Escape
* Note that the fast-forward button looks pressed, but the rabbits are walking slowly.

Because our Android code is wrongly factored, when the user switches to another app, we save the state into a `Bundle`, including whether or not the fast-forward button is pressed, but when the user switches back again, the Rabbit Escape code creates a whole new Game instance (because `GameSurfaceView` receives a `surfaceCreated` call) but we have not actually received the saved state `Bundle` because `onCreate` was not called - only `onResume`.  Android expects us to have remembered our state in memory as well as having saved to to the `Bundle`.

We should create a `Game` in `onCreate` and hold on to it in `AndroidGameActivity`, instead of re-creating it every time a surface is created.

I will work on this, but I think it's too disruptive to put in just before the 0.8 release, and not important enough to delay that release, so I'm tracking it here.

**Comment by andybalaam** [comment]
Snapshot 0.8.0.2 contains this fix: http://artificialworlds.net/rabbit-escape/snapshots/

We need to play with this a bit - I may have broken things.

I also probably want to do a bit more further tidying.

**Comment by andybalaam** [comment]
I'm getting a crash in 0.8.0.2 when I switch between applications.  More work required.

**Comment by colonelfazackerley** [comment]
I got a crash switching back to RE on my phone too.

**Comment by andybalaam** [comment]
New snapshot 0.8.0.3 at http://artificialworlds.net/rabbit-escape/snapshots/

Please let me know whether it works.  I tried it here and it seems ok.

Again, there will be some tidying needed, if we find this basically works.

**Comment by andybalaam** [comment]
btw anyone concerned that our download size has gone up to 13MB?

**Comment by andybalaam** [comment]
(Due to the extra images.)

**Comment by colonelfazackerley** [comment]
Let's worry when we get near 50MB. (Which might happen with water....).

**Comment by colonelfazackerley** [comment]
The fire pngs sum to 5.4MiB. There are 4 variants. Could easily drop this to 3 or 2 to save a MiB or two.

**Comment by andybalaam** [comment]
Yes, we should consider that.

**Comment by andybalaam** [comment]
Meanwhile, I appear to have made another bug, so re-opening this.

**Comment by andybalaam** [comment]
When you open level easy 1 on Android, choose the dig ability, and rotate the screen, you find you no longer have the dig ability selected, and you can't select it.  I believe this is probably caused by my changes for this issue, so I am re-opening it.  If it turns out this is a separate bug I will create a separate issue.

**Comment by andybalaam** [comment]
I have just confirmed that this works fine in 0.8 so it's almost definitely been caused by my changes for this bug.

**Comment by andybalaam** [comment]
Looks like a nice easy fix (92b41dd) but I'll leave this open for a bit for further testing.  Snapshot 0.8.0.4 uploaded to http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by andybalaam** [comment]
btw my latest podcast is 39MB so probably no need to panic quite yet.
