### ISSUE TITLE
Discussion: reduction of dependence on GitHub

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#326]
GitHub is awesome at hosting Git repos.  GitHub issues are brilliant.  GitHub is a thriving social network that gives us exposure to lots of potentially interested developers.

But, GitHub is proprietary, so if they change the rules we have no power to stop them.

Also, GitHub issues are online-only, meaning it's hard to work when GitHub is down, as it was the other day when I wanted to work.

Can we get the advantages of GitHub without the disadvantages?  I'd like a usable backup of all our issues (preferably stored in a Git repo) so that we can continue working when it's down, and move to another service when they go all Sourceforge.

This might be of interest: https://github.com/dspinellis/gi

Also, this: http://blog.printf.net/articles/2015/05/29/announcing-gittorrent-a-decentralized-github/

Thoughts?

**Comment by colonelfazackerley** [comment]
I have thought the same, I want the github issues when I am on the bus, and don't have inet.

I was thinking of a script that downloaded the issues using the github api. Both the things you found look much better. I guess we need to try them.

**Comment by andybalaam** [comment]
I don't think I'm ready to stop using git hub issues but it would be nice to have a backup in something like gi. I'd also really like to write a ui for gi that works like git hub's issue ui but realistically I'm not going to find time for it.

**Comment by andybalaam** [comment]
The perfect solution would be a system that synchronised in both directions.

**Comment by andybalaam** [comment]
I think we could choose to publish a git torrent url that pointed at our git hub repo right now.

**Comment by andybalaam** [comment]
I am in favour of this but unlikely to get to it, so closing it until I or someone else starts work on it.
