### ISSUE TITLE
Animation for blocker on slope...

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#330]
...in progress. I need to tweak the code, and do one for a right rise.
![animation](https://cloud.githubusercontent.com/assets/9596719/13072427/2e18c682-d491-11e5-9066-ce0f272e494b.gif)

**Comment by andybalaam** [comment]
@GamingInky and I simultaneously exclaimed "That's so cool"

**Comment by tttppp** [comment]
That's so cool!

**Comment by colonelfazackerley** [comment]
Glad you guys approve. Almost ready.

![re](https://cloud.githubusercontent.com/assets/9596719/13090431/88e1f3ac-d4ed-11e5-8c1b-4a9c7d5d5d5f.gif)

**Comment by colonelfazackerley** [comment]
implemented #332
