### ISSUE TITLE
Tokens start higher than the centre of the square

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#338]
I presume this is a side-effect of the code to place tokens higher on slopes ( @colonelfazackerley )

![token-high](https://cloud.githubusercontent.com/assets/76812/13170077/6d31d690-d6e1-11e5-9455-8cabd5334a61.png)

When I place tokens they appear about half a square higher than they should (on both Swing and Android).

They then jump down when they start to float and float down normally.

**Comment by colonelfazackerley** [comment]
i am working on this now. it's a bit fiddly.

On 19 February 2016 at 08:19, Andy Balaam <notifications@github.com> wrote:

> I presume this is a side-effect of the code to place tokens higher on
> slopes ( @colonelfazackerley <https://github.com/colonelfazackerley> )
>
> [image: token-high]
> <https://cloud.githubusercontent.com/assets/76812/13170077/6d31d690-d6e1-11e5-9455-8cabd5334a61.png>
>
> When I place tokens they appear about half a square higher than they
> should (on both Swing and Android).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andybalaam/rabbit-escape/issues/338>.
>



-- 
/* andy buckle */

**Comment by andybalaam** [comment]
Nice fix
