### ISSUE TITLE
auto-crop images

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#348]
Lots of the images have large regions of nothing but transparency. I dont think this makes the pngs bigger, as it compresses well. Would I be correct in thinking that cropping these would decrease
 memory usage, as the game caches them uncompressed?

- analyse each image (probably easier when rendered to png) and figure out what can be cropped
- removing bits from the right and bottom is easier
- find all rea where the image is used
- crop the top and right
- adjust the offset values in the rea to compensate

I think I could do this. The bit I am least sure of is programmatically cropping the svg files.

**Comment by andybalaam** [comment]
Can we do something to check whether it affects memory usage before you do all this work?

**Comment by andybalaam** [comment]
Also, I am worried it will make it harder to do animations if every frame is a different size. Could we keep the originals somehow?

**Comment by andybalaam** [comment]
An alternative could be to use SVG images at runtime instead of pngs. I dismissed this at the time because SVG rendering is an additional dependency but as our memory and download sizes increase it might be worth revisiting.

**Comment by andybalaam** [comment]
Further thought: is runtime memory usage a problem any more? If not spend your time on something more interesting :-)

**Comment by colonelfazackerley** [comment]
- runtime memory is not a problem for me personally, but I know you like to keep the min spec under control
- i totally understand how having a large document in inkscape is necessary. i was wondering if it could be sorted later. if the steps i listed are achieved, i think we could also have a system that reversed them. ie added borders top and left to set offsets back to zero, and offsets right and bottom to make each frame in an animation the same size.
- i am not working on this at the moment, but i know you were tweaking the cache system. is that so successful that we dont need to worry about memory usage.

**Comment by andybalaam** [comment]
I am pretty happy that the cache will keep us safe at the moment.

**Comment by andybalaam** [comment]
I'll close this until we find a good reason to work on it.
