### ISSUE TITLE
Level: Dig quick

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#359]
Needs #355 to play. An easy level to demonstrate pipes and drowning.

```
:name=Dig quick
:description=Find a way to the exit before all the rabbits drown.
:author_name=tttppp
:num_rabbits=6
:num_to_save=5
:dig=5
:solution.1.code=%HfCH\}l`h%%^EC%|h}jX
:music=tryad-witness
###########
# P Q # P #
#  \ /#  /#
#\  ##  /##
# #\   /  #
#  ####   #
#\       O#
###########
```

**Comment by andybalaam** [comment]
Haven't played it yet but this level really makes the point for me that we must fix decisions about water behaviour and speed now and live with them forever. 

Really looking forward to playing.

**Comment by tttppp** [comment]
Agreed. The water speed is completely unrealistic - water spreads at the same speed as rabbits walk, it falls at half the speed of a rabbit. However the speed seems really good for making challenging levels - it's slow enough that a) you can see what's going on, and b) you can race against it, but fast enough that you feel pressured.

I'd encourage people to try playing with the current settings and see if they seem reasonable. Drowning on slopes is an area I'm not sure works that well yet, and this level is a good place to test it.

**Comment by colonelfazackerley** [comment]
Let's just say you have developed an extremely realistic model of anti-gravity custard.

(Seriously - I could make it yellow...)

**Comment by andybalaam** [comment]
Wow. Custard! I think I like it.

**Comment by tttppp** [comment]
I prefer water - everyone knows that you can walk on custard: http://www.rsc.org/chemistryworld/2012/07/why-can-we-walk-custard

I'm not sure if the research has been done with rabbits yet though...

**Comment by andybalaam** [comment]
Oh dear.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/?q=dig%20quick
