### ISSUE TITLE
License permission for work by @tttppp

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#36]
@tttppp, do you agree I (and any company or organisation I one-day form) can distribute any code, levels, graphics, sound effects you have provided to me under all of the following licenses?

- **CC-BY-NC-SA**: Creative Commons Attribution Non-Commercial ShareAlike license
- **CC-BY-SA**: Creative Commons Attribution ShareAlike license
- **GPL**: GNU General Public License, v2 or a later version

The first license (CC-BY-NC-SA) is used for levels, graphics etc. at the moment, and the third (GPL) is used for code.  By agreeing to all three, we make it easy to re-license to a completely [Free Culture](https://creativecommons.org/freeworks) license if we decide to do this in future.

This allows me to use the work commercially, but prevents others from doing so.  If/when we relicense to a Free Culture license, everyone will be allowed use it commercially.

**Comment by tttppp** [comment]
Hi Andy, I agree to these license conditions.

**Comment by andybalaam** [comment]
Woot, ta.

**Comment by andybalaam** [comment]
@tttppp 

I have decided to release all our work under "GPL v2 or later", as you agreed above.

I regret using a non-free license originally.  This change should make it easier for others to build on our work, distribute it more widely, and have fun making modified versions with no restrictions other than the reciprocity provided by the GPL.  More info: https://creativecommons.org/share-your-work/public-domain/freeworks/

Separately, but related, I plan to release a free-of-charge version on the Google Play store.  The pay-for version will remain too, but make it clear you can get the free one if you prefer.

**Comment by tttppp** [comment]
Sounds great Andy! Thanks for all he work you've put into this project :-)

**Comment by andybalaam** [comment]
Thank you!
