### ISSUE TITLE
Level: Aquifer

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#362]
Needs #355 to play. I think this is quite a hard level, although I bet it's possible to save more rabbits than the target. (The target of 5 is my current high score).

```
:name=Aquifer
:description=Try not to drown.
:author_name=tttppp
:solution.1.code= v :v 8ZRu}0CR(R:u v  EC?< (C a~B EC 6:v 3z3`8:R}2~(CZ68: -R-v CR:v/C-} 3 B2~`23`B v 6 <:5u28v 6~v E8:0CRa :uZuu C ZC v5uC8(C:(R v 3 :? 3a3`zv 5 R /? 2 6uCuB:v  RC5C(8 R6 C  E:36R5:0B v` u vC:( Z:Z:  - 3Cv2 ZB} ` v 5C:8(R6:/URv:R-}aC3Z -z5Cv8R?6R  Uu  U3 a?5uav z6R< 8 (}} z :<:C(Rv<EZ2v BR ~CZ~  5}3: ?R33 2zvB<u``R Zu5
:num_rabbits=10
:num_to_save=5
:block=10
:dig=20
:bash=20
:explode=10
:music=tryad-witness
#####################
#         Q         #
#  ###\       /###  #
#    ###########    #
#                   #
#####################
#  #P           P#  #
#  ###############  #
#### #    O    # ####
     ###########     
```

**Comment by colonelfazackerley** [comment]
I got 6 out. Let's make that a deja vu.

**Comment by colonelfazackerley** [comment]
Nice level, BTW.

**Comment by colonelfazackerley** [comment]
I got 8 out
:solution.2.code=j[yI~z[|Ip#[pp7jpIp;IjO[[##[}p#_I%*jpO;f#'$pOAh#jjp"|y%I

A simpler 5
:solution.3.code=OFO+?!?F_IFO!I_+@L^+!AZ!p??Y_O+_FF!I

**Comment by tttppp** [comment]
8 sounds very impressive. That should be a Deja Vu level.

Now we have future levels in the source code, I think extra solutions and proposals for Deja Vu should be submitted as pull requests. I'm not sure how Andy wants to handle it, eg should we try to avoid lots of small pull requests? Also, should this issue be closed now that the level is in the development directory?

**Comment by andybalaam** [comment]
Tentative proposal: levels managed as pull requests and level sets as issues. Discussion of difficulty, deja vu etc can go in the level set issue. Sound ok?

Small pull requests are good by the way. Especially levels in development, which I can merge almost immediately.

**Comment by andybalaam** [comment]
#87 deja vu

**Comment by tttppp** [comment]
Sounds good to me. I can imagine that single levels as issues may still be useful in a few cases:

1. When the author doesn't understand how to use git (and has no intention of becoming a developer).
2. When the level might benefit from some collaborative discussion.
3. When the level is actually demonstrating a bug.
4. When the author isn't able to get to a computer?

But generally I think getting levels into source control sooner rather than later sounds good.

**Comment by andybalaam** [comment]
Agree on all counts. Eventually we need a way to submit levels without a github account but that is for later.

**Comment by GamingInky** [comment]
I solved it but I think it might be able to be improved by you making it a bit less hectic:

```
:name=Aquifer
:description=Try not to drown.
:author_name=tttppp
:num_rabbits=10
:num_to_save=5
:block=10
:dig=20
:bash=20
:explode=10
:music=tryad-witness
#####################
#         Q         #
#  ###\       /###  #
#    ###########    #
#                   #
#####################
#  #P           P#  #
#  ###############  #
###  #    O    #  ###
   ###############   
```
So you could do the normal thing or go round the water.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/29-aquifer
