### ISSUE TITLE
RFC: Store future levels in source code

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#364]
Currently we store future levels in Github issues. This means we don't know if the solutions are broken by changes to the source. It also means  (less importantly) that theres

**Comment by tttppp** [comment]
Accidentally hit "Comment" part way through :-(

**Comment by tttppp** [comment]
... no way to test future levels on Android.

I suggest we create some new folders for levels called "Staging" and "Development", and within each we have folders called "Deja Vu", "Paradise", "Small World" and "Unsorted". Levels which are completely ready for publishing can go in "Staging". Levels which are missing hints, solutions or descriptions can go in "Development".

The tests should check all the mandatory fields are present in "Staged" levels, and all the solutions in all levels.

The cheat mode could unlock all these extra levels, allowing us to test levels on Android before they're released as part of a level set.

**Comment by andybalaam** [comment]
Yes, very good

**Comment by tttppp** [comment]
I pushed the testing changes and a few random levels to tttppp/FutureLevels. Adding all the existing levels will take a little effort.

I'm not planning to change the menu code to work with the cheat mode, as Andy's refactoring the level completed code at the moment, and I imagine there will be significant potential for overlap. Anyway, it should probably go in a separate pull request to keep the diffs small.

**Comment by tttppp** [comment]
Right, I've added all the levels I could find, and I'll create a pull request. Then everyone can review their levels to check they're ok.

**Comment by andybalaam** [comment]
Had a very quick look. Any reason why you're using real files and dirs instead of loading from the classpath? I would much prefer the latter.

**Comment by andybalaam** [comment]
You'd need to use ls.txt files like we do for normal levels but I think we could easily do that.

**Comment by tttppp** [comment]
I just copied the pattern that was already there. Besides I think I am loading from the classpath. Are you concerned because you saw File.separator?

**Comment by tttppp** [comment]
Presumably the only code that actually loads anything from the file system is the custom level loader (and the Github level loader seems to piggy back on it).

I just checked the pull request and the bit which makes me think I'm not actually loading from files is the use of NothingExistsFileSystem. I've not looked to see what it does (I'm on my phone now) but it would be surprising if it found something on the file system.

**Comment by andybalaam** [comment]
Sounds like I completely misread the code. I'll have a proper look when I get a sec. Sorry, reviewing cod on a phone is a bad idea.

**Comment by andybalaam** [comment]
All merged. Reopen if there's more to do but I think this is done?
