### ISSUE TITLE
Bug: Water connected into blocks

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#368]
I have been using the following test world for water rendering.

```
#  P 
#\1/2
#####
```
After it has run for a while, the WaterRegion objects for cells marked 1 and 2 both return true when asked if they are connected down. This can't be right, as there are solid blocks beneath.

I am using the a test for falling water that @tttppp suggested (connected down and the cell below not full), so this is causing problems for me.

**Comment by tttppp** [comment]
Those cells are connected down, as they have no internal wall on on the bottom. The cells beneath aren't connected upwards.

In this case the cells beneath are full, as they have a capacity of zero.

Although I created a temporary graphic for falling water, I never got around to writing the logic, so you may find the model needs improvement. Hope this is helpful.

**Comment by colonelfazackerley** [comment]
Ok, so it is only slope blocks where isConnected matters. For most cells I only need to test if the block below is full. This should fix the pipe at the start of the level too.

**Comment by tttppp** [comment]
Ahh, good point. I forgot that there are no WaterRegions in cells with solid blocks. That was an optimisation I added for the Java code which wasn't in the Python prototype.
