### ISSUE TITLE
Feature request: Pools of water start in the world.

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#369]
perhaps a W, so we don't have to use pipes to have some water.

**Comment by colonelfazackerley** [comment]
@tttppp

**Comment by tttppp** [comment]
This is a really useful idea, as pipes are far more lethal than is needed in some levels. I'd suggest using 'N' as a full WaterRegion (1024 units in a square gap, 512 units in a triangular gap). The text display also uses 'n' as a partially filled WaterRegion, so we could interpret it as a half filled WaterRegion.

If the blocks result in multiple WaterRegions in a cell then I suggest we apply the amount of water to all WaterRegions in the cell. (Currently blocks can't be arranged to create multiple regions in a cell, but the code supports it, so it make sense to handle this case).

**Comment by andybalaam** [comment]
Sounds good.

**Comment by tttppp** [comment]
I made a brief start on this, but I stopped because it was going to be far more work than I expected. I ended up creating a new class called StandingWater, which was just a Tuple<Position, Integer>. I passed this into the World constructor (which is already huge). I didn't write any tests or update the existing references to World.

**Comment by tttppp** [comment]
I think I have a fix for this. I need to test it.

**Comment by tttppp** [comment]
The implementation I went for means that N is always 1024 units of water, and n is always 512 units, unless a water description line is given for the cell. A water description line  specifies the position and amount of water of something that isn't 1024 or 512 units (or 0 units). For example 400 units of water in cell x=2, y=3 would be specified with a line at the end of the file that looks like:
```
:n=2,3,400
```

If there is no water region in this cell then the modifier is ignored. We could possibly do validation on the water amount description line, but I don't really think user-created levels will contain them very often.

**Comment by tttppp** [comment]
This can be closed now.
