### ISSUE TITLE
Level hard 20 seems a bit too easy

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#37]
Drop 3 tokens, the lead rabbit picks them up, and it's done.
![h20e](https://cloud.githubusercontent.com/assets/9596719/9918303/ecd014e6-5cbd-11e5-9e96-ee923e477e1e.png)
I guess it is supposed to be harder?

**Comment by andybalaam** [comment]
D'oh, yes.

**Comment by andybalaam** [comment]
See also https://github.com/andybalaam/rabbit-escape/issues/53#issuecomment-143303426

**Comment by tttppp** [comment]
Another solution to worry about:

![screenshot_2015-09-25-18-16-40](https://cloud.githubusercontent.com/assets/7073263/10108053/a9b821a8-63b6-11e5-9f6d-ac4274abcfca.png)

**Comment by tttppp** [comment]
I tried to find a more complicated solution to this that wasn't trivially simplified to one of these (e.g. use the climber to make a bridge up to the platform from the exit side) but I couldn't.  I did find another simple solution by falling into the pit, bridging, bashing and then bridging to the exit (similar to my previous solution, but bashing across between the two bridges).  Whatever the 'proper' answer is it must be quite tough!

**Comment by andybalaam** [comment]
OK, can you crack this?

    :name=Mary Poppins
    :description=Chim chim-in-ey, chim chim-in-ey\nChim chim cher-ee!
    :hint1=Bridge.
    :hint2=Bash.
    :hint3=Bash.
    :num_rabbits=10
    :num_to_save=10
    :climb=1
    :bridge=4
    :bash=3
    :music=tryad-the_final_rewind
    ######################
    #          \ \ \ \   #
    #  Q       # # # #   #
    #         ########  ##
    # #######           O#
    #   \ \ # ############
    #   # #   ############
    #   # #   ############
    ######################

**Comment by andybalaam** [comment]
I tried to do something like https://github.com/andybalaam/rabbit-escape/issues/37#issuecomment-143349510 but only ever got them stuck like this.

![hard-20-bridge-up](https://cloud.githubusercontent.com/assets/76812/10115305/d8d37ae8-63fa-11e5-855c-4a13bf25dc6c.png)

(Yuck behaviour btw with these constrained bridges.)

**Comment by tttppp** [comment]
Ok, I just solved the 'correct' way. Very nice puzzle!

**Comment by colonelfazackerley** [comment]
It's difficulty is well pitched now.
