### ISSUE TITLE
Level: Dambusters

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#379]
For #241 
It's 9 wide, I think this should be the limit for #241

I may have left loopholes allowing alternative solutions, but I think this level is a bit @tttppp. 
```
:name=Dambusters
:description=
:author_name=colonelfazackerley
:author_url=
:num_rabbits=5
:num_to_save=5
:rabbit_delay=4
:solution.1.code=|CiC|CB?UH1H(U>C(U11(_|CHr9>B=|DC|?+UZHF(XHUD(1(_X|CHC|C991r)1Bk$>U(D(_?r9=CU(>H)CC||9_XLH}}C|A9BCFHHiCC$C(kDU=C
:block=2
:climb=1
:bash=1
:bridge=6
:explode=5
:dig=2
/# #  ##\
 P #  #  
#  #  # A
## #    #
####  ###
 Q       
   ### AO
#########
```

**Comment by tttppp** [comment]
This level was excellent! I went through many many wrong attempts before finding all the tricks.

My solution: `9m7E^r6s_GE,meLm0-7EdEL^*m92xr^m7maEm0emaL<^fL2*ma_m0m*,,mGG[^-Gmmm7F*xr2[79^ermLx2[cdL*mm_**0-',0XGm/-mmc0m7,mE77ammeaaL_^ca[7mm[L*aead*EL`

Comparing them, the two solutions are almost identical, with a few token drops shuffled around.  Very nice puzzle!

**Comment by colonelfazackerley** [comment]
They are very similar solutions.

I thought you might like this one.

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Dambusters.rel
