### ISSUE TITLE
Level: "Half The World Away"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#38]
Not a bug report this time - just a normal level!
```
:name=Half The World Away
:description=Dreaming of jetpacks...
:num_rabbits=2
:num_to_save=2
:rabbit_delay=2
:climb=1
:bash=2
:dig=1
:bridge=3
:music=tryad-witness
#########          
#                 O
#                  
#Q                 
#       #          
#                  
###### #           
#      #           
#      #           
#    ###           
#                  
#########          
```

**Comment by colonelfazackerley** [comment]
I think this is the first level where the exit is floating. I made a test level, to check: the bridge has to go through the exit. The animation for the exit is not pretty.

Drawing the diagonal bridge line backwards, and you come the end of the lowest platform. The exit is one square too far to the right for the 3 bridges supplied to reach.

**Comment by andybalaam** [comment]
Yes, a floating exit is a fun idea, but it doesn't work in terms of the animation or the perceived physics.

**Comment by colonelfazackerley** [comment]
Here's a variation that
* is possible to complete,
* avoids a completely floating exit, and,
* feels a little more outdoors to go with the next set under construction.
```
:name=Half The World Away
:description=Dreaming of jetpacks...
:num_rabbits=2
:num_to_save=2
:rabbit_delay=2
:climb=1
:bash=2
:dig=1
:bridge=4
:music=tryad-witness
                   
                  O
                  #
 Q                 
        #          
                   
######             
                   
       #           
     ###           
#                  
#########          
```

**Comment by tttppp** [comment]
I'm pretty sure the original was possible to complete. I'll check later when I'm at a computer.

**Comment by tttppp** [comment]
The original is possible to complete. Here's a variation with one extra block underneath the exit:
```
:name=Half The World Away
:description=Dreaming of jetpacks...
:num_rabbits=2
:num_to_save=2
:rabbit_delay=2
:climb=1
:bash=2
:dig=1
:bridge=3
:music=tryad-witness
#########          
#                 O
#                 #
#Q                 
#       #          
#                  
###### #           
#      #           
#      #           
#    ###           
#                  
#########          
```
The roof is just to make the level feel like half of it is missing - this doesn't quite work with the outdoor theme though.

(I haven't solved colonelfazackerley's variation yet)

**Comment by colonelfazackerley** [comment]
I completed tttppp's variation. It's hard. I find that clicks are not always registered on windows (I was using jre1.8), which meant I could not do it. I switched to linux (jdk1.7 jre), and did it 5th attempt, even though this was in a VM, so should, if anything, be less responsive.

It's still reasonably open, even with a half-roof. I suggest it goes in.

**Comment by tttppp** [comment]
Finally solved colonelfazackerley's version. I didn't spot the extra builder at first!

**Comment by andybalaam** [comment]
Thanks, I intend to commit @tttppp's variation unless anyone prefers @colonelfazackerley's.

**Comment by andybalaam** [comment]
Woah, that felt hard.  Took me about 5 goes.
Thought: 9 Skill: 8

**Comment by andybalaam** [comment]
@colonelfazackerley please split your variant into a separate issue if it's different enough (which it sounds like it is).

**Comment by colonelfazackerley** [comment]
It's too similar. I am happy to ditch it.
