### ISSUE TITLE
Level: Water tower

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#381]
I was trying to make a level where understanding the new features is essential. This one has
- fire
- water
- brollies
- metal

With a height of 9, this just meets the #241 criteria.

```
:name=Water tower
:description=
:author_name=colonelfazackerley
:author_url=
:num_rabbits=5
:num_to_save=4
:rabbit_delay=4
:solution.1.code=M3<j`{I/`.3:"}/~QHe3/`/{/3/C};.FI/M/j/}/Fm$`//$F/}<*{~hMQ}3QhFUM://v`/m3{/}{`{`vMC}/MDFM
:brolly=2
:bridge=2
:block=2
:bash=2
:dig=2
     Q  
        
       #
    MMMM
    MP M
#*A #  #
MMM #  #
M M #  #
########
:*=OA
```

**Comment by colonelfazackerley** [comment]
Bunnies falling too far and dying in a square that also contains a fire will show splat and then burning animations. Don't know if this is a bad thing: black comedy, if you ask me.

**Comment by andybalaam** [comment]
Looks very cool. I am guessing the double animation only happens when they fall an odd number of squares. It demonstrates a common kind of big where one behaviour takes over from another but in this case it seems harmless.

**Comment by GamingInky** [comment]
I've just played this level it's very good and fun ( I had to look at the solution ).

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Water-tower.rel
