### ISSUE TITLE
Level: Escape from Shurrapak

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#382]
I think this is hard. Possibly not in a good way.

It started from The traitor, but diverged a lot. It's too different for deja. Not sure where this will fit.

```
:name=Escape from Shurrapak
:description=[To Gilgamesh] I thought you were dead.
:author_name=colonelfazackerley
:author_url=https://github.com/colonelfazackerley
:hint.1=
:hint.2=
:hint.3=
:solution.1.code=7[ce^dF7[-*^de7[c*^de0c,^Gc,^_20-7[-7[-m[-^F7m[c^F7m[c^F7m[-^-[c[c7c[F[-[-fmdF^F7[-e7dF*[-*^de7[^*^97[7<7*c9x9Fef,^dF/ed_7d9*^0[72eFx^^c[e77cd*7[^e'ed^^[--777*d*c[^e'ee^^dc7-77-d,[[[d'd0^^-c^-77Fdd2[d['[c^ed-^/7-dd7e[2d'e-^[/cf^7^eFc6
:music=tryad-beat_into_submission
:num_rabbits=5
:num_to_save=5
:bridge=30
:bash=5
:dig=4
:rabbit_delay=9,6,5
   P               

  P     #        # 
###   #   #     # #
#Q    #  (  # #    
   #  # ### #P ## O
##(  ( ( ( (  ((( #
###################
```

**Comment by andybalaam** [comment]
Looking forward to trying these. Finding myself wanting to be able to try development levels in snapshots. Maybe in cheat mode, or in a second secret mode.

**Comment by colonelfazackerley** [comment]
you mean on android?

in swing i use the load level feature and navigate to the dev levels under blah..engine..blah..blah..blahdey...blah...blah.

**Comment by colonelfazackerley** [comment]
seeing the merge comment in #383 

perhaps this could be an extra for outdoors.

**Comment by andybalaam** [comment]
Sounds good.

**Comment by andybalaam** [comment]
Yes, I do mean Android. I do most of my rabbit escape work on the toilet these days.

**Comment by andybalaam** [comment]
I am working on https://github.com/andybalaam/rabbit-escape-level-editor/issues/1 so we can put this level on the forum.

**Comment by andybalaam** [comment]
Now the forum supports it, moving this to here: https://www.artificialworlds.net/rabbit-escape/levels/d/28-escape-from-shurrapak
