### ISSUE TITLE
Level set: elemental

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#383]
For non-small fire and water levels, like #382

**Comment by colonelfazackerley** [comment]
and #361

**Comment by colonelfazackerley** [comment]
.

**Comment by andybalaam** [comment]
At least until we start merging them into other level sets.

**Comment by ChickenMaster128** [comment]
I realy like that idea , I will make some levels for it.

**Comment by ChickenMaster128** [comment]
And by the way whats the dot for.

**Comment by colonelfazackerley** [comment]
Re: dot. 
I forgot to terminate the sentence in my previous comment. Just mild OCD.

Welcome to Rabbit Escape.

**Comment by colonelfazackerley** [comment]
Levels with lots of metal blocks in would also fit the theme.

**Comment by andybalaam** [comment]
Anyone still interested in making this level set?

**Comment by tttppp** [comment]
Sure, it's quite a good idea for a set that introduces fire and water. Reordering the levels for 1.0 makes some sense to me, but I think we still need to avoid introducing all concepts in the first level set.

**Comment by GamingInky** [comment]
Could include Rabbot levels too as the element of evil

**Comment by GamingInky** [comment]
Lightning #498 was intended for this levelset.

**Comment by andybalaam** [comment]
Let's re-create this at https://www.artificialworlds.net/rabbit-escape/levels if we want it.
