### ISSUE TITLE
Discussion: java version

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#387]
We want to stick with 1.7 for compiling, so we stay compatible with elderly droids.

openJDK 's 1.7 JRE has poor performance for drawing transparent polygons in swing.

This seems to work. (Note; I think you need to set java first, then javac, as it sets the JAVA_HOME env var).

```
cf@kl:~/re/rabbit-escape$ sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /opt/java/64/jre1.8.0_77/bin/java                2000      auto mode
* 1            /opt/java/64/jre1.8.0_77/bin/java                2000      manual mode
  2            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
  3            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
```

```
cf@kl:~/re/rabbit-escape$ sudo update-alternatives --config javac
There are 2 choices for the alternative javac (providing /usr/bin/javac).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-openjdk-amd64/bin/javac   1081      auto mode
* 1            /usr/lib/jvm/java-7-openjdk-amd64/bin/javac   1071      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/bin/javac   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
```

We could also consider using the --source arg for javac to use the 1.8 JDK to make v1.7 class files.

**Comment by andybalaam** [comment]
The situation is worse than you outline, and java is stupider than you imply. We should compile for java 6 to support Android api level 8, but so far we've got away with it. Meanwhile, java makes it basically impossible to compile for one version with a compiler of a different version. It will check the syntax for new constructs but it won't check your library usage for new methods and classes. (You can specify a different library to use but at this point you need a path specific to your system. )

I think we should have a continuous integration setup that compiles with java 6, 7 and 8, and probably a couple of Android versions too.

**Comment by tttppp** [comment]
I've tried using Travis for a python project and it works really well with Github. The docs are here for java projects: https://docs.travis-ci.com/user/languages/java

**Comment by andybalaam** [comment]
Did you ever try openjdk 8 for the polygon drawing performance?

**Comment by colonelfazackerley** [comment]
I did just now. it's about the same as orasun JRE8. yay free software.

note that the problem is only with transparent polygons. if the paint is opaque, openJDK7 JRE is fine.

**Comment by andybalaam** [comment]
Excellent! I have no problem at all recommending openjdk 8 on PC - it's pretty much exactly as easy to install as 7.

**Comment by andybalaam** [comment]
@tttppp then I think it's time for us to get Travis set up when one of us has time and inclination. Not free software, but neither is GitHub :-(

Is it docker based?

**Comment by tttppp** [comment]
I don't think it's exclusively docker based, though they have support for it. I think I saw somewhere that they used Google cloud. For java projects it looks like they support ant, maven and gradle.

**Comment by colonelfazackerley** [comment]
I think is superseded by #393

**Comment by andybalaam** [comment]
And #396
