### ISSUE TITLE
Bug: on android 3rd hint is never shown.

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#389]
I was trying to make it more tolerant of no hints, and my code dropped the 3rd hint. After getting no where for a while I reverted Dialogs.java and found it drops the 3rd hint now, and it's not even my fault.

I will fix this in my Water4 branch.

**Comment by colonelfazackerley** [comment]
```java
        for (int i = 0; i < world.hints.length; i++)
        {
            Log.i("RE","hint i:"+i+ ":"+world.hints[i]);
        }
```

from within Dialog.java yields

```
04-03 17:35:20.995 4338-4338/net.artificialworlds.rabbitescape I/RE: hint i:0:The bridge tokens are yellow. They will build across 3 squares, unless the rabbit runs out of space.
04-03 17:35:20.995 4338-4338/net.artificialworlds.rabbitescape I/RE: hint i:1:If you fall into the hole, drop more bridging tokens to climb back out.
04-03 17:35:20.995 4338-4338/net.artificialworlds.rabbitescape I/RE: hint i:2:
04-03 17:35:20.995 4338-4338/net.artificialworlds.rabbitescape I/RE: hint i:3:Place a bridge token next to the step and before the hole.
```

So the problem is in the parser?

**Comment by colonelfazackerley** [comment]
Swing seems fine, so the parser behaves differently on Android?

Is there a bug in the android API?

Some of the Util.isEmpty calls in Dialogs.java make me think that there was a workaround for this already.

i guess we need a workaround.

**Comment by colonelfazackerley** [comment]
I tried update-alternatives to try openJDK 1.8. Android studio was deeply confused and refused to push the apk to my phone.

**Comment by colonelfazackerley** [comment]
i implemented a workaround in my Water4 branch.

also handles levels with fewer than 3 hints without AIOOB.

**Comment by colonelfazackerley** [comment]
fixed by 	7a52fdb

in Water4 #372 

Though that may get rebased.

**Comment by andybalaam** [comment]
I'd definitely like to figure out what is going on. Are you saying the 3rd hint is gone in all levels on Android now?

**Comment by colonelfazackerley** [comment]
I checked 2 different levels.

in swing world.hints has 3 elements, as expected. when i build a debug android version it has 4 elements. the 3rd is a null string. the 1st, 2nd and 4th are the expected hints.

This leads to the 3rd hint being lost in the current master.

**Comment by colonelfazackerley** [comment]
.rel seems to be parsed OK the first time. As it saves and loads and saves (eg turn screen), it inserts more and more null string hints.

```
04-10 08:49:36.531 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 1 ) Value:"Drop a bashing token when the rabbit is not there, to make sure you bash to the right."
04-10 08:49:36.532 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 2 ) Value:"Choose a token on the left, then drop it next to the wall to the right of the rabbits."
04-10 08:49:36.532 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 3 ) Value:""
04-10 08:49:36.532 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 4 ) Value:""
04-10 08:49:36.532 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 5 ) Value:""
04-10 08:49:36.532 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 6 ) Value:""
04-10 08:49:36.532 13540-13540/net.artificialworlds.rabbitescape I/System.out: Parsing:KeyListKey( hint, 7 ) Value:"Make sure your to
```

**Comment by colonelfazackerley** [comment]
This also explains why android is afflicted, and not swing.

**Comment by colonelfazackerley** [comment]
in serialising with this
```
--- a/rabbit-escape-engine/src/rabbitescape/engine/textworld/TextWorldManip.java
+++ b/rabbit-escape-engine/src/rabbitescape/engine/textworld/TextWorldManip.java
@@ -316,6 +316,7 @@ public class TextWorldManip
         addMeta( ret, author_name, world.author_name, world.comments );
         addMeta( ret, author_url,  world.author_url,  world.comments );
 
+        for ( String s: world.hints ) System.out.println( "world hints >" + s + "<" );
         addMetaKeyArrayLines( ret, hint, world.hints, world );
         addMetaKeyArrayLines( ret, solution, world.solutions, world );
 
```
the null strings can be seen.

**Comment by colonelfazackerley** [comment]
It's final, so unless something very wrong is happening, it must be the parser.
```
public final String[] hints;
```

**Comment by colonelfazackerley** [comment]
I confirmed that there are null strings inserted in hints[] by the time it gets to the World constructor.

**Comment by colonelfazackerley** [comment]
LineProcessor line 165, I think.

Just trying to understand what it's supposed to do. It does seem to behave differently on linux and android.

hope you are enjoying the live blogging.

**Comment by tttppp** [comment]
With your pointer I think the reason is (megacoded):
```
7~~Y;CCY8&;:~C;Y:x7;mC;;Y/q`9S7CCY9Fx;i;C7Y~PCw;FOF;w2;xx8~:8~xxF7OCFx;PFCPCC;m9t;;x&CwuF;&;~;HCPSxmm&8;;5~72FC9xX9_&;r29;C;FCwn{Cl9&CC2&xC7;F~F;iOmFYxC~wY;CxOr8C~;&CxC7;C88ww$P
```

**Comment by colonelfazackerley** [comment]
> temp.entrySet() isn't ordered, so there's no guarantee the entries will be returned in ascending order. We should either change the logic or use e.g. a TreeSet or LinkedHashMap.

I had figured that out. on linux, it always gave it in order. android did not. 

#397 fixes this.

**Comment by tttppp** [comment]
Cool! You'd done 90% of the investigation, so I thought it might be more satisfying to solve it yourself. Also, any excuse to use the MegaCoder ;-)

**Comment by andybalaam** [comment]
Lol
