### ISSUE TITLE
doxygen?

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#39]
or javadoc, or neither?

I have found doxygen handy before. Do you mind if I add comments in the correct style as I go, and add a makefile target?

**Comment by andybalaam** [comment]
Go for it

**Comment by colonelfazackerley** [comment]
I have a lot of fiddling to do with the doxygen config, but I have something.

http://www.extant.plus.com/rabbit_doxy/index.html

I will make a pull request for the Doxyfile and makefile tweak when it's a little more baked.

Doxygen makes html out of md as well as searching the code to make pages. It's nice.

**Comment by andybalaam** [comment]
Closed by 0591a040e6d036ac2238366d28ae0e2653d332a2
