### ISSUE TITLE
level: dig and bash avoid the metal

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#390]
```
:name=dig and bash avoid the metal
:description=dig and bash around the metal.
:author_name=GamingInky
:author_url=https://github.com/GamingInky
:solution.1=2;dig&(1,1);;bash;4;(1,3);4;dig;4;(6,3);;bash;5;(6,5);3;dig;5;(1,5);;bash;5;(1,7);18
:num_rabbits=10
:num_to_save=9
:dig=99
:bash=99
:music=tryad-witness
Q       

M#MMMMMM
M######M
MMMMMM#M
M######M
M#MMMMMM
M######M
MMMMMMOM
MMMMMMMM
```

**Comment by colonelfazackerley** [comment]
Looks like a nice intro to metal.

I try to obfuscate the solution when posting levels, so I don't give up the secret.

you can do 

```
./runrabbit --encode "2;dig&(1,1);;bash;4;(1,3);4;dig;4;(6,3);;bash;5;(6,5);3;dig;5;(1,5);;bash;5;(1,7);18"
```

It will tell you the obfuscated version. Then you can put 
```
:solution.1.code=<whatever was returned>
```

In the rel file.

**Comment by colonelfazackerley** [comment]
After that I also do
```
./runrabbit swing --level <level.rel> -s 1
```
to make sure I did the copy pasting correct, and it will show you the solution play out.

**Comment by GamingInky** [comment]
thanks that really helpful.

**Comment by GamingInky** [comment]
:name=dig and bash avoid the metal
:description=dig and bash around the metal.
:author_name=GamingInky
:author_url=https://github.com/GamingInky
:solution.1.code=GL{+EK+:OP>L9LAGL>Lc{OL9L9EA+,OLLL9cGL{f:0YLLK>Y7LKL97c7_Y{{{L:,A9:O:E+OOlLLLLLLPP+
:num_rabbits=10
:num_to_save=9
:dig=99
:bash=99
:music=tryad-witness
Q       
        
M#MMMMMM
M######M
MMMMMM#M
M######M
M#MMMMMM
M######M
MMMMMMOM
MMMMMMMM

**Comment by GamingInky** [comment]
I think this should go in easy set.

**Comment by tttppp** [comment]
Nice and easy. 99 of each token feels very generous :smile:

**Comment by GamingInky** [comment]
But what if they accidentally place it when the rabbit is facing the wrong direction?

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/88-dig-and-bash-to-avoid-the-metal
