### ISSUE TITLE
keyboard shortcuts and hover descriptions

### ISSUE THREAD

**Issue by antonpiatek** [andybalaam/rabbit-escape#4]
I often want to select an action quickly, number key shortcuts would be good - add a number icon next to each to make it obvious. Also add some hover over help so I can learn what each is faster

**Comment by andybalaam** [comment]
I will merge this and make the strings translatable when I have a sec, or feel free to re-do with calls to the t() function wrapped around each string.

**Comment by andybalaam** [comment]
I went for consecutive numbers for visible abilities, rather than consistent shortcuts for the same ability in different levels.  Any feedback on that decision appreciated.
