### ISSUE TITLE
Text interface does not work

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#40]
Does the text interface work?

* "make runmenu"
* choose easy 1
* I think "dig 7 2" (and beating the enter key) should solve it, but I just get exceptions.

**Comment by colonelfazackerley** [comment]
oh, I saw on the TODO, that it does not.

**Comment by andybalaam** [comment]
Yes, I plan to do it as part of the work to write automated tests for all levels.

**Comment by andybalaam** [comment]
Will be fixed by 3a9cf7c38d99eb463a2d6c4468a0f980237d8bdd and commits leading up to that, when that branch is merged.

**Comment by colonelfazackerley** [comment]
Text mode is playable. Sweet.

I think this issue can be closed, :)
and individual issues opened for each bug :(

**Comment by andybalaam** [comment]
Woot
