### ISSUE TITLE
Level: It's behind you!

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#410]
```
:name=Its-behind-you
:description=
:author_name=
:author_url=
:num_rabbits=2
:num_to_save=2
:rabbit_delay=3
:solution.1.code=8M8c8c8MWM0~~G0'8M1EN~1~1m1~@~1M1M0M8MN08[::R1:W:Mi00`~0c 80:: L'8ic:101'~cR
:bridge=2
:bash=6
:dig=3
##)    ##
#  )    #
 Q  )    
#c   )  #
Oc    ) #
#########
```

for #241

**Comment by tttppp** [comment]
Another nice level. I did this one fairly quickly, and got the same solution. It's nice exploring the limitations of climbers.  Also I hit a bug with the solution recorder that I'll raise separately.

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Its-behind-you.rel
