### ISSUE TITLE
Level: Dive!

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#411]
I had to pressurise the water with ```:n=``` to get the tank full, instead of just using ```N```s.

```
:name=Dive
:description=Who dropped it in the water?
:author_name=
:author_url=
:hint.1.code=\c1HG7}\1-7y}99,c\(\}7
:hint.2.code=|O3]|d$O$ORX]OjHIdRHO$a<$dOO$&2d]Hk3^Hllss|OO_j2$|Hm2OplmjOOd|Rll_pd
:hint.3.code=mWYqW7qWM;W;WWM{vWW;m;WMI2;B-q"UvBmW`YfWMv$0;~-mqMW6;v`WWW2`;f6fWqqmfWm8$YMvM$Bf{B-W22v;6$0
:solution.1.code=7q8XdH8XoH&y]daXdUdz-dUddc8&EUdXcc]dHzX7q8X=z&&*A8g%U&gE]dUdHdaE*XoH8a{]dAz{UH&dd]&Ed=dzU&d88UzU*da8EX-gdzd*X]7&a{]HAydqd*=&8&EUEU8U&XaddXdgdX
:num_rabbits=3
:num_to_save=3
:rabbit_delay=3
:block=4
:bridge=2
:dig=6
 Q    
/    \
######
)#NN#(
 #NN# 
 #NN# 
 #N*# 
 #### 
:*=NO
:n=2,3,1500
:n=3,3,1500
:n=2,4,1500
:n=3,4,1500
:n=2,5,1500
:n=3,5,1500
:n=2,6,2000
:n=3,6,2000
```

Uses #400 
for #241

**Comment by andybalaam** [comment]
Wow, looking forward to this one!

**Comment by andybalaam** [comment]
Levels as PRs are acceptable too btw. Are you actively choosing to use issues?

**Comment by colonelfazackerley** [comment]
It seems quicker to drop the issue on.

I will do a PR for them at some point. I do like the dev levels in the repo being tested. It has helped me catch a few bugs early.

**Comment by tttppp** [comment]
I like two things about having levels in the repo. Firstly, as you say, it means they stay tested. Secondly it makes it really easy to see how near we are to a level set being completed.

**Comment by tttppp** [comment]
Nice level, it took me several goes to learn the mechanics. I ended up with the same answer as you (but less polished).

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Dive.rel
