### ISSUE TITLE
Solution recorder records futile clicks

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#414]
When playing #410 I decided it was necessary to franticly hammer the left mouse button. This resulted in me clicking to try to place more bash tokens than there actually were.  When using the recorded solution as a solution string and running the tests we get:

rabbitescape.engine.solution.SolutionExceptions$UsedRunOutAbility: Solution failed: ability 'bash' was used when there were none left at command 5 of solution 2 in unsorted/LevelItsbehindyou

The solution recorder should ideally not record futile clicks.

**Comment by andybalaam** [comment]
Yes. I have half a memory of saying in the past that we might conceivably want futile clicks recorded for some kind of demo mode but if I did say that I now disagree with myself.
