### ISSUE TITLE
Discussion: Why are we using Stack?

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#416]
```
/ui/swing/MenuUi.java:        this.stack = new Stack<>();
/ui/text/TextMenu.java:    private final Stack<Menu> stack = new Stack<Menu>();
```
http://stackoverflow.com/questions/12524826/why-should-i-use-deque-over-stack

I daresay I could swap to Deque, but wanted to check there was not a good reason.

**Comment by andybalaam** [comment]
So long as Deque is available in Android API level 8 I have no objection. I didn't realise it was considered deprecated.

**Comment by colonelfazackerley** [comment]
It does not say deprecated. It says "A more complete and consistent set of LIFO stack operations is provided by the Deque interface and its implementations, which should be used in preference to this class."

https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html

However, Deque is level 9, so I will get my coat.

http://developer.android.com/reference/java/util/Deque.html

**Comment by andybalaam** [comment]
D'oh

**Comment by colonelfazackerley** [comment]
I wiki'd the level 8 thing.

https://github.com/andybalaam/rabbit-escape/wiki/Code-style-and-version

**Comment by andybalaam** [comment]
Thanks. @GamingInky just pointed out to me that because this is ui code we could use anything in java 7. It's probably simpler to stick to api level 8 everywhere though.
