### ISSUE TITLE
Level editor

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#422]
I want to start working on a level editor.
Here's a screenshot of what we have done so far:
![q](https://cloud.githubusercontent.com/assets/15169323/15091024/4ffce95e-1433-11e6-8e23-278a853cb854.png)
(It does not do anything.)

**Comment by GamingInky** [comment]
This is my branch https://github.com/GamingInky/rabbit-escape/tree/level-editor

**Comment by colonelfazackerley** [comment]
Is it going to work on droids too?

I recall a discussion about simply copying the level text in/out to avoid the need for extra droid permissions.

**Comment by tttppp** [comment]
Or having it available only in a dev release?

**Comment by andybalaam** [comment]
We definitely need this on droids, but the code will be largely independent because it's almost all UI.

**Comment by andybalaam** [comment]
> I recall a discussion about simply copying the level text in/out to avoid the need for extra droid permissions.

Yes, this is the plan for the first draft of a level editor on both Swing and Android.

**Comment by andybalaam** [comment]
> Or having it available only in a dev release?

If/when we need more permissions, we will have to make a separate dev build, yes.  For now, we can get a long way with copy/paste.

**Comment by GamingInky** [comment]
Plans for level editor:
- **A ingame editor** in which you can make levels, save them, upload them and when you test them you can fast forward, reverse or change the level while testing.
- **A online editor** you won't be able to save but you will be able to look at other peoples work other than that they are the same.
- **The archives** at first will be where you upload you levels and look at other peoples through the online level editor, the address for a level may look like this: ```www.artificialworlds.net/rabbit-escape-archives/4qu6d0b```
    but later there will be accouts so you can comment, like, dislike or follow and then a level's address may look like this: ```www.artificialworlds.net/rabbit-escape-archives/GamingInky/Rabbot-Practice```.

**Comment by GamingInky** [comment]
I think we have decided that there won't be a ingame editor.

**Comment by GamingInky** [comment]
However, I think the online editor could save to the archives and a play button.

**Comment by GamingInky** [comment]
We also think the archives could be a edited forum.

**Comment by tttppp** [comment]
That's a shame. I think this would really help to speed up the rate of new level creation.

**Comment by andybalaam** [comment]
I definitely want at least a text box to paste a level in version 1.0.  If anyone wants to work on an in-game level editor, please do.

**Comment by GamingInky** [comment]
#561

**Comment by andybalaam** [comment]
Closing this.  We want a text-box to paste a level into for Release 1.0, and if anyone works on an in-game editor, we will welcome your pull requests!  For now, the web-based level editor at https://www.artificialworlds.net/rabbit-escape/levels/ is our focus.  We will link to it from in-game to make it feel a little more integrated.
