### ISSUE TITLE
Level: "Slippery Slopes"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#423]
Deja Vu of "Sloping Off" #409 where the target is 10. Having the dev and staging levels on my phone has been a good way to test them.

**Comment by andybalaam** [comment]
#409

**Comment by andybalaam** [comment]
Yes it is brilliant and hopefully will be a standard feature very soon

**Comment by andybalaam** [comment]
Deja Vu #87

**Comment by andybalaam** [comment]
This was included in Deja Vu, so closing.
