### ISSUE TITLE
Level: "Platforms, large"

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#43]
```
:name=Platforms, large
:description=Here and there
:num_rabbits=6
:num_to_save=5
:bash=1
:dig=1
:bridge=6
:climb=1
:block=1
:explode=10
:rabbit_delay=9
Q          Q               
                           
###        #####           
                      #### 
#               ######     
                           
  ######                   
             ######   ###  
                           
                           
                Q          
                           
      ######               
                           
                           
O              #######     
#######                    
                           
                           
```

**Comment by andybalaam** [comment]
Took me about 4 goes.  Would like to see whether there's a way to save the 6th.
Thought: 8 Skill: 8

**Comment by tttppp** [comment]
I'm fairly sure you can only save five. This is a tough level, and has given me a new appreciation of how hard some of these levels will be on a phone!

I think including 10 explode tokens between 6 rabbits is a little excessive!  (I dumped them all on my blocker). Maybe we should scale this back to just 6 tokens (or maybe just 1 given that we can only lose one rabbit?)

**Comment by andybalaam** [comment]
@colonelfazackerley any reason you gave 10 explode tokens?  If not I'll accept merge requests to reduce them...

**Comment by colonelfazackerley** [comment]
Sometimes it's good to give useless tokens as a red herring. If you always have exactly what you need and no more, it can be a big clue.

**Comment by andybalaam** [comment]
Agreed, just checking whether it was deliberate.
