### ISSUE TITLE
Bug: Falling water is invisible (on both Swing and Android).

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#431]

**Comment by GamingInky** [comment]
I have an idea:
![tmp_14738-1484398527824-778198263](https://cloud.githubusercontent.com/assets/15169323/21955248/c5a06068-da5e-11e6-80f1-5f8758f926fb.png)

**Comment by tttppp** [comment]
I did think something like that would work, maybe different ratios of air to drops based on how full the cell is?

**Comment by andybalaam** [comment]
I was thinking something ultra simple. I want to get the water feature actually released otherwise it will have been a waste. Maybe just one animation meaning "there is some falling water here".

**Comment by tttppp** [comment]
Maybe just a full cell, but with a higher alpha (transparency) than usual?

**Comment by andybalaam** [comment]
Definitely an option. Probably the neatest-looking option.

**Comment by andybalaam** [comment]
Fixed as part as #443.  Feel free to contribute more coolness, e.g. a sense of fally-downy-ness.
