### ISSUE TITLE
Discussion: :n= format

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#436]
Its a bit weird how ```:n=``` needs coordinates, but ```:*=``` does not. I think I prefer the starpoints method of taking them in order.

**Comment by tttppp** [comment]
I agree this is inconsistent. My thought was that for a running level there will probably be tens or hundreds of water descriptions, so it would be useful to easily look up a particular depth. In practice I'm not sure the format is likely to be read by a human, and the rel files we've created so far only have a handful of water description lines.

**Comment by tttppp** [comment]
If we're fixing his then it should be fixed before the release, or we'll be left with two formats forever. (For backwards compatibility).

**Comment by andybalaam** [comment]
I too agree it is inconsistent, but was swayed by @tttppp 's arguments that a starpoint style would be unwieldy.  Yes, avoiding an upgrade step would be good.

**Comment by colonelfazackerley** [comment]
I have made a couple of levels using ```:n=```. I think changing it to starpoint style would be more wieldy. It's annoying counting coordinates in a text editor. The more water there is the more annoying it gets.

**Comment by andybalaam** [comment]
Both formats have serious downsides. Can we think of anything better than both?

**Comment by andybalaam** [comment]
If we don't come up with an alternative I am minded to stick with what we have for 2 reasons:

1. We have it

2. Using a starpoint approach will mean some levels will just be a sea of *s when there is water around.  The :n=(x,y) approach means we don't have to pollute the grid with water everywhere.

**Comment by andybalaam** [comment]
Leaving time for further comment, but if @colonelfazackerley doesn't feel too strongly, I will leave things as-is.
