### ISSUE TITLE
bug: blockers on slopes dont block where the slope changes direction

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#437]
```
r  
   
) r
 )*
:*=(k
r r
 (*
(  
:*=)k
r  
   
\ r
#\*
:*=/k
r r
 /*
/##
:*=\k
```

**Comment by colonelfazackerley** [comment]
![re](https://cloud.githubusercontent.com/assets/9596719/15263535/ca819b3c-1962-11e6-8ba7-d2be7b21f295.gif)

**Comment by tttppp** [comment]
I've definitely used this feature to make levels harder. Fixing this probably won't break any tests, but it will change the experience of playing certain levels.

**Comment by colonelfazackerley** [comment]
> I've definitely used this feature to make levels harder
I think this is a bug.


It seems OK when the blocker is on a slope and blockee is on the flat
```
r r
  *
###
:*=(k
r  
  r
##*
:*=)k
r r
  *
###
:*=/k
r  
  r
##*
:*=\k
```

**Comment by colonelfazackerley** [comment]
It seems OK when the blocker is on a slope and blockee is on the flat
```
r r
  *
###
:*=(k
r  
  r
##*
:*=)k
r r
  *
###
:*=/k
r  
  r
##*
:*=\k
```

**Comment by colonelfazackerley** [comment]
It also seems OK when the blocker is on the flat and the blockee is on a slope.
```
r  
  r
#)k
###
  r
r k
 (#
###
r  
  r
#\k
###
  r
r k
 /#
###

```

**Comment by andybalaam** [comment]
I totally agree this is a bug.

**Comment by colonelfazackerley** [comment]
I have a fix. The solution to arcade/Tetris relies on the bug, so I need to fix that too.

**Comment by colonelfazackerley** [comment]
I fixed the solution for Tetris. Just need a new unit test.
