### ISSUE TITLE
Level: Dig metal

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#438]
```
:name=Dig metal
:description=You can't dig through metal.
:author_name=GamingInky
:author_url=https://github.com/GamingInky
:hint.1.code=?I^-,y2)@a2I@^
:hint.2.code=Sv]*Pr]<*yyPAvS%Prer*,5yr]:yrn
:hint.3.code=EE1I*\|E'GGE\[|FFkk1#Guu1E
:solution.1.code=#-lz-`oK2ao`Kzoo.[joA.o$l2!o
:num_rabbits=10
:num_to_save=10
:rabbit_delay=4
:bash=1
:dig=2
MMMMMMMMMMMMM
M#   Q     #M
M#\       /#M
MMMMMMMMMMM#M
M#         #M
M#\       OMM
MMMMMMMMMMMMM
```

for #241

**Comment by andybalaam** [comment]
This is good but very easy.  Can we think of a way of making it a little harder?  Maybe it would be ok as the first level of a set.

Also, if you made it a little narrower (and probably had fewer rabbits) it could be s small world level #241

**Comment by colonelfazackerley** [comment]
I was thinking this could be shrunk to small world. But then I thought it's quite nice how it riffs on easy level 1.

**Comment by tttppp** [comment]
Yes, this is a novel level because it relies on earth and metal looking similar. The (relatively easy) challenge is to spot that not all the blocks are metal.

**Comment by andybalaam** [comment]
But see #440 for my opinion that they should not look to similar. It is kind of the visual equivalent of poking people in the eye while playing to make the game more difficult.

**Comment by GamingInky** [comment]
what about this:
```
:name=Dig metal
:description=You can't dig through metal.
:author_name=GamingInky
:author_url=https://github.com/GamingInky
:hint.1.code=?I^-,y2)@a2I@^
:hint.2.code=Sv]*Pr]<*yyPAvS%Prer*,5yr]:yrn
:hint.3.code=EE1I*\|E'GGE\[|FFkk1#Guu1E
:solution.1.code=#-lz-`oK2ao`Kzoo.[joA.o$l2!o
:num_rabbits=10
:num_to_save=10
:rabbit_delay=4
:bash=1
:dig=2
MMMMMMMMM
M#   Q #M
M#\   /#M
MMMMMMM#M
M#     #M
M#\   OMM
MMMMMMMMM
```
it's a bit smaller

**Comment by andybalaam** [comment]
Looks good

**Comment by andybalaam** [comment]
Could work for #241

**Comment by andybalaam** [comment]
Can we think of a way of adapting this to make it harder? @tttppp always likes a challenge. ..

**Comment by tttppp** [comment]
I think a metal and earth maze might be good.

**Comment by andybalaam** [comment]
Yeah, definitely liking the idea of a maze you have to dig through, possibly with an annoying lack of floor at certain points, to remind you about gravity.

**Comment by tttppp** [comment]
Also, it's much harder to go up than down. This could mean that some routes through the maze weren't possible. (Eg Lack of Bridges, or earth directly above the rabbits).

**Comment by andybalaam** [comment]
Yes

**Comment by andybalaam** [comment]
Closing until someone comes up with a way to make it harder.

**Comment by GamingInky** [comment]
I guess
