### ISSUE TITLE
Level: "K2"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#44]
```
:name=K2
:description=Climb up from base camp and down the other side.
:num_rabbits=10
:num_to_save=2
:bridge=5
:block=2
:explode=10
:music=tryad-witness
                              
                   /\         
 \                /##\        
 #\              /#### /\     
 #       /\      ##### ##     
 ##\     ##\/\  /##### ##\   /
/#Q#\   /############# ###   #
#   #   #######/\###/\/###\ /#
#   #  /######/##\#/##\##  /##
# *   /###/\#/####/####\ /  O#
#########/##\####/###### #####
:*=cccccccccc
```

**Comment by colonelfazackerley** [comment]
It's hard. I have a vague notion how it might be possible. It's scenic!

**Comment by colonelfazackerley** [comment]
Managed. I got 4 out. I dont suggest dropping the criterion from 2, as getting any out is tricky.

I think it needs an extra blank row of sky. Also, could the width be reduced by taking a bit of the middle out? It's OK on a computer, not sure how it will play on a phone.

**Comment by tttppp** [comment]
An extra row of sky would work fine.  The width is primarily for appearance (and was designed on a computer screen), but the width and shape of the mountain makes it a little hard to find the right spot for a blocker.  Well done on getting four out!

**Comment by andybalaam** [comment]
Wow.  I am stuck.

**Comment by colonelfazackerley** [comment]
I did a pull request with hints for this level. It is possibly @tttppp's most evil creation.

**Comment by andybalaam** [comment]
I shall not look at it, nor at the comments above.

**Comment by colonelfazackerley** [comment]
I did not give it away in the issue comments, I try not to.

**Comment by andybalaam** [comment]
I shall not be defeated.

**Comment by tttppp** [comment]
This gives me an idea for a rot13 feature on hints in source files. To help avoid us spoiling levels when creating them with hints.

**Comment by andybalaam** [comment]
Did it on about my 20th go.  Fantastic level.  I am quite pumped about solving it.  I felt it must be some kind of cheat, but it's not at all.  Very satisfying and enjoyable.
Thought: 10 Skill: 8

**Comment by andybalaam** [comment]
Added more sky, but too late for v0.6

**Comment by colonelfazackerley** [comment]
I got 5 out on Android. What's the max possible? could go in deja vu.

**Comment by tttppp** [comment]
The best I've managed on Android was 5 too. I've only got one method of solving the level, and 5 out is just what happens when I use efficient clicking. Do you have significantly different solutions?
