### ISSUE TITLE
Metal looks messy

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#440]
I am having second thoughts about the graphics for metal blocks.  I think this screenshot shows what I mean - it looks a bit chaotic.  It should be easy to see the non-metal blocks and understand that the metal blocks are all the same:

![metal-looks-messy](https://cloud.githubusercontent.com/assets/76812/15266791/c126a646-19a7-11e6-9701-a1b0d93b031b.png)

I think the different images should be more consistent with each other, and the blue-ish colour should be less patchy.

Thoughts?

**Comment by GamingInky** [comment]
Here we are @andybalaam said he approved:
![metal_isn t_messy](https://cloud.githubusercontent.com/assets/15169323/15447348/649516ac-1f37-11e6-9108-fd374c9c942e.png)
