### ISSUE TITLE
Pipe graphics are draft

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#441]
I'm fairly sure the pipe graphics we had were just a placeholder until we drew something better, but maybe it looks OK - what do you think?

![pipe](https://cloud.githubusercontent.com/assets/76812/15266851/4622d8aa-19a9-11e6-96e8-b74fc115e663.png)

**Comment by tttppp** [comment]
The water in it is in the in the old style, so probably that should be replaced. It's not even the right colour. If someone wants to replace the circle too that's fine :-)

**Comment by ChickenMaster128** [comment]
they look like some one drew it . It could have more detail

**Comment by andybalaam** [comment]
I think it should look like a tap or something so it's clearer what it actually is

**Comment by GamingInky** [comment]
Maybe add a grate and when the water reaches the level of the pipe, the pipe starts to fill up as well.

**Comment by andybalaam** [comment]
With the new water particles #578 I am happy with how this looks, although new graphics suggestions would be welcome if anyone wants to work on it.
