### ISSUE TITLE
Water is not ready

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#444]
Playing through the levels in staging, it has become clear to me that water is not ready.  I think we should not release any water levels until we have fixed:
- ~#431 Falling water is invisible~
- ~~#442 ConcurrentModificationException when resizing window with water in it~~
- ~#443 Glitches in water rendering~

There are also other water issues we may also want to fix before release:
- ~~#432 Water polygons don't ignore bridges~~
- ~~#441 Pipe graphics are draft~~

**Comment by colonelfazackerley** [comment]
#432 Water polygons don't ignore bridges
fixed

**Comment by andybalaam** [comment]
Since #578 water is ready!

**Comment by tttppp** [comment]
Woohoo! Need to get cracking on the levels.
