### ISSUE TITLE
Token drifts down too early after dropping in the air

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#447]
I noticed when playing "Whack a Rat" (in staging/smallworld) that the brolly token appears below where it should when you drop it, then moves up and continues as normal after that.

I only clicked once to get this:

![brolly-glitch2](https://cloud.githubusercontent.com/assets/76812/15447634/d5410c86-1f40-11e6-9e68-a2ef28b7b58b.gif)

Note that the token appears where you would expect it, then flips to be above where you'd expect it.

I think the original behaviour was to sit still until the end of the time step, and then start drifting down.

**Comment by tttppp** [comment]
I reproduced this with another token (I think it was dig), and I was on Swing.

**Comment by andybalaam** [comment]
Updated the description with a gif
