### ISSUE TITLE
In Swing when I resize a lot the screen flickers for ages

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#452]
* Open the Swing UI and start a level.
* Resize the window in and out a few times.
* Note that the screen flickers for several seconds afterwards, and the "you lost" screen only appears (when relevant) after it's stopped flickering.

**Comment by andybalaam** [comment]
I am investigating.

**Comment by colonelfazackerley** [comment]
I found that using a JRE 8 (oracle or swing), there was still flicker, but not the latent lingering flicker with JRE 7s.

**Comment by andybalaam** [comment]
The root of the problem was the queueing of resize events, made worse by slow rendering on JRE 7.

**Comment by andybalaam** [comment]
I am wondering whether water has made rendering slow even on levels with no water, since I had not seen this problem before.
