### ISSUE TITLE
Level: Tunnel

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#455]
Easy, but thought I'd better start contributing to #241 Small World.

```
:name=Tunnel
:description=The exit is buried!
:author_name=Andy Balaam
:author_url=http://artificialworlds.net/rabbit-escape/
:hint.1.code=BzdzzLw1g[z7DzBFBzmmz[.Bfe"^"Xgzm^mdddzmzcLI
:hint.2.code=@jjY}ER7_jREI!ZY!mY:UjR:$[j(j@UYZ~c
:hint.3.code=bSa_7nonaPoSEoa9P-aaPyVS~EBSyoaSV9aoS8D-yM-Sb_-_zEaaVaaVEnnV_Sh-o~Vb;S)baoMS~aa-E~{nadab-odSV-~SS*aaa_oa-EaP*So-aanUPaahESU9y-9PyS-SdoaMz
:solution.1.code=+wYR:D:wd::@LY:$j>cqcD@q]MM::+:>:w+>+Dh
:num_rabbits=3
:num_to_save=3
:rabbit_delay=4
:bash=1
:bridge=1
:dig=1
#Q     
#      
####MMM
######O
#   M##
#######
```

**Comment by colonelfazackerley** [comment]
I dont mind easy: the set should start easy. Dug in the wrong place the first time, so it took me 2 goes.

It is unnecessarily large. It should be shrunk. I think it will retain it's character if the width is several fewer than 9 blocks.

**Comment by andybalaam** [comment]
Hmm yes I wasn't considering smallness with sufficient urgency.

**Comment by andybalaam** [comment]
Shrunk, and committed at https://github.com/andybalaam/rabbit-escape/blob/75ec177b735eafb3c576d3942b132039b0d84357/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Tunnel.rel

**Comment by andybalaam** [comment]
Closing the issue because it's committed to Git, not to prevent further discussion.
