### ISSUE TITLE
Level "Bed"

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#463]
For small world #241

```
:name=Bed
:description=Snuggle up
:author_name=Andy Balaam
:author_url=http://www.artificialworlds.net/rabbit-escape
:num_rabbits=2
:num_to_save=3
:bash=3
:bridge=2
:solution.1=bash;4;(6,2);2;(5,3);(4,4);4;bridge;5;(2,5);2;(7,1);14;until:WON
              
 M r    MMMOM 
 M####/#####M 
 M###/######M 
 MQ#/#######M 
 M          M 
##############
```

Committed to https://github.com/andybalaam/rabbit-escape/blob/5ed29b92ce0331e43d8c21131378517b369e7689/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Bed.rel

**Comment by tttppp** [comment]
I think the behaviour changed for this, as it now only needs one bash token!

**Comment by andybalaam** [comment]
Hmm yeah I think I spotted this months or years ago.  I think I'm happy to leave it as it is.

**Comment by tttppp** [comment]
Ok, great. We should probably make a test solution for it and some levels based around this trick!
