### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#474]
Submitting the app to the F-Droid Free Software app store looks slightly involved, but would be good to do.

Info: https://f-droid.org/contribute/

The fact that we require various tools (Make, sox, Inkscape) to build may make it harder.

We should do this after the 0.10 release #469 so the license is straightforward.

**Comment by andybalaam** [comment]
Example commit: https://gitlab.com/fdroid/fdroiddata/commit/6884c64348c9a14b9934868a56443caf8dc3589b

(This uses gradle, so is simpler than we would need.)

**Comment by GamingInky** [comment]
¿¡¿¡HƆ┴I˥פ ∀ ┴S∩ſ ┴I SI ɹO ¿pƎʞƆ∀H פNIƎq I W∀ פNINƎԀԀ∀H SIH┴ SI MOH ¡¿¡¿¡¿ON ¡˥OOƆ

**Comment by andybalaam** [comment]
https://f-droid.org/repository/browse/?fdfilter=Rabbit&fdid=net.artificialworlds.rabbitescape

**Comment by tttppp** [comment]
Brilliant news!

**Comment by andybalaam** [comment]
Someone on the F-Droid IRC even called it "kinda good"!
