### ISSUE TITLE
API Compatibility Issues

### ISSUE THREAD

**Issue by lilicoding** [andybalaam/rabbit-escape#478]
Dear developers,

We have recently developed a state-of-the-art static analysis tool for uncovering API compatibility issues in Android apps. Applying this tool to open source apps on F-droid, we have exposed a few instances of compatibility issues and submitting them to development teams for a fix. 

For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

<java.util.Properties: java.util.Set stringPropertyNames()>:[9,25]
<java.util.concurrent.ThreadLocalRandom: int nextInt(int,int)>:[21,25]
<java.util.Properties: void store(java.io.Writer,java.lang.String)>:[9,25]
<java.lang.Throwable: void addSuppressed(java.lang.Throwable)>:[19,25]
<java.util.concurrent.ThreadLocalRandom: java.util.concurrent.ThreadLocalRandom current()>:[21,25]

Note that, because of the nature of the static analysis, we cannot confirm whether the flagged APIs would actually be called at runtime (e.g., unreachable code). However, we still believe that those APIs, which may cause compatibility issues, should not be accessed or at least be accessed with proper protections. 

In addition to the aforementioned APIs (i.e., backward-compatibility), which could cause app crashes if accessed, we have also identified that this project has also accessed some APIs that have been removed from the latest public SDK, making the app possibly suffer from forward-compatibility issues.

<java.lang.reflect.Array: java.lang.Object newInstance(java.lang.Class,int[])>:[1,8]

We would be very much appreciated if you can acknowledge to us that those reported APIs are indeed problematic for the project’s long-term stability. please let us know if you need any more information relating to this issue report.

**Comment by andybalaam** [comment]
Interesting.  I will look into this when I get time.

It would be really helpful if you could tell us where in our source code these methods were called.

**Comment by tttppp** [comment]
I had a few minutes, so here's some grep output:

```
./rabbit-escape-engine/src/rabbitescape/engine/config/ConfigFile.java:77:        for ( String name : props.stringPropertyNames() )
./rabbit-escape-engine/src/rabbitescape/engine/Fire.java:23:        int r = ThreadLocalRandom.current().nextInt( 0, 4 );
./rabbit-escape-engine/src/rabbitescape/engine/config/ConfigFile.java:149:            props.store( writer, null );
```
I'm not sure about `store` - there were lots of hits for this in the code.  No hits in java code for `addSuppressed` or `newInstance`. Note that one line in Fire is contains two of the reported issues.

**Comment by lilicoding** [comment]
Dear developers,

Thank you very much for your quick feedback, which is very useful for us to improve the quality of our research tool.

Regarding the source code the aformentioned methods were called, please find them below:

```
<java.lang.reflect.Array: java.lang.Object newInstance(java.lang.Class,int[])>:[1,8]--><rabbitescape.engine.textworld.Chars: void <init>(rabbitescape.engine.World,boolean)>

<java.util.Properties: void store(java.io.Writer,java.lang.String)>:[9,25]--><rabbitescape.engine.config.ConfigFile: java.lang.String propertyLine(rabbitescape.engine.config.Config,java.lang.String)>

<java.util.concurrent.ThreadLocalRandom: int nextInt(int,int)>:[21,25]--><rabbitescape.engine.Fire: rabbitescape.engine.ChangeDescription$State chooseVariant()>

<java.util.concurrent.ThreadLocalRandom: java.util.concurrent.ThreadLocalRandom current()>:[21,25]--><rabbitescape.engine.Fire: rabbitescape.engine.ChangeDescription$State chooseVariant()>

<java.lang.Throwable: void addSuppressed(java.lang.Throwable)>:[19,25]--><rabbitescape.engine.util.RealFileSystem: void write(java.lang.String,java.lang.String)>

<java.lang.Throwable: void addSuppressed(java.lang.Throwable)>:[19,25]--><rabbitescape.engine.util.RealFileSystem: java.lang.String[] readLines(java.lang.String)>

<java.util.Properties: java.util.Set stringPropertyNames()>:[9,25]--><rabbitescape.engine.config.ConfigFile: void load()>
```

Note that, as I cannot build the latest code to an apk, this experiment we run is based on the latest apk version available on F-Droid, which may not be the same as the one in github.

**Comment by andybalaam** [comment]
The latest code in git is the same as what is on f droid.

**Comment by andybalaam** [comment]
> <java.lang.reflect.Array: java.lang.Object newInstance(java.lang.Class,int[])>:[1,8]--><rabbitescape.engine.textworld.Chars: void <init>(rabbitescape.engine.World,boolean)>

As far as I can see, this must be triggered by our use of [Arrays.fill](https://developer.android.com/reference/java/util/Arrays.html#fill(char[],%20char)) but according to the Android docs this has been available since API level 1, so must be OK.  I wonder whether the tool is picking up on some changed implementation of Arrays.fill that was updated in a later version.  If so, I am not sure whether this shows a real problem or a false positive.

@lilicoding any comment?

**Comment by andybalaam** [comment]
> <java.util.Properties: void store(java.io.Writer,java.lang.String)>:[9,25]--><rabbitescape.engine.config.ConfigFile: java.lang.String propertyLine(rabbitescape.engine.config.Config,java.lang.String)>

[Properties.store(Writer, String)](https://developer.android.com/reference/java/util/Properties.html#store(java.io.Writer,%20java.lang.String)) was added in API level 9, so we must use the old version.

Fixed in 7e2c1d83f4e22bd3858580573e2c39346f400487

**Comment by andybalaam** [comment]
> <java.util.concurrent.ThreadLocalRandom: int nextInt(int,int)>:[21,25]--><rabbitescape.engine.Fire: rabbitescape.engine.ChangeDescription$State chooseVariant()>
> <java.util.concurrent.ThreadLocalRandom: java.util.concurrent.ThreadLocalRandom current()>:[21,25]--><rabbitescape.engine.Fire: rabbitescape.engine.ChangeDescription$State chooseVariant()>

Yes, and also we shouldn't use a random number generator here anyway.  Fixed in d3491251f1879358abb7c14bfbba5110d727fdec

**Comment by andybalaam** [comment]
> <java.lang.Throwable: void addSuppressed(java.lang.Throwable)>:[19,25]--><rabbitescape.engine.util.RealFileSystem: void write(java.lang.String,java.lang.String)>
> <java.lang.Throwable: void addSuppressed(java.lang.Throwable)>:[19,25]--><rabbitescape.engine.util.RealFileSystem: java.lang.String[] readLines(java.lang.String)>

These look like false positives to me again, or some wrong version of a library getting pulled in.  We are using FileWriter and FileReader, which are both available in API level 8.

@lilicoding any comment?

**Comment by andybalaam** [comment]
> <java.util.Properties: java.util.Set stringPropertyNames()>:[9,25]--><rabbitescape.engine.config.ConfigFile: void load()>

Yes! - [Properties.stringPropertyNames](https://developer.android.com/reference/java/util/Properties.html#stringPropertyNames()) was added in API level 9.

Fixed in 731dbe9

**Comment by andybalaam** [comment]
@lilicoding this was very useful, thank you.

**Comment by andybalaam** [comment]
I will close this issue fairly soon unless we get more info about the things that I currently think were false positives.
