### ISSUE TITLE
Level: The Guard

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#494]
```
########
Q       
        
       O
   /# y#
########
:bridge=2
:name=The Guard
:num_rabbits=1
```

Untested. Intro to rabbots.

**Comment by GamingInky** [comment]
Good introduction to rabbots.

**Comment by andybalaam** [comment]
I tested it and it can be solved

**Comment by colonelfazackerley** [comment]
Got it first time. A nice simple level for the beginning of a set.

**Comment by andybalaam** [comment]
My plan is for this to be the first rabbot level - it shows you that rabbots kill rabbits and doesn't require you to control the rabbot.  Next will be a simple one like Showdown #495  or the double-showdown level I now realise I uploaded a while ago #482.

**Comment by tttppp** [comment]
Solution 1:
```bridge&(4,3);23```
Solution 2:
```;bridge;(6,4);8```

**Comment by andybalaam** [comment]
Rejected for the Rabbots set - too trivial.  Not of much use elsewhere, so closing.
