### ISSUE TITLE
Level: Showdown

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#495]
```
########
r     Oy
########
:explode=1
:name=Showdown
:num_rabbits=0
```

Untested. Intro to tokens affecting rabbots.

**Comment by GamingInky** [comment]
Possible and interesting as the answer is staring you in the face the whole time.

**Comment by colonelfazackerley** [comment]
Nice intro.

typo correction "tokens affecting rabbots."

**Comment by andybalaam** [comment]
My phone autocorrects it every single time :{)

**Comment by GamingInky** [comment]
Why is the rabbot behind the exit? (It's not like it would make any different whether or not, would it?)

**Comment by tttppp** [comment]
Solution (as there isn't one here yet): ```;explode;(4,1);4```

**Comment by andybalaam** [comment]
Rejected for the Rabbots set - too trivial.  Not of much use elsewhere, so closing.
