### ISSUE TITLE
Level does not end when only rabbots left

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#497]
When I have saved all the rabbits in a level and there are only rabbots left, it should end, but actually the game waits until all rabbots have died.

**Comment by GamingInky** [comment]
However, we could say it is an intended feature to increase the difficulty and make the puzzle more interesting (all current levels are still possible while this bug exists)

**Comment by andybalaam** [comment]
Yes, this is a bug. I don't think having to kill all the rabbots feels very natural.

**Comment by colonelfazackerley** [comment]
As the last rabbit leaves/dies and victory conditions are met, perhaps auto-trigger the bomb-all action.

**Comment by andybalaam** [comment]
Yeah, that could be nice
