### ISSUE TITLE
Level: Saboteur

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#500]
```
:name=Saboteur
:description=
:author_name=
:author_url=
:solution.1.code=PIVYGLybA-GP0kcG*kAzj8I=?wkkz-P0kc=zdTPk5A{cX
:solution.2.code=(%=_((B} #fRI-8hGpJy{9
:solution.3.code=nf=4wBvf*fOI=f8OR-z/4Eff-^Pff29zBaj)P1,e;
:num_rabbits=3
:num_to_save=3
:rabbit_delay=5
:bash=1
:bridge=1
:dig=1
#        
#     Q  
    y#  #
  #######
  br     
         
         
O#      M
MMMMMMMMM
```
Tested.  Solution 1 wins, and solution 2 loses, demonstrating that the trivial way does not work.  Solution 3 is a better winning solution from @colonelfazackerley

**Comment by colonelfazackerley** [comment]
I am sure there is a mistake. It's trivial. I cant quite figure out the intention.

**Comment by andybalaam** [comment]
Adjusted.  Failing solution:

bash;2;(6,1);11;FAIL

I haven't checked it's possible ;-)

**Comment by andybalaam** [comment]
OK, it works now, and is not trivial.  Sorry for the time waste.

**Comment by colonelfazackerley** [comment]
I don't consider it a waste of time. I am aware that levels posted on github issues are experimental.

**Comment by colonelfazackerley** [comment]
I like it. not sure my solution is intended.

U$.Uz[!.[[j'qma#qn[-$lljoN#[

**Comment by andybalaam** [comment]
Yeah, yours is a simpler way to prevent disaster.  I have made the floor metal to avoid it.

**Comment by colonelfazackerley** [comment]
This is my solution

cF~?xZoU`~v~@~~v?x"]~~`@^' YYf&xO~

I tried "./runrabbit swing -l sabotuer.rel -s 1" to see yours, but it excepted out before finishing. Yours looked much more complicated than mine.

**Comment by colonelfazackerley** [comment]
I decoded your solution 78ca%i^i*`7{z]^`ziHio`c*==%Eioc^qcq`a*]ya7]yzc=

It ends with the rabbits in the top right still stuck and no tokens left to spend. There is a null pointer exception when the solution runs out.

**Comment by andybalaam** [comment]
I think we are disagreeing about how many empty lines there are at the top. This is an annoying feature of using github issues.

**Comment by colonelfazackerley** [comment]
i added 1, then 2, then 3 blank lines at the top. solution 1 still does not work.

```
        #
         
         
#     Q  
    y#  #
  #######
  br     
         
         
O#      M
MMMMMMMMM
:name=Saboteur
:description=
:author_name=
:author_url=
:solution.1.code=78ca%i^i*`7{z]^`ziHio`c*==%Eioc^qcq`a*]ya7]yzc=
:solution.2.code=(%=_((B} #fRI-8hGpJy{9
:num_rabbits=3
:num_to_save=3
:rabbit_delay=5
:bash=1
:bridge=1
:dig=1
```

Could you redo it with a block at the end of the top line to protect the whitespace? (level above does not work)

**Comment by andybalaam** [comment]
How annoying!  I will fix it when I get a chance, and try yours.

**Comment by colonelfazackerley** [comment]
my solution may not work for you, because the coords will be out. perhaps you could repost the level with the first blank line protected, and I will record the solution again.

**Comment by andybalaam** [comment]
OK, fixed and added your solution as number 3.  All of these succeed:

```
$ ./runrabbit -l Saboteor.rel -s 1
$ ./runrabbit -l Saboteor.rel -s 2
$ ./runrabbit -l Saboteor.rel -s 3
```

Can we find a way of preventing your solution, since the idea was to need to do what I do?

**Comment by colonelfazackerley** [comment]
I wondered about putting in blocks, so the lower rabbit cant bridge. does not work. a solution like mine is still possible

```
:name=Saboteur
:description=
:author_name=
:author_url=
:solution.1.code=/"w&}XV8//}KA/h/Xv//I`KzIBhs>/X!
:num_rabbits=3
:num_to_save=3
:rabbit_delay=5
:bash=1
:bridge=1
:dig=1
#        
#     Q  
    y#  #
  #######
  #######
  #######
  br#####
O#      M
MMMMMMMMM
```

**Comment by colonelfazackerley** [comment]
I tried a few more things, but I cant find a way of preventing solutions simpler than you intended.

**Comment by tttppp** [comment]
My solution:
```ibLc8]+b}}{pR{W{L{T{y{llTyRqCx}Q8{x+/8Tb```

I like @colonelfazackerley's solution better - nice.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/85-saboteur
