### ISSUE TITLE
Level: Fire Diamond

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#501]
```
            
            
     **     
M   *OO*   M
 *  *OO*  \ 
  M  **  M  
           \
 MMMMMMMMMM 
:*=(A
:*=)A
:*=(A
:*=)A
:*=/Q
:*=)A
:*=(A
:*=)A
:*=(A
:bash=6
:bridge=8
:dig=2
:name=Fire Diamond
:num_rabbits=4
:num_to_save=2
:rabbit_delay=8
```
Possible, but not in the way I originally intended, and arguably because of a bug.

**Comment by colonelfazackerley** [comment]
I am stumped. I can only get one out.

A block token can stop a basher moving after removing a block. It seems a bridge token cannot.

**Comment by andybalaam** [comment]
I updated it and it is now possible, but I don't like the solution.

**Comment by andybalaam** [comment]
8L<@:1[W:ML8L<LmML@L~1<EL01L'0'8EL:@:1<GL[:LRmME8[WcRN<LcNW0RN ~m8<L:'010'LL

**Comment by colonelfazackerley** [comment]
I can rescue 3. The level seems OK now.

e^_0de^fd7F[,6^[cm/m[mm',,<F_G99m7Gfm0mf/7Fc

**Comment by andybalaam** [comment]
Nice solution!

**Comment by tttppp** [comment]
I can save three. I thought I might be able to save four, but it turns out that it's possible to juggle fire using bridge and bash tokens!

This looks basically the same as colonel's solution:
```q=@GeGeGehEqGGGDEd=Dqtgb=|^dyG^FI@bEIG(F(D#(hDeE```

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/84-fire-diamond
