### ISSUE TITLE
Still Flagging

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#504]
@andybalaam encouraged me to submit this as a level. Blame him.

```
:name=Still Flagging
:description=Deja poo
:author_name=tttppp
:author_url=https://github.com/tttppp
:num_rabbits=5
:num_to_save=5
:rabbit_delay=10
:climb=5
:dig=1
:music=tryad-the_final_rewind
##############
#            #
#            #
#   ######   #
#   ######   #
# Q ######   #
#   ######   #
#   #      O #
##############
```

Solution: ```!e!e!e!Vy{DV*~}U|5T`6`TVT`T`p~VNVQ%N|`%l%!eN%NTN5|V!-N4%T`atV```

Please don't include anywhere except at the end of a level set - I have a hunch that this level is far beyond fun! :smile:

**Comment by colonelfazackerley** [comment]
utututuyjOcojctcj>jcjO>uoQQccQnQt>>>Ioju>Io

took 10 min. timing is very tricky. perhaps i got lucky. there are so few tokens that there can only be one solution.

Checked, and my solution is essentially the same.

**Comment by tttppp** [comment]
Only 10 minutes? That's pretty awesome.

**Comment by colonelfazackerley** [comment]
I think there is only one solution. The timing is tricky, but sometimes I roll a six. I guess I could see how long it takes me to do it again...

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/83-still-flagging
