### ISSUE TITLE
Catch The Flames (Level)

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#507]
```
Q       Q  
           
     A    O
###########
:author_name=GamingInky
:author_url=https://github.com/GamingInky
:bash=3
:block=4
:bridge=1
:description=It may seem hard but that's what you've got to do...
:hint.1=Stop the rabbits walking into the flames.
:hint.2=Maybe use a blocker?
:hint.3=Make the block closest to the exit bash then bridge onto the flames from the right with the closest blocker, then make the other two blockers bash.
:name=Catch The Flames
:num_to_save=9
```

**Comment by GamingInky** [comment]
Untested

**Comment by GamingInky** [comment]
Impossible

**Comment by GamingInky** [comment]
When the rabbits walk past the bridge with fire on they die (Intended feature?).

**Comment by tttppp** [comment]
This definitely isn't impossible. It's not completely trivial either:

Save 9:
```Ao`KKo[q`Njo..N-l#$'!'oRz2ao```
Save 10:
```@Z@Y`]Y@Z&ofx]@Zvo]?"Yc vOUvb!'x^@```

**Comment by colonelfazackerley** [comment]
I thought it was trivial...
I saved 9 on my first go by placing 1 ladder, and 10 on my second go
<4HnOY"zY"t9n=uq{Y"hVnGn9:4H"lH9kkQY<LH"Vnn@9$GQnYLklnzk@n"nkH}

**Comment by tttppp** [comment]
Ah yeah - saving 10 wasn't completely trivial. Winning the level was trivial.

**Comment by colonelfazackerley** [comment]
to get 10 you have to delay one slightly, or pen them in. both are established methods.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/81-catch-the-flames
