### ISSUE TITLE
Hints for easy, medium and hard levels

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#51]
See https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/easy/level_01.rel for an example.

Each level should have 3 hints.  The first should be a clue, the second a hint, and the third a description of the key points of the solution (space willing).

**Comment by andybalaam** [comment]
Once this is done, I will check everything over and make a release (0.5).

**Comment by andybalaam** [comment]
If you want to do any of this, add a comment here saying what levels you are doing so we don't duplicate effort.

**Comment by colonelfazackerley** [comment]
I will do hints for the hard set.

It would be good to make the number of retries before hints configurable for each level.

**Comment by andybalaam** [comment]
I plan to change the way levels are named so that level file names are a kind of ID used to track whether you've completed and how many attempts you have made.  I think it will take a bit of work to do this, so I planned to release "always-on" hints in the meantime.  Disastrous?

**Comment by colonelfazackerley** [comment]
No, that's fine. It's nice and simple as it is.

I have almost finished the hard set hints. I had the day off work. I have to work this evening, though.

**Comment by andybalaam** [comment]
You are a machine.

**Comment by andybalaam** [comment]
Think I should fix #37 before making a release btw, which might necessitate a hint change too.

**Comment by colonelfazackerley** [comment]
Indeed. I have written hints for hard 20, but I am basically taking the piss...

**Comment by andybalaam** [comment]
:-) I will do hints for the easy levels.

**Comment by andybalaam** [comment]
Easy hints are in.  Comments welcome: f23403c01ec5b9caa21e9af8e9ca10bffc88d89c

**Comment by andybalaam** [comment]
Hard hints merged in bc16e83064af4e10e4c2e9d049b4d87215387216

**Comment by andybalaam** [comment]
"That's a nice thick roof".  Genius.

**Comment by andybalaam** [comment]
I'll do medium now.  The night is young.

**Comment by andybalaam** [comment]
ab216ed0ee227211f747ab8445a66a1c3ab37081 does hints for medium 1-10.  I must go to bed.  If anyone wants to do 11-20 before I get to it, announce it here and go for it.

**Comment by colonelfazackerley** [comment]
I think that the easy levels often don't need 3 hints. For several, hint1 is a reworded description. I think they should be changed to only have 2 hints. Or maybe teach a principle instead, like where you explain that climbers retain the ability: this would give all hints some purpose.

**Comment by colonelfazackerley** [comment]
I will work on medium 11-20 hints this evening.

**Comment by colonelfazackerley** [comment]
I struggled to think of hints for medium 19 without giving away hard 16 (but I have now). Almost there.

**Comment by colonelfazackerley** [comment]
see #60

**Comment by andybalaam** [comment]
Closed by #60 , 3dc7f8cc1b2b681126cb13b8e681b2976fe0be66 , c5b157b4c5276c7cac6894080f9944487d2ce0b9 , ab216ed0ee227211f747ab8445a66a1c3ab37081 , 8aa3c767a225979ae6168ee3d6d45eb310f3c1fb , 9dd1ef1d3c0f2087b6120e8d2e460dce9a44e398 , 2cef7a681ad8d2900ce1dab1742b40a3fcd79f11 , #55 , f23403c01ec5b9caa21e9af8e9ca10bffc88d89c and possibly others.

**Comment by andybalaam** [comment]
Regarding https://github.com/andybalaam/rabbit-escape/issues/51#issuecomment-143462454 I agree, and would accept a pull request making the Easy hints contain general tips relevant to the level you are on (especially hint1).
