### ISSUE TITLE
Bug: Bridge through walls

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#511]
```
:name=Bridge through walls
:author_name=tttppp
:author_url=https://github.com/tttppp
:num_rabbits=0
:num_to_save=1
:bridge=1
   O 
##   
#i   
#)###
#)r##
#####
```

I'm not sure if this is a duplicate issue or not, but I feel like this level should really be impossible.

**Comment by colonelfazackerley** [comment]
19;bridge;(1,3);10

That does not look right

**Comment by andybalaam** [comment]
Updated the level at the top to show the behaviour without any clicks needed.  Rabbit bridges rightwards, with its head clearly passing through the ceiling.
