### ISSUE TITLE
Upshotshot

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#515]
Again I don't have a clever name for this.

Deja Vu version of Upshot (#458) with only three bridges and no dig.

English explanation of solution:
```
JJZu/E.7$u$vu$q5?wE{E?qJ?JZ/6Ju{ZKe6Jv3ZJJvJ:3?6tZ69>J;vJ;EvJ/?q/u{9vJE_J9/vv$quZ{Z$JeJJJJu{Z;{J>$E?O3?3JJ{{J53ZZq$E3?E$EJ9$?$\3{{q3Oq{Zur3$0$J0J>{ZZ/$JuJev{v$Z3{?6;JJXq#JJ$qqE?;5uZ:/Zo96J{eJJ{Et/JE5v/JZ{$`?uvJJ3{t;EuZ$E`?${v?$EeZ5JO{JJntOJ{u$;?6u3{J$E7ZJ{qq;?v`33q/6?9JE{$/
```

**Comment by tttppp** [comment]
Maybe it could be called "Shot up"?

```
:name=Shot up
:description=See if you can still get two up with no digging and one fewer bridge.
:author_name=tttppp
:author_url=http://github.com/tttppp
:solution.1.code=wx.NwX.&7n7dvdxT7)7X-wxnhTd7nh:.Tv5xT*Iw&m;I7n.n-57J*R7&7gIw7dXnh*5wXX"TdnJw3.tTC7hXX.)TCh&:7
:num_rabbits=3
:num_to_save=2
:rabbit_delay=7
:bash=3
:block=1
:bridge=3
:climb=1
:explode=1
        
#####   
#O  #   
##  #   
#   #   
#Q  #   
#   #   
#####   
```

**Comment by colonelfazackerley** [comment]
yVgiz.]\a7yV\g'k>k{zg\i<]z.3;f\&3hg{zGf3<]\i3;z<]]5]<]]>5\?35#.]bfk];a<]f]]]\\]g7z<<agi3]zk]&#73&]y{3#z.5DxV<;kg&]?]]g

Bit rusty. I cant recall playing the original...

**Comment by tttppp** [comment]
@colonelfazackerley I can't decode your solution - if you still have it please could you put it within triple backticks?

The original was in Small World, and there was also a very similar level earlier in the set called "Up" (#457) .

**Comment by colonelfazackerley** [comment]
I got the impression that the encoder added a carriage return. Is that possible?

I will try and do it again later

**Comment by tttppp** [comment]
I think that only happens if you include carriage returns in the plaintext.

**Comment by colonelfazackerley** [comment]
```>_W_r_W_i>=)H$B$_W_G$)=ZWG(}CGWrk_?)C9_Z=}_|(C9GWZ_F(|X_|=C_$BC(U}?LrCA?U=G_U=U_1$=WDXZ|W(_=_)(_k_C+)i(iD_D99U>(```

**Comment by tttppp** [comment]
Oh interesting! I'd not seen that solution before. Mine uses one fewer bash, but neither of these are the "intended" solution to the original level, which requires the dig token.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/78-shot-up
