### ISSUE TITLE
Level set: Rabbots

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#520]
20 levels all featuring at least one rabbot.

Approximate order of difficulty:

1. #482 Rabbot Practice (thinking: 1, skill: 2)
2. #526 Bot (thinking:2 skill: 3)
3. #519 One from each side (thinking: 3, skill: 2)
4. #493 Red Army (thinking: 3, skill: 2)
5. #496 Double Showdown (thinking: 2, skill: 5)
6. #518 Plunk (thinking: 3, skill: 4)
7. #536 The Simplest Level (thinking: 4, skill: 3)
8. #499 Bomb on the hill (thinking: 5, skill: 4)
9. #524 Tailgating (thinking:6, skill: 4)
10. #509 The Chase (thinking: 5, skill: 5)
11. #527 Saboteur (thinking:7, skill: 6)
12. #529 Clones (thinking: 6, skill: 5)
13. #539 Rabucket (thinking: 6, skill: 5)
14. #510 Lock Smith (thinking:7, skill: 8)
15. #505 Big Brother (thinking: 8, skill: 7)
16. #512 Too close for comfort (thinking:8, skill: 8)
17. #530 Snail (thinking:8, skill: 8)
18. #513 Much too close for comfort (thinking: 8, skill: 9)
19. #543 Escalator (thinking: 9: skill: 8)
20. #552 Three Drops (thinking:10, skill: 8)

Rejected:
* GCD #549, but we can re-use this elsewhere - it's in staging
* ~#494 The Guard~
* ~#480 Nemeses (thinking: 1, skill: 3)~
* ~Showdown #495 (thinking: 1, skill: 3) totally trivial~

**Comment by tttppp** [comment]
Woo - an update on my favourite rabbit-related repo! There are a few more rabbot levels, e.g. https://github.com/andybalaam/rabbit-escape/issues/510

I'll have to have a think about other ways to use them.

**Comment by andybalaam** [comment]
I'm going to make a concerted effort to get #490 Release 0.11 done by end of September, and then see about fixing water.  Thanks for the enthusiasm @tttppp !

**Comment by andybalaam** [comment]
Please add any rabbot-containing levels I missed.

**Comment by andybalaam** [comment]
Snapshot 0.10.3.3 contains all the levels listed above http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by andybalaam** [comment]
Snapshot 0.10.3.4 contains all 20 levels listed above.

**Comment by andybalaam** [comment]
In theory we now have enough levels but actually I am waiting for:
* A new level by @GamingInky we are working on together that looks cool
* Some people to nominate their least favourite of the easy levels in this set, because I think there are too many
* Someone to write a super-hard level to end this set (@tttppp ?)

So we need to cull 2 easy levels to fit those I mention above. Nominations?

**Comment by tttppp** [comment]
Too close for comfort and Much too close for comfort should either be the other way around, or have their titles swapped. I'll try to play through and see which is a nomination for dropping.

**Comment by tttppp** [comment]
I've played through the first few just now and here are my thoughts:

* The Guard - Potentially won't actually discover rabbot+rabbit = boom.
* Rabbot practice - Nice intro. Have to click quite fast, but someone who hasn't seen rabbots before will almost certainly see the explosion first go.
* Nemeses - The description in this is useful for teaching, but the level isn't very exciting. It's more like an introduction to creating rabbot levels than an introduction to how rabbots work.
* Showdown - This usefully teaches that rabbots can't exit the level, but requires quick reactions and no thinking.
* Bot - Basically does everything that Showdown does, but is generally more interesting.
* One from each side - I'd not seen this before. Nice little level.
* Red Army - Nice level! Plenty of options here, and not trivial.

**Comment by andybalaam** [comment]
I'm happy to lose The Guard, Nemeses and Showdown.  Then, with Escalator (coming soon from @GamingInky ) and Rabucket #539 we will have 20.

**Comment by andybalaam** [comment]
I felt like *close for comfort were both really good, and different enough to be both included.

**Comment by andybalaam** [comment]
Snapshot 0.10.3.7 contains a rabbots level set with the 18 current candidates in it: http://artificialworlds.net/rabbit-escape/snapshots/

We're just looking for:
* 2 more levels, one of which we know is in development by GamingInky.
* Feedback on the difficulty ratings I have done, including Rabucket which I am too close to to rate.
* Feedback on the levels themselves, especially trivial solutions we missed.

**Comment by andybalaam** [comment]
Snapshot 0.10.3.9  contains Escalator, GCD and Three drops: http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by tttppp** [comment]
I've updated Three Drops in line with the fix for rabbot-blockers.

**Comment by andybalaam** [comment]
I propose to drop GCD unless anyone objects, because we already have a fine-timing level with Lock Smith, and whether or not it's fun has been questioned ;-)

That leaves us with 20.  I will update the improved levels, evaluate difficulty and re-order, and then make a snapshot as a release candidate.

**Comment by tttppp** [comment]
Dropping GCD sounds like a great idea!

**Comment by andybalaam** [comment]
Snapshot 0.10.3.10 contains the latest, with GCD removed and Escalator and Three drops updated.

**Comment by andybalaam** [comment]
This level set is ready for release (unless someone pipes up with a problem).  It will be released in #490 0.11

**Comment by tttppp** [comment]
The levels all look great to me. I wondered if I need to add hints and descriptions. I think there are a few I didn't get around to.

**Comment by andybalaam** [comment]
Please do add hints and descriptions.  I will fill in any missing ones over the next few days.

**Comment by andybalaam** [comment]
Released in 0.11
