### ISSUE TITLE
Generating images doesn't work for me

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#522]
This is bound to be my environment rather than the project, but I can't get the image generation to work any more.

```$ make test
. Checking for warnings in Makefile
.. Generating rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/fire_fall_to_rise_right_a_07.png
convert-im6.q16: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504.
convert-im6.q16: no images defined `rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/fire_fall_to_rise_right_a_07.png' @ error/convert.c/ConvertImageCommand/3258.
Makefile:135: recipe for target 'rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/fire_fall_to_rise_right_a_07.png' failed
make: *** [rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/fire_fall_to_rise_right_a_07.png] Error 1
```

I've spent some time looking through the documentation and the old issues, but can't remember what I should be doing. I've installed all the prerequisites from [here](https://github.com/andybalaam/rabbit-escape/blob/master/INSTALL.md#prerequisites), except for openjdk, which is outdated and no longer exists.

I also saw Andy's suggestion of running in Docker, and that seems to create the images perfectly (using openjdk:7-jdk-jessie).

Also, unrelatedly, it would be good to add a more prominent link to http://artificialworlds.net/rabbit-escape/level-editor/ somewhere. It was hard to re-find!

**Comment by tttppp** [comment]
I'm on Ubuntu 18.04 btw.

**Comment by andybalaam** [comment]
Hmm.  Looks like the `convert` progam is failing when converting a resized image.  We will either need to find some library it is missing, or give it a different command so it does it in a different mode maybe.  I am on 18.04 too, so I will try sometime soon.

**Comment by andybalaam** [comment]
You will need some version of Java btw, possibly a later openjdk.  We should update the prerequisites for a modern system.

**Comment by andybalaam** [comment]
Or!  Is it possible you need to install the [ImageMagik](https://www.imagemagick.org) tools?  It looks like we are missing `imagemagick` from the list in INSTALL.

If that is it, you will need this now:

```
sudo apt install imagemagick
```

**Comment by andybalaam** [comment]
I added it to the list.  Let me know whether that fixes it.

**Comment by tttppp** [comment]
Unfortunately I also have imagemagick installed already.

I have several versions of java installed. By default I'll be using java 8 (Oracle), but I also have 7 and 9 just in case.

I can work around this by copying the generated files from my docker image.

**Comment by andybalaam** [comment]
Hmm.  Works for me here on Ubuntu MATE 18.04.  Maybe I have a different package installed.

**Comment by andybalaam** [comment]
My googling suggests this should work out of the box.  Did you install ImageMagick from source?  If not, maybe an `apt remove imagemagick` and `apt install imagemagick` might persuade it?

Here are the relevant packages I have installed:

```$ apt list | grep imagemagick

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

graphicsmagick-imagemagick-compat/bionic,bionic 1.3.28-2 all
imagemagick/bionic-updates,bionic-security,now 8:6.9.7.4+dfsg-16ubuntu6.3 amd64 [installed]
imagemagick-6-common/bionic-updates,bionic-updates,bionic-security,bionic-security,now 8:6.9.7.4+dfsg-16ubuntu6.3 all [installed]
imagemagick-6-doc/bionic-updates,bionic-updates,bionic-security,bionic-security 8:6.9.7.4+dfsg-16ubuntu6.3 all
imagemagick-6.q16/bionic-updates,bionic-security,now 8:6.9.7.4+dfsg-16ubuntu6.3 amd64 [installed]
imagemagick-6.q16hdri/bionic-updates,bionic-security 8:6.9.7.4+dfsg-16ubuntu6.3 amd64
imagemagick-common/bionic-updates,bionic-updates,bionic-security,bionic-security 8:6.9.7.4+dfsg-16ubuntu6.3 all
imagemagick-doc/bionic-updates,bionic-updates,bionic-security,bionic-security 8:6.9.7.4+dfsg-16ubuntu6.3 all
node-imagemagick/bionic,bionic 0.1.3-1 all
```

**Comment by andybalaam** [comment]
I have no idea what is causing this - it looks like something is messed up in your Ubuntu - I am closing this unless/until we can find something to investigate, sorry.  (I suggest re-installing if you're desperate.)

**Comment by tttppp** [comment]
I might try to fix using the nuclear option of a new laptop.

**Comment by colonelfazackerley** [comment]
I have a script on my laptop (kubuntu) for switching between different installed versions of java. i cant remember it, but I will try to remember to have a look when i am at home.

**Comment by tttppp** [comment]
Thanks @colonelfazackerley, that might be useful, but it's not my issue. My imagemagick installation can't find codecs for png or gif. I've been working around it with Docker, but a fresh OS (or laptop) should fix it.
