### ISSUE TITLE
Link to the level editor on the web site

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#523]
As mentioned in #522:

It would be good to add a more prominent link to http://artificialworlds.net/rabbit-escape/level-editor/ somewhere. It was hard to re-find!

**Comment by GamingInky** [comment]
Yes, this is needed

**Comment by andybalaam** [comment]
This page https://www.artificialworlds.net/rabbit-escape/create-levels.html links to https://www.artificialworlds.net/rabbit-escape/levels/ so I think we are covered now.
