### ISSUE TITLE
Misc level set

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#525]
Some levels for a new set:

* #262 Brollychuting 101
* #261 Brolly intro
* #264 The great divide
* #316 Heavy metal
* Flagellate (might be included, or need renaming? - is in development/unsorted)
* #501 Fire diamond
* #228 Cliff hanger 2
* The floor is fire #439 
* Brolly descent #263
* Lightning #498
* The Closest To Flying Ever #508
* Catch The Flames #507
* Leafing #506
* Still Flagging #504
* Level: Prison Broken #556

**Comment by tttppp** [comment]
I just wanted to note that we've already released at least one brolly level. Uno has a brolly in it. Also several of the rabbot levels have brollies.

Basically I think we should come up with a new name for the level set (e.g. Mixed Bag 1)

**Comment by andybalaam** [comment]
Yes, I agree.

**Comment by GamingInky** [comment]
I would say remove planet paradise and sky island paradise, the are too big and we have closed their level set #109.

**Comment by andybalaam** [comment]
Removed those 2, thanks.

**Comment by andybalaam** [comment]
I am experimenting with tracking this level set here: https://www.artificialworlds.net/rabbit-escape/levels/t/misc-levelset

**Comment by andybalaam** [comment]
Moved to forum, which is no longer experimental :-)
