### ISSUE TITLE
Level: Snail

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#530]
For #520:

```
  r   j      
  MMMMM      
 M   t M    j
 M MMM M  # #
 M MOM M     
 M  yM M  # #
 rMMM  M  # #
 ############
#r          #
############ 
:name=Snail
:description=Rabbits and rabbots slugging it out!
:bash=6
:block=2
:bridge=13
:climb=1
:dig=6
:num_to_save=4
:hint.1.code=P2@mP2@oqzjP9jq<@mjMcjzh39RhMMoRMz'qj@o2qhMMq22ZMcj99MhZj_<99qqZPMqMM
:hint.2.code=V;;HzI*h>mH$4HI;>H<=z;I;g;;)hmJW<<IhP;$;Ih4h=<HH$;;E<II)M;VH
:hint.3.code=3}j3zz33zH>?v3*3IvvI}33}+jv3z33z\)3z*v3zV+IIvWV33v*v@z>zz3H3H3v2*H V3vv32H 3}3z*2z+v?H+XT33HX*? vvvWb3W?vjz**3zHv 3*v2z(v3*v+3iV+IIV3IITWIHvz+3vvH?IjV33HWvTj*v3z3 3Hz+V3W3VXv}*TWvz*33zv?zH**3zH?v@V 3:
:solution.1.code=qWWqWK$WqW$)L?tWp'yt4ytWqWGW4tKGWqWpWqWAy0n(WqWW2AGWK$A$)07*WnIAWWA@q5tyKh*Im$RW@Wq?t-0WGW(pWW0@yqGW4tWtW@WW2Kp@nRMp0tWqW((6'tW-A@W?I@@-6IKqqW0GWqWWWW@RRpWqW@(@4W(qLWLtWt'@00Ky0pWIm4IKyiGq*EG-5ptt(W?h0W@KtAMmq*4ydWtWWh4tKWWMGp2@Wd(4hh-@nKAy@Aq(qyAytytWqh@?KW0nKLpyWG2t(d@'W(hWW@@RRpnqqR0-'t@thWWK0WM0A2@tdL*WWp@-G?tIq5LAWWtKGhnM@p4?GtqWdA'(tWWWW0@W@?@WqR5Aqqt-Wh'WKW'n?IpKWG@K(LW'p
```

I'm out of practice at setting levels, so I think this will be an easier one.

**Comment by tttppp** [comment]
Getting the rabbits into the exit using bridge-stacking looks a bit weird.  This has been around forever though, so I'm treating it as a feature.

**Comment by andybalaam** [comment]
I've had a couple of goes and I have no clue!

**Comment by andybalaam** [comment]
I managed to save 5!
```
)<M$ggJ<)<MgmhJ<\HJv|gJ<)<nM)<)<[\MgH*J@{ 4M)4Jhv<n[\:<S4M)VJhM<J<)HM*)nHgJ[\:E<<ngmJ<)<MhmHJ<)<MgHnJ_<<MVh_J<E4JHJH:<)<Mg^nJ:h<n$$\J<Eh:MM<4<\))<hhMJg<EhMvJh[h)n)h:<<\*<S<vE:)vMn{-:C<E8rSw<EE)\Mhn_<\)_JVHMJQh<M)H*$<MJMVngvv))[V<SJ::E)\v<S-OEr<M|4=<(
```

**Comment by andybalaam** [comment]
Could my solution work as a deja-vu?

**Comment by tttppp** [comment]
Five sounds very good. Definite deja vu. I'll have to try that later!

**Comment by tttppp** [comment]
I eventually managed to save five on my phone! I couldn't actually manage to reproduce my intended solution on my phone, as I couldn't remember the exact timing needed.

Definitely deja vu-able though!

**Comment by tttppp** [comment]
My "save 5" solution was identical to Andy's (give or take a bit of timing). I even freed the blockers the same way.

**Comment by andybalaam** [comment]
Released in 0.11

**Comment by colonelfazackerley** [comment]
I only saved 4, but I relied more on timing and had tokens of all types left.

g;g4eaw1fa'm'f'gIg4fEm'gIz1)'E'E'g3r4fEm4XIz'w^/3r1Eg4gXRmI/g'm^z4e^/z3gg1g4a^BEE'g3r4IgfgII4mEm''Iggf/zIg8zI;^/Ba'^YY,z8>ge2RgzII4^g9'gIg/X4g'w4z3e4mIR1eRr4I)gm4''EmzII/fg3'g1g4zE44XIR4gI4gmEa'Iazf4^'m,a4>j92geg9a4E1jIwI'IR'g'ggz3

good level. very manic at the start.

**Comment by andybalaam** [comment]
Nice solution.
