### ISSUE TITLE
Longer fall distance for rabbots

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#533]
While trying to think of rabbot level ideas I thought it would be cool if rabbots could fall further than rabbits without getting squished. This would enable another way to distinguish between rabbits and rabbots, and make rabbots a little more desirable at times. Rabbits look much stronger than rabbits, so I think this makes sense thematically.

If this would break existing levels then let's just close this, but I didn't spot any that it would significantly affect.

**Comment by andybalaam** [comment]
Yes, I like this idea.

**Comment by GamingInky** [comment]
I think it's a great idea, I will add lots of new level ideas. I have a idea for one already.

**Comment by colonelfazackerley** [comment]
I feel that the rabbit's antiparticle should be symmetric with respect to terminal height.

**Comment by tttppp** [comment]
Boo!

But is it an antiparticle, or is it a metal cyborg version? The cut scenes are severely lacking on detail.

**Comment by andybalaam** [comment]
Rabbots don't have exits or entrances, and they are impervious to water.  They are more like the bad robot Bill & Ted than anti-particles.

**Comment by andybalaam** [comment]
Also, subtly different behaviours make them suitable for nice level ideas, I think.

**Comment by tttppp** [comment]
Tricky question. I would want to keep the rabbot -> cogs animation in the game, so if this is the only chance to view it then I'd object.

My other concern is that we'd be removing a potential puzzle component. I can think of puzzle ideas where the challenge would revolve around killing off a rabbot, and other puzzles where the challenge would be trying to prevent the rabbot smashing to pieces.  Perhaps it would be worth fleshing out some puzzles where this is the lynch pin?

**Comment by andybalaam** [comment]
I can't offer an opinion on this at the moment.  Both sides have strong points.  At the moment, we have 4 blocks implemented, so we will get locked in to that soon if we don't change it.

**Comment by andybalaam** [comment]
I am going to leave the rabbot fall height at 4.  I agree it's annoying to count squares, but I like the fall animation and the puzzle ideas that are opened by a different-but-not-unlimited height.

**Comment by colonelfazackerley** [comment]
To confuse things further, should rabbots falling in to water have their fall cushioned and terminal height increased?

**Comment by andybalaam** [comment]
Yes, that would be good for puzzles, I reckon.

**Comment by tttppp** [comment]
I think that sounds good too.  Perhaps using the Minecraft logic of falling into a single cell of water is safe from any height?  This would be another point in favour of water - it puts out fire and helps rabbots to survive long drops.

**Comment by andybalaam** [comment]
+1 from me.
