### ISSUE TITLE
Pause screen is too dark

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#537]
I reckon the pause screen is too dark - it's hard to see what's going on in the level, and it looks a little like the game has crashed.

Anyone agree or disagree?

**Comment by tttppp** [comment]
I think I disagree with this, it's easy to read the green text at the moment, and I mainly use pause to change tokens and scroll around.

**Comment by andybalaam** [comment]
Hmm. Maybe I am worrying about nothing. Is it a bit... unpolished?

**Comment by GamingInky** [comment]
I kind of agree with @andybalaam however, I don't think we should change it and if I did I don't know what to do.

**Comment by andybalaam** [comment]
I just had another look and I think it's fine.
