### ISSUE TITLE
Levelset: Double Trouble

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#540]
As discussed before somewhere, it would be cool to create a set of levels which were designed with multiple solutions in mind.

Obviously we already have plenty of levels with multiple solutions, but not many were designed that way.

(PS I'm not set on Double Trouble as the title, it was the first thing that came to mind).

**Comment by andybalaam** [comment]
Sounds cool

**Comment by GamingInky** [comment]
Really interesting idea.

**Comment by colonelfazackerley** [comment]
'Degeneracy' as a possible alternative name for the set.

**Comment by andybalaam** [comment]
If/when we have levels, make a levelset post in the levels forum.  Closing here.
