### ISSUE TITLE
Bug: Rabbots stop being blockers after turning one rabbit away

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#541]
I think rabbots should stay as blockers even when rabbits approach them.

In this level it looks like the two rabbits should get saved, but in fact only the first makes it out alive.

```
*    j   jO
###########
:*=tk
:bash=1
:block=1
:bridge=1
:brolly=1
:climb=1
:dig=1
:explode=1
:name=Rablock or Rab-not?
:num_rabbits=0
:num_to_save=2
```

**Comment by tttppp** [comment]
There's also another slight rendering bug where the rabbot appears as a blocker even before the blocker token is consumed.

**Comment by tttppp** [comment]
Also, I just realised that I left a load of tokens in the level file by mistake. They aren't needed to see the bug (and the level can actually be solved with a couple of the tokens).

**Comment by andybalaam** [comment]
Before you logged this I had a thought that rabbots might stop being blockers if their direction of facing was towards the approaching rabbit. Is that what is happening here?

**Comment by tttppp** [comment]
Yep, that's when I saw it. I haven't tried the other way around.

**Comment by andybalaam** [comment]
The fix for this should include tests for rabbits who are blocking when facing both towards and away from rabbots, and rabbots who are blocking when facing both towards and away from rabbits.

**Comment by andybalaam** [comment]
![rabbot-unblocks](https://user-images.githubusercontent.com/76812/44124828-08d18d46-a027-11e8-95a3-45892585343d.gif)

**Comment by andybalaam** [comment]
Here's a render of the level tttppp pasted:

![rabbot-unblocks](https://user-images.githubusercontent.com/76812/44124880-62e1ea7e-a027-11e8-9949-f6e0091bdd41.gif)

The "token visible even though I'm a blocker" is interesting, but I think we can ignore it until we understand it better, so I won't cover that here.

**Comment by andybalaam** [comment]
![blocker-stays-blocking](https://user-images.githubusercontent.com/76812/44126191-af55827e-a02e-11e8-9018-871aaf49e73e.gif)
