### ISSUE TITLE
Bug: Rabbots don't turn around when facing rabbit blockers on slopes

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#546]
Discovered on One from each side. Make the left rabbit a blocker on the slope and dig with the rabbot.

The rabbot should march back and forth, but it just stops.

In addition the rabbot can stand on nothing by being given a dig token (it should fall off the bottom of the world).

After this I gave the rabbit a floater token to free it, and it actually left the level! I don't think this should happen with floaters. If it's deliberate then it could form a really hard puzzle!

**Comment by andybalaam** [comment]
I think the blocker thing is highly related to #541 as you mentioned, but the other thing sounds bad too - is it easy for you to make a gif of it?

**Comment by tttppp** [comment]
This is the floater behaviour. Given that it happens with all floaters then I presume it's deliberate and we should be using it to set puzzles!

![floater](https://user-images.githubusercontent.com/7073263/44052834-b18ca65c-9f35-11e8-9944-dbe98ecdadc9.gif)

**Comment by tttppp** [comment]
The full behaviour can be seen with:

```
block&(2,3);(2,3);dig&(4,0);16;(3,3);7;brolly;(2,3);8
```

**Comment by andybalaam** [comment]
Your gif looks like fine behaviour to me, so I agree we should use it to set puzzles.

**Comment by andybalaam** [comment]
I'm 95% sure the rabbot standing still when it sees a blocker is all covered by #541.

Standing in the air is a good one, and we can use this bug to cover that.

Floating into the exit seems a good feature.

Is falling into the exit possible?  If so I think it's a bug.

**Comment by tttppp** [comment]
I've since determined that the rabbot stands on air for a single tick (presumably while waiting for the rabbit to join it), but it then falls to its demise.

**Comment by andybalaam** [comment]
Ah, my last worry is not a problem - see TestExit.java:

```
    @Test
    public void Fall_past_exit()
    {
        // All must die
        World world = createWorld(
            "rrrrrrr",
            "O      ",
            " O     ",
            "  O    ",
            "   O   ",
            "    O  ",
            "     O ",
            "      O"
        );

        assertWorldEvolvesLike(
            world,
            5,
            new String[] {
                "       ",
                "O      ",
                " O     ",
                "  O    ",
                "   O   ",
                "    O  ",
                "     O ",
                "      O"
            });

        // None lived
        assertThat( world.num_saved, equalTo ( 0 ) );
    }
```

**Comment by andybalaam** [comment]
Now that #541 is fixed, we see this:
![one-from-each-side-correct-blocking](https://user-images.githubusercontent.com/76812/44126244-f296f1f8-a02e-11e8-8d50-88f8b040739e.gif)

So the behaviour with respect to blockers is OK now.

**Comment by andybalaam** [comment]
Despite trying quite a few things, I can't get the rabbot to do its "waiting" behaviour in mid-air, so I am closing this for now.  Please re-open if you can find a way to make it happen.
![rabbot-not-waiting-midair](https://user-images.githubusercontent.com/76812/44126464-5c9ae07c-a030-11e8-90c8-6e2d0adb05cb.gif)

**Comment by andybalaam** [comment]
To get the above animation:

```
$ cat tmp.rel 
 * 
 * 
 * 
 *t
 * 
 *d
 j#
 j 
## 
:*=jl
:*=jl
:*=jl
:*=jl
:*=jl
:*=jl
:solution.1=until:WON

./record-level tmp.rel 5
```

**Comment by andybalaam** [comment]
Ah no, I got it:

![rabbot-waiting-midair](https://user-images.githubusercontent.com/76812/44126642-62aa0f0a-a031-11e8-86dc-a59e0d2984e8.gif)


```
 ry
   
  d
  #
   
## 
:solution.1=until:WON
```

**Comment by andybalaam** [comment]
![rabbot-does-not-wait-when-digging](https://user-images.githubusercontent.com/76812/44127113-b0af067c-a033-11e8-8e56-0d753209ed10.gif)

Fixed!

**Comment by tttppp** [comment]
That looks much better!
