### ISSUE TITLE
Bug: Rabbit can fall past climber rabbot on a bridge

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#547]
On The simplest level I managed to save the rabbit when the climbing rabbot was still climbing up from his bridge. I've definitely seen explosions when falling past a climber before, so I assume the bridge has something to do with this.

**Comment by andybalaam** [comment]
Yes - in general things can miss each other when a rabbit is falling - e.g. a rabbit can fall past a token.  Fixes for this kind of thing are welcome.  I suspect they will be piecemeal, rather than having some comprehensive solution.

**Comment by GamingInky** [comment]
I don't think this is a bug.

**Comment by tttppp** [comment]
I think we agree that this is a valid way to get rabbots past rabbits (and requires very careful timing). Closing this issue.

**Comment by andybalaam** [comment]
Can you paste a gif?  I'm not sure whether this is ok or not yet.

**Comment by tttppp** [comment]
Oh, maybe @andybalaam didn't agree. Feel free to reopen if you like!
