### ISSUE TITLE
Level: GCD

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#549]
```
######t#######
##   y######r#
#######    b##
#    y######r#
#######    b##
############O#
##############
:name=GCD
:description=For an extra challenge why not try adding more rows or columns?
:dig=1
:num_rabbits=0
:num_to_save=2
:solution.1.code=G%pI !y}z!#kh?c@B@{=m8
```

I don't know how hard this is, but as mentioned, we could add some more rows or columns to make it a final level candidate!

**Comment by tttppp** [comment]
```
########t#######
###    y######r#
#########   lb##
##     y######r#
#########    b##
#      y######r#
#########    b##
##############O#
################
:name=GCD
:description=For an extra challenge why not try adding more rows or columns?
:dig=1
:num_rabbits=0
:num_to_save=3
:solution.1.code=G%pI !y}z!Okh?c@B@{=#8
```

This is the same level with an extra row.

For some reason the brollier-bot is white in my installation. Maybe the animation for brolly-bots hasn't been tested before?  Maybe my animations are broken?

**Comment by tttppp** [comment]
For comparison clicking after a random time in the original wins once every 40 games, and with the extra row it wins once every 420 games. We could even "improve" the starting positions of the rabbots to help avoid exhaustive search.

When a level gets like this, does it even count as fun any more?  It was fun to create...

**Comment by tttppp** [comment]
Also - I guess really it should be called LCM rather than GCD.

**Comment by andybalaam** [comment]
Interesting. Haven't solved it yet. I think it's fun...

**Comment by tttppp** [comment]
Linking to #520

**Comment by andybalaam** [comment]
We are dropping this from #520 Rabbots, but it can be used in another level set.

**Comment by andybalaam** [comment]
Moved to https://www.artificialworlds.net/rabbit-escape/levels/d/77-gcd
