### ISSUE TITLE
Bug: Animation for brollybot is missing

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#555]
For example give the rabbot a brolly token on One From Each Side, and make it dig down. The rabbot changes to white when it pulls out the umbrella.

Tested on my laptop and a recent Android snapshot.

**Comment by andybalaam** [comment]
Hmm.  Do you get this?

```
$ file rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/rabbot_brollychuting_01.png 
rabbit-escape-ui-swing/src/rabbitescape/ui/swing/images32/rabbot_brollychuting_01.png: PNG image data, 30 x 38, 8-bit/color RGBA, non-interlaced
```

**Comment by andybalaam** [comment]
Nope, the rabbot SVG and PNG are both red.  Investigating.

**Comment by tttppp** [comment]
Fixed this - I'll make a PR.

**Comment by andybalaam** [comment]
Nice, thanks!
