### ISSUE TITLE
No bash completion in the Makefile

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#560]
If I type `make` then press tab in the top directory of Rabbit Escape, I would expect to see the possible Makefile targets listed.  Actually, nothing happens.

Some of the complexity of our Makefile is confusing bash completion.

Unconfuse it.

**Comment by colonelfazackerley** [comment]
Adding this to my .bashrc works.

```bash
# autocomplete for makefiles called Makefile
complete -W "\`grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' Makefile | sed 's/[^a-zA-Z0-9_.-]*$//'\`" make
```

via
https://stackoverflow.com/a/38415982/5924453

**Comment by andybalaam** [comment]
I should have mentioned in the initial comment - I have the bash-completion package installed, so tab-completion works for other Makefiles I have on my system.  Only the Rabbit Escape one doesn't work, presumably because something in our massive Makefile confuses the regular expressions it is using.  The expression you pasted is presumably dumb enough to avoid getting confused.
