### ISSUE TITLE
Levelset: Super Easy

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#563]
A levelset for the people who find rabbit escape hard (someone asked us for some easy levels).

**Comment by andybalaam** [comment]
We had some nice ideas for levels to go in this - @GamingInky please add them if you can remember.

**Comment by andybalaam** [comment]
Moved to the forum: https://www.artificialworlds.net/rabbit-escape/levels/d/45-super-easy-levelset
