### ISSUE TITLE
Level: Hills with save 6

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#566]
The original level was "save 3", the given solution is "save 5", but it's possible to save all six rabbits.

Original level: https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/02_medium/15_Hills.rel

**Comment by andybalaam** [comment]
See also: https://www.artificialworlds.net/rabbit-escape/levels/d/2-hills-save-6

**Comment by andybalaam** [comment]
Tracking this on the forum.
