### ISSUE TITLE
Level hard 4 "Stairs" is easier than I meant

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#57]
I meant you to have to send a lone rabbit all the way up, over the gaps, down the slope, climb back up, and then become a blocker.  In fact, you can do it an easier way than that by just making a blocker after the first gap.

**Comment by colonelfazackerley** [comment]
The level is "Stairs". I found that I could save all 10, if I used a permutation of the over the gaps, fall down the cliff and climb back up sequence. I suspect mine is not what you had in mind.

It's a very nice level. As it is, it is not pitched too badly for the start of the hard set.

**Comment by andybalaam** [comment]
Thanks, corrected bug title.

**Comment by andybalaam** [comment]
I guess it's OK as it is.  If one day we are looking for more levels, maybe we could make a variant that required what I had in mind.

**Comment by tttppp** [comment]
I think this would be good as a Deja Vu level with "Save 10" if it's not already.

**Comment by colonelfazackerley** [comment]
So a note pops up in #87
