### ISSUE TITLE
Rabbits on Fedora

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#570]
most things on INSTALL.md are the same.
`sudo dnf install git make ant sox inkscape expect grep sed python3-lxml`

couple of things have different package names
`sudo dnf install java-1.8.0-openjdk-devel ImageMagick`

I can't find a fedora package "rename", or what rabbit escape uses from ubuntu's rename. I carried on without it. I do have a standard linux util called "rename" (from a fedora package called util-linux). 

INSTALL.md says to `make all-images` first. That failed. `make compile` first seems OK. `make all-images`after gives no errors, but I think is not required now.

I could do a pull request for INSTALL.md adding the fedora dependencies, and removing the bit about `make all-images`, but that is possibly a makefile bug better fixed. "rename" thing probably needs clarifying.

My machine has functioning sound, but I'm not getting any from rabbit escape.

(
I'm trying fedora because a buggy BIOS issue stops ubuntu from working.
https://askubuntu.com/questions/1073434/acpi-errors-prevent-boot-after-upgrade-to-kubuntu-18-04/1074424#
)

**Comment by andybalaam** [comment]
The `rename` we use is the standard one I think, so your instructions should probably include util-linux.

**Comment by andybalaam** [comment]
Yes please on a PR for fedora instructions.

**Comment by andybalaam** [comment]
Could you log a separate issue for `make all-images` please? It is _way_ faster than running make normally.

**Comment by andybalaam** [comment]
Sound is disabled on OpenJDK since it crashes from time to time. (Grr)

**Comment by andybalaam** [comment]
Good to hear from you :-)

**Comment by colonelfazackerley** [comment]
the `rename` thing confused me. the ubuntu package does not provide a file called rename. i think you get a rename command via a symlink or something.

**Comment by andybalaam** [comment]
```
$ ls -l /usr/bin/rename
lrwxrwxrwx 1 root root 24 May 11 08:59 /usr/bin/rename -> /etc/alternatives/rename
$ update-alternatives --list rename
/usr/bin/file-rename
```

So yes, the package installed file-rename and prename, and update-alternatives lets you choose file-rename as the thing that provides "rename".  Confusing.
