### ISSUE TITLE
Level: bunny poppinses

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#573]
for #563 

```
:name=Bunny Poppinses
:description=Winds in the east, there's a mist coming in, like something is brewing, about to begin.
:author_name=ColonelFazackerley
:author_url=https://github.com/colonelfazackerley
:hint.1.code==fm\=~=|1'Zu'e\&~Il\Z|\h\Z
:hint.2.code=duu{d/d++/uueDe/{Su><{+JDw$c.$u{++u+Dw:
:hint.3.code=fJ2Zfwff=ffXIfw4XWJw[2=ff4WNJNJ22+fTXX5N2g4FN*WINTJff.zwwIfTF+YI)2[ffJNT=WwX*w=4f4fNg WJw2FTfTYIf2XJf=TNwF
:solution.1.code=HLHL]\!a!maTLH"TaTa!am,)LV'ma]"m3H"0'!0m!6L|!f"""vHLm
:num_rabbits=5
:num_to_save=4
:rabbit_delay=6
:bash=1
:bridge=1
:climb=3
:dig=5
:brolly=5
:block=1
  Q     
#    #  
######  
        
        
        
  #   O#
  ######
```

I think there is only one approach. Wouldn't be surprised to be proved wrong.

**Comment by andybalaam** [comment]
Looks very cool.  I am trying to get people to use https://www.artificialworlds.net/rabbit-escape/levels/ to post new levels - is there a reason you posted this to github, or were you just not aware that is what I'm trying to do?

**Comment by colonelfazackerley** [comment]
habbit.

I was aware of the forum, but not that it was now sufficiently ready to take over the function.

**Comment by andybalaam** [comment]
I declare it ready.  Let me know it is not.

**Comment by colonelfazackerley** [comment]
moved https://www.artificialworlds.net/rabbit-escape/levels/d/14-bunny-poppinses
