### ISSUE TITLE
bash-block-dig bug(s)

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#587]
```
:name=bug
:bash=1
:block=1
:dig=1
:solution.1=bash;(1,1)&block&(1,1);dig;2;(1,0);4
r #
 ( 
#  
```
Rabbit standing on bridge bashes, but is turned into blocker before moving into the cell from which the block was bashed. Rabbit is then turned into digger.
1. The rabbit as blocker does not stand on the bridge properly
2. The memory of being a basher is enough for them to walk on air.
![re](https://user-images.githubusercontent.com/9596719/48443296-8e135400-e788-11e8-9a9f-b31f31a6c0ee.gif)
I think this is a bug that has been fixed before, but not for all cases.

**Comment by colonelfazackerley** [comment]
I have a fix for this. I need to think about it a bit more, and write a test.

**Comment by tttppp** [comment]
We should also check fixes to this against all the solutions to puzzles in the forum. I'm fairly sure I assumed rabbit on bridge + bash token was meant to raise them by a cell. I remember using that to get a rabbit through an exit.
