### ISSUE TITLE
What is your highest score on "Panic!"?

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#59]
https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/hard/level_19.rel

I just scored 14 while developing hints, and I reckon that is the theoretical maximum.  Care to prove me wrong?

**Comment by andybalaam** [comment]
I just got 15.  Man I rule.

**Comment by tttppp** [comment]
I can do 15, but I don't think more is possible.

**Comment by colonelfazackerley** [comment]
Same here. I can get 15 if everything goes perfectly and I can't see an approach that would get me more.

**Comment by andybalaam** [comment]
We all rule.
