### ISSUE TITLE
Can't build android

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#599]
I think we are on java 8 now. I cant figure out where the "targetCompatibility" bit is coming from.

```
[cf@localhost rabbit-escape]$ make android-debug-test 
. Building rabbit-escape-ui-android/app/build/outputs/apk/app-paid-debug.apk
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
...while parsing rabbitescape/engine/Behaviour.class
    PARSE ERROR:
    unsupported class file version 52.0
    ...while parsing rabbitescape/engine/Behaviour.class
    
1 error; aborting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForPaidDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output /home/cf/re/rabbit-escape/rabbit-escape-ui-android/app/build/intermediates/pre-dexed/paid/debug/rabbit-escape-generic_99362d7337f8d50c7107843df9ccf88d5f14d2a8.jar /home/cf/re/rabbit-escape/rabbit-escape-ui-android/app/libs/rabbit-escape-generic.jar}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
make: *** [Makefile:466: rabbit-escape-ui-android/app/build/outputs/apk/app-paid-debug.apk] Error 1
```

**Comment by andybalaam** [comment]
I think it may be time to increase to a more sane Android API version at this point, which may smooth this out.  We currently have this really bad situation where the Android code requires only the Java 1.7 library, but on PC we use Java 8.  When we move to a new version we should ensure we are consistent across all platforms.

Realistically, I have a Moto C with Android 7.0, so unless an active developer has an older phone we could consider moving up to that as a baseline (I'd have to look up what that really means).  If we did this we could remove quite a few workarounds in the codebase.

**Comment by colonelfazackerley** [comment]
Not sure why this was working for me before. I can't install java 1.7 from standard repo anymore. I agree with upping to 8 for android too, and losing older droids.

**Comment by tttppp** [comment]
I think I have an older phone - I'm running Marshmallow.

**Comment by colonelfazackerley** [comment]
Had to look this up. 

Nougat   7.0    API level 24
Marshmallow   6.0    API level 23

The oldest phone that I own is also android 6 (Nexus 5).

**Comment by colonelfazackerley** [comment]
https://developer.android.com/studio/write/java8-support

I think java 8 implies API level 24

**Comment by andybalaam** [comment]
That page appears almost completely incomprehensible, but I if we need level 24 to do Java 8 I feel like we should wait a while longer.  Don't want to exclude people unnecessarily.

**Comment by andybalaam** [comment]
I attempted to build on the versions now allowed by the Play Store tonight and failed.  I will try again sometime.

**Comment by andybalaam** [comment]
If I git checkout 4491ba4135b7f0dd1de75b0fe4d7560992519f5b (before Ryan's change to upgrade grade) I can `make`, `make android-debug-test` and build inside Android Studio.

So something went wrong in 380afd97486c5dd4711392bee1768611f793a857 .  I will apply bits of it gradually and see what happens.

**Comment by andybalaam** [comment]
@colonelfazackerley this means I can't reproduce the issue you reported at the top.  If/when I sort this mess out I'll ask you to retry.

**Comment by andybalaam** [comment]
@colonelfazackerley with the latest code I definitely can `make android-debug-test ` - please could you re-try with `make clean` beforehand?  It looks like the rabbit-escape-generic.jar accidentally got compiled with Java 8.  This is actually unrelated to the problems I have been having with the Android build :-)

**Comment by andybalaam** [comment]
Snapshot 0.11.0.4 has this fix in it.  Please try it out and let me know whether it works! http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by andybalaam** [comment]
Good, I guess :-)
