### ISSUE TITLE
android build failure with newer ndk

### ISSUE THREAD

**Issue by ryanhaining** [andybalaam/rabbit-escape#600]
building gives the error

```
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
```

Because mips64 isn't in newer ndks. Updating gradle fixes this

**Comment by andybalaam** [comment]
Snapshot 0.11.0.4 has this fix in it.  Please try it out and let me know whether it works! http://artificialworlds.net/rabbit-escape/snapshots/
