### ISSUE TITLE
Bridges make water think it is falling

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#605]
![image](https://user-images.githubusercontent.com/76812/50986203-1189c100-14fe-11e9-8ffc-af30112994ea.png)

A bridge below seems to make water think it is falling when it shouldn't be.  I'd expect the above screenshot to show a full-looking cup of tea.

**Comment by colonelfazackerley** [comment]
Are the cells full? If you pause the overlay shows the amount of water in each cell. Knowing this will help to show if the bug is in engine or render.

**Comment by andybalaam** [comment]
Really enjoyed generating this screenshot because water is so cool.

**Comment by andybalaam** [comment]
![image](https://user-images.githubusercontent.com/76812/50996790-ccc05300-151a-11e9-94c6-2ab23335add0.png)

Yep, definitely looks like rendering is the problem.

**Comment by colonelfazackerley** [comment]
I've had a few goes at making a simple level that I can just run without user interaction to demonstrate the problem. I can't reproduce it. Can you post a simple level, or a solution to a level that shows the problem?

**Comment by andybalaam** [comment]
Interesting.  When I make the bridges be there at the start of the level it doesn't seem to happen...

**Comment by andybalaam** [comment]
Ah, got one:

```rel
#P  i #
#     #
#    (#
#     #
#r    #
#iri  #
#######
```

**Comment by andybalaam** [comment]
![tmp](https://user-images.githubusercontent.com/76812/51027087-eba8fe80-1587-11e9-9818-8add776fa4f3.gif)
I love just watching water flowing.

**Comment by colonelfazackerley** [comment]
isFalling() looks uses isFull() for the cell below. isFull needs the height and targetWaterHeight to reach 32. In the cell with the bridge in above the solid block these get stuck at 19. WaterRegion.getContents() returns  622 (622/32=19). Now need to figure out why that is stuck. Problem actually seems to be in engine...
@tttppp ?

**Comment by colonelfazackerley** [comment]
in setTargetWaterHeight() WaterRegionRendered.getContents() is used, and returns 622 for the cell. When the overlay is drawn WaterRegionRenderer.contents is 1616. Need to understand why this number is changing within 1 time step.

**Comment by tttppp** [comment]
If it's a problem in the engine then it'll be because bridges are being treated like slopes for some reason. We should fix this before releasing a load of levels with solutions that depend on the current behaviour :-)

**Comment by tttppp** [comment]
I've just checked the code and I'm pretty sure it's not a problem with the slopes being confused with bridges.  Perhaps it might be an issue with the code that re-evaluates the WaterRegion grid when changing the block type (i.e. none -> bridge).

**Comment by tttppp** [comment]
I can observer the issue in `WaterAnimation.step`. There are a list of `WaterRenderers` that each maintain a reference to a `WaterRegion`. I've added some debugging around the cell at (3,5):

```
    /**
     * Game step. Usually ten animation steps per game step.
     */
    public void step( World world )
    {
        if ( null == world || null == lookupRenderer )
        {
            return;
        }

        moderateParticleCount();

        List<WaterRegionRenderer> currentRR = lookupRenderer.getListCopy();
        for ( WaterRegion w: world.waterTable )
        {
            if ( w.getContents() == 0 )
            { // Empty regions do not need renderers.
                continue;
            }
            WaterRegionRenderer r = lookupRenderer.getItemAt( w.x, w.y );
            if ( null == r)
            { // Create renderer for region that does not have one
                lookupRenderer.add( new WaterRegionRenderer( w, world, this ) );
            }
            else
            { // Remove renderers that are being used from temporary list.
                if (w.x == 3 && w.y == 5)
                {
                    System.out.println("#Remove r: w: " + w.getContents()); // 1120
                    System.out.println("#Remove r: r: " + r.region.getContents()); // 622
                }
                currentRR.remove( r );
            }
        }
        // Remove renderers that no longer have regions
        lookupRenderer.removeAll( currentRR );

        for( WaterRegionRenderer wrr: lookupRenderer )
        {
            wrr.setTargetWaterHeight();
        }
    }
```

If we add the following hack at that point, to set the region in the WaterRenderer then the animation looks better:

```
                if (r.region != w)
                {
                    r.region = w;
                }
```


![smoother3](https://user-images.githubusercontent.com/7073263/53297084-3a48ea00-3810-11e9-8a1b-2bf58cab62e4.gif)

**Comment by tttppp** [comment]
Potential fix here:
https://github.com/andybalaam/rabbit-escape/pull/611

**Comment by colonelfazackerley** [comment]
I started looking at your PR. It's quite a big diff! I ran out of time.

As it was, with a WaterRegionRenderer for each WaterRagion, it was quite complicated. It sounds like a good idea to simplify this.

**Comment by andybalaam** [comment]
I merged it since the cod looked sensible.  I will re-run the animation above to check whether this but is fixed.

@colonelfazackerley I really want to encourage people other than me to review, so now regret merging this without your go-ahead.  I will do better in future.

**Comment by andybalaam** [comment]
![n605](https://user-images.githubusercontent.com/76812/53332595-9f254280-38eb-11e9-8540-541e866cc021.gif)
Fixed!

**Comment by colonelfazackerley** [comment]
I will still try to have a look. The original problem was my fault, I think.

I can still enjoy posthumously whining about @tttppp 's PR :)

**Comment by andybalaam** [comment]
2 things that would have have made it easier to merge this @tttppp :
1. If I had established an automatically-enforced code formatter there would be no whitespace in the diff
2. If you had made the code formatting a separate PR.

**Comment by andybalaam** [comment]
Awesome work from both of you, thank you!

**Comment by tttppp** [comment]
Agree about making the code formatting a separate PR. Unfortunately I made my change on an old copy of the code, and then had to rebase across a massive reformatting change.  I decided it was easier simply to reformat the whole file again, which then caused a whole load more things to get formatted.

Anyway - thanks for merging!

**Comment by andybalaam** [comment]
Thanks for the good fix.
