### ISSUE TITLE
Bug: Double Digging with a Brolly

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#609]
See the levels in this thread:

https://www.artificialworlds.net/rabbit-escape/levels/d/57-digging-bug

A rabbit (or rabbot) that has a brolly will dig through two layers that are one space apart.

```
#r #
#ld#
####
#  O
####
:name=Dig through just one layer?```

**Comment by andybalaam** [comment]
Thank you!

**Comment by andybalaam** [comment]
Updated top comment so there's no need to click to see the bug.
