### ISSUE TITLE
Custom levels from file and URL

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#61]
Something I would like to work on. I wanted to agree a specification before working on it. This is my interpretation of something on the TODO.
- created a git ignored directory called dev, experimental or something. It should sit next to easy, medium, test, etc.
- Bung new .rel files in there. don't worry about naming them level0*n*.
- "make leveldev" or something would compile the project, like rungui, but would then present a menu.
- The menu would probably just be in the terminal. it would list the levels in the dev directory for you to choose.
- If the level is lost it would restart. (Can Alt-F4 or similar to kill the process)
- If the level is won, process would exit.

The default label of "Enhancement" would be OK, but a custom label of "RFC" or "specification" would be better for this issue.

**Comment by andybalaam** [comment]
What about a menu item in the game to open a level file from disk (and/or from a URL)?  Would that solve the same problem in a way that is accessible to non-devs too?

**Comment by colonelfazackerley** [comment]
Sounds good to me. While I am sure you would knock out the feature in an evening, can you leave it for me to have a go?

**Comment by andybalaam** [comment]
Yes, absolutely.  It's not near the top of my mental list, so no danger of me trampling on your work.

**Comment by andybalaam** [comment]
Soon, we are going to have to either implement or remove the "Demo" menu item.  Maybe "load level" should replace it.

**Comment by andybalaam** [comment]
Then, one day, there will be a "level editor" button, and "load level" could be inside that?

**Comment by andybalaam** [comment]
Level editor is down the line a bit though, because I plan to implement an online level editor first, I think.

**Comment by andybalaam** [comment]
Note: there is code that runs a single level using a different main class, and a Makefile target that launches it.  I think it is hardcoded to launch level test/level_01.rel or similar.  I tend to think that the "normal" main class should accept a command-line option to open a level or set of levels, instead of having a different main class.

**Comment by andybalaam** [comment]
Note also that the various *Main classes are horrible at the moment - a bad attempt to share code.  I'd prefer to make them much simpler and throw away a lot of that logic.

**Comment by colonelfazackerley** [comment]
I have been using test/level_01.rel, for playing levels in the dev build with "make runlevel". It's a bit clunky. I will try the menu item idea to launch a file chooser dialog. 

I had noticed the multiple entry points with different main() methods. I can see about removing any that are obviated.

**Comment by andybalaam** [comment]
Cool.  I still like the idea of being able to launch on the command line, so feel free to leave it alone if it's not related to what you're doing.  I just want to get rid of the clunky abstract Main class, and the separate class for running a single level.

**Comment by colonelfazackerley** [comment]
Excited note: I have a menu item that loads a level working. I want to refactor, tidy and have it remember where you like to save your test files, then I will pull request.

**Comment by colonelfazackerley** [comment]
I have it working (with the dir you last read from being stored with the other config). I will do some last checking and make a pull request this evening.

i would then like to add
- retrieval of levels from github issue pages
- retrieval of levels from any URL

**Comment by colonelfazackerley** [comment]
Oh, and I would also like to add some non command-line feedback when your fantastic new level makes the parser choke. probably just the command line text on a dialog with a monospaced font.

**Comment by andybalaam** [comment]
Also excited, about all of the above.

**Comment by colonelfazackerley** [comment]
With 3 methods of reading arbitrary files, I was thinking the main menu would be cluttered: The 3 methods should be in a submenu. How about this?

```
Start Game  +
            -Easy-
            -Medium-
            ...
About
Experimental+
            Level File
            Github Issue
            URL Get
Quit
```

**Comment by andybalaam** [comment]
Yes, there should only be one menu item for this stuff.  Eventually it may be just "Level editor".

I like the idea of a name like "Experimental".  I think it's closer than "Load level", but maybe not quite there.  "Custom levels"?

For GitHub issue - are you planning to parse the issues list and display logged issues in a dialog, or just allow pasting a URL?  If the latter, I think there should be just one menu item for both GitHub Issue and URL Get - the code should work out what it's looking at when it fetches the page.

**Comment by andybalaam** [comment]
btw in future I plan:

    Play (jumps to the next unsolved level, or the last one you failed to complete)
    Choose Level +
        -Easy-
       etc.
    About
    etc.

**Comment by colonelfazackerley** [comment]
I was thinking that you would give the issue number with a jspinner or something. In the HTML of the issue pages, the md triple backtick becomes a code tag. So just pick out those bits and give a choice.

The URL one would be much simpler. Assume the URL just points to a level definition.

**Comment by andybalaam** [comment]
Cool.

**Comment by colonelfazackerley** [comment]
I have looked at this some more. GitHub has an API that returns JSON. I think this is the pro way to go for getting the levels from issues. Do you mind adding a dependency on a JSON library?

**Comment by andybalaam** [comment]
http://artificialworlds.net/find-the-dependencies-and-eliminate-them

We should be very careful _which_ JSON library.  Some are terrible, abandoned etc.  I might even feel the need to write my own because I have strong opinions about the existing libraries I have seen.

But, I am not against it in principle, especially if the license means we can embed the source code directly rather than some evil with Maven or checking the binary into our repo.

**Comment by colonelfazackerley** [comment]
The dialogue that let's you choose the level from the issues is going to take a while. When its halfway functional I will push the branch to my fork and ask for advice.

Re JSON, I will take that as carte blanche to half bake my own parser.  :)

**Comment by tttppp** [comment]
JSON.simple: https://code.google.com/p/json-simple/

Aims to be lightweight and has an apache licence, which is fine to embed in a GPL 3 project. (ie Upgrade the license to GPL3+).

http://www.gnu.org/licenses/license-list.html#apache2

**Comment by andybalaam** [comment]
I'm not particularly keen on GPLv3 and would need some convincing to change to that.  A very brief look at that project suggests to me it won't convince me.

**Comment by andybalaam** [comment]
Here's how I'd like to express JSON objects in Java:

    ob(
        pr( "key1", "value1" ),
        ...
    )

    ar( ob(), "xyz", 4 )

and here's how I'd like to "explore" them:

    jsonobj.pr( "key1" ).asString() == "val1"

    jsonarr.get( 0 )

    jsonint.asInt() == 3

With runtime type-checking.

Make any sense?

**Comment by andybalaam** [comment]
Because Java is rubbish we can't consider int or Integer to be a JsonArtifact so we'd need JsonNumber and JsonString classes.

**Comment by andybalaam** [comment]
I'm not sure I can express myself well enough or devote enough time to implementing this now, so I'd suggest finding the smallest functional library we can legally paste into our (GPLv2) source code and using that until I can pull my finger out and do it properly.

**Comment by colonelfazackerley** [comment]
Or I will have a go at it. If I do the OO right, and you don't like my JSON parser then you can rebuild the parser and my issue chooser dialog should work the same.

**Comment by andybalaam** [comment]
I'd recommend using something else instead of writing your own parser.  I only want to do it because I'm an idiot, and if I did it I'd probably use a parser generator.

**Comment by andybalaam** [comment]
But yes, swapping in a different library should be relatively easy.

**Comment by andybalaam** [comment]
I should have mentioned earlier there is an extremely half-baked JSON parser here https://github.com/andybalaam/rabbit-escape/blob/f23443a470f9333e8063add59eca33e5973c798f/rabbit-escape-engine/src/rabbitescape/engine/config/ConfigTools.java#L110 .  It's limited to only ever consuming its own output, so doesn't support arbitrary JSON, and it probably wrong in almost every way imaginable.

Real JSON parsing involved Hard Problems like character encodings.

**Comment by andybalaam** [comment]
I wrote it during a long evening.  It looks pretty inspired.

**Comment by tttppp** [comment]
@andybalaam I'm normally very happy to spend my evening re-inventing the wheel, but that's some craziness!

Would grepping for triple backticks not suffice (as suggested above https://github.com/andybalaam/rabbit-escape/issues/61#issuecomment-147982648 )? If this is a temporary feature until a level-editor is made this might do. It certainly wouldn't increase the footprint of the jar much!

Another thing to consider is that the Android library already contains a json parser: http://developer.android.com/reference/android/util/JsonReader.html

**Comment by colonelfazackerley** [comment]
sample below. i would like to get the number, title, and the text body too. it had occurred to me that picking out a few bits instead of tokenizing everything might be the way to go.

I made some progress with the dialog this evening. sizing the components and such.

```
 {
    "url": "https://api.github.com/repos/andybalaam/rabbit-escape/issues/104",
    "labels_url": "https://api.github.com/repos/andybalaam/rabbit-escape/issues/104/labels{/name}",
    "comments_url": "https://api.github.com/repos/andybalaam/rabbit-escape/issues/104/comments",
    "events_url": "https://api.github.com/repos/andybalaam/rabbit-escape/issues/104/events",
    "html_url": "https://github.com/andybalaam/rabbit-escape/issues/104",
    "id": 111460464,
    "number": 104,
    "title": "Level: \"Galton Box\"",
    "user": {
      "login": "tttppp",
      "id": 7073263,
      "avatar_url": "https://avatars.githubusercontent.com/u/7073263?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tttppp",
      "html_url": "https://github.com/tttppp",
      "followers_url": "https://api.github.com/users/tttppp/followers",
      "following_url": "https://api.github.com/users/tttppp/following{/other_user}",
      "gists_url": "https://api.github.com/users/tttppp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tttppp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tttppp/subscriptions",
      "organizations_url": "https://api.github.com/users/tttppp/orgs",
      "repos_url": "https://api.github.com/users/tttppp/repos",
      "events_url": "https://api.github.com/users/tttppp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tttppp/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-14T18:26:55Z",
    "updated_at": "2015-10-14T18:26:55Z",
    "closed_at": null,
    "body": "I think this is fairly easy, but I wanted to make a level that looks like the \"Galton Box\" game.  It's a school-fate-type game where you drop a penny in the top, which bounces off some nails before falling into one of several zones at the bottom.  If you get near one of the edges then you win a big prize, and if it falls near the middle you lose.  I found the name \"Galton Box\" by googling, but if anyone can think of a better name then I'm all ears.\r\n```\r\n:name=Galton Box\r\n:description=\r\n:num_rabbits=30\r\n:num_to_save=21\r\n:block=10\r\n:climb=10\r\n:dig=10\r\n:bridge=10\r\n:bash=10\r\n:explode=10\r\n:music=tryad-witness\r\n####### O #######\r\n######  #  ######\r\n#####   *   #####\r\n####  *   *  ####\r\n###           ###\r\n## Q*  *Q*  *Q ##\r\n#               #\r\n#################\r\n:*=()pppppppppp\r\n:*=(pppppppppp\r\n:*=)pppppppppp\r\n:*=(pppppppppp\r\n:*=(pppppppppp\r\n:*=)pppppppppp\r\n:*=)pppppppppp\r\n```"
  },
````

**Comment by colonelfazackerley** [comment]
draft of the dialog
![git-issue-dialog-draft](https://cloud.githubusercontent.com/assets/9596719/10557532/9c701638-74a8-11e5-969f-490c629deadb.png)

**Comment by tttppp** [comment]
Just to check - can the design cope with multiple versions of levels in a single issue?  That seems to be a common occurance.

**Comment by colonelfazackerley** [comment]
The issue choosing spinner (currently says 111) will have another spinner underneath to choose from the levels in an issue.

**Comment by tttppp** [comment]
Looking great then!

**Comment by colonelfazackerley** [comment]
I have it retrieving stuff from github, and you can cycle through the issues (it displays the issue titles) with the spinner.

I should push to a branch on my fork, so everyone can tell me how horrible the code is.

**Comment by colonelfazackerley** [comment]
check it out (possibly in the git sense)
https://github.com/colonelfazackerley/rabbit-escape/commit/56b68fde38f4db7e607b0f595c6b27460f620346

**Comment by colonelfazackerley** [comment]
So exciting!
![issuedialogdraft2](https://cloud.githubusercontent.com/assets/9596719/10564091/d412796e-759d-11e5-8841-ef13f0faa77f.png)

**Comment by andybalaam** [comment]
Really cool. Will look at the code when I have time. We need to catch Android up with the Swing interface. I don't want them to get out of sync.

**Comment by tttppp** [comment]
Looking good. Looks like the json needs unescaping (backslashes and double quotes), and for it to work well I guess we need to add interpreting blank lines as rows of spaces.

Adding this to the Android app will require Internet access, and I usually try to avoid using games that require it (usually because I've not seen the source code).

**Comment by colonelfazackerley** [comment]
yeah, this is very much work-in-progress.  I have plans for unescaping and some auto-fixing.

new version of android (marshmallow) allows you to deny apps individual permissions.

**Comment by colonelfazackerley** [comment]
I pushed more to my fork's branch. I can play #104 using it. 

https://github.com/andybalaam/rabbit-escape/compare/master...colonelfazackerley:github-issue-level-get

**Comment by colonelfazackerley** [comment]
If a level editor is implemented, it could use the github api to post levels as issues.

**Comment by andybalaam** [comment]
I am planning to write a web app that stores levels. My main concern with github is it could be hard for non-programmers. That will obviously take time.

**Comment by andybalaam** [comment]
@tttppp I also want to avoid too many permissions but hard to avoid this one?

**Comment by andybalaam** [comment]
Can we provide an alternative app that doesn't access the Internet? Or make the permission optional (before marshmallow)?

**Comment by colonelfazackerley** [comment]
Pre marshmallow, I am pretty sure they have to be separate play store entities.

**Comment by andybalaam** [comment]
I feel really conflicted about this. I don't want to cripple the Android app but I hate permissions.

**Comment by tttppp** [comment]
The marshmallow change is of course junk though, because it removes all control from the user over which apps access the internet. :-(

Personally I'd see level loading from a url or github as being experimental to the point of development-only. The average user isn't going to know what github is, let alone why they can load levels from it. For the desktop client I think having this feature is fine, because anyone finding the download and running the java application has already proved themselves to be fairly tech savy!

Just my opinion though :-)

**Comment by colonelfazackerley** [comment]
my latest push makes the dialog appear before the get to github. there's supposed to be dots appearing to show progress, but that does not work.

i need to tidy it, a lot. i should probably make it work with the indented md next.

**Comment by andybalaam** [comment]
@tttppp fair point that at least for now accessing levels over the Internet is a dev thing. One day I plan a huge community of level swappers but at that point we could revisit the decision. For us though this could be really cool so I think we should have a dev build of the app.

**Comment by colonelfazackerley** [comment]
The progress ...... works now. I will push later.

@andybalaam - if you could look at the branch on my fork and give me restructuring advice, it would be great. I have over 500 lines unshepherded. I am sure you will want changes. If I had a bit of early input to give me direction, that should speed progress later.

**Comment by andybalaam** [comment]
The next few days are crazy but I will do what I can.

**Comment by colonelfazackerley** [comment]
The level/bug/all filters work
![screenshot from 2015-10-23 12 05 16](https://cloud.githubusercontent.com/assets/9596719/10691126/a9963240-797e-11e5-97c4-dd60aedeef43.png)

**Comment by andybalaam** [comment]
woot/aiee!  I hope to browse through this sometime next week (I am on hols, so no idea whether I'll manage it).  Swing UIs are really ugly - we can commit it and then try to make it as nice as possible later, if that makes sense.  I am mainly thinking of spacing things out, and aligning them.

**Comment by colonelfazackerley** [comment]
I have hit some problems
- the api returns the 30 or 40 most recent issues in one go
- there seems to be no way of getting older ones in groups
- can request single issues, but you are limited to 60 requests in total per hour.
- there seems to be no way of getting anything but the first comment.

so having spent days on this, I am not sure it was worthwhile. I have certainly been revising my java and regices.

I may try switching over to requesting web pages, and parsing those. the problem with this is that github may choose to change the format without notice. the api should be more stable, but seems pretty useless.

**Comment by andybalaam** [comment]
https://api.github.com/repos/andybalaam/rabbit-escape/issues?page=2

**Comment by andybalaam** [comment]
https://api.github.com/repos/andybalaam/rabbit-escape/issues/116/comments

**Comment by andybalaam** [comment]
I guess you would have to fetch the comments when you clicked the level, to keep the number of requests down.

**Comment by colonelfazackerley** [comment]
aha. 
The api doc did not describe how to get the followup comments, but I see now that the issue response gives the URL to get the followup comments.

how did you figure out the '?page=2' thing? is it just so obvious it does not need mentioning? (This sort of thing is new to me)

**Comment by andybalaam** [comment]
On this page https://developer.github.com/v3/issues/ I noticed they mentioned this header response:

    Link: <https://api.github.com/resource?page=2>; rel="next",
          <https://api.github.com/resource?page=5>; rel="last"

Side note: to see headers, you can use `curl -v`

**Comment by andybalaam** [comment]
Based on that, I guessed.

**Comment by colonelfazackerley** [comment]
I have the subsequent page loading working. I pushed it to my fork.

**Comment by andybalaam** [comment]
Comments on the code so far.  Basically looks really good.  Minor comments below.  Most of these could be fixed in co-operation after a merge, so don't feel they are fences that you must jump.

- Lots of missing spaces e.g. inside brackets, around operators etc.
- Wow, the JSON parsing is extremely ad-hoc :-)
- GitHubClient: I recommend splitting HTTP request logic from JSON parsing logic.  Then we can unit test JSON parsing.  I also recommend splitting the "read stream into string" logic into a separate class, just because it blatantly should be part of the Java standard library.
- I recommend, where possible, making objects immutable i.e. all fields are declared final, and initialised in the constructor.  E.g. the String result of the request could be passed in to the constructor of the JSON parsing object.
- GitHubIssue: again, where possible I recommend immutable objects with all fields set in the constructor.  Then we know every time we have an instance of the class we know it's valid.  The logic that is currently in the setters can be in static methods that are called from the constructor, and return the values that will be fields.  Ping me if this doesn't make sense.
- Wow, regular expressions in Java are horrific.  Don't know how to make this better.
- Raw strings e.g. `"x"` should be replaced by calls to `t( "x" )` to cover us in future for translation.
- Resizeable dialogs are always good.
- TestGitHubInterface: convention for names of test methods: No need for the word "Test".  Capital letter for first word.  Words separated by underscores.
- TestNoInfiniteLoop contains a very long line.

**Comment by andybalaam** [comment]
Further comment: some of this should be re-used in the Android client (dev version), so at some point, some of it should be moved to rabbit-escape-render.  [Rule of thumb: rabbit-escape-engine is the game itself, and rabbit-escape-render is the cross-platform bits that surround it.]

Again, this can all be done post-merge.  No need to fiddle with that at this stage.

**Comment by colonelfazackerley** [comment]
I have had this in mind (though not sure exactly where you would want all the classes). Hence, all the swing stuff is in GitHubIssueDialog.

Goes without saying that this should also be in the text interface.

**Comment by colonelfazackerley** [comment]
Another thought. Even after there are better ways of getting level designs from the web, we may want the github issue parsing to extract little toy worlds that demonstrate bugs.

**Comment by andybalaam** [comment]
Absolutely. This is going to be invaluable. I also plan an extension that spits out code for a unit test. On a side note I am always open to ways of making the unit tests clearer. I'm not particularly happy with them as they are now.

**Comment by colonelfazackerley** [comment]
![screenshot from 2015-10-24 22 26 08](https://cloud.githubusercontent.com/assets/9596719/10712881/d4ed09f2-7a9e-11e5-83b6-1b6973d47dfa.png)
All the GUI elements you can see in the screenshot work. i just need to go through the tidying list above, and I think it's ready for a pull request.

**Comment by tttppp** [comment]
Great stuff! Did you solve the level while you were at it ;-)

Really looking forward to being able to use this. I'm already getting milage from the load from file feature, and this will save another step.

**Comment by colonelfazackerley** [comment]
No, I have not been playing. All the spare time I have has gone into coding. I want to get this merged.

**Comment by colonelfazackerley** [comment]
TODO
-    Lots of missing spaces e.g. inside brackets, around operators etc.
-    Wow, the JSON parsing is extremely ad-hoc :-)
-    GitHubClient: I recommend splitting HTTP request logic from JSON parsing logic. Then we can unit test JSON parsing. I also recommend splitting the "read stream into string" logic into a separate class, just because it blatantly should be part of the Java standard library.
-    I recommend, where possible, making objects immutable i.e. all fields are declared final, and initialised in the constructor. E.g. the String result of the request could be passed in to the constructor of the JSON parsing object.
    GitHubIssue: again, where possible I recommend immutable objects with all fields set in the constructor. Then we know every time we have an instance of the class we know it's valid. The logic that is currently in the setters can be in static methods that are called from the constructor, and return the values that will be fields. Ping me if this doesn't make sense.
-    Wow, regular expressions in Java are horrific. Don't know how to make this better.
-    Raw strings e.g. "x" should be replaced by calls to t( "x" ) to cover us in future for translation.
-    Resizeable dialogs are always good.

DONE
-    TestGitHubInterface: convention for names of test methods: No need for the word "Test". Capital letter for first word. Words separated by underscores.
-    TestNoInfiniteLoop contains a very long line.

**Comment by colonelfazackerley** [comment]
see #123 

still TODO
- resizable dialog. i can get back to this when its merged.
- move things to correct package (I can do this, if you tell me where you want it, or it may be quicker if you do it).

**Comment by tttppp** [comment]
Regular expressions are just terrible in java, there's not really anything you can do about it. Some standard methods hide the regex implementation lines within them (e.g String.replaceAll), but this doesn't solve problems like the quadruple backslash.

**Comment by andybalaam** [comment]
It's not you. It's Java. Pretty much always.

**Comment by andybalaam** [comment]
I will review and plan to merge and then we will continue to improve. Especially JSON parsing.

**Comment by andybalaam** [comment]
Is this done?

**Comment by colonelfazackerley** [comment]
yes. it would ideally need some polishing.

i used it to get the 20 levels for the arcade set, but hit the github api call limit.

I think I would like to see how much it is used before spending more time on it.

**Comment by andybalaam** [comment]
Sounds sensible. I plan to incorporate its logic into the level editor.
