### ISSUE TITLE
License: GPLv3 ?

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#610]
I originally chose GPLv2 as the license for Rabbit Escape.  Since then, I have personally become much more favourable towards GPLv3 as a license (I was a bit suspicious towards it at first).

I would quite like to use https://github.com/remkop/picocli for a command line interface, and it would be convenient to incorporate its source code rather than depending on a library.  Because it is Apache 2-licensed, this would not be allowed under GPLv2, but is allowed under GPLv3.

Does anyone object to changing the license to GPLv3?  Feel free to ask questions below.

@colonelfazackerley @tttppp @GamingInky 

If anyone does object, I don't feel strongly enough to try and push it.

Some argument in favour of GPLv3 is here: https://www.gnu.org/licenses/rms-why-gplv3.html

> Side note: in the past we have got permission from contributors to allow us to change the license of Rabbit Escape to one of a number of licenses, including "GPLv2 or later", which would allow us to move to GPLv3, but that is a legal right, and I am looking for agreement, not just a legal right.  #317 #36 #22

**Comment by tttppp** [comment]
I'm happy with GPL 3. Go for it!

**Comment by colonelfazackerley** [comment]
GPL 3+ is fine with me.

**Comment by andybalaam** [comment]
Thanks.  If I get to the command line changes I will consider it.
