### ISSUE TITLE
Simplify the build

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#616]
Lots of things about the build process are over-complex.  I am going to try and write a new Makefile that makes things simpler.

**Comment by andybalaam** [comment]
Here are my thoughts so far:

![build-flow](https://user-images.githubusercontent.com/76812/54685049-c4355b80-4b0d-11e9-9cc8-db6c4dcbef24.png)

**Comment by andybalaam** [comment]
Branch for this work: [simplify-build](https://github.com/andybalaam/rabbit-escape/tree/simplify-build)

**Comment by tttppp** [comment]
Sounds really good to me. You've potentially missed off the following scenarios:
 * A user just wants to play using the text interface (i.e. no assets need preparing except level lists)
 * A user doesn't have sox installed (i.e. a user wants to play with no sound)

Also did you think about how to build an update with/without recreating all the assets? The images in particular take a long time to create, so being able to skip that if they already exist would be useful.

**Comment by andybalaam** [comment]
If a user appears who wants to use only the text interface, we should prepare a release JAR for that, so they don't have to build from source.  It would be really small - exciting!

**Comment by andybalaam** [comment]
My general approach to build-time dependencies like sox is "just install it".  This is in stark contrast to my approach to run-time dependencies which is "no!".

**Comment by andybalaam** [comment]
The assets currently don't get rebuilt unless they are needed, and I would expect that to remain the case.  I'd like to make the `all-images` script clever enough to only rebuild what is needed instead of everything, and then we can stop the one-at-a-time behaviour of standard make, because launching the Inkscape executable is too slow.

**Comment by andybalaam** [comment]
I have done some work on this by moving image generation into scripts instead of defining everything in the Makefile and it's definitely simpler.  I want to check I didn't break the F-Droid build so I pushed tag v0.13.1 which should trigger a build at https://f-droid.org/wiki/page/net.artificialworlds.rabbitescape/lastbuild

**Comment by andybalaam** [comment]
v0.13.1 succeeded.  I also; fixed #560 (bash completion) today. Continuing by extracting sound/music into a separate makefile, and I may then continue with levels files.

**Comment by andybalaam** [comment]
Also on the radar: an F-Droid dev suggested adding sox to the build environment was easy, so we could try that, and remove the generated files from the repo and remove the special F-Droid build.

Also on special stuff for F-Droid, it would be good to stop including binary jars (test libraries) in the code.  We could download during the build or find another way.

**Comment by andybalaam** [comment]
The main Makefile is much simpler now, so I'm calling this done.
