### ISSUE TITLE
Bug: after dig through bridge, rabbits walk on air

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#62]
Not sure if this is a manifestation of a known issue. Watch this run without doing anything.
```
:name=Bug
:num_rabbits=10
:num_to_save=12
:rabbit_delay=5,5,1
:bridge=3
:dig=3
:block=2
:music=tryad-witness
               
               
      Q        
 )          (  
  )k  )k   (   
   )   )  (    
    )   )(     
     ) d()     
      )(  )    
      (O   )   
 ############  
```

**Comment by colonelfazackerley** [comment]
Much simpler test level.
```
    d( 
    (  
rrr(  O
#### ##
```
The second rabbit hops over the hole and makes it to the exit. I don't think he should. Do you agree?

**Comment by tttppp** [comment]
This sounds like a cleaner version of #35 "The Bomb", or at least they might both be fixed in one change.

**Comment by tttppp** [comment]
Actually, I'm not sure. This is digging from a bridge; that was digging after climbing.

**Comment by colonelfazackerley** [comment]
fixed by a commit near  04f95e1392674

**Comment by andybalaam** [comment]
In the level at the top of this page, in the latest code, 1 rabbit gets past.  Do you think that's right?

**Comment by colonelfazackerley** [comment]
I confess I had not gone back to the first bug demo, as it seemed unnecessarily large. I will look later.

**Comment by colonelfazackerley** [comment]
```
  r 
 rd(
 )( 
 (O 
 ###
 d  
 )jj
 O) 
####
```
The bug lives. A simpler test world demo. 
- a rabbit is behind the other, so that when the first stops to dig into the slope, they are on top of each other
- I think its the case that the bug persists when the digger rabbit comes before the follower in the World.rabbits List.

**Comment by colonelfazackerley** [comment]
```
     
 rb( 
r (O 
#####
```
Similar bug for bashing.

I think there needs to be a pre-precessing loop. Need to know which blocks will be bashed/dug that before stepping all rabbits.

**Comment by colonelfazackerley** [comment]
bah, that's not right. I think I need a list of recently removed blocks. If a rabbit is on a block that was just removed, that overrides onSlope.

**Comment by andybalaam** [comment]
Maybe it's right that the rabbit walks on a block that existed at the beginning of the time step. If so we may need to ensure it works the same no matter the order of rabbits in the array. (Thought: We may be able to run all unit tests with arrays reversed)

**Comment by colonelfazackerley** [comment]
See my last pull request. Behaviour does not depend on rabbit order in that. Several extra tests are included.

I don't think rabbits should be able to walk off a block removed in that time step. It looks weird.

**Comment by andybalaam** [comment]
I definitely bow to the @colonelfazackerley looks weird radar.

**Comment by andybalaam** [comment]
Again, behaviour changes like this emphasise the need for automated tests of all levels.  So it's good we're doing that :-)

**Comment by andybalaam** [comment]
Are you sure behaviour doesn't depend on rabbit order?  From my initial look at the patch I'm not sure, but I haven't looked at it properly.  I added #151 to help us know this stuff for sure.
