### ISSUE TITLE
Ubuntu intelliJ configuration error

### ISSUE THREAD

**Issue by KaganHamzacebi** [andybalaam/rabbit-escape#624]
**make compile** and **make test** successfully done, but could not create the jar file having this error.

make dist-swing
. Checking for warnings in Makefile
. Checking version number (0.13.1) is consistent everywhere
. Checking for use of java.awt in engine code
. Generating animations list
. Generating level lists
. Converting images
. Building Swing jar dist/rabbit-escape-0.13.1.jar
java.io.FileNotFoundException: ../../dist/rabbit-escape-0.13.1.jar (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at sun.tools.jar.Main.run(Main.java:195)
	at sun.tools.jar.Main.main(Main.java:1288)
make: *** [Makefile:38: dist/rabbit-escape-0.13.1.jar] Error 1

**Comment by andybalaam** [comment]
Hi, did you close this because you found a solution?

**Comment by KaganHamzacebi** [comment]
Actually i thought i found it but it doesn't work. I still need help.

**Comment by andybalaam** [comment]
Ooh, I just tried it and I get the same!  Sorry for the bug.  Looking for a fix now.

**Comment by andybalaam** [comment]
@KaganHamzacebi  please try again - I just pushed a commit that fixes this problem for me.
