### ISSUE TITLE
IntelliJ import settings

### ISSUE THREAD

**Issue by KaganHamzacebi** [andybalaam/rabbit-escape#626]
Hello, Im having some problems to work on IntelliJ. Can you please specify the orders for how to work on intelliJ please? 

My questions are; 
Should i create a second directory without the android directory(under rabbit-escape) to work for non-android part?
Which directory should i import?
Which build automation tool should i select? (Eclipse, gradle)
Which tools do i need except the noted ones.

Thanks for helping.

**Comment by andybalaam** [comment]
> Should i create a second directory without the android directory(under rabbit-escape) to work for non-android part?

No, just open the main directory and ensure that these ones get included by IntelliJ: 

> Which directory should i import?

The rabbit-escape directory (the top-level one)

> Which build automation tool should i select? (Eclipse, gradle)

Use the IntelliJ build, not gradle or Eclipse.

> Which tools do i need except the noted ones.

Just what is listed in the INSTALL file.

**Comment by andybalaam** [comment]
I made a video of me setting up from scratch in case it's helpful: https://peertube.mastodon.host/videos/watch/11dc5754-7b75-46ea-af62-f983892f882e

**Comment by andybalaam** [comment]
Please re-open this issue if you have more questions!
