### ISSUE TITLE
Super-Easy Two bridges level description

### ISSUE THREAD

**Issue by username-is-not** [andybalaam/rabbit-escape#628]
In the Super-Easy mode the start level description for "Two bridges" (No. 4) says: 
> Rabbits: 1 Must save: 2

... When there are two and both must be saved (by acting super quickly and accurately right away).

Just want to add that this is a wonderful game for kids to develop thinking and skills, just like (the later ported) Lemmings for the Amiga and deserves to be cherished. :)

**Comment by andybalaam** [comment]
Hi, thank you for the kind comments!  Yeah, the description is misleading: the `Rabbits: 1` part means how many rabbits will come out of entrances, and does not include the rabbits that are already in the world at the start.

I'd welcome someone working on improving that, but I'm unlikely to do it myself, so I'll close this issue so as not to give a false impression.
