### ISSUE TITLE
Author key in levels

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#64]
eg
:author=andybalaam

The info would be shown at the start of the level, along with the description. Just noting here that I am working on this. I hope that players seeing various contributors will subliminally absorb the idea that authoring levels is for everyone, perhaps even them? This game needs a thousand levels or so.

Everyone OK with github usernames for author string?

While I am on the subject: I was thinking it might be good to have an end-of-set message directing players to artificialworlds.net to get involved.

**Comment by colonelfazackerley** [comment]
I have something working in swing. I wanted to have "by andybalaam" in a smaller font or muted colour, but I read that there is a plan to change away from the dialog, so I didn't do anything fancy.

"make test" is clean.

I don't know how to test for android, so I have not made any changes there.

I will insert the :author= stuff into the rel files. Then I think the pull request will be ready, unless you suggest something else.

**Comment by andybalaam** [comment]
I don't think I have immediate plans to move away from the dialog.  Did I put something in the TODO?

**Comment by andybalaam** [comment]
See my comment on pull request #65 .  I think we need author name and URL to make it accessible to non-developer types.

**Comment by andybalaam** [comment]
Love the idea of linking to "get involved" when you finish a level set.

**Comment by colonelfazackerley** [comment]
"I don't think I have immediate plans to move away from the dialog. Did I put something in the TODO?"
I thought I read something. Don't recall where. I may have it completely backwards.

**Comment by andybalaam** [comment]
The sooner we dispatch the TODO and use GitHub issues, the better.  I really like them.  This is my first proper experience using them.

**Comment by andybalaam** [comment]
Commit 43fd0f5e3b3c9a11d6a249525a67bb247acd82ff finishes this on Swing.  Android still to come.
