### ISSUE TITLE
Level: "Keep"

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#67]
```
:name=Keep
:description=Become the King of the castle
:num_rabbits=20
:num_to_save=15
:bash=5
:dig=1
:bridge=10
:climb=5
:block=2
:explode=10
:rabbit_delay=30,30,30,30,4
        #               #  
  #           O            
     #        #            
                           
        # # # # # #  Q     
        ###########        
        )#       #(        
         #       #         
         #       #         
        /#########\        
        #         #       /
\       #         #       #
#Q      ###########       #
#       #         #       #
###########################
```
Curious to know how hard this is, and how many solutions there are. I took a screenie of mine. I will post it when you guys have had a go.

**Comment by colonelfazackerley** [comment]
With the outdoor levels in the repo, and the levels in the issues in-tray, we have enough for a set of 20.

**Comment by tttppp** [comment]
After quite a few false starts, I managed to save 17. Spoilerific image:
![kingofcastle](https://cloud.githubusercontent.com/assets/7073263/10346426/0b8ed6f0-6d27-11e5-9125-fc3ba5973591.png)
Definitely easier than I thought to start with. My first few plans were much more involved, as I tried to use a climber to dig down through the top to allow a bridge to be created through the roof.

**Comment by colonelfazackerley** [comment]
That's slightly better than my solution. It is similar though. I only got 15 out.

**Comment by colonelfazackerley** [comment]
merged to master f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a

**Comment by andybalaam** [comment]
I got 15 out by bridging up from the bottom, with a blocker on the far right sloping block. Really enjoyed this one. Definite candidate for the deja vu set #87

**Comment by andybalaam** [comment]
I reckon 18 or 19 must be possible.

**Comment by andybalaam** [comment]
Just got 17. 18 looks hard, but I reckon @tttppp can do it.

**Comment by colonelfazackerley** [comment]
re-opening to include in deja-vu

**Comment by tttppp** [comment]
I think 18 must be impossible. I can't stop two from falling to their death at the start, and I can't find a way to rescue the blocker. Maybe with a lot more dig and bridge tokens I could make room to bridge up, but I think there isn't enough spare swag!

**Comment by andybalaam** [comment]
Well, if @tttppp can't do it, it's not possible.

**Comment by andybalaam** [comment]
But for deja vu we could add those tokens if we wanted.

**Comment by andybalaam** [comment]
Would be nice if we could somehow find a way to save the 2nd faller.  I miss it by about 1 time step when I go as fast as I can.

**Comment by tttppp** [comment]
Making a Deja Vu level with extra tokens and "save 18" as the goal sounds a good challenge!

**Comment by andybalaam** [comment]
Deja Vu is #87

**Comment by andybalaam** [comment]
Closing - we will track deja vu levels in its issue, not this one.

**Comment by andybalaam** [comment]
#296 is the deja vu version mentioned above.
