### ISSUE TITLE
Bug?: Rabbit walks up bridge, should bump head

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#68]
```
###   ###  
  (#     # 
r(# O ri# O
##### #####
```
-Rabbit on the left walks up bridge, but should bump head, and turn around.
-Rabbit on the right correctly can't build the bridge.

The only way the bridge could get like that, is in a level design. So, it might be considered a bug in the level, instead of a bug in the rabbit movement.

The parser could just check for solid blocks above bridges, and forbid them. However, sometimes they just look nice (#67 example). So, I think it would be better to check the rabbit's movement and make them turn around.

**Comment by colonelfazackerley** [comment]
```    
 #  
ri#O
####
```
Oh, they will build a bridge, inappropriately.

**Comment by andybalaam** [comment]
I think, if I am understanding right, both of these behaviours should be forbidden.

**Comment by colonelfazackerley** [comment]
they are both "playable" levels. watch them play out.
