### ISSUE TITLE
Level: "Tunnels"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#70]
One of the most annoying levels so far (and not an outdoors level). Hope you enjoy it as much as I have ("Argh! Stop being blown up.")
```
:name=Tunnels
:description=Dig a path through the minefield!
:num_rabbits=4
:num_to_save=2
:bash=99
:dig=99
:bridge=99
:rabbit_delay=30
:music=tryad-witness
########### #### ###
#  Q  ##### ###*####
#\   /#*############
#####*## ######## *#
#*#### # #####*## ##
 ##### #####*###### 
 ######** ########*#
####*#### ##########
#*###### ####### ###
 ####### ###*### *##
 ##*###*##### ######
############# ######
#### #####*##### #O#
#### ## ######## ###
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
:*=pppp
```

**Comment by colonelfazackerley** [comment]
I just learnt that the mines fall when you dig the blocks from under them...

**Comment by colonelfazackerley** [comment]
Completed it eventually. It's fiendish. It took me an hour or so. I got the minimum 2 out.

Another lovely original work.

**Comment by andybalaam** [comment]
Wow, this looks amazing.  I am excited about the arcade level set.

**Comment by colonelfazackerley** [comment]
close me
merged to master with f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a

**Comment by andybalaam** [comment]
Brilliant! Took me ages and very excited when I did it. I got 3 out so maybe one for deja vu? Do you think 4 is possible?

**Comment by andybalaam** [comment]
Deja vu is #87

**Comment by andybalaam** [comment]
Hint 3 has an extra backslash.

**Comment by tttppp** [comment]
I've felt close to getting 4 a couple of times. If it is possible then it could definitely be a Deja Vu level. Getting 3 out is quite a lot harder than 2, so nice work!

**Comment by andybalaam** [comment]
The hint was fixed somewhere.
