### ISSUE TITLE
Level: "The Traitor"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#71]
There may be some hacks to win this one, but I've tried to eliminate them.
```
:name=The Traitor
:description=Get your rabbits out before it's too late!
:num_rabbits=5
:num_to_save=5
:bridge=5
:bash=5
:rabbit_delay=5
:music=tryad-witness
###################
#r                #
#c# # # # # # # #*#
###################
                   
                   
                   
                   
                   
#        #        #
###   #  ##     # #
#     #  (  # #   p
#Q #  # ### #  ## #
# (  ( ( ( (  ((( O
###################
:*=dd
```

**Comment by colonelfazackerley** [comment]
Took 20 min or so. Amazed at the novelty of the levels.

I had to play with my hand over the keyboard, hitting 'p' constantly. I wonder if this level is possible on a tablet.

I got 5 out, and my feeling is that I used the intended solution.

**Comment by tttppp** [comment]
Yes, this requires quite a lot of accuracy, which might be harder on some devices.

**Comment by andybalaam** [comment]
I have developed a technique on my phone where one thumb selects tokens and the other places them. I will try this level like that when I get time.

**Comment by colonelfazackerley** [comment]
merged to master f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a
close me

**Comment by andybalaam** [comment]
This level is awesome. It is difficult on my phone but I reckon I'll be able to do it. (Technically I have got nowhere near yet)

**Comment by andybalaam** [comment]
I did it! Again, I was confused about what was going on. Because it said rabbits:5 at the beginning I thought I had to save the traitor. Anyway, amazing level. I was able to do it on my phone, with copious use of pause.
