### ISSUE TITLE
Level: "Sailing"

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#73]
```
:name=Sailing
:description=Sink or swim
:num_to_save=3
:num_rabbits=3
:dig=5
:block=2
:bridge=8
:rabbit_delay=10
           ##        
          ####    ## 
 ##              ####
####      /          
         /# \        
        /## #\       
       /### ##\      
Q         #         O
      ##########   /#
() ( )( (( )( (  )  #
( )) ( )( ) () )) ) (
```

**Comment by tttppp** [comment]
Very attractive!  I used all 8 bridges and no blockers.  I solved it again using the two blockers instead of two of the bridgers.  A nice challenge.

**Comment by colonelfazackerley** [comment]
I put the blockers in as a distraction. What's your blocker solution? Did you use the diggers?

Glad you enjoyed it.

**Comment by tttppp** [comment]
I just rechecked - I miscounted. My bridger solution used two bridgers to delay rabbits, whereas the blocker solution delays them with blockers and frees them again with bridgers.

**Comment by andybalaam** [comment]
Tricky! I did it accidentally on about the 4th try. I don't know how long it would have taken me to figure out how to trap the 2 rabbits between the sails - I clicked wrong and it happened!
Thought: 9 Skill:8

**Comment by andybalaam** [comment]
Sounds like we have a number of solutions to this...

**Comment by colonelfazackerley** [comment]
As long as none of those solutions are too trivial, I don't think that us a bad thing.

**Comment by andybalaam** [comment]
No, definitely not. Would be nice to add several solutions for automated testing when we've got it.

**Comment by tttppp** [comment]
Just solved with three diggers remaining.

**Comment by tttppp** [comment]
I meant 3 bridgers remaining.

**Comment by colonelfazackerley** [comment]
Perhaps for déjà vu with fewer bridge tokens?

**Comment by tttppp** [comment]
Good idea. I'll make a issue for it.
