### ISSUE TITLE
Level: "Catch Me If You Can"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#75]
```
:name=Catch Me If You Can
:description=Meet your falling friends before they meet their maker.
:num_rabbits=25
:num_to_save=13
:bridge=99
:rabbit_delay=10
:music=tryad-witness
#Q Q Q Q Q    #
#             #
#             #
#             #
#             #
#\           O#
##\         /##
###\       /###
####\     /####
###############
```

**Comment by colonelfazackerley** [comment]
I can only get 12 out after 20 minutes.

**Comment by tttppp** [comment]
I was initially going to submit the level with a target of 10, then I discovered how to save 12 and then eventually 13.

**Comment by colonelfazackerley** [comment]
I can still only get 12.

This level highlights game behaviour that might be considered undesirable: a rabbit falling to death consumes a token.

**Comment by tttppp** [comment]
Yep - the soon-to-be-flat rabbits taking the pre-placed tokens does make things a little harder! I have a walkthrough diagram of how to save 13 which I can post at a later date if this is unsolved.

**Comment by andybalaam** [comment]
Yes, splatting should not consume a token. Please log as a bug.

**Comment by colonelfazackerley** [comment]
I can get 13 if I add an extra row of sky.

**Comment by colonelfazackerley** [comment]
@tttppp - unless you tell me it would ruin your lovely level, I will add sky to this for arcade.

**Comment by tttppp** [comment]
The lack of height on this one was deliberate. There's a way to get 13 out with an extra row of sky that I found too, so I'd prefer to keep it as is.

Given that this seems to be a very hard level, I propose we use the "save 12" version, and have the "save 13" version in Deja Vu.

**Comment by andybalaam** [comment]
Sounds good. I have yet to try it but am really looking forward to it!

**Comment by colonelfazackerley** [comment]
How about a roof? In swing the sky limit is not very clear, and it's upsetting when they bridge up and dissolve.

This has a 12 limit.

```
:name=Catch Me If You Can
:description=Meet your falling friends before they meet their maker.
:hint1=Place a bridge token under the 3rd\nentrance. Extend the bridge with\na second token.
:hint2=Start another 2 token bridge\under the 2nd entrance.
:hint3=Start a 1 token bridge between the\n1st and 2nd entrances. Finally, start a\n1 token bridge under the 1st entrance.
:num_rabbits=25
:num_to_save=12
:bridge=99
:rabbit_delay=10
:music=tryad-witness
###############
#Q Q Q Q Q    #
#             #
#             #
#             #
#             #
#\           O#
##\         /##
###\       /###
####\     /####
###############
```

**Comment by tttppp** [comment]
I think putting a roof on still makes it too easy as the bridgers stop before leading their friends to the void. I agree that it's not easy to see the edge though, and maybe a better long term solution is to highlight the death squares somehow.

**Comment by andybalaam** [comment]
I do think the edge should be visible. We could just not draw graph paper outside the playing area but I like it extending a bit.

**Comment by colonelfazackerley** [comment]
The padding could be scribble-coloured in, but in a lighter grey than the blocks.

**Comment by colonelfazackerley** [comment]
save 12 version merged to master with f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a
However, leave this open for a 13 version in deja vu.

**Comment by andybalaam** [comment]
Really great level. So original again!  Yes to 12 target and 13 for deja vu.

**Comment by andybalaam** [comment]
Deja vu is #87

**Comment by andybalaam** [comment]
Backslash in hint 2.

**Comment by andybalaam** [comment]
Btw I suggest closing level issues (when hints etc are fixed) even if they are planned for deja vu. We can use #87 to track deja vu and create or reopen issues if there is more work to do.

**Comment by tttppp** [comment]
We should create a folder of levels that are ready to be included in future releases. That way we can run tests against them even though they aren't released. This would let us close lots of issues too (as releasing the levels would be covered by a single level-set issue) .

**Comment by andybalaam** [comment]
Yes, good idea.

**Comment by andybalaam** [comment]
I have totally failed to save 13 despite really trying for a long time. Please can I have some help @tttppp ?

**Comment by tttppp** [comment]
> I have a walkthrough diagram of how to save 13 which I can post at a later date if this is unsolved.

I said that a year ago, so this is going to be a real test of my filing. No idea even which device the diagram might be on.

**Comment by tttppp** [comment]
I'm pretty sure it's not on this computer or my phone. I think it was on an old hard drive that died...

I'll have a go from scratch!

**Comment by colonelfazackerley** [comment]
I tried for a quite a while. I never managed 13.

This story reminds me of Fermat's marginalia.

**Comment by andybalaam** [comment]
Yes, I am becoming more skeptical by the minute :-)

**Comment by andybalaam** [comment]
Because I am preparing for the Deja Vu level set in #87 and because I think saving 12 is pretty tricky, I have changed the target to 12 for now, but if @tttppp finds the 13 solution we can update it, or include it as another level.

It will be a few days before I can make a real release, so there is time to update it in this release if you find it.

**Comment by andybalaam** [comment]
Oh, I am a fool - the original level has a target of 12.

I will remove this level from the set until @tttppp can find the 13 solution.

**Comment by tttppp** [comment]
Yes, this reminded me of Fermat's Last Theorem too!

**Comment by tttppp** [comment]
Just solved it again. I'll try to put it in a pull request later.

**Comment by tttppp** [comment]
Still no internet, so this is from my phone.

![tmp_16363-screenshot_2017-01-06-12-03-20-68337273](https://cloud.githubusercontent.com/assets/7073263/21735062/cba5663a-d45e-11e6-89ce-7cbfdd11cdb9.png)

**Comment by andybalaam** [comment]
How did you get it to stop bridging?

**Comment by andybalaam** [comment]
Aaaaaaaah I just got it!

**Comment by andybalaam** [comment]
You are amazing

**Comment by andybalaam** [comment]
Considering this for level 20 of deja vu, at the expense of Flagging, which I don't like much

**Comment by tttppp** [comment]
I don't remember Flagging very well, but I thought Minefield Mind-fail is a bit annoying. I'll have a look at Flagging.

**Comment by tttppp** [comment]
I agree that Flagging should come out. It might be nice to shuffle the flag-related names around as Flagging is quite a natural pun!
