### ISSUE TITLE
Visible token numbers in Swing UI

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#76]
In 0.4.2 it was possible to see what tokens you had while the level title showed. Now the title and description have been made modal, so to find out what I have I need to quickly pausing the game after start.

**Comment by andybalaam** [comment]
Yes.  I'd like to improve this by displaying the number of tokens under each ability, like it is on Android.  Would that satisfy you?  If so, I'll remodel this issue to represent that feature.

**Comment by tttppp** [comment]
Yep - seeing the numbers before the start would be just as good (actually better than before).

**Comment by tttppp** [comment]
Woo!

**Comment by andybalaam** [comment]
Not sure I like it as-is.  I might move the numbers to the right of the buttons.  Good idea?

**Comment by andybalaam** [comment]
![image](https://user-images.githubusercontent.com/76812/56434255-bb31d880-62cb-11e9-9db0-0f27f04cc355.png)

That last commit makes it look like this.  What do you think?

**Comment by tttppp** [comment]
Fine on Swing, bad on Android IMO. This is purely down to width being at a premium on a phone.

**Comment by andybalaam** [comment]
Yep, something else is needed on phone - maybe the number hovering over the button somehow.
