### ISSUE TITLE
Level idea: baddy rabbit kamikaze freedom fighter

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#77]
Imagine for a second we have implemented baddy rabbits.  An implementation is being worked on, slowly.

They behave exactly like normal rabbits, except you don't have to save them, and they explode on contact with normal rabbits, killing them both.

They will open up loads of level ideas.  Here's one I had today.

Imagine you had to drop a baddy rabbit onto a blocker in order to free the other rabbits.

I am imagining dropping it a long, long way, and having to stop it dropping too early.

Of course, baddy rabbits will open up lots of less-dramatic puzzle ideas too.

**Comment by tttppp** [comment]
Sounds like rabbits made of anti-matter. Maybe this could be acheived with a new anti-matter token? I'm not sure what the point of using it would be - maybe anti-matter rabbits can travel through some type of wall, or fly, or something really cool...

**Comment by colonelfazackerley** [comment]
sounds great. while I think calling them anti-matter rabbits is great, I am not sure it is stylistically sound.

**Comment by andybalaam** [comment]
Closing until we have baddy rabbits.
