### ISSUE TITLE
Ability idea: upside-down rabbit

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#78]
When you pick up this token, gravity is reversed for you.

I think this will provide lots of puzzletunities.

**Comment by andybalaam** [comment]
Yes, I am frustrated about not having proper Internet to be able to work on Rabbit Escape, so I am noting down silly ideas instead.

**Comment by colonelfazackerley** [comment]
not sure it fits with the style. sounds like it would be interesting, though.

**Comment by andybalaam** [comment]
Could be good, but no plans at the moment.
