### ISSUE TITLE
Rabbits enter exit when they should die from falling

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#8]
If a rabbit falls too far, but lands on the exit, it escapes.  Actually, it should die.

**Comment by tttppp** [comment]
Actually I expected them to escape in this case (I think that was the case in Lemmings). It doesn't make much physical sense though!

**Comment by andybalaam** [comment]
Yes, it seems nice to be generous, so my first thought was to allow it, but then I began to wonder how I'd feel if someone designed a level that depended on this behaviour.  I think I'd feel cheated if I had to drop rabbits off a clearly-fatal drop to save them, as I might never try it because it doesn't make physical sense.

**Comment by tttppp** [comment]
I found a reference to how lemmings worked:

"Direct drop": Lemmings falling onto the exit's trigger area will exit if there is terrain under it, even if they would splat from the fall if the exit wasn't there.

From here: http://giovanniviglietta.com/files/lemmings/Glitches.html

**Comment by andybalaam** [comment]
Huh.  Managed to reproduce a Lemmings bug.  Still think it's a bug :-)

**Comment by colonelfazackerley** [comment]
I wouldn't mind if it was possible to fall into an exit, as long as the rabbit has not fallen too far

rabbit falls into exit and escapes.
```
>
##

  O
```

Rabbit will fall too far, and so the portal will reject him.
```
>
##

 


  O
```
 
Also, I would almost prefer it if elements were different to Lemmings.

**Comment by andybalaam** [comment]
I would be happy with this behaviour.  Impl would be non-trivial since rabbits fall 2 squares per time step so could skip past.

**Comment by colonelfazackerley** [comment]
I had seen some testing things to do with falling odd or even distances. This makes sense.
