### ISSUE TITLE
Music for outdoor level set

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#81]
I will be a dictator about this, but am open to suggestions.

Life will be simpler if we choose another track by Tryad http://tryad.org/

We are looking for loops of a few seconds only, to keep memory and disk usage down.

Candidates so far:

* "empty" from "listen" (at about 3m 30s) ... unsettling
* "mesmerise" from "listen" (at about 3m 40s) ... purposeful
* "beat into submission" from "public domain" (at about 1m 14s) ... rocking

**Comment by colonelfazackerley** [comment]
I like "beat into submission": it reminds me of FSOL.

However, I think "empty" is the best suited to the purpose. That's my vote, in this not-democracy.

**Comment by andybalaam** [comment]
"arcardia" from "public domain" (at about 4s) ... calm and purposeful walk, like the outdoors?

**Comment by andybalaam** [comment]
"hello world" from "vavrek" (at about 3m) ... funky, light

**Comment by andybalaam** [comment]
I chose "empty".

**Comment by andybalaam** [comment]
Closed in c4ab6359c146531ca424d7b0e91e1c7e4337636d
