### ISSUE TITLE
Level: "Breakout"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#83]
I'm not overly satisfied with the solution to this. Maybe someone can make it harder/easier/better in some way!
```
:name=Breakout
:description=This level is not related to the Atari game of the same name, and any resemblance is purely coincidental.
:num_rabbits=10
:num_to_save=14
:climb=5
:dig=5
:bridge=99
:music=tryad-witness
################
#             O#
###r############
##########r#####
#####r##########
#############r##
#######   ######
#Q      #      #
#              #
#    /##\      #
################
```

**Comment by colonelfazackerley** [comment]
It looks great. I stared at it for a few minutes, but managed on my first go. 

I am not sure I like bridge stacks. I can't see how to tweak it in a way that does not leave bridge stacking as an option.

**Comment by tttppp** [comment]
How about this alternative?
```
:name=Breakout
:description=This level is not related to the Atari game of the same name, and any resemblance is purely coincidental.
:num_rabbits=10
:num_to_save=10
:block=2
:climb=4
:dig=4
:bridge=3
:bash=3
:explode=2
:music=tryad-witness
################
#Q             #
#             O#
################
################
################
######   #######
#Q     #       #
#              #
#      /##\    #
################
```

**Comment by colonelfazackerley** [comment]
That is great. Took 20 min. Several restarts. Left an abiding sense of satisfaction when complete.

**Comment by colonelfazackerley** [comment]
I have a hunch there are several ways of doing this, but none are trivial.

**Comment by colonelfazackerley** [comment]
merged to master f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a
close me

**Comment by andybalaam** [comment]
Great fun. Took me several goes and then was easier than I thought when I did it. So many excellent levels!

**Comment by andybalaam** [comment]
My solution involves allowing 1 rabbit to walk into the exit then digging with 4 to make space to bridge up.

**Comment by tttppp** [comment]
That sounds like the solution I intended (and I think it's the solution that colonelfazackerley used in the solution). I was much happier with this version than the original.

**Comment by andybalaam** [comment]
Yes, looking at the hints I now see that is what is expected of me.  It is a great level.
