### ISSUE TITLE
Outdoor levels.

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#86]
Choose and sort 8 more levels for the outdoors set.

So far, chosen:

#10
#11 
#12 
#13
#14 
#15 
#16 
#17 
#18 
#19 
#20 
#21

**Comment by andybalaam** [comment]
Also, set the correct author names and (optionally) URLs.

**Comment by andybalaam** [comment]
Also, hints (and descriptions).

**Comment by colonelfazackerley** [comment]
01 #10 no bunny left behind: needs to feel more outdoors
02 #11 prison break
03 #12 tree climb
04 #13 rabbit hole descent
05 #14 home sweet home
06 #15 london bridge
07 #16 saw
08 #17 re-entry
09 #18 cups and bridges
10 #19 spare a blocker
11 #20 spare 2 blockers?
12 #21 cloud bunnies

13 #24 F
14 #26 platforms, small
15 #38 half the world away
16 #39 blockers
17 #43 platforms, large
20 #44 K2
21 #46 slot machine


remove #10, we have more outdoors feeling levels. it could be used for the first level of the next set. (i suggest the next set is created in the repo, and levels are assigned to it, even if it is not in the next release)

I think they are all good levels. #26 should go earlier. #39 could be the first in the set. #44 is good, but may be too difficult for android and too large. if these get committed, we can all play them through in order, and suggest order swaps.

i would be happy to draft the meta (authors, desc, hints) when they are chosen.

**Comment by tttppp** [comment]
#46 is fun but fairly easy. There just aren't many options for placement. If it's "outdoorsy" then I think it should be mid-set. Otherwise it could be grouped together in a later set (maybe an arcade set??)

Blockers is #41 (not #39) and I think it should go near the beginning of the set as it introduces an idea.

**Comment by andybalaam** [comment]
If someone makes a merge request, I'll merge it.  I'd be happy with either an out-of-order list as above, or a proposed order.  Either way we will continue to discuss order (and in/exclusion) here and/or as merge requests.

**Comment by colonelfazackerley** [comment]
I am working on a pull request for this.

**Comment by colonelfazackerley** [comment]
see #98 
if I do more work on it, it will be tommorrow, and i will leave a note here.

**Comment by colonelfazackerley** [comment]
for ease of reference. my pull req has this order of levels

levels/outdoors$ grep :name -r *.rellevel_01.rel::name=Tree climb
level_02.rel::name=Saw
level_03.rel::name=Prison break
level_04.rel::name=Blockers
level_05.rel::name=Spare a blocker
level_06.rel::name=Rabbit hole descent
level_07.rel::name=London Bridge
level_08.rel::name=Home sweet home
level_09.rel::name=Re-entry
level_10.rel::name=Cloud bunnies
level_11.rel::name=Spare 2 blockers?
level_12.rel::name=Platforms, small
level_13.rel::name=C
level_14.rel::name=Platforms, large
level_15.rel::name=F
level_16.rel::name=Half The World Away
level_17.rel::name=Chasm
level_18.rel::name=Cups and bridges
level_19.rel::name=Sailing
level_20.rel::name=K2

**Comment by colonelfazackerley** [comment]
I am going to work on outdoor level desc, hints, now.

**Comment by andybalaam** [comment]
Ratings so far:

    #12 Tree Climb          Thought: 5 Skill: 5
    #16 Saw                 Thought: 5 Skill: 5
    #11 Prison break        Thought: 7 Skill: 4
    #41 Blockers
    #19 Spare a blocker     Thought: 7 Skill: 5-8
    #13 Rabbit hole descent Thought: 7 Skill: 7
    #15 London Bridge       Thought: 7 Skill: 7
    #14 Home sweet home     Thought: 7 Skill: 8
    #17 Re-entry            Thought: 8 Skill: 7
    #21 Cloud bunnies       Thought: 8 Skill: 7
    #20 Spare 2 blockers?   With more work, maybe: Thought: 9 Skill: 9
    #26 Platforms, small
    #23 C
    #43 Platforms, large
    #24 F
    #38 Half The World Away
    #69 Chasm
    #18 Cups and Bridges Thought: 9 Skill: 9
    #73 Sailing
    #44 K2

**Comment by andybalaam** [comment]
Do we want the save-4 version of Rabbit hole descent as the last outdoors level?

**Comment by colonelfazackerley** [comment]
I like K2 for the last outdoors level.

keep harder hole descent for set of repeated levels.

**Comment by andybalaam** [comment]
Cool, agreed.

**Comment by andybalaam** [comment]
#41 Blockers Thought: 1 Skill: 1

**Comment by andybalaam** [comment]
I suggest moving #19 Spare a Blocker one or two places further down so it's not right next to #41 Blockers

**Comment by andybalaam** [comment]
#26 Platforms, Small Thought: 6 Skill: 7

**Comment by andybalaam** [comment]
#23 C Thought: 5 Skill: 6

**Comment by andybalaam** [comment]
#43 Platforms, large Thought: 8 Skill: 8

**Comment by andybalaam** [comment]
#24 F Thought: 8 Skill: 7

**Comment by andybalaam** [comment]
#38 Half the world away Thought: 9 Skill: 8

**Comment by andybalaam** [comment]
#69 Chasm Thought: 9 Skill: 8

**Comment by andybalaam** [comment]
#73 Sailing Thought: 9 Skill:8

**Comment by andybalaam** [comment]
Snapshot uploaded here: http://artificialworlds.net/rabbit-escape/snapshots/ mainly to allow me to play K2 on my phone.

**Comment by colonelfazackerley** [comment]
How big is your phone? K2 is a big tricky level. I would like to know how well it works.

I do find on Android (tablet or phone) that the lost token drops (due to small drags) are not a problem, like it is for swing.

**Comment by andybalaam** [comment]
Large levels are hard but not impossible on my phone (Samsung S3).  If you zoom in, it crashes (Out of memory), which I plan to fix, but interestingly we've only ever had 1 crash report (from you!) for out of memory, so I've put it off for now.

Yes, small drags don't lose token drops on Android, but zoom often drops a token when you didn't want it to, which again I plan to fix sometime...

**Comment by andybalaam** [comment]
New snapshots at http://artificialworlds.net/rabbit-escape/snapshots/ with the new hints and descriptions - thanks @colonelfazackerley !

**Comment by andybalaam** [comment]
btw I haven't reached K2 on my phone yet so I'll let you know when I do...

**Comment by andybalaam** [comment]
#44 K2 Thought: 10 Skill: 8

**Comment by andybalaam** [comment]
Ratings now:

#12 Tree Climb Thought: 5 Skill: 5
#16 Saw Thought: 5 Skill: 5
#11 Prison break Thought: 7 Skill: 4
#41 Blockers Thought: 1 Skill: 1
#19 Spare a blocker Thought: 7 Skill: 5-8
#13 Rabbit hole descent Thought: 7 Skill: 7
#15 London Bridge Thought: 7 Skill: 7
#14 Home sweet home Thought: 7 Skill: 8
#17 Re-entry Thought: 8 Skill: 7
#21 Cloud bunnies Thought: 8 Skill: 7
#20 Spare 2 blockers? With more work, maybe: Thought: 9 Skill: 9
#26 Platforms, small Thought: 6 Skill: 7
#23 C Thought: 5 Skill: 6
#43 Platforms, large Thought: 8 Skill: 8
#24 F Thought: 8 Skill: 7
#38 Half The World Away Thought: 9 Skill: 8
#69 Chasm Thought: 9 Skill: 8
#18 Cups and Bridges Thought: 9 Skill: 9
#73 Sailing Thought: 9 Skill:8
#44 K2 Thought: 10 Skill: 8

So this suggests we should move #26 Platforms, small and #23 C earlier, and #20 Spare 2 blockers? later if I can make it work the way it should.  The rest are pretty good.  I don't think #41 Blockers should go earlier since it's kind of challengeless and might put people off if it came right at the beginning (but I think it's worth having).

**Comment by andybalaam** [comment]
After the rename:

    $ grep ':name=' *
    level_01.rel::name=Tree climb
    level_02.rel::name=Saw
    level_03.rel::name=C
    level_04.rel::name=Blockers
    level_05.rel::name=Platforms, small
    level_06.rel::name=Spare a blocker
    level_07.rel::name=Prison break
    level_08.rel::name=Rabbit hole descent
    level_09.rel::name=London Bridge
    level_10.rel::name=Home sweet home
    level_11.rel::name=Re-entry
    level_12.rel::name=Cloud bunnies
    level_13.rel::name=Spare 2 blockers?
    level_14.rel::name=Platforms, large
    level_15.rel::name=F
    level_16.rel::name=Half The World Away
    level_17.rel::name=Chasm
    level_18.rel::name=Cups and bridges
    level_19.rel::name=Sailing
    level_20.rel::name=K2

**Comment by andybalaam** [comment]
New snapshots here: http://artificialworlds.net/rabbit-escape/snapshots/ .  Please test ready for release, especially level 13 #20 Spare 2 blockers?

**Comment by andybalaam** [comment]
I made the release here: https://github.com/andybalaam/rabbit-escape/releases/tag/v0.6 .  Please test.  If it's ok I'll stick it on the Play store in a day or so.

**Comment by tttppp** [comment]
Level 4 blockers has the older version of the level. @colonelfazackerly suggested raising the initial rabbits up a bit to be level with the entrance.

The new Spare 2 Blockers has me stumped at the moment. It should be renamed - "Spare 1 bridger".

**Comment by tttppp** [comment]
Ok, solved "Spare 2 Blockers", and it's not as hard as I was making out ;-)  They never are in retrospect!

I think it shouldn't have a left hand wall on the bottom level. With the wall there's only a desire for 1 blocker, and it's very easy to solve with just one.

**Comment by tttppp** [comment]
(easier to solve with one blocker than with two)

**Comment by GamingInky** [comment]
Level 1 #12 I think should be easier and/or put later, because it took me about a hundred goes
to complete it. I also think the next to are easier.

**Comment by andybalaam** [comment]
@tttppp the latest version 0.6.1 should have no wall on the left. I realised my mistake.

**Comment by colonelfazackerley** [comment]
@GamingInky  - Did you play the easy, medium and hard sets first? Did you have to use the hints?

#23 "C" is definitely easier, so could go first. I prefer #12 "Tree Climb" first, as I think it is prettier. "Saw" may or may not be easier: depends on the player.

**Comment by GamingInky** [comment]
Well maybe we could edit it so it's still a tree but it's a bit easier.

**Comment by andybalaam** [comment]
I like #12 first because it looks very pretty and is outdoorsy. I'm happy with how hard it is because it kind of comes after the hard set.
