### ISSUE TITLE
Level set: "Déjà vu": repeated earlier levels, with higher targets and different solutions

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#87]
**Levels in this set:**
1. Block drop stop shop #472  **skill:6, thought:7**
2. You wait here but not forever #292 **skill:5, thought:6**
3. Tree, tree, tree again #113 **skill:6, thought:6 [not modified, because I backported the change to #12]**
4. C Red #111 **skill:7, thought:8 [There are 4 ways to do it, so it can't be too hard!]**
5. Oh we do like to be beside the tree-side #160 **[modified]** **skill:8, thought:8**
6. White Flag #235 **skill:7, thought:8**
7. Flagellate #235 **skill: 7, thought:8** [brilliant!]
8. Flagrant disregard #235 **skill:7 thought:8 [excellent fun]**
9. Badtet #158 **skill:8, thought:9 [I found this quite easy (thought:7?) but others found it hard to save more than 7]**
10. Upstairs #57 **skill:7, thought:9**
11. Slippery Slopes" #423 **skill:8, thought:9**
12. Alice in Painland #99  **skill:8, thought:9**
13. Carpal tunnels #70  **skill:8, thought:10**
14. Cups of suffering #18 **skill:9, thought:9**
15. Flagging #235 **skill:9, thought:8 [a bit annoying?]**
16. Tomb of Doom #230 **skill:9, thought:9**
17. The crazy mother #56 **skill:8, thought: 10**
18. Minefield Mind-fail #237 **skill:9, thought:10 [Same as "Carpal tunnels" but save one more]**
19. Three down, one to go #236 **skill:10, thought:9**
20. Keep On Trying #296 **skill:9, thought:9**

**Not included:**
- **[water]** Aquifer **but save 6** #362 (original: ./development/unsorted/Aquifer.rel)
- **[water]** Under pressure **but save 9** #435 (original: ./staging/smallworld/Under-pressure.rel)
- **[no solution]** Gotta catch em all  #75 (development/unsorted/Gotta-catch-em-all.rel)

**TODO**
- ~Read issue comments, create and format level files~
- ~Release a snapshot containing all levels~
- ~Rename any dodgy names (including Bastet)~
- ~Rate for difficulty and re-order~
- ~Update levels with solutions~
- ~Write descriptions~
- ~Write authors and URLs~
- ~Write hints~
- ~Reformat levels~
- ~Ensure music is set in level files~
- ~Add to menu~
- ~Update Block Drop Stop Shop~

**Background:**

Given that we probably haven't found the best solution for each level it would be nice to allow people to submit their solutions. This could be done if the token placement and timing was recorded for each play, and the option to send this to Andy was available if the score was better than the target.*

It would be good to do this without using the in-app internet permission, by presenting the recording in a plain text format for emailing to Andy (alternatively a link could be placed to redirect to an artificial worlds URL?)

Maybe Andy could host a 'high scores' or 'hall of fame' page for the first player to get the best score on a level?

Once twenty solutions had been received that were improvements on the existing targets then a new set could be made containing the new targets (with attribution to the solvers).
- Note that some levels have a deliberately lower target than is possible to misdirect the player.

**Comment by colonelfazackerley** [comment]
A set of repeat levels that are harder is a great idea. We could allow other small tweaks too, to make levels harder.

The hall of fame thing is not a bad idea, but seems quite fiddly compared to the benefits it brings.

**Comment by andybalaam** [comment]
Yes this sounds really cool.  While I've been playing through I've often felt proud that I found a better way and it would be good to reward this.

Another option would be a "stretch target" for some levels indicating you can do better than the normal target.  Maybe when you achieve the stretch target you get a different congratulating message too?

**Comment by andybalaam** [comment]
Hall of fame as a manual thing sounds manageable, and would help foster community.

**Comment by andybalaam** [comment]
Generally, recording your actions as you play would be very useful for generating solutions and "anti-solutions" for test cases, demo modes etc.  Would be nice to encourage people to exchange solution files, add them to bug reports etc.

**Comment by colonelfazackerley** [comment]
How about calling the set of repeated, but harder, levels "Déjà vu"?

**Comment by andybalaam** [comment]
Good idea.  Renamed the issue in honour of it.

**Comment by andybalaam** [comment]
Note: only levels with substantially different solutions should be included, to keep it interesting.

**Comment by andybalaam** [comment]
#99 is a candidate

**Comment by GamingInky** [comment]
I,ve created a level which might fit with this level set #113.

**Comment by andybalaam** [comment]
So, we have 20 levels, but 2 of them are modified, so if someone comes up with any more, we will move the modified ones out.  I'm OK with including them, otherwise.

**Comment by andybalaam** [comment]
Two of the level names I made up (Bastet and The crazy mother) refer to offensive things.  They are oblique references, but if anyone can come up with better names, please let me know.

**Comment by andybalaam** [comment]
"Carpal tunnel" and "Minefield mind-fail" are identical but with different numbers to save.  If the solutions are similar we should find something different - I will update if and when I find the solutions :-)

**Comment by andybalaam** [comment]
Snapshot 0.9.1.1 available now at http://artificialworlds.net/rabbit-escape/snapshots/

Activate cheat mode to find the Deja Vu level set. Not all levels have solutions, so it's possible I have messed up and some are impossible. I will be play-testing over the next few days and updating this issue with my difficulty ratings - please let me know yours too.

**Comment by tttppp** [comment]
The solutions to the minefield levels are all basically the same. The later levels are just trickier to get the timing right.

**Comment by andybalaam** [comment]
Hrmmm.  Ideally, we'd have a few more deja vu levels so we could take out some of the minefield ones and also the ones that are not true deja vu because they were changed.

**Comment by andybalaam** [comment]
I am having a lot of fun tonight playing through and trying to find better solutions, especially for "Keep on Trying"

**Comment by andybalaam** [comment]
I added solutions and re-ordered based on my perception of difficulty.  Comments on the order are welcome.  I put all the "flag" levels together except the one that irritates me, which I put quite late so hopefully if you got that far you like the game...

**Comment by andybalaam** [comment]
There are some good levels.  They are _way_ harder than other stuff we have released.  This level set will go last, so it should be OK.

**Comment by andybalaam** [comment]
A snapshot will all levels in the above order, available without cheat mode is 0.9.1.2 here: http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by andybalaam** [comment]
I updated the order to make more interesting levels last.

**Comment by andybalaam** [comment]
I put Gotta catch em all in, and took Flagging out

**Comment by GamingInky** [comment]
cool
