### ISSUE TITLE
Level set: Arcade

### ISSUE THREAD

**Issue by colonelfazackerley** [andybalaam/rabbit-escape#88]
@tttppp's plan of having an arcade set after the outdoor set is good. suitable candidates so far

updated list:

01 #46 slot machine
02 #47 dig for victory
03 #53 ufo
04 #56 mothership
05 #63 the matrix
06 #70 tunnels
07 #75 catch me if you can
08 #83 breakout (second version with 3 bridges)
09 #104 galton box
10 #93 ghost versus pie
11 #90 invader
12 #89 space invaders
13 #71 the traitor
14 #142 cliff hanger
15 #156 Asteroids
----not entirely arcade, but whatever---
16 #97 forest
17 #74 meander
18 #72 tomb raider (not a great level, but it makes up the numbers)
19 #67 keep

and #158 tetris makes 20. Is tetris an arcade game? oh, whatever.

New comment: leaving some levels that have to go in deja vu or paradise, we have just enough for arcade.
new new comment: I double counted #83. Still need one more.

I just numbered them to see how many we have. i have no suggestions about order atm.

i suggest pushing them to shorten the open issue list. i am sure we can make enough new levels to fit the theme.

**Comment by andybalaam** [comment]
Sounds good.  My Internet is back and I will begin catching up.

Slightly longer-term plan is to allow arbitrarily-named levels, which would make it easier to propose levels using merge requests.  I am still happy with using issues but it is making me a bottleneck at the moment.

**Comment by andybalaam** [comment]
When I have time I will make a release with an outdoor set.

**Comment by andybalaam** [comment]
Suggestions for arcade music from http://tryad.org/ :

"beat into submission" from "public domain" (at about 1m 14s) ... rocking
"hello world" from "vavrek" (at about 3m) ... funky, beepy

Most of vavrek sounds computer-game inspired, which might be good.

**Comment by andybalaam** [comment]
There are 20 issues open with label "level", so I reckon if we start collecting them together we can make this set.

**Comment by colonelfazackerley** [comment]
Many don't fit the theme. We may need an outdoors2 and an arcade.

**Comment by andybalaam** [comment]
I have no compunction whatsoever about including levels that don't fit the theme.  Maybe if we rename some we can make them seem a bit closer, but I'm mostly just keen to get the levels into people's hands.

**Comment by colonelfazackerley** [comment]
I am working on a pull request for this.

**Comment by colonelfazackerley** [comment]
Do you mind if I call the files 
01_<name1>.rel
02_<name1>.rel
...
?

It seems to work without further ado.

**Comment by tttppp** [comment]
I definitely like tomb raider in this set. The name fits even if the level isn't immediately obvious. Maybe some of the other levels could be renamed?

**Comment by andybalaam** [comment]
The fact that levels can't yet have order-independent file names makes committing them to git before deciding the order annoying but happy to do so if the issues list is stressing you out.

**Comment by andybalaam** [comment]
Note these levels will need hints, descriptions authors etc. before we can release.

**Comment by colonelfazackerley** [comment]
I am not suggesting a pull request, yet. I will do hints and descriptions. possibly solutions too, if that stuff is working.

Look at my arcade branch

https://github.com/andybalaam/rabbit-escape/compare/master...colonelfazackerley:arcade

```
cf@re:~/re/rabbit-escape$ ls rabbit-escape-engine/src/rabbitescape/levels/arcade/
01_Ghost-versus-pie.rel  05_Invader.rel   09_Asteroids.rel        13_Space-invaders.rel  17_Tunnels.rel              _Tetris.rel
02_Cliff-hanger.rel      06_Forest.rel    10_UFO.rel              14-The-mothership.rel  18_Catch-me-if-you-can.rel
03_The-matrix.rel        07_Breakout.rel  11_Dig-for-victory.rel  15_Traitor.rel         19_Galton-box.rel
04_Tomb-raider.rel       08_Keep.rel      12_Slot-machine.rel     16_Meander.rel         ls.txt
```

This works without changes to the code. I like that I can see which level is which from the filename, but they also have numbers in, so ```ls``` shows them in the correct order.

I would like to rename the set directories too, so ```ls``` gives them the correct order.
01_easy
02_medium
03_hard
04_outdoors
05_arcade

**Comment by tttppp** [comment]
Swap forest for tetris.  I think forest might go in the paradise set, or possibly in a set dedicated to tree-based levels!

**Comment by colonelfazackerley** [comment]
I miscounted (OP corrected now). If I remove forest we need another. If you make another, I will swap forest out. I just made Tetris and Asteroids to make up the numbers.

**Comment by tttppp** [comment]
Oh great. We can leave forest in then. It's a famous forest arcade game where you look at trees and clouds.

**Comment by colonelfazackerley** [comment]
See my progress here
https://github.com/andybalaam/rabbit-escape/compare/master...colonelfazackerley:arcade

**Comment by colonelfazackerley** [comment]
Almost ready
https://github.com/andybalaam/rabbit-escape/compare/master...colonelfazackerley:arcade2
just need the text ui working so i can sort the last few solutions.

Please suggest improvements to desc, hints, order, etc

**Comment by andybalaam** [comment]
I've been doing too much cod and not enough play.  I will build a snapshot with these levels in, and try them on my phone.

**Comment by andybalaam** [comment]
Snapshot to try these levels here: http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by andybalaam** [comment]
>  Is tetris an arcade game?

Yes

**Comment by andybalaam** [comment]
> Do you mind if I call the files
> 01_[name1].rel
> 02_[name2].rel
> ...
> ?

Not at all.

> It seems to work without further ado.

That is just how good I am.

**Comment by andybalaam** [comment]
I will play these tomorrow and give some feedback.

ghost versus pie is cool, and suitable to be early.

**Comment by andybalaam** [comment]
Ghost vs pie #93 thought 6 skill 6

**Comment by colonelfazackerley** [comment]
solutions in here are broken. i will fix soon
- i could not run make test becuase "until" did not work
- the reports from text mode were wrong. they are not all affected.

**Comment by andybalaam** [comment]
Cliff hanger #142 thought 5 skill 3 (but good not to have it first)

**Comment by andybalaam** [comment]
I rebased your branch on top of master and the only solution that failed was level 20.

**Comment by andybalaam** [comment]
Text mode should now be fixed. Please report any unfixedness with extreme prejudice.

**Comment by andybalaam** [comment]
The Matrix #63 thought 6 skill 7

**Comment by andybalaam** [comment]
Tomb raider #72 thought 4 skill 6

**Comment by andybalaam** [comment]
Invader #90 thought 8 skill 9

**Comment by andybalaam** [comment]
Ufo #53 thought 7 skill 6

**Comment by colonelfazackerley** [comment]
TODO: 
- 2nd hint on Ghost v pie needs an initial capital

**Comment by andybalaam** [comment]
Breakout #83 thought 7 skill 7

**Comment by andybalaam** [comment]
Slot machine #46 thought 7 skill 1

**Comment by andybalaam** [comment]
Asteroids #156 thought 8 skill 8

**Comment by andybalaam** [comment]
New snapshot 0.6.1.2 uploaded, based on current master. http://artificialworlds.net/rabbit-escape/snapshots/

(btw I am updating doxygen when I remember: http://artificialworlds.net/rabbit-escape/doxygen )

**Comment by andybalaam** [comment]
Forest #97 thought 9 skill 9

**Comment by andybalaam** [comment]
Dig for victory #47 thought 6 skill 8

**Comment by andybalaam** [comment]
Keep #67 thought 7 skill 8

**Comment by andybalaam** [comment]
The traitor #71 thought 8 skill 9

**Comment by andybalaam** [comment]
Mothership #56 thought 8 skill 7

**Comment by andybalaam** [comment]
Space Invaders #89 thought 10 skill 9

**Comment by andybalaam** [comment]
Tetris #158 thought 8 skill 8

**Comment by andybalaam** [comment]
Galton box #104 thought 7 skill 8

**Comment by andybalaam** [comment]
Catch me if you can #75 thought 8 skill 8

**Comment by andybalaam** [comment]
@colonelfazackerley were these in a suggested order? It approximately agrees with my ratings but not perfectly. On the other hand I think several of my ratings are pretty suspect.

**Comment by colonelfazackerley** [comment]
They are in a rough difficulty order. I don't mind if you want to tweak it a bit.

**Comment by andybalaam** [comment]
Do you think Space invaders #89 should go last?

**Comment by andybalaam** [comment]
Other than that I think all the tricky ones are approximately as tricky as each other and because there is so much variety the true difficulty will vary person to person.

**Comment by colonelfazackerley** [comment]
Space invaders could go a little later. I think Galton, Tetris, Catch me (and possibly some more) are harder. But difficulty depends on the player, mood, ...

Don't really mind.

**Comment by colonelfazackerley** [comment]
Actually, my impression of Catch me being very hard may be because I still have not got 13 out. Getting 12 out may not be so tricky.

**Comment by andybalaam** [comment]
12 was ok for me. On the principle of getting the release out asap let's leave them as they are. I certainly enjoyed playing them in this order.

**Comment by andybalaam** [comment]
Done!

**Comment by colonelfazackerley** [comment]
I played through this on my phone I found dig, tunnels and forest hard to execute, even though I know how to do them. I guess these should have gone a little later in the set. The thing about dig for victory, is that I find it impossible to remember the exact token placement, so I have to figure it out again every time.

**Comment by andybalaam** [comment]
I think the order is very arguable. Most of the levels are pretty hard, so it varies by person.

**Comment by colonelfazackerley** [comment]
I would also argue that strict monotonic difficulty is not desirable. If all the hardest levels are clumped at the end, and a player gets stuck on each one, it may be a little disheartening.

**Comment by andybalaam** [comment]
Fair point.
