### ISSUE TITLE
Level: "Space Invaders"

### ISSUE THREAD

**Issue by tttppp** [andybalaam/rabbit-escape#89]
I have a feeling this is quite hard! Potential candidate for an arcade theme.
```
:name=Space Invader
:description=
:num_to_save=10
:num_rabbits=10
:dig=3
:bash=2
:block=2
:bridge=8
:rabbit_delay=9
##    O         ##
# #   #   #   #  #
    #   #   #   # 
  #           #   
        #         
        #         
     Q            
        #         
#      /#\       #
##   #######    ##
```

**Comment by colonelfazackerley** [comment]
It's hard. Took 45min, and some cursing...

**Comment by colonelfazackerley** [comment]
I relied on this behaviour twice to get through.

```
i O
*##
###
:*=rb   
```
rabbit bashes a block out, before the rabbit has moved, I drop a bridge block, and the rabbit builds the bridge from the current position.

I think this is probably OK.

**Comment by tttppp** [comment]
I'm fairly sure you found a different solution from mine then. My solution:

Step 1:
https://cloud.githubusercontent.com/assets/7073263/10412822/8c7d7690-6f89-11e5-8f82-8be0d66fcda9.png

Step 2:
https://cloud.githubusercontent.com/assets/7073263/10412819/8c507938-6f89-11e5-82ea-0074503978ce.png

Step 3:
https://cloud.githubusercontent.com/assets/7073263/10412820/8c74106e-6f89-11e5-9c65-67b0d2931e3c.png

Step 4 (Profit):
https://cloud.githubusercontent.com/assets/7073263/10412821/8c7a885e-6f89-11e5-8d6f-1830084e5970.png

**Comment by colonelfazackerley** [comment]
How do you upload an image to github as a link? (then I can show my solution, but Andy can choose to look, or figure out his own method first(.

**Comment by colonelfazackerley** [comment]
Here's a variant on mine.
```
:solution.1=bash;(6,8);block;(5,8);bridge;2;(8,8);dig;(8,3);bridge;3;(11,6);12;(12,5);12;bash;(9,3);3;bridge;3;(9,3);6;(5,8);until&WON
```
please record yours

**Comment by colonelfazackerley** [comment]
merged to master f96dd5696bc0d3c0f44b4856ba75e3a7d2bc201a
close me

**Comment by andybalaam** [comment]
Wow that was hard. Brilliant level. Took a lot of tries and felt really good to solve. I didn't rely on bridging immediately after bashing.

**Comment by andybalaam** [comment]
The name is missing an 's' at the end and I think the hints should avoid the bash then bridge behaviour. I will post my solution when I get a chance if it's different from the above one.

**Comment by andybalaam** [comment]
Just looked. Mine is similar but not identical.

**Comment by colonelfazackerley** [comment]
A note on bashing then bridging. I think it works because the rabbit can't use the bridge token at first, so ignores it. As soon as the block in front has been bashed away, it can use use the bridge token, so picks it up before moving.

**Comment by andybalaam** [comment]
Right. I'm not too bothered that you can do this. Are you?

**Comment by colonelfazackerley** [comment]
The fact it's possible seems a little counter-intuitive. Now I get it, I quite like it.

**Comment by tttppp** [comment]
Pushed my "official" solution to tttppp/outdoorsSolutions.

**Comment by andybalaam** [comment]
s added in 520621268bc72e5f717eb62aaf3c0d5e87138721

**Comment by andybalaam** [comment]
Reopening to fix the hints to use the better solution.  I am working on this now.

**Comment by andybalaam** [comment]
Wow, writing hints of levels like this could be a game in itself.  Tricky!
