### ISSUE TITLE
When audio is on on the Linux version, Rabbit Escape sometimes freezes.

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#9]
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

Sometimes, the JVM actually crashes.

Disabling audio makes the problem go away.

When it freezes, one thread always has this stack trace in the debugger:

    Daemon Thread [SwingWorker-pool-1-thread-2] (Suspended)	
        waiting for: PulseAudioClip$ClipThread  (id=32)	
        Object.wait(long) line: not available [native method]	
        PulseAudioClip$ClipThread(Thread).join(long) line: 1281	
        PulseAudioClip$ClipThread(Thread).join() line: 1355	
        PulseAudioClip.stop() line: 555	
        SwingSoundCache.get(String) line: 32	
        SwingSound.musicClip() line: 107	
        SwingSound.stopMusic() line: 91	
        SwingSound.setMusic(String) line: 63	
        SwingGameLaunch.<init>(SwingGameInit, World, LevelWinListener, SwingSound) line: 82	
        SwingSingleGameMain.createGameLaunch(World, LevelWinListener) line: 77	
        SwingSingleGameMain(Main).launchGame(String[], LevelWinListener) line: 52	
        MenuUi$1.doInBackground() line: 266	
        MenuUi$1.doInBackground() line: 260	
        SwingWorker$1.call() line: 296	
        SwingWorker$2(FutureTask<V>).run() line: 262	
        MenuUi$1(SwingWorker<T,V>).run() line: 335	
        ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1145	
        ThreadPoolExecutor$Worker.run() line: 615	
        Thread.run() line: 745

**Comment by andybalaam** [comment]
I'm pretty sure this is due to a bug in OpenJDK.

**Comment by andybalaam** [comment]
I just tried this in Oracle's JVM on linux and it didn't crash.  This was version 8, so it's possible it's been fixed in OpenJDK 8 but I suspect it's only fixed in the Oracle version.  Needs further testing.

**Comment by colonelfazackerley** [comment]
Android Studio does winge a lot about openjdk. will you use the oracle jdk to build releases?

**Comment by andybalaam** [comment]
Back from a work trip and will be working through activity on here.

**Comment by andybalaam** [comment]
I don't think the choice of compiler makes much difference. Do you have other information to suggest it does?

**Comment by andybalaam** [comment]
I just tried this for quite a while using OpenJDK 8 and it was fine.

On Ubuntu 14.04 I did this with:

    sudo apt-add-repository ppa:openjdk-r/ppa
    sudo apt-get update
    sudo apt-get install openjdk-8-jre

I've updated the [Linux download page](http://artificialworlds.net/rabbit-escape/download-linux.html) to recommend OpenJDK 8+.  Let me know if there's anywhere else we need to update.

**Comment by andybalaam** [comment]
No, I was wrong.  I still see crashes under OpenJDK 8, so I have disabled sound in OpenJDK as per #95.
