### ISSUE TITLE
Bug: Rabbit ignores Block above him

### ISSUE THREAD

**Issue by RapidPanther** [andybalaam/rabbit-escape#91]
Hey,

I detected a possible bug in level 7 (medium):
```
######################
#                /#  #
#                / (O#
#                /# ##
#               (/#  #
#              (/##/)#
#             ( /#\# #
#            (    # /#
# Q         (    #/###
#          (     ##\##
#     r   (     /###/#
######################
```

After climbing a Triangle-Block ('/') the rabbit ignores the block above him and goes further instead of turning around.

![lvl7](https://cloud.githubusercontent.com/assets/14246178/10412202/cb58011c-6f86-11e5-90b6-47cbfa023196.PNG)

The block above is also ignored when it's a full block.

**Comment by colonelfazackerley** [comment]
Thanks for the nice report with screenshot. I think this report is related to #68. In #68 it's a bridge underfoot, here it's a slope block.

**Comment by andybalaam** [comment]
Thanks @RapidPanther yes, this bug makes this level far too easy!

**Comment by andybalaam** [comment]
As a side note: I plan to make tests that check each level is soluble, but I think bug reports like this could also provide useful test cases for ways that a level should *not* be solved.

**Comment by tttppp** [comment]
+1 for the idea of solutions/failures as test cases. If done right it could make level development much smoother.
