### ISSUE TITLE
Congratulations message when you complete a level set

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#94]
Congratulating the player, possibly showing a picture of a happy rabbit (or a custom picture per set), and suggesting they visit the web site to find out how to make their own levels.

(As suggested in #64)

**Comment by andybalaam** [comment]
I'll leave adding images or sounds for if/when we get some images sent in (I asked on Mastodon but must remind those who volunteered).  For now, a message will suffice.

**Comment by tttppp** [comment]
🐰 Congratulate them with an emoji! 🐰

**Comment by andybalaam** [comment]
I just tried this and it didn't display :-(

**Comment by tttppp** [comment]
Oh :disappointed: 

Maybe something like this?
```
  //
 ('>
 /rr
*\))_
```
I guess it won't look right in Swing though.

Btw if you want to use that then you might need to attribute it to Linda Ball from here: https://www.asciiart.eu/animals/rabbits  It's a 13 character work of art!

**Comment by andybalaam** [comment]
I am getting increasingly frustrated with Swing, and have already concluded that JavaFX is at least as bad.  If I had the time again I would implement something manually based on a canvas, and take the hit to make it keyboard-accessible.  We would lose out on all the stuff we are ignorant about around accessibility, but right now we are losing potential users because our interface is so unattractive.
