### ISSUE TITLE
Harder version of Rabbit Hole Descent, requiring saving 4

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#99]
Harder version of #13 Rabbit Hole Descent by @colonelfazackerley (solution discovered by @tttppp)

    :name=Rabbit hole descent
    :description=Rabbit hole descent
    :author=colonelfazackerley
    :num_rabbits=4
    :num_to_save=4
    :rabbit_delay=25
    :bridge=5
    :dig=4
    :bash=4
    :block=1
    :music=tryad-witness
    ###################

      Q                

    #######   #########
    #######   #########
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   ##       
         ##   O#       
    #######   #########
    #######   #########

**Comment by colonelfazackerley** [comment]
hah, now we need to modify the rel format to allow 2 authors.

**Comment by andybalaam** [comment]
:authorName=colonelfazackerley and tttppp

?

**Comment by colonelfazackerley** [comment]
What's the URL?

**Comment by andybalaam** [comment]
The main author? I don't think it warrants extra complexity to support multiple authors.

**Comment by tttppp** [comment]
When we have automated solution testing then credit me in the solution file. I only changed one digit in the setting of this puzzle, so I'm barely an author. Once my name is in the solutions file I will live off my new-found fame.

**Comment by andybalaam** [comment]
I like it:

    :solution=foobar
    :solution_author_name=tttppp
    :solution_author_url=etc

**Comment by andybalaam** [comment]
What a nice gif:

![alice-in-painland-solution](https://cloud.githubusercontent.com/assets/76812/16064082/1d76b0ec-3296-11e6-8551-09fcc19476cf.gif)

**Comment by tttppp** [comment]
This level was pretty tough. Eventually I discovered how to solve it with one bridge leftover though! Result :-)

**Comment by andybalaam** [comment]
You are the deja deja vu master
